{
  "version": "4.16.6",
  "time": 7.098,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "fl_convenio_alteracao",
        "title": "Convênio Alteração",
        "path": "data/fl_convenio_alteracao.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_convenio",
              "title": "Convênio / Parceria - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "nr_alteracao",
              "title": "Número da Alteração",
              "type": "string",
              "format": "default",
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "dt_publicacao",
              "title": "Data da Alteração",
              "type": "date",
              "format": "default"
            },
            {
              "name": "tp_alteracao",
              "title": "Tipo de Alteração",
              "type": "string",
              "format": "default",
              "description": "Tipo de alteração ocorrida no Convênio / Parceria:\n - adequação do convênio;\n - alteração simples;\n - ampliação de meta;\n - cancelamento convênio;\n - dotação orcamentaria;\n - gestor parceria;\n - prorrogação de ofício;\n - retificação por erro humano;\n - termo aditivo;\n - valor;\n - vigência e\n - vigência/valor\n",
              "missingValues": [
                "sem classificação",
                "outros"
              ],
              "constraints": {
                "required": true
              }
            },
            {
              "name": "objetivo",
              "title": "Objetivo da Alteração",
              "type": "string",
              "format": "default"
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_convenio"
              ],
              "reference": {
                "fields": [
                  "id_convenio"
                ],
                "resource": "dm_convenio"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "fl_convenio_alteracao"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "27261ec84d27b47052c6369eaddc3733",
          "bytes": 3568357,
          "fields": 5,
          "rows": 47714
        }
      },
      "time": 7.098,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "id_convenio",
            "nr_alteracao",
            "dt_publicacao",
            "tp_alteracao",
            "objetivo"
          ],
          "rowNumber": 47216,
          "rowPosition": 47217,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"47217\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "nr_alteracao",
            "dt_publicacao",
            "tp_alteracao",
            "objetivo"
          ],
          "rowNumber": 47217,
          "rowPosition": 47218,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"47218\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "nr_alteracao",
            "dt_publicacao",
            "tp_alteracao",
            "objetivo"
          ],
          "rowNumber": 47295,
          "rowPosition": 47296,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"47296\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "nr_alteracao",
            "dt_publicacao",
            "tp_alteracao",
            "objetivo"
          ],
          "rowNumber": 47336,
          "rowPosition": 47337,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"47337\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "nr_alteracao",
            "dt_publicacao",
            "tp_alteracao",
            "objetivo"
          ],
          "rowNumber": 47379,
          "rowPosition": 47380,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"47380\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "nr_alteracao",
            "dt_publicacao",
            "tp_alteracao",
            "objetivo"
          ],
          "rowNumber": 47410,
          "rowPosition": 47411,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"47411\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "nr_alteracao",
            "dt_publicacao",
            "tp_alteracao",
            "objetivo"
          ],
          "rowNumber": 47416,
          "rowPosition": 47417,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"47417\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_convenio",
            "nr_alteracao",
            "dt_publicacao",
            "tp_alteracao",
            "objetivo"
          ],
          "rowNumber": 47453,
          "rowPosition": 47454,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"47454\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 8
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 8,
    "tasks": 1
  },
  "valid": false
}