{
  "version": "4.38.0",
  "time": 409.43,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_compras",
        "title": "Compras",
        "path": "data/ft_compras.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_tempo",
              "title": "Tempo - Chave",
              "type": "integer",
              "format": "default",
              "description": "- > \n  Chave estrangeira (Foreign Key) que aponta para a Chave Primária (Primary keys) da tabela dm_tempo_diario. \n  Ou seja, por meio dessa chave é possível identificar a data completa a qual o dado se refere.\n\n  Nota: \n  No site dados.mg.gov.br a tabela dm_tempo_diario pode ser encontrada no recurso Calendários - Dias \n  de cada conjunto.\n",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_procedimento",
              "title": "Procedimento de Contratação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_demanda",
              "title": "Órgão Demandante - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_contrato",
              "title": "Órgão do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_proc",
              "title": "Situação do Processo de Compra - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_cont",
              "title": "Situação do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_municipio",
              "title": "Município - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contratado",
              "title": "Contratado - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_tipo_licitacao",
              "title": "Tipo de Licitação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_grupo_matserv",
              "title": "Grupo Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_classe_matserv",
              "title": "Classe Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_material_servico",
              "title": "Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item_matserv",
              "title": "Item Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_processo",
              "title": "Processo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contrato",
              "title": "Número do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_medida",
              "title": "Unidade de Medida - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_linha_fornec",
              "title": "Linha de Fornecimento - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_orc",
              "title": "Unidade Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "unique": false
              }
            },
            {
              "name": "ano_particao",
              "title": "Ano Partição",
              "type": "year",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true
              }
            },
            {
              "name": "dt_item_homologa",
              "title": "Data da Homologação do Item",
              "type": "date",
              "format": "default",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "qt_item_pedido",
              "title": "Item do Pedido - Quantidade",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_referencia",
              "title": "Valor Unitário de Referência",
              "description": "Valor unitário estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_referencia",
              "title": "Valor de Referência",
              "description": "Valor estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_homologado",
              "title": "Valor Unitário Homologado",
              "description": "Valor unitário final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_homologado",
              "title": "Valor Homologado",
              "description": "Valor final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_atualizado",
              "title": "Valor Atualizado",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_processo"
              ],
              "reference": {
                "fields": [
                  "id_processo"
                ],
                "resource": "dm_processo"
              }
            },
            {
              "fields": [
                "id_situacao_cont"
              ],
              "reference": {
                "fields": [
                  "id_situacao_cont"
                ],
                "resource": "dm_situacao_cont"
              }
            },
            {
              "fields": [
                "id_situacao_proc"
              ],
              "reference": {
                "fields": [
                  "id_situacao_proc"
                ],
                "resource": "dm_situacao_proc"
              }
            },
            {
              "fields": [
                "id_linha_fornec"
              ],
              "reference": {
                "fields": [
                  "id_linha_fornec"
                ],
                "resource": "dm_linha_fornec"
              }
            },
            {
              "fields": [
                "id_classe_matserv"
              ],
              "reference": {
                "fields": [
                  "id_classe_matserv"
                ],
                "resource": "dm_classe_matserv"
              }
            },
            {
              "fields": [
                "id_tempo"
              ],
              "reference": {
                "fields": [
                  "id_tempo"
                ],
                "resource": "dm_tempo_diario"
              }
            },
            {
              "fields": [
                "id_municipio"
              ],
              "reference": {
                "fields": [
                  "id_municipio"
                ],
                "resource": "dm_municipio"
              }
            },
            {
              "fields": [
                "id_item_matserv"
              ],
              "reference": {
                "fields": [
                  "id_item_matserv"
                ],
                "resource": "dm_item_matserv"
              }
            },
            {
              "fields": [
                "id_tipo_licitacao"
              ],
              "reference": {
                "fields": [
                  "id_tipo_licitacao"
                ],
                "resource": "dm_tipo_licitacao"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_material_servico"
              ],
              "reference": {
                "fields": [
                  "id_material_servico"
                ],
                "resource": "dm_material_servico"
              }
            },
            {
              "fields": [
                "id_orgao_contrato"
              ],
              "reference": {
                "fields": [
                  "id_orgao_contrato"
                ],
                "resource": "dm_orgao_contrato"
              }
            },
            {
              "fields": [
                "id_contrato"
              ],
              "reference": {
                "fields": [
                  "id_contrato"
                ],
                "resource": "dm_contrato"
              }
            },
            {
              "fields": [
                "id_orgao_demanda"
              ],
              "reference": {
                "fields": [
                  "id_orgao_demanda"
                ],
                "resource": "dm_orgao_demanda"
              }
            },
            {
              "fields": [
                "id_unidade_medida"
              ],
              "reference": {
                "fields": [
                  "id_unidade_medida"
                ],
                "resource": "dm_unidade_medida"
              }
            },
            {
              "fields": [
                "id_grupo_matserv"
              ],
              "reference": {
                "fields": [
                  "id_grupo_matserv"
                ],
                "resource": "dm_grupo_matserv"
              }
            },
            {
              "fields": [
                "id_contratado"
              ],
              "reference": {
                "fields": [
                  "id_contratado"
                ],
                "resource": "dm_contratado"
              }
            },
            {
              "fields": [
                "id_procedimento"
              ],
              "reference": {
                "fields": [
                  "id_procedimento"
                ],
                "resource": "dm_procedimento"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_compras"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "80fef268f9e578408d99794826059495",
          "bytes": 58460666,
          "fields": 27,
          "rows": 1919024
        }
      },
      "time": 409.43,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "44434",
            "1",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "73283",
            "1",
            "77",
            "187",
            "20450",
            "110021",
            "386042",
            "79225",
            "889",
            "1831904",
            "3144",
            "1760",
            "2022",
            "2023-01-09",
            "0.0000",
            "7200.0000",
            "7200.00",
            "7200.0000",
            "7200.00",
            "7200.00"
          ],
          "rowNumber": 1913595,
          "rowPosition": 1913596,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79225\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913596\" violates the foreign key: for \"id_contrato\": values \"79225\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44438",
            "4",
            "1831019",
            "95",
            "1",
            "1",
            "66",
            "34089",
            "1",
            "39",
            "130",
            "21730",
            "388167",
            "385180",
            "79223",
            "889",
            "1831805",
            "3067",
            "2000",
            "2022",
            "2022-12-26",
            "0.0000",
            "55250.5200",
            "55250.52",
            "54425.6300",
            "54425.63",
            "54425.63"
          ],
          "rowNumber": 1914106,
          "rowPosition": 1914107,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1914107\" violates the foreign key: for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44438",
            "4",
            "1831019",
            "95",
            "1",
            "1",
            "66",
            "34089",
            "1",
            "39",
            "834",
            "22816",
            "387932",
            "385180",
            "79223",
            "1729",
            "1831739",
            "3067",
            "2000",
            "2022",
            "2022-12-26",
            "0.0000",
            "1638.0000",
            "1638.00",
            "1419.7900",
            "1419.79",
            "1419.79"
          ],
          "rowNumber": 1914107,
          "rowPosition": 1914108,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1914108\" violates the foreign key: for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44438",
            "4",
            "1831019",
            "95",
            "1",
            "1",
            "66",
            "34089",
            "1",
            "39",
            "834",
            "22816",
            "388169",
            "385180",
            "79223",
            "1729",
            "1831739",
            "3067",
            "2000",
            "2022",
            "2022-12-26",
            "0.0000",
            "1482.0000",
            "1482.00",
            "1419.7900",
            "1419.79",
            "1419.79"
          ],
          "rowNumber": 1914108,
          "rowPosition": 1914109,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1914109\" violates the foreign key: for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44455",
            "2",
            "1831058",
            "54",
            "1",
            "1",
            "241",
            "40145",
            "1",
            "9",
            "581",
            "12418",
            "93129",
            "386068",
            "79226",
            "322",
            "1831697",
            "2932",
            "2012",
            "2022",
            "2023-01-11",
            "0.0000",
            "156000.0000",
            "156000.00",
            "156000.0000",
            "156000.00",
            "156000.00"
          ],
          "rowNumber": 1914109,
          "rowPosition": 1914110,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79226\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1914110\" violates the foreign key: for \"id_contrato\": values \"79226\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44438",
            "4",
            "1831019",
            "95",
            "1",
            "1",
            "66",
            "34089",
            "1",
            "39",
            "834",
            "22816",
            "387933",
            "385180",
            "79223",
            "1729",
            "1831739",
            "3067",
            "2000",
            "2022",
            "2022-12-26",
            "0.0000",
            "1638.0000",
            "1638.00",
            "1569.2500",
            "1569.25",
            "1569.25"
          ],
          "rowNumber": 1914277,
          "rowPosition": 1914278,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1914278\" violates the foreign key: for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44438",
            "4",
            "1831019",
            "95",
            "1",
            "1",
            "66",
            "34089",
            "1",
            "39",
            "834",
            "22816",
            "387936",
            "385180",
            "79223",
            "1729",
            "1831739",
            "3067",
            "2000",
            "2022",
            "2022-12-26",
            "0.0000",
            "1794.0000",
            "1794.00",
            "2465.9600",
            "2465.96",
            "2465.96"
          ],
          "rowNumber": 1914278,
          "rowPosition": 1914279,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1914279\" violates the foreign key: for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44438",
            "4",
            "1831019",
            "95",
            "1",
            "1",
            "66",
            "34089",
            "1",
            "39",
            "834",
            "22816",
            "387931",
            "385180",
            "79223",
            "1729",
            "1831739",
            "3067",
            "2000",
            "2022",
            "2022-12-26",
            "0.0000",
            "1638.0000",
            "1638.00",
            "1569.2500",
            "1569.25",
            "1569.25"
          ],
          "rowNumber": 1914279,
          "rowPosition": 1914280,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1914280\" violates the foreign key: for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44438",
            "4",
            "1831019",
            "95",
            "1",
            "1",
            "66",
            "34089",
            "1",
            "39",
            "834",
            "22816",
            "388168",
            "385180",
            "79223",
            "1729",
            "1831739",
            "3067",
            "2000",
            "2022",
            "2022-12-26",
            "0.0000",
            "1326.0000",
            "1326.00",
            "1419.7900",
            "1419.79",
            "1419.79"
          ],
          "rowNumber": 1914280,
          "rowPosition": 1914281,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1914281\" violates the foreign key: for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44438",
            "4",
            "1831019",
            "95",
            "1",
            "1",
            "66",
            "34089",
            "1",
            "39",
            "834",
            "22816",
            "387934",
            "385180",
            "79223",
            "1729",
            "1831739",
            "3067",
            "2000",
            "2022",
            "2022-12-26",
            "0.0000",
            "1326.0000",
            "1326.00",
            "1419.7900",
            "1419.79",
            "1419.79"
          ],
          "rowNumber": 1914281,
          "rowPosition": 1914282,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1914282\" violates the foreign key: for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44438",
            "4",
            "1831019",
            "95",
            "1",
            "1",
            "66",
            "34089",
            "1",
            "39",
            "834",
            "22816",
            "387937",
            "385180",
            "79223",
            "1729",
            "1831739",
            "3067",
            "2000",
            "2022",
            "2022-12-26",
            "0.0000",
            "1326.0000",
            "1326.00",
            "1419.7900",
            "1419.79",
            "1419.79"
          ],
          "rowNumber": 1914282,
          "rowPosition": 1914283,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1914283\" violates the foreign key: for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44438",
            "4",
            "1831019",
            "95",
            "1",
            "1",
            "66",
            "34089",
            "1",
            "39",
            "834",
            "22816",
            "388170",
            "385180",
            "79223",
            "1729",
            "1831739",
            "3067",
            "2000",
            "2022",
            "2022-12-26",
            "0.0000",
            "1170.0000",
            "1170.00",
            "1120.8900",
            "1120.89",
            "1120.89"
          ],
          "rowNumber": 1914283,
          "rowPosition": 1914284,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1914284\" violates the foreign key: for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44438",
            "4",
            "1831041",
            "95",
            "1",
            "1",
            "66",
            "34089",
            "1",
            "39",
            "130",
            "21730",
            "388167",
            "385114",
            "79223",
            "889",
            "1831805",
            "3067",
            "2689",
            "2022",
            "2022-12-26",
            "0.0000",
            "114751.0800",
            "114751.08",
            "113037.8600",
            "113037.86",
            "113037.86"
          ],
          "rowNumber": 1914747,
          "rowPosition": 1914748,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1914748\" violates the foreign key: for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44438",
            "4",
            "1831041",
            "95",
            "1",
            "1",
            "66",
            "34089",
            "1",
            "39",
            "834",
            "22816",
            "387932",
            "385114",
            "79223",
            "1729",
            "1831739",
            "3067",
            "2689",
            "2022",
            "2022-12-26",
            "0.0000",
            "3402.0000",
            "3402.00",
            "2948.8100",
            "2948.81",
            "2948.81"
          ],
          "rowNumber": 1914748,
          "rowPosition": 1914749,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1914749\" violates the foreign key: for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44438",
            "4",
            "1831041",
            "95",
            "1",
            "1",
            "66",
            "34089",
            "1",
            "39",
            "834",
            "22816",
            "388169",
            "385114",
            "79223",
            "1729",
            "1831739",
            "3067",
            "2689",
            "2022",
            "2022-12-26",
            "0.0000",
            "3078.0000",
            "3078.00",
            "2948.8100",
            "2948.81",
            "2948.81"
          ],
          "rowNumber": 1914749,
          "rowPosition": 1914750,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1914750\" violates the foreign key: for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44438",
            "4",
            "1831041",
            "95",
            "1",
            "1",
            "66",
            "34089",
            "1",
            "39",
            "834",
            "22816",
            "387933",
            "385114",
            "79223",
            "1729",
            "1831739",
            "3067",
            "2689",
            "2022",
            "2022-12-26",
            "0.0000",
            "3402.0000",
            "3402.00",
            "3259.2100",
            "3259.21",
            "3259.21"
          ],
          "rowNumber": 1914750,
          "rowPosition": 1914751,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1914751\" violates the foreign key: for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44438",
            "4",
            "1831041",
            "95",
            "1",
            "1",
            "66",
            "34089",
            "1",
            "39",
            "834",
            "22816",
            "387936",
            "385114",
            "79223",
            "1729",
            "1831739",
            "3067",
            "2689",
            "2022",
            "2022-12-26",
            "0.0000",
            "3726.0000",
            "3726.00",
            "5121.6200",
            "5121.62",
            "5121.62"
          ],
          "rowNumber": 1914751,
          "rowPosition": 1914752,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1914752\" violates the foreign key: for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44438",
            "4",
            "1831041",
            "95",
            "1",
            "1",
            "66",
            "34089",
            "1",
            "39",
            "834",
            "22816",
            "387931",
            "385114",
            "79223",
            "1729",
            "1831739",
            "3067",
            "2689",
            "2022",
            "2022-12-26",
            "0.0000",
            "3402.0000",
            "3402.00",
            "3259.2100",
            "3259.21",
            "3259.21"
          ],
          "rowNumber": 1914752,
          "rowPosition": 1914753,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1914753\" violates the foreign key: for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44438",
            "4",
            "1831041",
            "95",
            "1",
            "1",
            "66",
            "34089",
            "1",
            "39",
            "834",
            "22816",
            "388168",
            "385114",
            "79223",
            "1729",
            "1831739",
            "3067",
            "2689",
            "2022",
            "2022-12-26",
            "0.0000",
            "2754.0000",
            "2754.00",
            "2948.8100",
            "2948.81",
            "2948.81"
          ],
          "rowNumber": 1914753,
          "rowPosition": 1914754,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1914754\" violates the foreign key: for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44438",
            "4",
            "1831041",
            "95",
            "1",
            "1",
            "66",
            "34089",
            "1",
            "39",
            "834",
            "22816",
            "387934",
            "385114",
            "79223",
            "1729",
            "1831739",
            "3067",
            "2689",
            "2022",
            "2022-12-26",
            "0.0000",
            "2754.0000",
            "2754.00",
            "2948.8100",
            "2948.81",
            "2948.81"
          ],
          "rowNumber": 1914754,
          "rowPosition": 1914755,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1914755\" violates the foreign key: for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44438",
            "4",
            "1831041",
            "95",
            "1",
            "1",
            "66",
            "34089",
            "1",
            "39",
            "834",
            "22816",
            "387937",
            "385114",
            "79223",
            "1729",
            "1831739",
            "3067",
            "2689",
            "2022",
            "2022-12-26",
            "0.0000",
            "2754.0000",
            "2754.00",
            "2948.8100",
            "2948.81",
            "2948.81"
          ],
          "rowNumber": 1914755,
          "rowPosition": 1914756,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1914756\" violates the foreign key: for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44438",
            "4",
            "1831041",
            "95",
            "1",
            "1",
            "66",
            "34089",
            "1",
            "39",
            "834",
            "22816",
            "388170",
            "385114",
            "79223",
            "1729",
            "1831739",
            "3067",
            "2689",
            "2022",
            "2022-12-26",
            "0.0000",
            "2430.0000",
            "2430.00",
            "2328.0100",
            "2328.01",
            "2328.01"
          ],
          "rowNumber": 1914756,
          "rowPosition": 1914757,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1914757\" violates the foreign key: for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44438",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "34089",
            "1",
            "39",
            "130",
            "21730",
            "388167",
            "385189",
            "79223",
            "889",
            "1831805",
            "3067",
            "3043",
            "2022",
            "2022-12-26",
            "0.0000",
            "255002.4000",
            "255002.40",
            "251195.2500",
            "251195.25",
            "251195.25"
          ],
          "rowNumber": 1915937,
          "rowPosition": 1915938,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1915938\" violates the foreign key: for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44438",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "34089",
            "1",
            "39",
            "834",
            "22816",
            "387932",
            "385189",
            "79223",
            "1729",
            "1831739",
            "3067",
            "3043",
            "2022",
            "2022-12-26",
            "0.0000",
            "7560.0000",
            "7560.00",
            "6552.9100",
            "6552.91",
            "6552.91"
          ],
          "rowNumber": 1915938,
          "rowPosition": 1915939,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1915939\" violates the foreign key: for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44438",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "34089",
            "1",
            "39",
            "834",
            "22816",
            "388169",
            "385189",
            "79223",
            "1729",
            "1831739",
            "3067",
            "3043",
            "2022",
            "2022-12-26",
            "0.0000",
            "6840.0000",
            "6840.00",
            "6552.9100",
            "6552.91",
            "6552.91"
          ],
          "rowNumber": 1915939,
          "rowPosition": 1915940,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1915940\" violates the foreign key: for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44438",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "34089",
            "1",
            "39",
            "834",
            "22816",
            "387933",
            "385189",
            "79223",
            "1729",
            "1831739",
            "3067",
            "3043",
            "2022",
            "2022-12-26",
            "0.0000",
            "7560.0000",
            "7560.00",
            "7242.7000",
            "7242.70",
            "7242.70"
          ],
          "rowNumber": 1915940,
          "rowPosition": 1915941,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1915941\" violates the foreign key: for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44438",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "34089",
            "1",
            "39",
            "834",
            "22816",
            "387936",
            "385189",
            "79223",
            "1729",
            "1831739",
            "3067",
            "3043",
            "2022",
            "2022-12-26",
            "0.0000",
            "8280.0000",
            "8280.00",
            "11381.3800",
            "11381.38",
            "11381.38"
          ],
          "rowNumber": 1915941,
          "rowPosition": 1915942,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1915942\" violates the foreign key: for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44438",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "34089",
            "1",
            "39",
            "834",
            "22816",
            "387931",
            "385189",
            "79223",
            "1729",
            "1831739",
            "3067",
            "3043",
            "2022",
            "2022-12-26",
            "0.0000",
            "7560.0000",
            "7560.00",
            "7242.7000",
            "7242.70",
            "7242.70"
          ],
          "rowNumber": 1915942,
          "rowPosition": 1915943,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1915943\" violates the foreign key: for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44438",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "34089",
            "1",
            "39",
            "834",
            "22816",
            "388168",
            "385189",
            "79223",
            "1729",
            "1831739",
            "3067",
            "3043",
            "2022",
            "2022-12-26",
            "0.0000",
            "6120.0000",
            "6120.00",
            "6552.9100",
            "6552.91",
            "6552.91"
          ],
          "rowNumber": 1915943,
          "rowPosition": 1915944,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1915944\" violates the foreign key: for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44438",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "34089",
            "1",
            "39",
            "834",
            "22816",
            "387934",
            "385189",
            "79223",
            "1729",
            "1831739",
            "3067",
            "3043",
            "2022",
            "2022-12-26",
            "0.0000",
            "6120.0000",
            "6120.00",
            "6552.9100",
            "6552.91",
            "6552.91"
          ],
          "rowNumber": 1915944,
          "rowPosition": 1915945,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1915945\" violates the foreign key: for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44438",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "34089",
            "1",
            "39",
            "834",
            "22816",
            "387937",
            "385189",
            "79223",
            "1729",
            "1831739",
            "3067",
            "3043",
            "2022",
            "2022-12-26",
            "0.0000",
            "6120.0000",
            "6120.00",
            "6552.9100",
            "6552.91",
            "6552.91"
          ],
          "rowNumber": 1915945,
          "rowPosition": 1915946,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1915946\" violates the foreign key: for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44438",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "34089",
            "1",
            "39",
            "834",
            "22816",
            "388170",
            "385189",
            "79223",
            "1729",
            "1831739",
            "3067",
            "3043",
            "2022",
            "2022-12-26",
            "0.0000",
            "5400.0000",
            "5400.00",
            "5173.3500",
            "5173.35",
            "5173.35"
          ],
          "rowNumber": 1915946,
          "rowPosition": 1915947,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1915947\" violates the foreign key: for \"id_contrato\": values \"79223\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43970",
            "4",
            "1831095",
            "96",
            "1",
            "1",
            "448",
            "23602",
            "1",
            "51",
            "383",
            "1831",
            "94055",
            "386012",
            "79227",
            "889",
            "1831360",
            "2670",
            "3293",
            "2022",
            "2023-01-05",
            "0.0000",
            "276468.3000",
            "276468.30",
            "198899.7000",
            "198899.70",
            "198899.70"
          ],
          "rowNumber": 1918655,
          "rowPosition": 1918656,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79227\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918656\" violates the foreign key: for \"id_contrato\": values \"79227\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43970",
            "4",
            "1831095",
            "96",
            "1",
            "1",
            "883",
            "23602",
            "1",
            "51",
            "383",
            "1831",
            "94055",
            "386012",
            "79227",
            "889",
            "1831360",
            "2670",
            "3293",
            "2022",
            "2023-01-05",
            "0.0000",
            "513168.3400",
            "513168.34",
            "258999.9700",
            "258999.97",
            "258999.97"
          ],
          "rowNumber": 1918656,
          "rowPosition": 1918657,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79227\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918657\" violates the foreign key: for \"id_contrato\": values \"79227\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44493",
            "14",
            "1831034",
            "50",
            "1",
            "8",
            "548",
            "73507",
            "1",
            "38",
            "444",
            "11583",
            "404794",
            "386215",
            "46296",
            "889",
            "1831189",
            "2658",
            "1760",
            "2023",
            "2023-01-24",
            "1.0000",
            "4622.5000",
            "4622.50",
            "4215.0000",
            "4215.00",
            "4215.00"
          ],
          "rowNumber": 1918931,
          "rowPosition": 1918932,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contratado\": values \"73507\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "message": "Row at position \"1918932\" violates the foreign key: for \"id_contratado\": values \"73507\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44493",
            "14",
            "1831034",
            "50",
            "1",
            "8",
            "548",
            "73507",
            "1",
            "38",
            "444",
            "2977",
            "405867",
            "386215",
            "46296",
            "889",
            "1831189",
            "2658",
            "1760",
            "2023",
            "2023-01-24",
            "1.0000",
            "10474.0000",
            "10474.00",
            "8105.0000",
            "8105.00",
            "8105.00"
          ],
          "rowNumber": 1918932,
          "rowPosition": 1918933,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contratado\": values \"73507\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "message": "Row at position \"1918933\" violates the foreign key: for \"id_contratado\": values \"73507\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "48971",
            "5",
            "1831084",
            "81",
            "1",
            "1",
            "856",
            "20415",
            "1",
            "17",
            "175",
            "6976",
            "92592",
            "386210",
            "79224",
            "889",
            "1831350",
            "2613",
            "1859",
            "2021",
            "2023-01-24",
            "0.0000",
            "3929771.1000",
            "3929771.10",
            "2817299.5500",
            "2817299.55",
            "2817299.55"
          ],
          "rowNumber": 1919024,
          "rowPosition": 1919025,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79224\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1919025\" violates the foreign key: for \"id_contrato\": values \"79224\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 37
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 37,
    "tasks": 1
  },
  "valid": false
}