{
  "version": "4.38.0",
  "time": 413.813,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_compras",
        "title": "Compras",
        "path": "data/ft_compras.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_tempo",
              "title": "Tempo - Chave",
              "type": "integer",
              "format": "default",
              "description": "- > \n  Chave estrangeira (Foreign Key) que aponta para a Chave Primária (Primary keys) da tabela dm_tempo_diario. \n  Ou seja, por meio dessa chave é possível identificar a data completa a qual o dado se refere.\n\n  Nota: \n  No site dados.mg.gov.br a tabela dm_tempo_diario pode ser encontrada no recurso Calendários - Dias \n  de cada conjunto.\n",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_procedimento",
              "title": "Procedimento de Contratação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_demanda",
              "title": "Órgão Demandante - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_contrato",
              "title": "Órgão do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_proc",
              "title": "Situação do Processo de Compra - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_cont",
              "title": "Situação do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_municipio",
              "title": "Município - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contratado",
              "title": "Contratado - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_tipo_licitacao",
              "title": "Tipo de Licitação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_grupo_matserv",
              "title": "Grupo Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_classe_matserv",
              "title": "Classe Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_material_servico",
              "title": "Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item_matserv",
              "title": "Item Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_processo",
              "title": "Processo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contrato",
              "title": "Número do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_medida",
              "title": "Unidade de Medida - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_linha_fornec",
              "title": "Linha de Fornecimento - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_orc",
              "title": "Unidade Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "unique": false
              }
            },
            {
              "name": "ano_particao",
              "title": "Ano Partição",
              "type": "year",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true
              }
            },
            {
              "name": "dt_item_homologa",
              "title": "Data da Homologação do Item",
              "type": "date",
              "format": "default",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "qt_item_pedido",
              "title": "Item do Pedido - Quantidade",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_referencia",
              "title": "Valor Unitário de Referência",
              "description": "Valor unitário estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_referencia",
              "title": "Valor de Referência",
              "description": "Valor estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_homologado",
              "title": "Valor Unitário Homologado",
              "description": "Valor unitário final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_homologado",
              "title": "Valor Homologado",
              "description": "Valor final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_atualizado",
              "title": "Valor Atualizado",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_processo"
              ],
              "reference": {
                "fields": [
                  "id_processo"
                ],
                "resource": "dm_processo"
              }
            },
            {
              "fields": [
                "id_situacao_cont"
              ],
              "reference": {
                "fields": [
                  "id_situacao_cont"
                ],
                "resource": "dm_situacao_cont"
              }
            },
            {
              "fields": [
                "id_situacao_proc"
              ],
              "reference": {
                "fields": [
                  "id_situacao_proc"
                ],
                "resource": "dm_situacao_proc"
              }
            },
            {
              "fields": [
                "id_linha_fornec"
              ],
              "reference": {
                "fields": [
                  "id_linha_fornec"
                ],
                "resource": "dm_linha_fornec"
              }
            },
            {
              "fields": [
                "id_classe_matserv"
              ],
              "reference": {
                "fields": [
                  "id_classe_matserv"
                ],
                "resource": "dm_classe_matserv"
              }
            },
            {
              "fields": [
                "id_tempo"
              ],
              "reference": {
                "fields": [
                  "id_tempo"
                ],
                "resource": "dm_tempo_diario"
              }
            },
            {
              "fields": [
                "id_municipio"
              ],
              "reference": {
                "fields": [
                  "id_municipio"
                ],
                "resource": "dm_municipio"
              }
            },
            {
              "fields": [
                "id_item_matserv"
              ],
              "reference": {
                "fields": [
                  "id_item_matserv"
                ],
                "resource": "dm_item_matserv"
              }
            },
            {
              "fields": [
                "id_tipo_licitacao"
              ],
              "reference": {
                "fields": [
                  "id_tipo_licitacao"
                ],
                "resource": "dm_tipo_licitacao"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_material_servico"
              ],
              "reference": {
                "fields": [
                  "id_material_servico"
                ],
                "resource": "dm_material_servico"
              }
            },
            {
              "fields": [
                "id_orgao_contrato"
              ],
              "reference": {
                "fields": [
                  "id_orgao_contrato"
                ],
                "resource": "dm_orgao_contrato"
              }
            },
            {
              "fields": [
                "id_contrato"
              ],
              "reference": {
                "fields": [
                  "id_contrato"
                ],
                "resource": "dm_contrato"
              }
            },
            {
              "fields": [
                "id_orgao_demanda"
              ],
              "reference": {
                "fields": [
                  "id_orgao_demanda"
                ],
                "resource": "dm_orgao_demanda"
              }
            },
            {
              "fields": [
                "id_unidade_medida"
              ],
              "reference": {
                "fields": [
                  "id_unidade_medida"
                ],
                "resource": "dm_unidade_medida"
              }
            },
            {
              "fields": [
                "id_grupo_matserv"
              ],
              "reference": {
                "fields": [
                  "id_grupo_matserv"
                ],
                "resource": "dm_grupo_matserv"
              }
            },
            {
              "fields": [
                "id_contratado"
              ],
              "reference": {
                "fields": [
                  "id_contratado"
                ],
                "resource": "dm_contratado"
              }
            },
            {
              "fields": [
                "id_procedimento"
              ],
              "reference": {
                "fields": [
                  "id_procedimento"
                ],
                "resource": "dm_procedimento"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_compras"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "88b600552f0cce6a4c742bf62cc4ce6b",
          "bytes": 58457978,
          "fields": 27,
          "rows": 1918926
        }
      },
      "time": 413.813,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "43506",
            "4",
            "1831017",
            "12",
            "2",
            "1",
            "883",
            "36309",
            "1",
            "77",
            "479",
            "4803",
            "353977",
            "383368",
            "79216",
            "889",
            "1831808",
            "2602",
            "2842",
            "2022",
            "2022-12-01",
            "0.0000",
            "73384.0000",
            "73384.00",
            "73384.0000",
            "73384.00",
            "73384.00"
          ],
          "rowNumber": 1862575,
          "rowPosition": 1862576,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79216\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1862576\" violates the foreign key: for \"id_contrato\": values \"79216\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43506",
            "4",
            "1831017",
            "12",
            "2",
            "1",
            "883",
            "36309",
            "1",
            "77",
            "479",
            "4803",
            "353981",
            "383368",
            "79216",
            "889",
            "1831808",
            "2602",
            "2842",
            "2022",
            "2022-12-01",
            "0.0000",
            "66768.0000",
            "66768.00",
            "66496.0000",
            "66496.00",
            "66496.00"
          ],
          "rowNumber": 1862576,
          "rowPosition": 1862577,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79216\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1862577\" violates the foreign key: for \"id_contrato\": values \"79216\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43506",
            "4",
            "1831017",
            "12",
            "2",
            "1",
            "883",
            "36309",
            "1",
            "77",
            "479",
            "12282",
            "353990",
            "383368",
            "79216",
            "889",
            "1831808",
            "2602",
            "2842",
            "2022",
            "2022-12-01",
            "0.0000",
            "56764.0000",
            "56764.00",
            "56764.0000",
            "56764.00",
            "56764.00"
          ],
          "rowNumber": 1862577,
          "rowPosition": 1862578,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79216\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1862578\" violates the foreign key: for \"id_contrato\": values \"79216\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43506",
            "4",
            "1831017",
            "12",
            "2",
            "1",
            "883",
            "36309",
            "1",
            "77",
            "479",
            "12282",
            "353980",
            "383368",
            "79216",
            "889",
            "1831808",
            "2602",
            "2842",
            "2022",
            "2022-12-01",
            "0.0000",
            "64239.0000",
            "64239.00",
            "64239.0000",
            "64239.00",
            "64239.00"
          ],
          "rowNumber": 1862578,
          "rowPosition": 1862579,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79216\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1862579\" violates the foreign key: for \"id_contrato\": values \"79216\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43506",
            "4",
            "1831017",
            "12",
            "2",
            "1",
            "883",
            "36309",
            "1",
            "77",
            "479",
            "12282",
            "353984",
            "383368",
            "79216",
            "889",
            "1831808",
            "2602",
            "2842",
            "2022",
            "2022-12-01",
            "0.0000",
            "12570.0000",
            "12570.00",
            "12570.0000",
            "12570.00",
            "12570.00"
          ],
          "rowNumber": 1862579,
          "rowPosition": 1862580,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79216\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1862580\" violates the foreign key: for \"id_contrato\": values \"79216\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43506",
            "4",
            "1831017",
            "12",
            "2",
            "1",
            "883",
            "36309",
            "1",
            "77",
            "479",
            "4803",
            "353988",
            "383368",
            "79216",
            "889",
            "1831808",
            "2602",
            "2842",
            "2022",
            "2022-12-01",
            "0.0000",
            "20115.4500",
            "20115.45",
            "20115.0000",
            "20115.00",
            "20115.00"
          ],
          "rowNumber": 1862580,
          "rowPosition": 1862581,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79216\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1862581\" violates the foreign key: for \"id_contrato\": values \"79216\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43506",
            "4",
            "1831017",
            "12",
            "2",
            "1",
            "883",
            "36309",
            "1",
            "77",
            "479",
            "4803",
            "353979",
            "383368",
            "79216",
            "889",
            "1831808",
            "2602",
            "2842",
            "2022",
            "2022-12-01",
            "0.0000",
            "11719.4000",
            "11719.40",
            "11718.0000",
            "11718.00",
            "11718.00"
          ],
          "rowNumber": 1862581,
          "rowPosition": 1862582,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79216\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1862582\" violates the foreign key: for \"id_contrato\": values \"79216\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43562",
            "15",
            "1831059",
            "57",
            "1",
            "1",
            "844",
            "39472",
            "1",
            "54",
            "119",
            "17031",
            "142864",
            "378685",
            "79214",
            "889",
            "1831296",
            "2944",
            "2081",
            "2022",
            "2022-09-27",
            "20.0000",
            "2942.5000",
            "58850.00",
            "2942.5000",
            "58850.00",
            "58850.00"
          ],
          "rowNumber": 1901378,
          "rowPosition": 1901379,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79214\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1901379\" violates the foreign key: for \"id_contrato\": values \"79214\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43562",
            "15",
            "1831059",
            "57",
            "1",
            "1",
            "844",
            "39472",
            "1",
            "54",
            "9",
            "17198",
            "123088",
            "378685",
            "79214",
            "889",
            "1831296",
            "2944",
            "2081",
            "2022",
            "2022-09-27",
            "6.0000",
            "2200.0000",
            "13200.00",
            "2200.0000",
            "13200.00",
            "13200.00"
          ],
          "rowNumber": 1901379,
          "rowPosition": 1901380,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79214\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1901380\" violates the foreign key: for \"id_contrato\": values \"79214\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43562",
            "15",
            "1831059",
            "57",
            "1",
            "1",
            "844",
            "39472",
            "1",
            "54",
            "9",
            "17198",
            "146904",
            "378685",
            "79214",
            "889",
            "1831296",
            "2944",
            "2081",
            "2022",
            "2022-09-27",
            "114.0000",
            "1761.8500",
            "200850.90",
            "1761.8500",
            "200850.90",
            "200850.90"
          ],
          "rowNumber": 1901380,
          "rowPosition": 1901381,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79214\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1901381\" violates the foreign key: for \"id_contrato\": values \"79214\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43562",
            "15",
            "1831059",
            "57",
            "1",
            "1",
            "844",
            "39472",
            "1",
            "54",
            "502",
            "4062",
            "138493",
            "378685",
            "79214",
            "889",
            "1831296",
            "2944",
            "2081",
            "2022",
            "2022-09-27",
            "130.0000",
            "1965.0000",
            "255450.00",
            "1965.0000",
            "255450.00",
            "255450.00"
          ],
          "rowNumber": 1901381,
          "rowPosition": 1901382,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79214\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1901382\" violates the foreign key: for \"id_contrato\": values \"79214\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44009",
            "2",
            "1831084",
            "81",
            "1",
            "1",
            "600",
            "22000",
            "1",
            "77",
            "73",
            "9726",
            "92493",
            "386170",
            "79218",
            "322",
            "1831901",
            "2623",
            "1859",
            "2022",
            "2023-01-20",
            "0.0000",
            "16076.6200",
            "16076.62",
            "16076.6200",
            "16076.62",
            "16076.62"
          ],
          "rowNumber": 1913360,
          "rowPosition": 1913361,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79218\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913361\" violates the foreign key: for \"id_contrato\": values \"79218\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44440",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "73038",
            "1",
            "77",
            "73",
            "7572",
            "143155",
            "386080",
            "79219",
            "889",
            "1831761",
            "2872",
            "3042",
            "2022",
            "2023-01-12",
            "0.0000",
            "8578.0000",
            "8578.00",
            "1905.9900",
            "1905.99",
            "1905.99"
          ],
          "rowNumber": 1913746,
          "rowPosition": 1913747,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79219\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913747\" violates the foreign key: for \"id_contrato\": values \"79219\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44440",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "73038",
            "1",
            "77",
            "73",
            "7572",
            "143155",
            "386080",
            "79219",
            "889",
            "1831761",
            "2872",
            "3042",
            "2022",
            "2023-01-12",
            "0.0000",
            "0.2700",
            "0.27",
            "3199.9500",
            "3199.95",
            "3199.95"
          ],
          "rowNumber": 1913747,
          "rowPosition": 1913748,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79219\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913748\" violates the foreign key: for \"id_contrato\": values \"79219\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44440",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "73038",
            "1",
            "66",
            "76",
            "4337",
            "90058",
            "386080",
            "79219",
            "889",
            "1831724",
            "2772",
            "3042",
            "2022",
            "2023-01-12",
            "0.0000",
            "75.6000",
            "75.60",
            "199999.9900",
            "199999.99",
            "199999.99"
          ],
          "rowNumber": 1913748,
          "rowPosition": 1913749,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79219\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913749\" violates the foreign key: for \"id_contrato\": values \"79219\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44440",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "73038",
            "1",
            "66",
            "76",
            "14973",
            "93918",
            "386080",
            "79219",
            "889",
            "1831724",
            "2772",
            "3042",
            "2022",
            "2023-01-12",
            "0.0000",
            "16000.0000",
            "16000.00",
            "0.0900",
            "0.09",
            "0.09"
          ],
          "rowNumber": 1913749,
          "rowPosition": 1913750,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79219\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913750\" violates the foreign key: for \"id_contrato\": values \"79219\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44440",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "73038",
            "1",
            "66",
            "76",
            "7035",
            "93917",
            "386080",
            "79219",
            "889",
            "1831724",
            "2772",
            "3042",
            "2022",
            "2023-01-12",
            "0.0000",
            "2500000.0000",
            "2500000.00",
            "0.0100",
            "0.01",
            "0.01"
          ],
          "rowNumber": 1913750,
          "rowPosition": 1913751,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79219\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913751\" violates the foreign key: for \"id_contrato\": values \"79219\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44440",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "73038",
            "1",
            "66",
            "76",
            "4337",
            "90059",
            "386080",
            "79219",
            "889",
            "1831724",
            "2772",
            "3042",
            "2022",
            "2023-01-12",
            "0.0000",
            "35784.0000",
            "35784.00",
            "0.0100",
            "0.01",
            "0.01"
          ],
          "rowNumber": 1913751,
          "rowPosition": 1913752,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79219\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913752\" violates the foreign key: for \"id_contrato\": values \"79219\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44440",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "73038",
            "1",
            "66",
            "76",
            "4337",
            "90057",
            "386080",
            "79219",
            "889",
            "1831724",
            "2772",
            "3042",
            "2022",
            "2023-01-12",
            "0.0000",
            "1789.9100",
            "1789.91",
            "0.0100",
            "0.01",
            "0.01"
          ],
          "rowNumber": 1913752,
          "rowPosition": 1913753,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79219\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913753\" violates the foreign key: for \"id_contrato\": values \"79219\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44440",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "73038",
            "1",
            "66",
            "76",
            "4337",
            "91084",
            "386080",
            "79219",
            "889",
            "1831724",
            "2772",
            "3042",
            "2022",
            "2023-01-12",
            "0.0000",
            "604.8000",
            "604.80",
            "0.0100",
            "0.01",
            "0.01"
          ],
          "rowNumber": 1913753,
          "rowPosition": 1913754,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79219\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913754\" violates the foreign key: for \"id_contrato\": values \"79219\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44440",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "73038",
            "1",
            "66",
            "76",
            "14973",
            "146182",
            "386080",
            "79219",
            "889",
            "1831724",
            "2772",
            "3042",
            "2022",
            "2023-01-12",
            "0.0000",
            "1760.0000",
            "1760.00",
            "0.0100",
            "0.01",
            "0.01"
          ],
          "rowNumber": 1913754,
          "rowPosition": 1913755,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79219\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913755\" violates the foreign key: for \"id_contrato\": values \"79219\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44440",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "73038",
            "1",
            "77",
            "73",
            "7572",
            "143155",
            "386080",
            "79219",
            "889",
            "1831761",
            "2872",
            "3294",
            "2022",
            "2023-01-12",
            "0.0000",
            "1906.0000",
            "1906.00",
            "8577.9900",
            "8577.99",
            "8577.99"
          ],
          "rowNumber": 1913756,
          "rowPosition": 1913757,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79219\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913757\" violates the foreign key: for \"id_contrato\": values \"79219\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44440",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "73038",
            "1",
            "77",
            "73",
            "7572",
            "143155",
            "386080",
            "79219",
            "889",
            "1831761",
            "2872",
            "3294",
            "2022",
            "2023-01-12",
            "0.0000",
            "0.0600",
            "0.06",
            "15999.9900",
            "15999.99",
            "15999.99"
          ],
          "rowNumber": 1913757,
          "rowPosition": 1913758,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79219\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913758\" violates the foreign key: for \"id_contrato\": values \"79219\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44440",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "73038",
            "1",
            "66",
            "76",
            "7035",
            "93917",
            "386080",
            "79219",
            "889",
            "1831724",
            "2772",
            "3294",
            "2022",
            "2023-01-12",
            "0.0000",
            "200000.0000",
            "200000.00",
            "2499999.8900",
            "2499999.89",
            "2499999.89"
          ],
          "rowNumber": 1913758,
          "rowPosition": 1913759,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79219\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913759\" violates the foreign key: for \"id_contrato\": values \"79219\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44440",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "73038",
            "1",
            "66",
            "76",
            "4337",
            "90057",
            "386080",
            "79219",
            "889",
            "1831724",
            "2772",
            "3294",
            "2022",
            "2023-01-12",
            "0.0000",
            "126.0500",
            "126.05",
            "0.0100",
            "0.01",
            "0.01"
          ],
          "rowNumber": 1913759,
          "rowPosition": 1913760,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79219\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913760\" violates the foreign key: for \"id_contrato\": values \"79219\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44440",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "73038",
            "1",
            "66",
            "76",
            "14973",
            "146182",
            "386080",
            "79219",
            "889",
            "1831724",
            "2772",
            "3294",
            "2022",
            "2023-01-12",
            "0.0000",
            "352.0000",
            "352.00",
            "0.0100",
            "0.01",
            "0.01"
          ],
          "rowNumber": 1913760,
          "rowPosition": 1913761,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79219\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913761\" violates the foreign key: for \"id_contrato\": values \"79219\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44440",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "73038",
            "1",
            "66",
            "76",
            "4337",
            "90059",
            "386080",
            "79219",
            "889",
            "1831724",
            "2772",
            "3294",
            "2022",
            "2023-01-12",
            "0.0000",
            "2520.0000",
            "2520.00",
            "0.0100",
            "0.01",
            "0.01"
          ],
          "rowNumber": 1913761,
          "rowPosition": 1913762,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79219\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913762\" violates the foreign key: for \"id_contrato\": values \"79219\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44440",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "73038",
            "1",
            "66",
            "76",
            "4337",
            "90058",
            "386080",
            "79219",
            "889",
            "1831724",
            "2772",
            "3294",
            "2022",
            "2023-01-12",
            "0.0000",
            "25.2000",
            "25.20",
            "0.0100",
            "0.01",
            "0.01"
          ],
          "rowNumber": 1913762,
          "rowPosition": 1913763,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79219\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913763\" violates the foreign key: for \"id_contrato\": values \"79219\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44440",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "73038",
            "1",
            "66",
            "76",
            "14973",
            "93918",
            "386080",
            "79219",
            "889",
            "1831724",
            "2772",
            "3294",
            "2022",
            "2023-01-12",
            "0.0000",
            "3200.0000",
            "3200.00",
            "0.0100",
            "0.01",
            "0.01"
          ],
          "rowNumber": 1913763,
          "rowPosition": 1913764,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79219\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913764\" violates the foreign key: for \"id_contrato\": values \"79219\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44440",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "73038",
            "1",
            "66",
            "76",
            "4337",
            "91084",
            "386080",
            "79219",
            "889",
            "1831724",
            "2772",
            "3294",
            "2022",
            "2023-01-12",
            "0.0000",
            "126.0000",
            "126.00",
            "0.0100",
            "0.01",
            "0.01"
          ],
          "rowNumber": 1913764,
          "rowPosition": 1913765,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79219\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913765\" violates the foreign key: for \"id_contrato\": values \"79219\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44057",
            "5",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "58505",
            "1",
            "17",
            "185",
            "20222",
            "92554",
            "385106",
            "79215",
            "889",
            "1831370",
            "2816",
            "1760",
            "2022",
            "2022-12-26",
            "0.0000",
            "9475252.0700",
            "9475252.07",
            "8442700.1400",
            "8442700.14",
            "8442700.14"
          ],
          "rowNumber": 1914105,
          "rowPosition": 1914106,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79215\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1914106\" violates the foreign key: for \"id_contrato\": values \"79215\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831030",
            "27",
            "1",
            "1",
            "821",
            "70897",
            "1",
            "51",
            "584",
            "9713",
            "92336",
            "385488",
            "79221",
            "889",
            "1831508",
            "2670",
            "2270",
            "2022",
            "2022-12-28",
            "0.0000",
            "19717.5000",
            "19717.50",
            "19700.0000",
            "19700.00",
            "19700.00"
          ],
          "rowNumber": 1916305,
          "rowPosition": 1916306,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79221\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916306\" violates the foreign key: for \"id_contrato\": values \"79221\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "4",
            "1831030",
            "27",
            "1",
            "1",
            "560",
            "70897",
            "1",
            "51",
            "584",
            "9713",
            "92336",
            "385488",
            "79221",
            "889",
            "1831508",
            "2670",
            "2270",
            "2022",
            "2022-12-28",
            "0.0000",
            "35850.0000",
            "35850.00",
            "35800.0000",
            "35800.00",
            "35800.00"
          ],
          "rowNumber": 1916306,
          "rowPosition": 1916307,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79221\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916307\" violates the foreign key: for \"id_contrato\": values \"79221\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44446",
            "1",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "10070",
            "1",
            "77",
            "808",
            "12309",
            "91623",
            "386156",
            "79222",
            "889",
            "1831741",
            "2902",
            "2925",
            "2022",
            "2023-01-19",
            "0.0000",
            "24000.0000",
            "24000.00",
            "24000.0000",
            "24000.00",
            "24000.00"
          ],
          "rowNumber": 1916504,
          "rowPosition": 1916505,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79222\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916505\" violates the foreign key: for \"id_contrato\": values \"79222\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44446",
            "1",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "10070",
            "1",
            "77",
            "808",
            "12309",
            "91623",
            "386156",
            "79222",
            "889",
            "1831741",
            "2902",
            "2925",
            "2022",
            "2023-01-19",
            "0.0000",
            "26400.0000",
            "26400.00",
            "26400.0000",
            "26400.00",
            "26400.00"
          ],
          "rowNumber": 1916505,
          "rowPosition": 1916506,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79222\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916506\" violates the foreign key: for \"id_contrato\": values \"79222\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43526",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "61564",
            "1",
            "77",
            "533",
            "4332",
            "95886",
            "386099",
            "79217",
            "98",
            "1831821",
            "2954",
            "2925",
            "2022",
            "2023-01-13",
            "0.0000",
            "79185.6000",
            "79185.60",
            "73872.0000",
            "73872.00",
            "73872.00"
          ],
          "rowNumber": 1916640,
          "rowPosition": 1916641,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79217\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916641\" violates the foreign key: for \"id_contrato\": values \"79217\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43526",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "61564",
            "1",
            "77",
            "533",
            "4332",
            "95886",
            "386099",
            "79217",
            "98",
            "1831821",
            "2954",
            "2925",
            "2022",
            "2023-01-13",
            "0.0000",
            "3133141.1300",
            "3133141.12",
            "2832498.7200",
            "2832498.72",
            "2832498.72"
          ],
          "rowNumber": 1916646,
          "rowPosition": 1916647,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79217\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916647\" violates the foreign key: for \"id_contrato\": values \"79217\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43970",
            "4",
            "1831095",
            "96",
            "1",
            "1",
            "883",
            "17782",
            "1",
            "51",
            "383",
            "1831",
            "94055",
            "386012",
            "79220",
            "889",
            "1831360",
            "2670",
            "3293",
            "2022",
            "2023-01-05",
            "0.0000",
            "678942.1800",
            "678942.18",
            "495000.0000",
            "495000.00",
            "495000.00"
          ],
          "rowNumber": 1918657,
          "rowPosition": 1918658,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79220\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918658\" violates the foreign key: for \"id_contrato\": values \"79220\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43970",
            "4",
            "1831095",
            "96",
            "1",
            "1",
            "883",
            "17782",
            "1",
            "51",
            "383",
            "1831",
            "94055",
            "386012",
            "79220",
            "889",
            "1831360",
            "2670",
            "3293",
            "2022",
            "2023-01-05",
            "0.0000",
            "522109.8400",
            "522109.84",
            "432388.4800",
            "432388.48",
            "432388.48"
          ],
          "rowNumber": 1918658,
          "rowPosition": 1918659,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79220\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918659\" violates the foreign key: for \"id_contrato\": values \"79220\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43970",
            "4",
            "1831095",
            "96",
            "1",
            "1",
            "883",
            "17782",
            "1",
            "51",
            "383",
            "1831",
            "94055",
            "386012",
            "79220",
            "889",
            "1831360",
            "2670",
            "3293",
            "2022",
            "2023-01-05",
            "0.0000",
            "411949.9400",
            "411949.94",
            "363163.7600",
            "363163.76",
            "363163.76"
          ],
          "rowNumber": 1918659,
          "rowPosition": 1918660,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79220\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918660\" violates the foreign key: for \"id_contrato\": values \"79220\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43970",
            "4",
            "1831095",
            "96",
            "1",
            "1",
            "883",
            "70093",
            "1",
            "51",
            "383",
            "1831",
            "94055",
            "386012",
            "79213",
            "889",
            "1831360",
            "2670",
            "3293",
            "2022",
            "2023-01-05",
            "0.0000",
            "675516.1000",
            "675516.10",
            "390429.1200",
            "390429.12",
            "390429.12"
          ],
          "rowNumber": 1918660,
          "rowPosition": 1918661,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79213\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918661\" violates the foreign key: for \"id_contrato\": values \"79213\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 41
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 41,
    "tasks": 1
  },
  "valid": false
}