{
  "version": "4.38.0",
  "time": 409.84,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_compras",
        "title": "Compras",
        "path": "data/ft_compras.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_tempo",
              "title": "Tempo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_procedimento",
              "title": "Procedimento de Contratação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_demanda",
              "title": "Órgão Demandante - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_contrato",
              "title": "Órgão do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_proc",
              "title": "Situação do Processo de Compra - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_cont",
              "title": "Situação do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_municipio",
              "title": "Município - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contratado",
              "title": "Contratado - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_tipo_licitacao",
              "title": "Tipo de Licitação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_grupo_matserv",
              "title": "Grupo Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_classe_matserv",
              "title": "Classe Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_material_servico",
              "title": "Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item_matserv",
              "title": "Item Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_processo",
              "title": "Processo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contrato",
              "title": "Número do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_medida",
              "title": "Unidade de Medida - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_linha_fornec",
              "title": "Linha de Fornecimento - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_orc",
              "title": "Unidade Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "unique": false
              }
            },
            {
              "name": "ano_particao",
              "title": "Ano Partição",
              "type": "year",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true
              }
            },
            {
              "name": "dt_item_homologa",
              "title": "Data da Homologação do Item",
              "type": "date",
              "format": "default",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "qt_item_pedido",
              "title": "Item do Pedido - Quantidade",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_referencia",
              "title": "Valor Unitário de Referência",
              "description": "Valor unitário estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_referencia",
              "title": "Valor de Referência",
              "description": "Valor estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_homologado",
              "title": "Valor Unitário Homologado",
              "description": "Valor unitário final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_homologado",
              "title": "Valor Homologado",
              "description": "Valor final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_atualizado",
              "title": "Valor Atualizado",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_processo"
              ],
              "reference": {
                "fields": [
                  "id_processo"
                ],
                "resource": "dm_processo"
              }
            },
            {
              "fields": [
                "id_situacao_cont"
              ],
              "reference": {
                "fields": [
                  "id_situacao_cont"
                ],
                "resource": "dm_situacao_cont"
              }
            },
            {
              "fields": [
                "id_situacao_proc"
              ],
              "reference": {
                "fields": [
                  "id_situacao_proc"
                ],
                "resource": "dm_situacao_proc"
              }
            },
            {
              "fields": [
                "id_linha_fornec"
              ],
              "reference": {
                "fields": [
                  "id_linha_fornec"
                ],
                "resource": "dm_linha_fornec"
              }
            },
            {
              "fields": [
                "id_classe_matserv"
              ],
              "reference": {
                "fields": [
                  "id_classe_matserv"
                ],
                "resource": "dm_classe_matserv"
              }
            },
            {
              "fields": [
                "id_tempo"
              ],
              "reference": {
                "fields": [
                  "id_tempo"
                ],
                "resource": "dm_tempo_diario"
              }
            },
            {
              "fields": [
                "id_municipio"
              ],
              "reference": {
                "fields": [
                  "id_municipio"
                ],
                "resource": "dm_municipio"
              }
            },
            {
              "fields": [
                "id_item_matserv"
              ],
              "reference": {
                "fields": [
                  "id_item_matserv"
                ],
                "resource": "dm_item_matserv"
              }
            },
            {
              "fields": [
                "id_tipo_licitacao"
              ],
              "reference": {
                "fields": [
                  "id_tipo_licitacao"
                ],
                "resource": "dm_tipo_licitacao"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_material_servico"
              ],
              "reference": {
                "fields": [
                  "id_material_servico"
                ],
                "resource": "dm_material_servico"
              }
            },
            {
              "fields": [
                "id_orgao_contrato"
              ],
              "reference": {
                "fields": [
                  "id_orgao_contrato"
                ],
                "resource": "dm_orgao_contrato"
              }
            },
            {
              "fields": [
                "id_contrato"
              ],
              "reference": {
                "fields": [
                  "id_contrato"
                ],
                "resource": "dm_contrato"
              }
            },
            {
              "fields": [
                "id_orgao_demanda"
              ],
              "reference": {
                "fields": [
                  "id_orgao_demanda"
                ],
                "resource": "dm_orgao_demanda"
              }
            },
            {
              "fields": [
                "id_unidade_medida"
              ],
              "reference": {
                "fields": [
                  "id_unidade_medida"
                ],
                "resource": "dm_unidade_medida"
              }
            },
            {
              "fields": [
                "id_grupo_matserv"
              ],
              "reference": {
                "fields": [
                  "id_grupo_matserv"
                ],
                "resource": "dm_grupo_matserv"
              }
            },
            {
              "fields": [
                "id_contratado"
              ],
              "reference": {
                "fields": [
                  "id_contratado"
                ],
                "resource": "dm_contratado"
              }
            },
            {
              "fields": [
                "id_procedimento"
              ],
              "reference": {
                "fields": [
                  "id_procedimento"
                ],
                "resource": "dm_procedimento"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_compras"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "1600799f945b76f83f4cb71ad7d837c9",
          "bytes": 57820497,
          "fields": 27,
          "rows": 1896213
        }
      },
      "time": 409.84,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "44403",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "860",
            "34040",
            "1",
            "77",
            "700",
            "14929",
            "93680",
            "380833",
            "77873",
            "889",
            "1831700",
            "2553",
            "1760",
            "2022",
            "2022-10-26",
            "0.0000",
            "30311469.3600",
            "30311469.36",
            "30311469.3600",
            "30311469.36",
            "30311469.36"
          ],
          "rowNumber": 1813358,
          "rowPosition": 1813359,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77873\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813359\" violates the foreign key: for \"id_contrato\": values \"77873\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44403",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "860",
            "34040",
            "1",
            "77",
            "700",
            "17682",
            "93674",
            "380833",
            "77873",
            "889",
            "1831731",
            "2879",
            "1760",
            "2022",
            "2022-10-26",
            "0.0000",
            "15564090.3600",
            "15564090.36",
            "15564090.3600",
            "15564090.36",
            "15564090.36"
          ],
          "rowNumber": 1813359,
          "rowPosition": 1813360,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77873\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813360\" violates the foreign key: for \"id_contrato\": values \"77873\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44404",
            "15",
            "1831027",
            "22",
            "1",
            "1",
            "883",
            "379",
            "1",
            "57",
            "779",
            "16006",
            "118342",
            "380887",
            "77864",
            "190",
            "1831313",
            "2928",
            "2045",
            "2022",
            "2022-10-26",
            "17000.0000",
            "5.6300",
            "95686.20",
            "5.6300",
            "95686.20",
            "95686.20"
          ],
          "rowNumber": 1813360,
          "rowPosition": 1813361,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77864\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813361\" violates the foreign key: for \"id_contrato\": values \"77864\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44404",
            "15",
            "1831027",
            "22",
            "1",
            "1",
            "883",
            "379",
            "1",
            "57",
            "779",
            "2941",
            "5465",
            "380887",
            "77864",
            "190",
            "1831313",
            "2928",
            "2045",
            "2022",
            "2022-10-26",
            "40000.0000",
            "3.9300",
            "157044.00",
            "3.9300",
            "157044.00",
            "157044.00"
          ],
          "rowNumber": 1813361,
          "rowPosition": 1813362,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77864\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813362\" violates the foreign key: for \"id_contrato\": values \"77864\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43569",
            "14",
            "1831105",
            "91",
            "1",
            "1",
            "291",
            "72327",
            "1",
            "77",
            "188",
            "12311",
            "91631",
            "379205",
            "77854",
            "889",
            "1831769",
            "2590",
            "3042",
            "2022",
            "2022-10-05",
            "0.0000",
            "5700.0000",
            "5700.00",
            "5700.0000",
            "5700.00",
            "5700.00"
          ],
          "rowNumber": 1818613,
          "rowPosition": 1818614,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77854\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1818614\" violates the foreign key: for \"id_contrato\": values \"77854\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44413",
            "4",
            "1831058",
            "54",
            "1",
            "1",
            "825",
            "2133",
            "1",
            "51",
            "75",
            "14915",
            "112967",
            "381411",
            "77874",
            "889",
            "1831500",
            "2670",
            "2012",
            "2022",
            "2022-11-08",
            "0.0000",
            "471.2100",
            "471.21",
            "471.2100",
            "471.21",
            "471.21"
          ],
          "rowNumber": 1820150,
          "rowPosition": 1820151,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77874\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1820151\" violates the foreign key: for \"id_contrato\": values \"77874\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44417",
            "21",
            "1831018",
            "11",
            "1",
            "1",
            "66",
            "9472",
            "1",
            "8",
            "687",
            "12333",
            "92275",
            "381445",
            "77861",
            "889",
            "1831039",
            "2883",
            "2008",
            "2022",
            "2022-11-08",
            "0.0000",
            "3700000.0000",
            "3700000.00",
            "3700000.0000",
            "3700000.00",
            "3700000.00"
          ],
          "rowNumber": 1820151,
          "rowPosition": 1820152,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77861\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1820152\" violates the foreign key: for \"id_contrato\": values \"77861\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43555",
            "4",
            "1831016",
            "16",
            "1",
            "1",
            "66",
            "17782",
            "1",
            "51",
            "383",
            "17638",
            "92858",
            "381112",
            "77875",
            "889",
            "1831360",
            "2670",
            "2082",
            "2022",
            "2022-10-28",
            "0.0000",
            "21493.0100",
            "21493.01",
            "17799.4000",
            "17799.40",
            "17799.40"
          ],
          "rowNumber": 1820542,
          "rowPosition": 1820543,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77875\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1820543\" violates the foreign key: for \"id_contrato\": values \"77875\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44406",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "876",
            "67434",
            "1",
            "3",
            "627",
            "91",
            "147574",
            "381092",
            "77858",
            "889",
            "1831295",
            "2611",
            "3043",
            "2022",
            "2022-10-28",
            "3.0000",
            "2185.0000",
            "6555.00",
            "2185.0000",
            "6555.00",
            "6555.00"
          ],
          "rowNumber": 1821417,
          "rowPosition": 1821418,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77858\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1821418\" violates the foreign key: for \"id_contrato\": values \"77858\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44406",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "876",
            "68447",
            "1",
            "3",
            "627",
            "16158",
            "147571",
            "381039",
            "77855",
            "889",
            "1831295",
            "2611",
            "3043",
            "2022",
            "2022-10-28",
            "24.0000",
            "1227.0000",
            "29448.00",
            "1227.0000",
            "29448.00",
            "29448.00"
          ],
          "rowNumber": 1821418,
          "rowPosition": 1821419,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77855\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1821419\" violates the foreign key: for \"id_contrato\": values \"77855\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44405",
            "17",
            "1831044",
            "36",
            "1",
            "1",
            "66",
            "68228",
            "1",
            "82",
            "44",
            "21766",
            "178376",
            "381115",
            "77863",
            "889",
            "1831189",
            "3088",
            "2633",
            "2022",
            "2022-10-29",
            "295.0000",
            "339.0000",
            "100005.00",
            "339.0000",
            "100005.00",
            "100005.00"
          ],
          "rowNumber": 1821452,
          "rowPosition": 1821453,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77863\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1821453\" violates the foreign key: for \"id_contrato\": values \"77863\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44408",
            "17",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "64989",
            "1",
            "3",
            "627",
            "19215",
            "301917",
            "381170",
            "77871",
            "889",
            "1831295",
            "2611",
            "3043",
            "2022",
            "2022-11-03",
            "1.0000",
            "14550.0000",
            "14550.00",
            "14550.0000",
            "14550.00",
            "14550.00"
          ],
          "rowNumber": 1825020,
          "rowPosition": 1825021,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77871\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1825021\" violates the foreign key: for \"id_contrato\": values \"77871\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43554",
            "1",
            "1831058",
            "54",
            "1",
            "1",
            "66",
            "19919",
            "1",
            "77",
            "700",
            "14929",
            "93680",
            "380073",
            "77856",
            "889",
            "1831700",
            "2553",
            "2012",
            "2022",
            "2022-10-17",
            "0.0000",
            "246592.4800",
            "246592.48",
            "246592.4800",
            "246592.48",
            "246592.48"
          ],
          "rowNumber": 1825685,
          "rowPosition": 1825686,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77856\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1825686\" violates the foreign key: for \"id_contrato\": values \"77856\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43536",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "60554",
            "1",
            "54",
            "502",
            "19883",
            "121256",
            "380315",
            "77876",
            "889",
            "1831296",
            "2944",
            "3294",
            "2022",
            "2022-10-19",
            "1.0000",
            "4500.0000",
            "4500.00",
            "3075.0000",
            "3075.00",
            "3075.00"
          ],
          "rowNumber": 1828406,
          "rowPosition": 1828407,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77876\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828407\" violates the foreign key: for \"id_contrato\": values \"77876\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43536",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "60554",
            "1",
            "54",
            "502",
            "19883",
            "213385",
            "380315",
            "77876",
            "889",
            "1831296",
            "2944",
            "3294",
            "2022",
            "2022-10-19",
            "1.0000",
            "1650.0000",
            "1650.00",
            "3075.0000",
            "3075.00",
            "3075.00"
          ],
          "rowNumber": 1828407,
          "rowPosition": 1828408,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77876\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828408\" violates the foreign key: for \"id_contrato\": values \"77876\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43583",
            "15",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "20941",
            "1",
            "77",
            "480",
            "17505",
            "90088",
            "380305",
            "77867",
            "889",
            "1831777",
            "3067",
            "1760",
            "2022",
            "2022-10-19",
            "68256.0000",
            "33.5800",
            "2292036.48",
            "33.5800",
            "2292036.48",
            "2292036.48"
          ],
          "rowNumber": 1828417,
          "rowPosition": 1828418,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77867\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828418\" violates the foreign key: for \"id_contrato\": values \"77867\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43583",
            "15",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "20941",
            "1",
            "3",
            "627",
            "3013",
            "308735",
            "380305",
            "77867",
            "889",
            "1831295",
            "2611",
            "1760",
            "2022",
            "2022-10-19",
            "4000.0000",
            "4634.0000",
            "18536000.00",
            "4634.0000",
            "18536000.00",
            "18536000.00"
          ],
          "rowNumber": 1828418,
          "rowPosition": 1828419,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77867\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828419\" violates the foreign key: for \"id_contrato\": values \"77867\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43583",
            "15",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "20941",
            "1",
            "3",
            "237",
            "11114",
            "173270",
            "380305",
            "77867",
            "889",
            "1831295",
            "2611",
            "1760",
            "2022",
            "2022-10-19",
            "4000.0000",
            "231.2400",
            "924960.00",
            "231.2400",
            "924960.00",
            "924960.00"
          ],
          "rowNumber": 1828419,
          "rowPosition": 1828420,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77867\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828420\" violates the foreign key: for \"id_contrato\": values \"77867\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43583",
            "15",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "20941",
            "1",
            "3",
            "306",
            "4541",
            "160342",
            "380305",
            "77867",
            "889",
            "1831295",
            "2584",
            "1760",
            "2022",
            "2022-10-19",
            "4000.0000",
            "97.0000",
            "388000.00",
            "97.0000",
            "388000.00",
            "388000.00"
          ],
          "rowNumber": 1828420,
          "rowPosition": 1828421,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77867\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828421\" violates the foreign key: for \"id_contrato\": values \"77867\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43583",
            "15",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "20941",
            "1",
            "30",
            "173",
            "4089",
            "93471",
            "380305",
            "77867",
            "889",
            "1831467",
            "3067",
            "1760",
            "2022",
            "2022-10-19",
            "4000.0000",
            "270.0000",
            "1080000.00",
            "270.0000",
            "1080000.00",
            "1080000.00"
          ],
          "rowNumber": 1828421,
          "rowPosition": 1828422,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77867\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828422\" violates the foreign key: for \"id_contrato\": values \"77867\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43583",
            "15",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "20941",
            "1",
            "3",
            "237",
            "11114",
            "173270",
            "380305",
            "77867",
            "889",
            "1831295",
            "2611",
            "1760",
            "2022",
            "2022-10-19",
            "1688.0000",
            "231.2400",
            "390333.12",
            "231.2400",
            "390333.12",
            "390333.12"
          ],
          "rowNumber": 1828423,
          "rowPosition": 1828424,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77867\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828424\" violates the foreign key: for \"id_contrato\": values \"77867\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43583",
            "15",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "20941",
            "1",
            "3",
            "306",
            "4541",
            "160342",
            "380305",
            "77867",
            "889",
            "1831295",
            "2584",
            "1760",
            "2022",
            "2022-10-19",
            "1688.0000",
            "97.0000",
            "163736.00",
            "97.0000",
            "163736.00",
            "163736.00"
          ],
          "rowNumber": 1828424,
          "rowPosition": 1828425,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77867\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828425\" violates the foreign key: for \"id_contrato\": values \"77867\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43583",
            "15",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "20941",
            "1",
            "3",
            "627",
            "3013",
            "308735",
            "380305",
            "77867",
            "889",
            "1831295",
            "2611",
            "1760",
            "2022",
            "2022-10-19",
            "1688.0000",
            "4634.0000",
            "7822192.00",
            "4634.0000",
            "7822192.00",
            "7822192.00"
          ],
          "rowNumber": 1828425,
          "rowPosition": 1828426,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77867\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828426\" violates the foreign key: for \"id_contrato\": values \"77867\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43583",
            "15",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "20941",
            "1",
            "3",
            "627",
            "3013",
            "308736",
            "380305",
            "77867",
            "889",
            "1831295",
            "2611",
            "1760",
            "2022",
            "2022-10-19",
            "491.0000",
            "5032.0000",
            "2470712.00",
            "5032.0000",
            "2470712.00",
            "2470712.00"
          ],
          "rowNumber": 1828427,
          "rowPosition": 1828428,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77867\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828428\" violates the foreign key: for \"id_contrato\": values \"77867\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43583",
            "15",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "20941",
            "1",
            "3",
            "237",
            "11114",
            "173270",
            "380305",
            "77867",
            "889",
            "1831295",
            "2611",
            "1760",
            "2022",
            "2022-10-19",
            "491.0000",
            "231.2400",
            "113538.84",
            "231.2400",
            "113538.84",
            "113538.84"
          ],
          "rowNumber": 1828428,
          "rowPosition": 1828429,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77867\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828429\" violates the foreign key: for \"id_contrato\": values \"77867\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43583",
            "15",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "20941",
            "1",
            "3",
            "306",
            "4541",
            "160342",
            "380305",
            "77867",
            "889",
            "1831295",
            "2584",
            "1760",
            "2022",
            "2022-10-19",
            "491.0000",
            "97.0000",
            "47627.00",
            "97.0000",
            "47627.00",
            "47627.00"
          ],
          "rowNumber": 1828429,
          "rowPosition": 1828430,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77867\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828430\" violates the foreign key: for \"id_contrato\": values \"77867\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43583",
            "15",
            "1831034",
            "21",
            "1",
            "1",
            "855",
            "20941",
            "1",
            "77",
            "480",
            "17505",
            "90088",
            "380305",
            "77867",
            "889",
            "1831777",
            "3067",
            "1760",
            "2022",
            "2022-10-19",
            "5892.0000",
            "33.5800",
            "197853.36",
            "33.5800",
            "197853.36",
            "197853.36"
          ],
          "rowNumber": 1828430,
          "rowPosition": 1828431,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77867\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828431\" violates the foreign key: for \"id_contrato\": values \"77867\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43570",
            "14",
            "1831066",
            "69",
            "1",
            "1",
            "66",
            "16304",
            "1",
            "77",
            "271",
            "7189",
            "107762",
            "380563",
            "77859",
            "889",
            "1831753",
            "3082",
            "2268",
            "2022",
            "2022-10-21",
            "0.0000",
            "14000.0000",
            "14000.00",
            "8900.0000",
            "8900.00",
            "8900.00"
          ],
          "rowNumber": 1828556,
          "rowPosition": 1828557,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77859\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1828557\" violates the foreign key: for \"id_contrato\": values \"77859\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43584",
            "14",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "61406",
            "1",
            "77",
            "533",
            "4338",
            "90067",
            "381018",
            "77866",
            "889",
            "1831751",
            "2807",
            "1760",
            "2022",
            "2022-10-28",
            "0.0000",
            "12731.5000",
            "12731.50",
            "12700.0000",
            "12700.00",
            "12700.00"
          ],
          "rowNumber": 1831283,
          "rowPosition": 1831284,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77866\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1831284\" violates the foreign key: for \"id_contrato\": values \"77866\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44405",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "883",
            "33019",
            "1",
            "3",
            "627",
            "3013",
            "226208",
            "380934",
            "77865",
            "889",
            "1831295",
            "2611",
            "3043",
            "2022",
            "2022-10-27",
            "1.0000",
            "4921.1000",
            "4921.10",
            "4921.1000",
            "4921.10",
            "4921.10"
          ],
          "rowNumber": 1847309,
          "rowPosition": 1847310,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77865\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1847310\" violates the foreign key: for \"id_contrato\": values \"77865\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43505",
            "4",
            "1831016",
            "16",
            "1",
            "1",
            "66",
            "39047",
            "1",
            "77",
            "700",
            "12265",
            "90066",
            "379085",
            "77877",
            "889",
            "1831564",
            "2774",
            "2082",
            "2022",
            "2022-10-04",
            "0.0000",
            "288637.2000",
            "288637.20",
            "134297.0800",
            "134297.08",
            "134297.08"
          ],
          "rowNumber": 1848013,
          "rowPosition": 1848014,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77877\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1848014\" violates the foreign key: for \"id_contrato\": values \"77877\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44405",
            "15",
            "1831065",
            "65",
            "1",
            "1",
            "883",
            "17536",
            "1",
            "48",
            "14",
            "7819",
            "330434",
            "380901",
            "77878",
            "889",
            "1831309",
            "3075",
            "2884",
            "2022",
            "2022-10-27",
            "39.0000",
            "85.1900",
            "3322.41",
            "74.9700",
            "2923.83",
            "2923.83"
          ],
          "rowNumber": 1854954,
          "rowPosition": 1854955,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77878\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1854955\" violates the foreign key: for \"id_contrato\": values \"77878\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44405",
            "15",
            "1831065",
            "65",
            "1",
            "1",
            "883",
            "17536",
            "1",
            "48",
            "313",
            "13424",
            "328650",
            "380901",
            "77878",
            "889",
            "1831309",
            "3075",
            "2884",
            "2022",
            "2022-10-27",
            "48.0000",
            "105.1700",
            "5048.16",
            "92.5500",
            "4442.40",
            "4442.40"
          ],
          "rowNumber": 1854955,
          "rowPosition": 1854956,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77878\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1854956\" violates the foreign key: for \"id_contrato\": values \"77878\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44405",
            "15",
            "1831065",
            "65",
            "1",
            "1",
            "883",
            "17536",
            "1",
            "48",
            "313",
            "15694",
            "330430",
            "380901",
            "77878",
            "889",
            "1831309",
            "3075",
            "2884",
            "2022",
            "2022-10-27",
            "72.0000",
            "79.5500",
            "5727.60",
            "70.0000",
            "5040.00",
            "5040.00"
          ],
          "rowNumber": 1854956,
          "rowPosition": 1854957,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77878\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1854957\" violates the foreign key: for \"id_contrato\": values \"77878\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44405",
            "15",
            "1831065",
            "65",
            "1",
            "1",
            "883",
            "17536",
            "1",
            "48",
            "128",
            "9473",
            "330650",
            "380901",
            "77878",
            "889",
            "1831309",
            "3075",
            "2884",
            "2022",
            "2022-10-27",
            "2.0000",
            "39.7700",
            "79.54",
            "35.0000",
            "70.00",
            "70.00"
          ],
          "rowNumber": 1854957,
          "rowPosition": 1854958,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77878\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1854958\" violates the foreign key: for \"id_contrato\": values \"77878\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44405",
            "15",
            "1831065",
            "65",
            "1",
            "1",
            "883",
            "17536",
            "1",
            "48",
            "14",
            "15750",
            "330438",
            "380901",
            "77878",
            "889",
            "1831309",
            "3075",
            "2884",
            "2022",
            "2022-10-27",
            "26.0000",
            "125.0000",
            "3250.00",
            "110.0000",
            "2860.00",
            "2860.00"
          ],
          "rowNumber": 1854958,
          "rowPosition": 1854959,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77878\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1854959\" violates the foreign key: for \"id_contrato\": values \"77878\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44405",
            "15",
            "1831065",
            "65",
            "1",
            "1",
            "883",
            "17536",
            "1",
            "48",
            "313",
            "13424",
            "330648",
            "380901",
            "77878",
            "889",
            "1831309",
            "3075",
            "2884",
            "2022",
            "2022-10-27",
            "2.0000",
            "106.2500",
            "212.50",
            "93.5000",
            "187.00",
            "187.00"
          ],
          "rowNumber": 1854959,
          "rowPosition": 1854960,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77878\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1854960\" violates the foreign key: for \"id_contrato\": values \"77878\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44405",
            "15",
            "1831065",
            "65",
            "1",
            "1",
            "883",
            "17536",
            "1",
            "48",
            "313",
            "15694",
            "330651",
            "380901",
            "77878",
            "889",
            "1831309",
            "3075",
            "2884",
            "2022",
            "2022-10-27",
            "2.0000",
            "79.5500",
            "159.10",
            "70.0000",
            "140.00",
            "140.00"
          ],
          "rowNumber": 1854960,
          "rowPosition": 1854961,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77878\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1854961\" violates the foreign key: for \"id_contrato\": values \"77878\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44405",
            "15",
            "1831065",
            "65",
            "1",
            "1",
            "883",
            "17536",
            "1",
            "48",
            "313",
            "15694",
            "330856",
            "380901",
            "77878",
            "889",
            "1831309",
            "3075",
            "2884",
            "2022",
            "2022-10-27",
            "1.0000",
            "69.0900",
            "69.09",
            "60.8000",
            "60.80",
            "60.80"
          ],
          "rowNumber": 1854961,
          "rowPosition": 1854962,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77878\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1854962\" violates the foreign key: for \"id_contrato\": values \"77878\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43565",
            "4",
            "1831097",
            "98",
            "1",
            "1",
            "883",
            "19282",
            "1",
            "42",
            "399",
            "10482",
            "312580",
            "380914",
            "77868",
            "1729",
            "1831230",
            "2923",
            "2078",
            "2022",
            "2022-10-27",
            "1.0000",
            "125000.0000",
            "125000.00",
            "69900.0000",
            "69900.00",
            "69900.00"
          ],
          "rowNumber": 1855908,
          "rowPosition": 1855909,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77868\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1855909\" violates the foreign key: for \"id_contrato\": values \"77868\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43565",
            "4",
            "1831097",
            "98",
            "1",
            "1",
            "883",
            "17398",
            "1",
            "42",
            "399",
            "10482",
            "168895",
            "380914",
            "77862",
            "1729",
            "1831230",
            "2923",
            "2078",
            "2022",
            "2022-10-27",
            "1.0000",
            "60000.0000",
            "60000.00",
            "25000.0000",
            "25000.00",
            "25000.00"
          ],
          "rowNumber": 1855909,
          "rowPosition": 1855910,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77862\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1855910\" violates the foreign key: for \"id_contrato\": values \"77862\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43565",
            "4",
            "1831097",
            "98",
            "1",
            "1",
            "883",
            "17398",
            "1",
            "42",
            "399",
            "333",
            "108754",
            "380914",
            "77862",
            "889",
            "1831230",
            "2923",
            "2078",
            "2022",
            "2022-10-27",
            "2.0000",
            "7500.0000",
            "15000.00",
            "5000.0000",
            "10000.00",
            "10000.00"
          ],
          "rowNumber": 1855910,
          "rowPosition": 1855911,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77862\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1855911\" violates the foreign key: for \"id_contrato\": values \"77862\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43565",
            "4",
            "1831097",
            "98",
            "1",
            "1",
            "883",
            "17398",
            "1",
            "42",
            "399",
            "10482",
            "168895",
            "380914",
            "77862",
            "1729",
            "1831230",
            "2923",
            "2078",
            "2022",
            "2022-10-27",
            "1.0000",
            "60000.0000",
            "60000.00",
            "26000.0000",
            "26000.00",
            "26000.00"
          ],
          "rowNumber": 1855911,
          "rowPosition": 1855912,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77862\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1855912\" violates the foreign key: for \"id_contrato\": values \"77862\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43565",
            "4",
            "1831097",
            "98",
            "1",
            "1",
            "883",
            "17398",
            "1",
            "42",
            "399",
            "333",
            "108754",
            "380914",
            "77862",
            "889",
            "1831230",
            "2923",
            "2078",
            "2022",
            "2022-10-27",
            "2.0000",
            "7500.0000",
            "15000.00",
            "5000.0000",
            "10000.00",
            "10000.00"
          ],
          "rowNumber": 1855912,
          "rowPosition": 1855913,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77862\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1855913\" violates the foreign key: for \"id_contrato\": values \"77862\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43583",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "876",
            "68447",
            "1",
            "3",
            "627",
            "16158",
            "147571",
            "380238",
            "77853",
            "889",
            "1831295",
            "2611",
            "3043",
            "2022",
            "2022-10-18",
            "1.0000",
            "1227.0000",
            "1227.00",
            "1227.0000",
            "1227.00",
            "1227.00"
          ],
          "rowNumber": 1872209,
          "rowPosition": 1872210,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77853\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1872210\" violates the foreign key: for \"id_contrato\": values \"77853\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43548",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "876",
            "30801",
            "1",
            "53",
            "722",
            "1230",
            "35982",
            "379906",
            "77860",
            "889",
            "1831301",
            "2584",
            "3043",
            "2022",
            "2022-10-14",
            "10.0000",
            "99.0000",
            "990.00",
            "119.0000",
            "1190.00",
            "1190.00"
          ],
          "rowNumber": 1892872,
          "rowPosition": 1892873,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77860\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1892873\" violates the foreign key: for \"id_contrato\": values \"77860\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43548",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "876",
            "30801",
            "1",
            "55",
            "674",
            "8608",
            "343011",
            "379906",
            "77860",
            "889",
            "1831986",
            "2744",
            "3043",
            "2022",
            "2022-10-14",
            "35.0000",
            "534.4800",
            "18706.80",
            "534.4800",
            "18706.80",
            "18706.80"
          ],
          "rowNumber": 1893599,
          "rowPosition": 1893600,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77860\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1893600\" violates the foreign key: for \"id_contrato\": values \"77860\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43548",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "876",
            "59537",
            "1",
            "44",
            "102",
            "5833",
            "102701",
            "379906",
            "77869",
            "889",
            "1831992",
            "2540",
            "3043",
            "2022",
            "2022-10-14",
            "30.0000",
            "15.0000",
            "450.00",
            "7.0000",
            "210.00",
            "210.00"
          ],
          "rowNumber": 1893601,
          "rowPosition": 1893602,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77869\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1893602\" violates the foreign key: for \"id_contrato\": values \"77869\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43548",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "876",
            "24550",
            "1",
            "73",
            "749",
            "127",
            "345166",
            "379906",
            "77872",
            "889",
            "1831974",
            "2685",
            "3043",
            "2022",
            "2022-10-14",
            "19.0000",
            "1697.0000",
            "32243.00",
            "1697.0000",
            "32243.00",
            "32243.00"
          ],
          "rowNumber": 1893602,
          "rowPosition": 1893603,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77872\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1893603\" violates the foreign key: for \"id_contrato\": values \"77872\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43548",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "876",
            "59801",
            "1",
            "3",
            "237",
            "15095",
            "115151",
            "379906",
            "77870",
            "889",
            "1831295",
            "2584",
            "3043",
            "2022",
            "2022-10-14",
            "50.0000",
            "173.8000",
            "8689.75",
            "105.5800",
            "5279.00",
            "5279.00"
          ],
          "rowNumber": 1893603,
          "rowPosition": 1893604,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77870\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1893604\" violates the foreign key: for \"id_contrato\": values \"77870\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43548",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "876",
            "59801",
            "1",
            "3",
            "237",
            "15095",
            "151931",
            "379906",
            "77870",
            "889",
            "1831295",
            "2584",
            "3043",
            "2022",
            "2022-10-14",
            "20.0000",
            "269.8000",
            "5396.00",
            "144.3000",
            "2886.00",
            "2886.00"
          ],
          "rowNumber": 1893604,
          "rowPosition": 1893605,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77870\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1893605\" violates the foreign key: for \"id_contrato\": values \"77870\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43548",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "876",
            "59801",
            "1",
            "3",
            "237",
            "15095",
            "173894",
            "379906",
            "77870",
            "889",
            "1831295",
            "2584",
            "3043",
            "2022",
            "2022-10-14",
            "20.0000",
            "300.0000",
            "6000.00",
            "223.0800",
            "4461.60",
            "4461.60"
          ],
          "rowNumber": 1893605,
          "rowPosition": 1893606,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77870\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1893606\" violates the foreign key: for \"id_contrato\": values \"77870\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43548",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "876",
            "59801",
            "1",
            "3",
            "237",
            "15095",
            "150580",
            "379906",
            "77870",
            "889",
            "1831295",
            "2584",
            "3043",
            "2022",
            "2022-10-14",
            "10.0000",
            "254.0900",
            "2540.90",
            "212.6900",
            "2126.90",
            "2126.90"
          ],
          "rowNumber": 1893606,
          "rowPosition": 1893607,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77870\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1893607\" violates the foreign key: for \"id_contrato\": values \"77870\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43548",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "876",
            "59801",
            "1",
            "3",
            "509",
            "12866",
            "190470",
            "379906",
            "77870",
            "889",
            "1831295",
            "2584",
            "3043",
            "2022",
            "2022-10-14",
            "60.0000",
            "427.5000",
            "25650.00",
            "213.3000",
            "12798.00",
            "12798.00"
          ],
          "rowNumber": 1893607,
          "rowPosition": 1893608,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77870\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1893608\" violates the foreign key: for \"id_contrato\": values \"77870\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43548",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "876",
            "59537",
            "1",
            "3",
            "306",
            "12537",
            "100239",
            "379906",
            "77869",
            "1510",
            "1831295",
            "2584",
            "3043",
            "2022",
            "2022-10-14",
            "10.0000",
            "891.9900",
            "8919.90",
            "791.5000",
            "7915.00",
            "7915.00"
          ],
          "rowNumber": 1893608,
          "rowPosition": 1893609,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77869\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1893609\" violates the foreign key: for \"id_contrato\": values \"77869\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43548",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "876",
            "30801",
            "1",
            "3",
            "143",
            "18490",
            "156568",
            "379906",
            "77860",
            "889",
            "1831295",
            "2584",
            "3043",
            "2022",
            "2022-10-14",
            "50.0000",
            "60.0000",
            "3000.00",
            "56.0000",
            "2800.00",
            "2800.00"
          ],
          "rowNumber": 1893609,
          "rowPosition": 1893610,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77860\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1893610\" violates the foreign key: for \"id_contrato\": values \"77860\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43548",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "876",
            "30801",
            "1",
            "24",
            "222",
            "20500",
            "170956",
            "379906",
            "77860",
            "889",
            "1831295",
            "2584",
            "3043",
            "2022",
            "2022-10-14",
            "15.0000",
            "1723.4500",
            "25851.75",
            "790.0000",
            "11850.00",
            "11850.00"
          ],
          "rowNumber": 1893610,
          "rowPosition": 1893611,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77860\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1893611\" violates the foreign key: for \"id_contrato\": values \"77860\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43548",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "876",
            "30801",
            "1",
            "24",
            "155",
            "8289",
            "170794",
            "379906",
            "77860",
            "585",
            "1831203",
            "2584",
            "3043",
            "2022",
            "2022-10-14",
            "10.0000",
            "94.4000",
            "944.00",
            "180.0000",
            "1800.00",
            "1800.00"
          ],
          "rowNumber": 1893611,
          "rowPosition": 1893612,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77860\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1893612\" violates the foreign key: for \"id_contrato\": values \"77860\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43548",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "876",
            "59801",
            "1",
            "19",
            "628",
            "13206",
            "91316",
            "379906",
            "77870",
            "889",
            "1831992",
            "2995",
            "3043",
            "2022",
            "2022-10-14",
            "108.0000",
            "533.0000",
            "57564.00",
            "342.7000",
            "37011.60",
            "37011.60"
          ],
          "rowNumber": 1893612,
          "rowPosition": 1893613,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77870\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1893613\" violates the foreign key: for \"id_contrato\": values \"77870\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43533",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "147",
            "71614",
            "1",
            "77",
            "533",
            "4332",
            "89794",
            "380607",
            "77857",
            "981",
            "1831821",
            "2954",
            "1760",
            "2022",
            "2022-10-24",
            "0.0000",
            "13202.4000",
            "13202.40",
            "13039.2000",
            "13039.20",
            "13039.20"
          ],
          "rowNumber": 1895480,
          "rowPosition": 1895481,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77857\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1895481\" violates the foreign key: for \"id_contrato\": values \"77857\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43583",
            "1",
            "1831105",
            "50",
            "1",
            "8",
            "66",
            "72633",
            "1",
            "77",
            "479",
            "20171",
            "93519",
            "381399",
            "46296",
            "889",
            "1831808",
            "2602",
            "3042",
            "2022",
            "2022-11-08",
            "0.0000",
            "7500.0000",
            "7500.00",
            "7500.0000",
            "7500.00",
            "7500.00"
          ],
          "rowNumber": 1895725,
          "rowPosition": 1895726,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contratado\": values \"72633\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "message": "Row at position \"1895726\" violates the foreign key: for \"id_contratado\": values \"72633\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 61
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 61,
    "tasks": 1
  },
  "valid": false
}