{
  "version": "4.38.0",
  "time": 411.533,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_compras",
        "title": "Compras",
        "path": "data/ft_compras.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_tempo",
              "title": "Tempo - Chave",
              "type": "integer",
              "format": "default",
              "description": "- > \n  Chave estrangeira (Foreign Key) que aponta para a Chave Primária (Primary keys) da tabela dm_tempo_diario. \n  Ou seja, por meio dessa chave é possível identificar a data completa a qual o dado se refere.\n\n  Nota: \n  No site dados.mg.gov.br a tabela dm_tempo_diario pode ser encontrada no recurso Calendários - Dias \n  de cada conjunto.\n",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_procedimento",
              "title": "Procedimento de Contratação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_demanda",
              "title": "Órgão Demandante - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_contrato",
              "title": "Órgão do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_proc",
              "title": "Situação do Processo de Compra - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_cont",
              "title": "Situação do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_municipio",
              "title": "Município - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contratado",
              "title": "Contratado - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_tipo_licitacao",
              "title": "Tipo de Licitação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_grupo_matserv",
              "title": "Grupo Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_classe_matserv",
              "title": "Classe Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_material_servico",
              "title": "Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item_matserv",
              "title": "Item Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_processo",
              "title": "Processo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contrato",
              "title": "Número do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_medida",
              "title": "Unidade de Medida - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_linha_fornec",
              "title": "Linha de Fornecimento - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_orc",
              "title": "Unidade Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "unique": false
              }
            },
            {
              "name": "ano_particao",
              "title": "Ano Partição",
              "type": "year",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true
              }
            },
            {
              "name": "dt_item_homologa",
              "title": "Data da Homologação do Item",
              "type": "date",
              "format": "default",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "qt_item_pedido",
              "title": "Item do Pedido - Quantidade",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_referencia",
              "title": "Valor Unitário de Referência",
              "description": "Valor unitário estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_referencia",
              "title": "Valor de Referência",
              "description": "Valor estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_homologado",
              "title": "Valor Unitário Homologado",
              "description": "Valor unitário final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_homologado",
              "title": "Valor Homologado",
              "description": "Valor final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_atualizado",
              "title": "Valor Atualizado",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_processo"
              ],
              "reference": {
                "fields": [
                  "id_processo"
                ],
                "resource": "dm_processo"
              }
            },
            {
              "fields": [
                "id_situacao_cont"
              ],
              "reference": {
                "fields": [
                  "id_situacao_cont"
                ],
                "resource": "dm_situacao_cont"
              }
            },
            {
              "fields": [
                "id_situacao_proc"
              ],
              "reference": {
                "fields": [
                  "id_situacao_proc"
                ],
                "resource": "dm_situacao_proc"
              }
            },
            {
              "fields": [
                "id_linha_fornec"
              ],
              "reference": {
                "fields": [
                  "id_linha_fornec"
                ],
                "resource": "dm_linha_fornec"
              }
            },
            {
              "fields": [
                "id_classe_matserv"
              ],
              "reference": {
                "fields": [
                  "id_classe_matserv"
                ],
                "resource": "dm_classe_matserv"
              }
            },
            {
              "fields": [
                "id_tempo"
              ],
              "reference": {
                "fields": [
                  "id_tempo"
                ],
                "resource": "dm_tempo_diario"
              }
            },
            {
              "fields": [
                "id_municipio"
              ],
              "reference": {
                "fields": [
                  "id_municipio"
                ],
                "resource": "dm_municipio"
              }
            },
            {
              "fields": [
                "id_item_matserv"
              ],
              "reference": {
                "fields": [
                  "id_item_matserv"
                ],
                "resource": "dm_item_matserv"
              }
            },
            {
              "fields": [
                "id_tipo_licitacao"
              ],
              "reference": {
                "fields": [
                  "id_tipo_licitacao"
                ],
                "resource": "dm_tipo_licitacao"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_material_servico"
              ],
              "reference": {
                "fields": [
                  "id_material_servico"
                ],
                "resource": "dm_material_servico"
              }
            },
            {
              "fields": [
                "id_orgao_contrato"
              ],
              "reference": {
                "fields": [
                  "id_orgao_contrato"
                ],
                "resource": "dm_orgao_contrato"
              }
            },
            {
              "fields": [
                "id_contrato"
              ],
              "reference": {
                "fields": [
                  "id_contrato"
                ],
                "resource": "dm_contrato"
              }
            },
            {
              "fields": [
                "id_orgao_demanda"
              ],
              "reference": {
                "fields": [
                  "id_orgao_demanda"
                ],
                "resource": "dm_orgao_demanda"
              }
            },
            {
              "fields": [
                "id_unidade_medida"
              ],
              "reference": {
                "fields": [
                  "id_unidade_medida"
                ],
                "resource": "dm_unidade_medida"
              }
            },
            {
              "fields": [
                "id_grupo_matserv"
              ],
              "reference": {
                "fields": [
                  "id_grupo_matserv"
                ],
                "resource": "dm_grupo_matserv"
              }
            },
            {
              "fields": [
                "id_contratado"
              ],
              "reference": {
                "fields": [
                  "id_contratado"
                ],
                "resource": "dm_contratado"
              }
            },
            {
              "fields": [
                "id_procedimento"
              ],
              "reference": {
                "fields": [
                  "id_procedimento"
                ],
                "resource": "dm_procedimento"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_compras"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "4a988a9c05099d8751b6b5cb672cc2ae",
          "bytes": 58467070,
          "fields": 27,
          "rows": 1919239
        }
      },
      "time": 411.533,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "43583",
            "1",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "28244",
            "1",
            "77",
            "479",
            "1836",
            "91508",
            "380864",
            "79240",
            "889",
            "1831808",
            "2806",
            "1760",
            "2022",
            "2022-10-26",
            "0.0000",
            "98960.0000",
            "98960.00",
            "98960.0000",
            "98960.00",
            "98960.00"
          ],
          "rowNumber": 1814990,
          "rowPosition": 1814991,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79240\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1814991\" violates the foreign key: for \"id_contrato\": values \"79240\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44045",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "66",
            "70028",
            "1",
            "77",
            "700",
            "14850",
            "105183",
            "382932",
            "79233",
            "889",
            "1831531",
            "3043",
            "2925",
            "2022",
            "2022-11-25",
            "0.0000",
            "9103096.3200",
            "9103096.32",
            "7560000.0000",
            "7560000.00",
            "7560000.00"
          ],
          "rowNumber": 1856316,
          "rowPosition": 1856317,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79233\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1856317\" violates the foreign key: for \"id_contrato\": values \"79233\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44451",
            "2",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "31915",
            "1",
            "39",
            "190",
            "20350",
            "98705",
            "386086",
            "79237",
            "889",
            "1831812",
            "3065",
            "2925",
            "2022",
            "2023-01-12",
            "0.0000",
            "111348.0000",
            "111348.00",
            "111348.0000",
            "111348.00",
            "111348.00"
          ],
          "rowNumber": 1913610,
          "rowPosition": 1913611,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79237\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913611\" violates the foreign key: for \"id_contrato\": values \"79237\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44451",
            "2",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "31915",
            "1",
            "39",
            "190",
            "20350",
            "98705",
            "386086",
            "79237",
            "889",
            "1831812",
            "3065",
            "2925",
            "2022",
            "2023-01-12",
            "0.0000",
            "139860.0000",
            "139860.00",
            "139860.0000",
            "139860.00",
            "139860.00"
          ],
          "rowNumber": 1913611,
          "rowPosition": 1913612,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79237\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913612\" violates the foreign key: for \"id_contrato\": values \"79237\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44451",
            "2",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "31915",
            "1",
            "39",
            "190",
            "4584",
            "105067",
            "386086",
            "79237",
            "889",
            "1831812",
            "3065",
            "2925",
            "2022",
            "2023-01-12",
            "0.0000",
            "61008.0000",
            "61008.00",
            "61008.0000",
            "61008.00",
            "61008.00"
          ],
          "rowNumber": 1913612,
          "rowPosition": 1913613,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79237\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913613\" violates the foreign key: for \"id_contrato\": values \"79237\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44451",
            "2",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "31915",
            "1",
            "39",
            "190",
            "20350",
            "98705",
            "386086",
            "79237",
            "889",
            "1831812",
            "3065",
            "2925",
            "2022",
            "2023-01-12",
            "0.0000",
            "21696.0000",
            "21696.00",
            "21696.0000",
            "21696.00",
            "21696.00"
          ],
          "rowNumber": 1913613,
          "rowPosition": 1913614,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79237\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913614\" violates the foreign key: for \"id_contrato\": values \"79237\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44451",
            "2",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "31915",
            "1",
            "39",
            "190",
            "20350",
            "98705",
            "386086",
            "79237",
            "889",
            "1831812",
            "3065",
            "2925",
            "2022",
            "2023-01-12",
            "0.0000",
            "1659600.0000",
            "1659600.00",
            "1659600.0000",
            "1659600.00",
            "1659600.00"
          ],
          "rowNumber": 1913614,
          "rowPosition": 1913615,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79237\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913615\" violates the foreign key: for \"id_contrato\": values \"79237\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44451",
            "2",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "31915",
            "1",
            "39",
            "190",
            "20350",
            "98705",
            "386086",
            "79237",
            "889",
            "1831812",
            "3065",
            "2925",
            "2022",
            "2023-01-12",
            "0.0000",
            "885768.0000",
            "885768.00",
            "885768.0000",
            "885768.00",
            "885768.00"
          ],
          "rowNumber": 1913615,
          "rowPosition": 1913616,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79237\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913616\" violates the foreign key: for \"id_contrato\": values \"79237\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44451",
            "2",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "31915",
            "1",
            "39",
            "190",
            "20350",
            "98705",
            "386086",
            "79237",
            "889",
            "1831812",
            "3065",
            "2925",
            "2022",
            "2023-01-12",
            "0.0000",
            "83268.0000",
            "83268.00",
            "83268.0000",
            "83268.00",
            "83268.00"
          ],
          "rowNumber": 1913616,
          "rowPosition": 1913617,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79237\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913617\" violates the foreign key: for \"id_contrato\": values \"79237\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44451",
            "2",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "31915",
            "1",
            "39",
            "190",
            "20350",
            "98705",
            "386086",
            "79237",
            "889",
            "1831812",
            "3065",
            "2925",
            "2022",
            "2023-01-12",
            "0.0000",
            "13944.0000",
            "13944.00",
            "13944.0000",
            "13944.00",
            "13944.00"
          ],
          "rowNumber": 1913617,
          "rowPosition": 1913618,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79237\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913618\" violates the foreign key: for \"id_contrato\": values \"79237\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44451",
            "2",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "31915",
            "1",
            "39",
            "190",
            "20350",
            "98705",
            "386086",
            "79237",
            "889",
            "1831812",
            "3065",
            "2925",
            "2022",
            "2023-01-12",
            "0.0000",
            "23160.0000",
            "23160.00",
            "23160.0000",
            "23160.00",
            "23160.00"
          ],
          "rowNumber": 1913618,
          "rowPosition": 1913619,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79237\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913619\" violates the foreign key: for \"id_contrato\": values \"79237\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44451",
            "2",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "31915",
            "1",
            "39",
            "190",
            "20350",
            "98705",
            "386086",
            "79237",
            "889",
            "1831812",
            "3065",
            "2925",
            "2022",
            "2023-01-12",
            "0.0000",
            "2316.0000",
            "2316.00",
            "2316.0000",
            "2316.00",
            "2316.00"
          ],
          "rowNumber": 1913619,
          "rowPosition": 1913620,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79237\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913620\" violates the foreign key: for \"id_contrato\": values \"79237\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44451",
            "2",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "31915",
            "1",
            "39",
            "190",
            "4584",
            "171501",
            "386086",
            "79237",
            "889",
            "1831812",
            "3065",
            "2925",
            "2022",
            "2023-01-12",
            "0.0000",
            "26040.0000",
            "26040.00",
            "26040.0000",
            "26040.00",
            "26040.00"
          ],
          "rowNumber": 1913620,
          "rowPosition": 1913621,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79237\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913621\" violates the foreign key: for \"id_contrato\": values \"79237\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44451",
            "2",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "31915",
            "1",
            "39",
            "190",
            "20350",
            "98705",
            "386086",
            "79237",
            "889",
            "1831812",
            "3065",
            "2925",
            "2022",
            "2023-01-12",
            "0.0000",
            "249840.0000",
            "249840.00",
            "249840.0000",
            "249840.00",
            "249840.00"
          ],
          "rowNumber": 1913621,
          "rowPosition": 1913622,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79237\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913622\" violates the foreign key: for \"id_contrato\": values \"79237\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44451",
            "2",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "31915",
            "1",
            "39",
            "190",
            "20350",
            "98705",
            "386086",
            "79237",
            "889",
            "1831812",
            "3065",
            "2925",
            "2022",
            "2023-01-12",
            "0.0000",
            "24744.0000",
            "24744.00",
            "24744.0000",
            "24744.00",
            "24744.00"
          ],
          "rowNumber": 1913622,
          "rowPosition": 1913623,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79237\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913623\" violates the foreign key: for \"id_contrato\": values \"79237\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44451",
            "2",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "31915",
            "1",
            "39",
            "190",
            "20350",
            "98705",
            "386086",
            "79237",
            "889",
            "1831812",
            "3065",
            "2925",
            "2022",
            "2023-01-12",
            "0.0000",
            "138780.0000",
            "138780.00",
            "138780.0000",
            "138780.00",
            "138780.00"
          ],
          "rowNumber": 1913623,
          "rowPosition": 1913624,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79237\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913624\" violates the foreign key: for \"id_contrato\": values \"79237\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44451",
            "2",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "31915",
            "1",
            "39",
            "190",
            "20350",
            "98705",
            "386086",
            "79237",
            "889",
            "1831812",
            "3065",
            "2925",
            "2022",
            "2023-01-12",
            "0.0000",
            "148320.0000",
            "148320.00",
            "148320.0000",
            "148320.00",
            "148320.00"
          ],
          "rowNumber": 1913624,
          "rowPosition": 1913625,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79237\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913625\" violates the foreign key: for \"id_contrato\": values \"79237\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44451",
            "2",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "31915",
            "1",
            "39",
            "190",
            "7099",
            "234266",
            "386086",
            "79237",
            "889",
            "1831812",
            "3065",
            "2925",
            "2022",
            "2023-01-12",
            "0.0000",
            "529200.0000",
            "529200.00",
            "529200.0000",
            "529200.00",
            "529200.00"
          ],
          "rowNumber": 1913625,
          "rowPosition": 1913626,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79237\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913626\" violates the foreign key: for \"id_contrato\": values \"79237\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44453",
            "1",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "73181",
            "1",
            "77",
            "479",
            "20171",
            "93519",
            "385446",
            "79235",
            "27",
            "1831808",
            "2867",
            "3042",
            "2022",
            "2022-12-28",
            "0.0000",
            "8008.6400",
            "8008.64",
            "8008.6400",
            "8008.64",
            "8008.64"
          ],
          "rowNumber": 1917048,
          "rowPosition": 1917049,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79235\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1917049\" violates the foreign key: for \"id_contrato\": values \"79235\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "36832",
            "1",
            "18",
            "22",
            "120",
            "140058",
            "386109",
            "79236",
            "889",
            "1831311",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "5248.0000",
            "2.9900",
            "15691.52",
            "2.9900",
            "15691.52",
            "15691.52"
          ],
          "rowNumber": 1918940,
          "rowPosition": 1918941,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79236\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918941\" violates the foreign key: for \"id_contrato\": values \"79236\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "55286",
            "1",
            "18",
            "22",
            "4299",
            "129060",
            "386109",
            "79244",
            "889",
            "1831311",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "1936.0000",
            "2.9000",
            "5614.40",
            "2.1800",
            "4220.48",
            "4220.48"
          ],
          "rowNumber": 1918941,
          "rowPosition": 1918942,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79244\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918942\" violates the foreign key: for \"id_contrato\": values \"79244\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "36832",
            "1",
            "18",
            "22",
            "633",
            "12717",
            "386109",
            "79236",
            "889",
            "1831311",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "2320.0000",
            "1.9500",
            "4524.00",
            "1.2900",
            "2992.80",
            "2992.80"
          ],
          "rowNumber": 1918942,
          "rowPosition": 1918943,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79236\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918943\" violates the foreign key: for \"id_contrato\": values \"79236\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "70040",
            "1",
            "18",
            "650",
            "21696",
            "199248",
            "386109",
            "79239",
            "1750",
            "1831311",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "65680.0000",
            "7.0100",
            "460416.80",
            "5.0600",
            "332340.80",
            "332340.80"
          ],
          "rowNumber": 1918943,
          "rowPosition": 1918944,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79239\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918944\" violates the foreign key: for \"id_contrato\": values \"79239\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "19758",
            "1",
            "18",
            "650",
            "21696",
            "199254",
            "386109",
            "79241",
            "1750",
            "1831311",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "31424.0000",
            "16.4500",
            "516924.80",
            "14.9400",
            "469474.56",
            "469474.56"
          ],
          "rowNumber": 1918944,
          "rowPosition": 1918945,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79241\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918945\" violates the foreign key: for \"id_contrato\": values \"79241\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "19758",
            "1",
            "18",
            "650",
            "21697",
            "173778",
            "386109",
            "79241",
            "1917",
            "1831311",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "210656.0000",
            "16.1800",
            "3407360.80",
            "16.1700",
            "3406307.52",
            "3406307.52"
          ],
          "rowNumber": 1918945,
          "rowPosition": 1918946,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79241\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918946\" violates the foreign key: for \"id_contrato\": values \"79241\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "36832",
            "1",
            "18",
            "22",
            "74",
            "79959",
            "386109",
            "79236",
            "889",
            "1831311",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "2464.0000",
            "3.9900",
            "9831.36",
            "1.8200",
            "4484.48",
            "4484.48"
          ],
          "rowNumber": 1918946,
          "rowPosition": 1918947,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79236\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918947\" violates the foreign key: for \"id_contrato\": values \"79236\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "19838",
            "1",
            "18",
            "506",
            "21741",
            "175920",
            "386109",
            "79245",
            "1071",
            "1831311",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "44768.0000",
            "4.8500",
            "216900.96",
            "2.2700",
            "101623.36",
            "101623.36"
          ],
          "rowNumber": 1918947,
          "rowPosition": 1918948,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79245\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918948\" violates the foreign key: for \"id_contrato\": values \"79245\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "58479",
            "1",
            "18",
            "506",
            "21741",
            "178925",
            "386109",
            "79243",
            "1071",
            "1831311",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "205744.0000",
            "3.1500",
            "648093.60",
            "1.0500",
            "216031.20",
            "216031.20"
          ],
          "rowNumber": 1918948,
          "rowPosition": 1918949,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79243\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918949\" violates the foreign key: for \"id_contrato\": values \"79243\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "58479",
            "1",
            "18",
            "506",
            "21741",
            "175924",
            "386109",
            "79243",
            "1916",
            "1831311",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "40720.0000",
            "7.0000",
            "285040.00",
            "5.2000",
            "211744.00",
            "211744.00"
          ],
          "rowNumber": 1918949,
          "rowPosition": 1918950,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79243\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918950\" violates the foreign key: for \"id_contrato\": values \"79243\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "32407",
            "1",
            "18",
            "22",
            "534",
            "9240",
            "386109",
            "79234",
            "889",
            "1831311",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "81872.0000",
            "1.1800",
            "96608.96",
            "0.8400",
            "68772.48",
            "68772.48"
          ],
          "rowNumber": 1918950,
          "rowPosition": 1918951,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79234\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918951\" violates the foreign key: for \"id_contrato\": values \"79234\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "36832",
            "1",
            "18",
            "22",
            "13877",
            "21225",
            "386109",
            "79236",
            "889",
            "1831311",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "304.0000",
            "4.4000",
            "1337.60",
            "3.2800",
            "997.12",
            "997.12"
          ],
          "rowNumber": 1918951,
          "rowPosition": 1918952,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79236\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918952\" violates the foreign key: for \"id_contrato\": values \"79236\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "36832",
            "1",
            "18",
            "22",
            "13877",
            "21517",
            "386109",
            "79236",
            "889",
            "1831311",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "464.0000",
            "8.3700",
            "3883.68",
            "6.4600",
            "2997.44",
            "2997.44"
          ],
          "rowNumber": 1918952,
          "rowPosition": 1918953,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79236\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918953\" violates the foreign key: for \"id_contrato\": values \"79236\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "32407",
            "1",
            "18",
            "506",
            "1305",
            "135383",
            "386109",
            "79234",
            "1769",
            "1831311",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "14016.0000",
            "3.4300",
            "48074.88",
            "1.7900",
            "25088.64",
            "25088.64"
          ],
          "rowNumber": 1918953,
          "rowPosition": 1918954,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79234\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918954\" violates the foreign key: for \"id_contrato\": values \"79234\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "32407",
            "1",
            "18",
            "239",
            "13323",
            "67291",
            "386109",
            "79234",
            "547",
            "1831311",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "4784.0000",
            "10.0000",
            "47840.00",
            "7.5400",
            "36071.36",
            "36071.36"
          ],
          "rowNumber": 1918954,
          "rowPosition": 1918955,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79234\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918955\" violates the foreign key: for \"id_contrato\": values \"79234\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "36832",
            "1",
            "80",
            "308",
            "5152",
            "45484",
            "386109",
            "79236",
            "889",
            "1831306",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "8608.0000",
            "2.9000",
            "24963.20",
            "1.7500",
            "15064.00",
            "15064.00"
          ],
          "rowNumber": 1918955,
          "rowPosition": 1918956,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79236\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918956\" violates the foreign key: for \"id_contrato\": values \"79236\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "32407",
            "1",
            "80",
            "308",
            "5152",
            "97533",
            "386109",
            "79234",
            "889",
            "1831306",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "27472.0000",
            "1.0900",
            "29944.48",
            "0.7800",
            "21428.16",
            "21428.16"
          ],
          "rowNumber": 1918956,
          "rowPosition": 1918957,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79234\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918957\" violates the foreign key: for \"id_contrato\": values \"79234\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "32556",
            "1",
            "80",
            "308",
            "9956",
            "109865",
            "386109",
            "79242",
            "889",
            "1831306",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "2720.0000",
            "2.1800",
            "5916.00",
            "1.8000",
            "4896.00",
            "4896.00"
          ],
          "rowNumber": 1918957,
          "rowPosition": 1918958,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79242\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918958\" violates the foreign key: for \"id_contrato\": values \"79242\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "32407",
            "1",
            "43",
            "315",
            "9831",
            "121304",
            "386109",
            "79234",
            "889",
            "1831306",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "304.0000",
            "80.0000",
            "24320.00",
            "75.9600",
            "23091.84",
            "23091.84"
          ],
          "rowNumber": 1918958,
          "rowPosition": 1918959,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79234\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918959\" violates the foreign key: for \"id_contrato\": values \"79234\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "24550",
            "1",
            "80",
            "308",
            "15718",
            "42429",
            "386109",
            "79238",
            "595",
            "1831306",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "416.0000",
            "6.0000",
            "2496.00",
            "2.7500",
            "1144.00",
            "1144.00"
          ],
          "rowNumber": 1918959,
          "rowPosition": 1918960,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79238\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918960\" violates the foreign key: for \"id_contrato\": values \"79238\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "55286",
            "1",
            "80",
            "308",
            "15718",
            "42430",
            "386109",
            "79244",
            "595",
            "1831306",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "2544.0000",
            "5.0000",
            "12720.00",
            "2.6900",
            "6843.36",
            "6843.36"
          ],
          "rowNumber": 1918960,
          "rowPosition": 1918961,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79244\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918961\" violates the foreign key: for \"id_contrato\": values \"79244\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "55286",
            "1",
            "80",
            "308",
            "15718",
            "42431",
            "386109",
            "79244",
            "595",
            "1831306",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "336.0000",
            "3.8200",
            "1283.52",
            "2.6800",
            "900.48",
            "900.48"
          ],
          "rowNumber": 1918961,
          "rowPosition": 1918962,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79244\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918962\" violates the foreign key: for \"id_contrato\": values \"79244\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "55286",
            "1",
            "80",
            "308",
            "13765",
            "75757",
            "386109",
            "79244",
            "889",
            "1831306",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "720.0000",
            "5.2000",
            "3744.00",
            "3.9000",
            "2808.00",
            "2808.00"
          ],
          "rowNumber": 1918962,
          "rowPosition": 1918963,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79244\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918963\" violates the foreign key: for \"id_contrato\": values \"79244\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "36832",
            "1",
            "80",
            "308",
            "11403",
            "26429",
            "386109",
            "79236",
            "889",
            "1831306",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "1744.0000",
            "1.7300",
            "3008.40",
            "1.7200",
            "2999.68",
            "2999.68"
          ],
          "rowNumber": 1918963,
          "rowPosition": 1918964,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79236\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918964\" violates the foreign key: for \"id_contrato\": values \"79236\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "36832",
            "1",
            "80",
            "308",
            "11403",
            "26428",
            "386109",
            "79236",
            "889",
            "1831306",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "2192.0000",
            "2.3000",
            "5041.60",
            "2.3000",
            "5041.60",
            "5041.60"
          ],
          "rowNumber": 1918964,
          "rowPosition": 1918965,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79236\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918965\" violates the foreign key: for \"id_contrato\": values \"79236\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "24550",
            "1",
            "80",
            "308",
            "13105",
            "127842",
            "386109",
            "79238",
            "889",
            "1831306",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "15040.0000",
            "4.0000",
            "60160.00",
            "2.7500",
            "41360.00",
            "41360.00"
          ],
          "rowNumber": 1918965,
          "rowPosition": 1918966,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79238\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918966\" violates the foreign key: for \"id_contrato\": values \"79238\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "24550",
            "1",
            "80",
            "308",
            "13105",
            "132025",
            "386109",
            "79238",
            "889",
            "1831306",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "23040.0000",
            "6.1000",
            "140544.00",
            "5.8500",
            "134784.00",
            "134784.00"
          ],
          "rowNumber": 1918966,
          "rowPosition": 1918967,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79238\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918967\" violates the foreign key: for \"id_contrato\": values \"79238\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "36832",
            "1",
            "80",
            "621",
            "16131",
            "7279",
            "386109",
            "79236",
            "189",
            "1831306",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "8064.0000",
            "26.5000",
            "213696.00",
            "6.0200",
            "48545.28",
            "48545.28"
          ],
          "rowNumber": 1918967,
          "rowPosition": 1918968,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79236\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918968\" violates the foreign key: for \"id_contrato\": values \"79236\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "32556",
            "1",
            "80",
            "308",
            "18356",
            "169557",
            "386109",
            "79242",
            "889",
            "1831306",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "1744.0000",
            "10.9800",
            "19149.12",
            "8.4800",
            "14789.12",
            "14789.12"
          ],
          "rowNumber": 1918968,
          "rowPosition": 1918969,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79242\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918969\" violates the foreign key: for \"id_contrato\": values \"79242\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "36832",
            "1",
            "80",
            "621",
            "21715",
            "174497",
            "386109",
            "79236",
            "1928",
            "1831306",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "1616.0000",
            "4.2000",
            "6787.20",
            "1.9600",
            "3167.36",
            "3167.36"
          ],
          "rowNumber": 1918969,
          "rowPosition": 1918970,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79236\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918970\" violates the foreign key: for \"id_contrato\": values \"79236\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "36832",
            "1",
            "80",
            "621",
            "21716",
            "177051",
            "386109",
            "79236",
            "1917",
            "1831306",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "1424.0000",
            "6.0000",
            "8544.00",
            "5.5300",
            "7874.72",
            "7874.72"
          ],
          "rowNumber": 1918970,
          "rowPosition": 1918971,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79236\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918971\" violates the foreign key: for \"id_contrato\": values \"79236\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "36832",
            "1",
            "80",
            "308",
            "301",
            "18982",
            "386109",
            "79236",
            "889",
            "1831306",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "320.0000",
            "4.0500",
            "1296.00",
            "2.6500",
            "848.00",
            "848.00"
          ],
          "rowNumber": 1918971,
          "rowPosition": 1918972,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79236\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918972\" violates the foreign key: for \"id_contrato\": values \"79236\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "55286",
            "1",
            "80",
            "308",
            "301",
            "10429",
            "386109",
            "79244",
            "889",
            "1831306",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "432.0000",
            "8.1000",
            "3499.20",
            "4.3500",
            "1879.20",
            "1879.20"
          ],
          "rowNumber": 1918972,
          "rowPosition": 1918973,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79244\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918973\" violates the foreign key: for \"id_contrato\": values \"79244\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "36832",
            "1",
            "80",
            "621",
            "364",
            "122845",
            "386109",
            "79236",
            "190",
            "1831306",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "73504.0000",
            "26.9300",
            "1979462.72",
            "4.4800",
            "329297.92",
            "329297.92"
          ],
          "rowNumber": 1918973,
          "rowPosition": 1918974,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79236\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918974\" violates the foreign key: for \"id_contrato\": values \"79236\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "32556",
            "1",
            "80",
            "755",
            "16262",
            "44736",
            "386109",
            "79242",
            "889",
            "1831306",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "368.0000",
            "28.0000",
            "10304.00",
            "20.8900",
            "7687.52",
            "7687.52"
          ],
          "rowNumber": 1919031,
          "rowPosition": 1919032,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79242\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1919032\" violates the foreign key: for \"id_contrato\": values \"79242\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "36832",
            "1",
            "80",
            "755",
            "16262",
            "137120",
            "386109",
            "79236",
            "889",
            "1831306",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "320.0000",
            "35.0000",
            "11200.00",
            "23.7500",
            "7600.00",
            "7600.00"
          ],
          "rowNumber": 1919032,
          "rowPosition": 1919033,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79236\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1919033\" violates the foreign key: for \"id_contrato\": values \"79236\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "36832",
            "1",
            "80",
            "755",
            "16262",
            "126917",
            "386109",
            "79236",
            "889",
            "1831306",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "1024.0000",
            "29.0000",
            "29696.00",
            "19.5300",
            "19998.72",
            "19998.72"
          ],
          "rowNumber": 1919033,
          "rowPosition": 1919034,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79236\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1919034\" violates the foreign key: for \"id_contrato\": values \"79236\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "36832",
            "1",
            "80",
            "755",
            "16262",
            "135949",
            "386109",
            "79236",
            "889",
            "1831306",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "384.0000",
            "42.0500",
            "16147.20",
            "36.4500",
            "13996.80",
            "13996.80"
          ],
          "rowNumber": 1919034,
          "rowPosition": 1919035,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79236\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1919035\" violates the foreign key: for \"id_contrato\": values \"79236\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "36832",
            "1",
            "80",
            "755",
            "16262",
            "82436",
            "386109",
            "79236",
            "889",
            "1831306",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "400.0000",
            "59.7900",
            "23916.00",
            "41.0000",
            "16400.00",
            "16400.00"
          ],
          "rowNumber": 1919035,
          "rowPosition": 1919036,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79236\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1919036\" violates the foreign key: for \"id_contrato\": values \"79236\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "32556",
            "1",
            "80",
            "755",
            "16262",
            "44737",
            "386109",
            "79242",
            "889",
            "1831306",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "1200.0000",
            "28.0000",
            "33600.00",
            "19.4000",
            "23280.00",
            "23280.00"
          ],
          "rowNumber": 1919036,
          "rowPosition": 1919037,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79242\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1919037\" violates the foreign key: for \"id_contrato\": values \"79242\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "36832",
            "1",
            "80",
            "755",
            "16262",
            "26844",
            "386109",
            "79236",
            "889",
            "1831306",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "448.0000",
            "28.7500",
            "12880.00",
            "23.6600",
            "10599.68",
            "10599.68"
          ],
          "rowNumber": 1919037,
          "rowPosition": 1919038,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79236\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1919038\" violates the foreign key: for \"id_contrato\": values \"79236\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "36832",
            "1",
            "80",
            "755",
            "16262",
            "43635",
            "386109",
            "79236",
            "889",
            "1831306",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "384.0000",
            "47.9200",
            "18399.36",
            "32.2000",
            "12364.80",
            "12364.80"
          ],
          "rowNumber": 1919038,
          "rowPosition": 1919039,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79236\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1919039\" violates the foreign key: for \"id_contrato\": values \"79236\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "36832",
            "1",
            "80",
            "308",
            "10895",
            "9984",
            "386109",
            "79236",
            "889",
            "1831306",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "80.0000",
            "5.9000",
            "472.00",
            "3.1200",
            "249.60",
            "249.60"
          ],
          "rowNumber": 1919039,
          "rowPosition": 1919040,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79236\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1919040\" violates the foreign key: for \"id_contrato\": values \"79236\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "55286",
            "1",
            "80",
            "308",
            "13163",
            "26033",
            "386109",
            "79244",
            "889",
            "1831306",
            "2994",
            "2925",
            "2022",
            "2023-01-17",
            "240.0000",
            "14.9000",
            "3576.00",
            "10.0000",
            "2400.00",
            "2400.00"
          ],
          "rowNumber": 1919040,
          "rowPosition": 1919041,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79244\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1919041\" violates the foreign key: for \"id_contrato\": values \"79244\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 63
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 63,
    "tasks": 1
  },
  "valid": false
}