{
  "version": "4.38.0",
  "time": 411.418,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_compras",
        "title": "Compras",
        "path": "data/ft_compras.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_tempo",
              "title": "Tempo - Chave",
              "type": "integer",
              "format": "default",
              "description": "- > \n  Chave estrangeira (Foreign Key) que aponta para a Chave Primária (Primary keys) da tabela dm_tempo_diario. \n  Ou seja, por meio dessa chave é possível identificar a data completa a qual o dado se refere.\n\n  Nota: \n  No site dados.mg.gov.br a tabela dm_tempo_diario pode ser encontrada no recurso Calendários - Dias \n  de cada conjunto.\n",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_procedimento",
              "title": "Procedimento de Contratação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_demanda",
              "title": "Órgão Demandante - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_contrato",
              "title": "Órgão do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_proc",
              "title": "Situação do Processo de Compra - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_cont",
              "title": "Situação do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_municipio",
              "title": "Município - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contratado",
              "title": "Contratado - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_tipo_licitacao",
              "title": "Tipo de Licitação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_grupo_matserv",
              "title": "Grupo Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_classe_matserv",
              "title": "Classe Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_material_servico",
              "title": "Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item_matserv",
              "title": "Item Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_processo",
              "title": "Processo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contrato",
              "title": "Número do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_medida",
              "title": "Unidade de Medida - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_linha_fornec",
              "title": "Linha de Fornecimento - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_orc",
              "title": "Unidade Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "unique": false
              }
            },
            {
              "name": "ano_particao",
              "title": "Ano Partição",
              "type": "year",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true
              }
            },
            {
              "name": "dt_item_homologa",
              "title": "Data da Homologação do Item",
              "type": "date",
              "format": "default",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "qt_item_pedido",
              "title": "Item do Pedido - Quantidade",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_referencia",
              "title": "Valor Unitário de Referência",
              "description": "Valor unitário estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_referencia",
              "title": "Valor de Referência",
              "description": "Valor estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_homologado",
              "title": "Valor Unitário Homologado",
              "description": "Valor unitário final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_homologado",
              "title": "Valor Homologado",
              "description": "Valor final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_atualizado",
              "title": "Valor Atualizado",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_processo"
              ],
              "reference": {
                "fields": [
                  "id_processo"
                ],
                "resource": "dm_processo"
              }
            },
            {
              "fields": [
                "id_situacao_cont"
              ],
              "reference": {
                "fields": [
                  "id_situacao_cont"
                ],
                "resource": "dm_situacao_cont"
              }
            },
            {
              "fields": [
                "id_situacao_proc"
              ],
              "reference": {
                "fields": [
                  "id_situacao_proc"
                ],
                "resource": "dm_situacao_proc"
              }
            },
            {
              "fields": [
                "id_linha_fornec"
              ],
              "reference": {
                "fields": [
                  "id_linha_fornec"
                ],
                "resource": "dm_linha_fornec"
              }
            },
            {
              "fields": [
                "id_classe_matserv"
              ],
              "reference": {
                "fields": [
                  "id_classe_matserv"
                ],
                "resource": "dm_classe_matserv"
              }
            },
            {
              "fields": [
                "id_tempo"
              ],
              "reference": {
                "fields": [
                  "id_tempo"
                ],
                "resource": "dm_tempo_diario"
              }
            },
            {
              "fields": [
                "id_municipio"
              ],
              "reference": {
                "fields": [
                  "id_municipio"
                ],
                "resource": "dm_municipio"
              }
            },
            {
              "fields": [
                "id_item_matserv"
              ],
              "reference": {
                "fields": [
                  "id_item_matserv"
                ],
                "resource": "dm_item_matserv"
              }
            },
            {
              "fields": [
                "id_tipo_licitacao"
              ],
              "reference": {
                "fields": [
                  "id_tipo_licitacao"
                ],
                "resource": "dm_tipo_licitacao"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_material_servico"
              ],
              "reference": {
                "fields": [
                  "id_material_servico"
                ],
                "resource": "dm_material_servico"
              }
            },
            {
              "fields": [
                "id_orgao_contrato"
              ],
              "reference": {
                "fields": [
                  "id_orgao_contrato"
                ],
                "resource": "dm_orgao_contrato"
              }
            },
            {
              "fields": [
                "id_contrato"
              ],
              "reference": {
                "fields": [
                  "id_contrato"
                ],
                "resource": "dm_contrato"
              }
            },
            {
              "fields": [
                "id_orgao_demanda"
              ],
              "reference": {
                "fields": [
                  "id_orgao_demanda"
                ],
                "resource": "dm_orgao_demanda"
              }
            },
            {
              "fields": [
                "id_unidade_medida"
              ],
              "reference": {
                "fields": [
                  "id_unidade_medida"
                ],
                "resource": "dm_unidade_medida"
              }
            },
            {
              "fields": [
                "id_grupo_matserv"
              ],
              "reference": {
                "fields": [
                  "id_grupo_matserv"
                ],
                "resource": "dm_grupo_matserv"
              }
            },
            {
              "fields": [
                "id_contratado"
              ],
              "reference": {
                "fields": [
                  "id_contratado"
                ],
                "resource": "dm_contratado"
              }
            },
            {
              "fields": [
                "id_procedimento"
              ],
              "reference": {
                "fields": [
                  "id_procedimento"
                ],
                "resource": "dm_procedimento"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_compras"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "c192ff0496ada00c15d35170d52686c0",
          "bytes": 58097672,
          "fields": 27,
          "rows": 1906115
        }
      },
      "time": 411.418,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "44413",
            "15",
            "1831042",
            "42",
            "1",
            "1",
            "883",
            "32428",
            "1",
            "39",
            "834",
            "21872",
            "339207",
            "381239",
            "78283",
            "889",
            "1831739",
            "3067",
            "2267",
            "2022",
            "2022-11-04",
            "250.0000",
            "1652.9300",
            "413232.50",
            "1652.9300",
            "413232.50",
            "413232.50"
          ],
          "rowNumber": 1812954,
          "rowPosition": 1812955,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78283\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812955\" violates the foreign key: for \"id_contrato\": values \"78283\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44413",
            "15",
            "1831042",
            "42",
            "1",
            "1",
            "883",
            "32428",
            "1",
            "39",
            "834",
            "21872",
            "335962",
            "381239",
            "78283",
            "889",
            "1831739",
            "3067",
            "2267",
            "2022",
            "2022-11-04",
            "10000.0000",
            "10.3500",
            "103500.00",
            "10.3500",
            "103500.00",
            "103500.00"
          ],
          "rowNumber": 1812955,
          "rowPosition": 1812956,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78283\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812956\" violates the foreign key: for \"id_contrato\": values \"78283\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44413",
            "15",
            "1831042",
            "42",
            "1",
            "1",
            "883",
            "32428",
            "1",
            "39",
            "834",
            "21889",
            "192740",
            "381239",
            "78283",
            "889",
            "1831739",
            "3067",
            "2267",
            "2022",
            "2022-11-04",
            "10.0000",
            "429.8500",
            "4298.50",
            "429.8500",
            "4298.50",
            "4298.50"
          ],
          "rowNumber": 1812956,
          "rowPosition": 1812957,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78283\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812957\" violates the foreign key: for \"id_contrato\": values \"78283\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44413",
            "15",
            "1831042",
            "42",
            "1",
            "1",
            "883",
            "32428",
            "1",
            "39",
            "130",
            "21730",
            "334463",
            "381239",
            "78283",
            "889",
            "1831805",
            "3067",
            "2267",
            "2022",
            "2022-11-04",
            "1.0000",
            "4748.6100",
            "4748.61",
            "4748.6100",
            "4748.61",
            "4748.61"
          ],
          "rowNumber": 1812957,
          "rowPosition": 1812958,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78283\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812958\" violates the foreign key: for \"id_contrato\": values \"78283\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44413",
            "15",
            "1831042",
            "42",
            "1",
            "1",
            "883",
            "32428",
            "1",
            "39",
            "130",
            "21730",
            "339215",
            "381239",
            "78283",
            "889",
            "1831805",
            "3067",
            "2267",
            "2022",
            "2022-11-04",
            "1.0000",
            "270.5200",
            "270.52",
            "270.5200",
            "270.52",
            "270.52"
          ],
          "rowNumber": 1812958,
          "rowPosition": 1812959,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78283\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812959\" violates the foreign key: for \"id_contrato\": values \"78283\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44431",
            "1",
            "1831055",
            "51",
            "1",
            "1",
            "66",
            "38145",
            "1",
            "77",
            "479",
            "1836",
            "91508",
            "383028",
            "78285",
            "889",
            "1831808",
            "2602",
            "2523",
            "2022",
            "2022-11-28",
            "0.0000",
            "20800.0000",
            "20800.00",
            "20800.0000",
            "20800.00",
            "20800.00"
          ],
          "rowNumber": 1816034,
          "rowPosition": 1816035,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78285\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1816035\" violates the foreign key: for \"id_contrato\": values \"78285\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43997",
            "4",
            "1831081",
            "77",
            "1",
            "1",
            "66",
            "21725",
            "1",
            "42",
            "12",
            "21615",
            "174643",
            "382721",
            "78286",
            "1913",
            "1831220",
            "2862",
            "2014",
            "2022",
            "2022-11-24",
            "96.0000",
            "73.5000",
            "7056.00",
            "25.8300",
            "2479.68",
            "2479.68"
          ],
          "rowNumber": 1817922,
          "rowPosition": 1817923,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78286\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1817923\" violates the foreign key: for \"id_contrato\": values \"78286\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43997",
            "4",
            "1831081",
            "77",
            "1",
            "1",
            "66",
            "21725",
            "1",
            "42",
            "12",
            "22478",
            "292627",
            "382721",
            "78286",
            "1071",
            "1831220",
            "2862",
            "2014",
            "2022",
            "2022-11-24",
            "216.0000",
            "386.8000",
            "83548.80",
            "90.5000",
            "19548.00",
            "19548.00"
          ],
          "rowNumber": 1817924,
          "rowPosition": 1817925,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78286\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1817925\" violates the foreign key: for \"id_contrato\": values \"78286\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43499",
            "4",
            "1831081",
            "77",
            "1",
            "1",
            "66",
            "20270",
            "1",
            "32",
            "100",
            "8368",
            "112099",
            "382637",
            "78289",
            "135",
            "1831400",
            "2796",
            "2014",
            "2022",
            "2022-11-24",
            "144.0000",
            "189.8500",
            "27338.40",
            "189.8500",
            "27338.40",
            "27338.40"
          ],
          "rowNumber": 1817940,
          "rowPosition": 1817941,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78289\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1817941\" violates the foreign key: for \"id_contrato\": values \"78289\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44444",
            "14",
            "1831034",
            "50",
            "1",
            "8",
            "66",
            "72888",
            "1",
            "77",
            "73",
            "10389",
            "158958",
            "383519",
            "46296",
            "889",
            "1831761",
            "2872",
            "1760",
            "2022",
            "2022-12-05",
            "0.0000",
            "4244.9100",
            "4244.91",
            "1520.0000",
            "1520.00",
            "1520.00"
          ],
          "rowNumber": 1820365,
          "rowPosition": 1820366,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contratado\": values \"72888\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "message": "Row at position \"1820366\" violates the foreign key: for \"id_contratado\": values \"72888\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44002",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "18037",
            "1",
            "85",
            "616",
            "14574",
            "277712",
            "381314",
            "78278",
            "889",
            "1831329",
            "2927",
            "3331",
            "2022",
            "2022-11-07",
            "822.0000",
            "39.6400",
            "32584.08",
            "13.0000",
            "10686.00",
            "10686.00"
          ],
          "rowNumber": 1832789,
          "rowPosition": 1832790,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78278\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1832790\" violates the foreign key: for \"id_contrato\": values \"78278\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44002",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "18037",
            "1",
            "85",
            "616",
            "14574",
            "277697",
            "381314",
            "78278",
            "889",
            "1831329",
            "2927",
            "3331",
            "2022",
            "2022-11-07",
            "100.0000",
            "23.9800",
            "2398.00",
            "13.0000",
            "1300.00",
            "1300.00"
          ],
          "rowNumber": 1832790,
          "rowPosition": 1832791,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78278\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1832791\" violates the foreign key: for \"id_contrato\": values \"78278\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44002",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "58665",
            "1",
            "48",
            "117",
            "5672",
            "50309",
            "381314",
            "78291",
            "598",
            "1831329",
            "2927",
            "3331",
            "2022",
            "2022-11-07",
            "120.0000",
            "52.8700",
            "6344.40",
            "42.9000",
            "5148.00",
            "5148.00"
          ],
          "rowNumber": 1832791,
          "rowPosition": 1832792,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78291\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1832792\" violates the foreign key: for \"id_contrato\": values \"78291\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44002",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "58665",
            "1",
            "48",
            "117",
            "5672",
            "34490",
            "381314",
            "78291",
            "598",
            "1831329",
            "2927",
            "3331",
            "2022",
            "2022-11-07",
            "150.0000",
            "28.0600",
            "4209.00",
            "28.0600",
            "4209.00",
            "4209.00"
          ],
          "rowNumber": 1832792,
          "rowPosition": 1832793,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78291\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1832793\" violates the foreign key: for \"id_contrato\": values \"78291\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44002",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "58665",
            "1",
            "48",
            "832",
            "21609",
            "170565",
            "381314",
            "78291",
            "1751",
            "1831329",
            "2927",
            "3331",
            "2022",
            "2022-11-07",
            "497.0000",
            "71.9100",
            "35739.27",
            "30.9000",
            "15357.30",
            "15357.30"
          ],
          "rowNumber": 1832793,
          "rowPosition": 1832794,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78291\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1832794\" violates the foreign key: for \"id_contrato\": values \"78291\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44002",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "58665",
            "1",
            "48",
            "832",
            "21609",
            "170578",
            "381314",
            "78291",
            "1751",
            "1831329",
            "2927",
            "3331",
            "2022",
            "2022-11-07",
            "1607.0000",
            "69.3400",
            "111429.38",
            "30.9000",
            "49656.30",
            "49656.30"
          ],
          "rowNumber": 1832794,
          "rowPosition": 1832795,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78291\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1832795\" violates the foreign key: for \"id_contrato\": values \"78291\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44002",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "58665",
            "1",
            "48",
            "832",
            "21609",
            "170564",
            "381314",
            "78291",
            "1751",
            "1831329",
            "2927",
            "3331",
            "2022",
            "2022-11-07",
            "1181.0000",
            "69.9000",
            "82551.90",
            "30.9000",
            "36492.90",
            "36492.90"
          ],
          "rowNumber": 1832795,
          "rowPosition": 1832796,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78291\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1832796\" violates the foreign key: for \"id_contrato\": values \"78291\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44002",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "58665",
            "1",
            "85",
            "616",
            "2582",
            "169887",
            "381314",
            "78291",
            "595",
            "1831329",
            "2927",
            "3331",
            "2022",
            "2022-11-07",
            "4.0000",
            "121.1000",
            "484.40",
            "101.2500",
            "405.00",
            "405.00"
          ],
          "rowNumber": 1832796,
          "rowPosition": 1832797,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78291\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1832797\" violates the foreign key: for \"id_contrato\": values \"78291\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44002",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "58665",
            "1",
            "85",
            "616",
            "2582",
            "74431",
            "381314",
            "78291",
            "595",
            "1831329",
            "2927",
            "3331",
            "2022",
            "2022-11-07",
            "7.0000",
            "121.1000",
            "847.70",
            "101.2500",
            "708.75",
            "708.75"
          ],
          "rowNumber": 1832797,
          "rowPosition": 1832798,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78291\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1832798\" violates the foreign key: for \"id_contrato\": values \"78291\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44002",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "58665",
            "1",
            "85",
            "616",
            "2582",
            "169949",
            "381314",
            "78291",
            "595",
            "1831329",
            "2927",
            "3331",
            "2022",
            "2022-11-07",
            "4.0000",
            "121.1000",
            "484.40",
            "101.2500",
            "405.00",
            "405.00"
          ],
          "rowNumber": 1832798,
          "rowPosition": 1832799,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78291\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1832799\" violates the foreign key: for \"id_contrato\": values \"78291\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44002",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "58665",
            "1",
            "85",
            "616",
            "2582",
            "169946",
            "381314",
            "78291",
            "595",
            "1831329",
            "2927",
            "3331",
            "2022",
            "2022-11-07",
            "9.0000",
            "121.1000",
            "1089.90",
            "101.2500",
            "911.25",
            "911.25"
          ],
          "rowNumber": 1832799,
          "rowPosition": 1832800,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78291\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1832800\" violates the foreign key: for \"id_contrato\": values \"78291\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44002",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "14353",
            "1",
            "48",
            "117",
            "5672",
            "100741",
            "381314",
            "78284",
            "595",
            "1831329",
            "2927",
            "3331",
            "2022",
            "2022-11-07",
            "44.0000",
            "46.7900",
            "2058.54",
            "25.0000",
            "1100.00",
            "1100.00"
          ],
          "rowNumber": 1832800,
          "rowPosition": 1832801,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78284\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1832801\" violates the foreign key: for \"id_contrato\": values \"78284\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44002",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "58665",
            "1",
            "48",
            "117",
            "5672",
            "148989",
            "381314",
            "78291",
            "598",
            "1831329",
            "2927",
            "3331",
            "2022",
            "2022-11-07",
            "42.0000",
            "13.8300",
            "580.86",
            "11.0500",
            "464.10",
            "464.10"
          ],
          "rowNumber": 1832801,
          "rowPosition": 1832802,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78291\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1832802\" violates the foreign key: for \"id_contrato\": values \"78291\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44002",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "58665",
            "1",
            "48",
            "117",
            "5672",
            "153707",
            "381314",
            "78291",
            "598",
            "1831329",
            "2927",
            "3331",
            "2022",
            "2022-11-07",
            "11.0000",
            "8.5000",
            "93.50",
            "8.5000",
            "93.50",
            "93.50"
          ],
          "rowNumber": 1832802,
          "rowPosition": 1832803,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78291\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1832803\" violates the foreign key: for \"id_contrato\": values \"78291\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44002",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "58665",
            "1",
            "48",
            "117",
            "5672",
            "169497",
            "381314",
            "78291",
            "598",
            "1831329",
            "2927",
            "3331",
            "2022",
            "2022-11-07",
            "19.0000",
            "8.5000",
            "161.50",
            "8.5000",
            "161.50",
            "161.50"
          ],
          "rowNumber": 1832803,
          "rowPosition": 1832804,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78291\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1832804\" violates the foreign key: for \"id_contrato\": values \"78291\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44002",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "14353",
            "1",
            "48",
            "117",
            "10616",
            "137166",
            "381314",
            "78284",
            "889",
            "1831329",
            "2927",
            "3331",
            "2022",
            "2022-11-07",
            "12.0000",
            "110.9200",
            "1331.04",
            "92.4000",
            "1108.80",
            "1108.80"
          ],
          "rowNumber": 1832804,
          "rowPosition": 1832805,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78284\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1832805\" violates the foreign key: for \"id_contrato\": values \"78284\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44002",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "14353",
            "1",
            "48",
            "117",
            "14461",
            "49090",
            "381314",
            "78284",
            "889",
            "1831329",
            "2927",
            "3331",
            "2022",
            "2022-11-07",
            "12.0000",
            "85.0000",
            "1020.00",
            "69.0000",
            "828.00",
            "828.00"
          ],
          "rowNumber": 1832805,
          "rowPosition": 1832806,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78284\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1832806\" violates the foreign key: for \"id_contrato\": values \"78284\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44002",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "14353",
            "1",
            "48",
            "117",
            "11103",
            "90412",
            "381314",
            "78284",
            "598",
            "1831329",
            "2927",
            "3331",
            "2022",
            "2022-11-07",
            "2.0000",
            "33.5700",
            "67.14",
            "31.1000",
            "62.20",
            "62.20"
          ],
          "rowNumber": 1832806,
          "rowPosition": 1832807,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78284\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1832807\" violates the foreign key: for \"id_contrato\": values \"78284\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44002",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "14353",
            "1",
            "85",
            "616",
            "19013",
            "26153",
            "381314",
            "78284",
            "595",
            "1831329",
            "2927",
            "3331",
            "2022",
            "2022-11-07",
            "2.0000",
            "22.2900",
            "44.58",
            "14.5000",
            "29.00",
            "29.00"
          ],
          "rowNumber": 1832807,
          "rowPosition": 1832808,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78284\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1832808\" violates the foreign key: for \"id_contrato\": values \"78284\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44002",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "14353",
            "1",
            "85",
            "616",
            "19196",
            "297364",
            "381314",
            "78284",
            "889",
            "1831329",
            "2927",
            "3331",
            "2022",
            "2022-11-07",
            "1.0000",
            "170.9000",
            "170.90",
            "114.6800",
            "114.68",
            "114.68"
          ],
          "rowNumber": 1832808,
          "rowPosition": 1832809,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78284\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1832809\" violates the foreign key: for \"id_contrato\": values \"78284\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44002",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "14353",
            "1",
            "85",
            "616",
            "19680",
            "70063",
            "381314",
            "78284",
            "889",
            "1831329",
            "3138",
            "3331",
            "2022",
            "2022-11-07",
            "2.0000",
            "40.5000",
            "81.00",
            "27.0000",
            "54.00",
            "54.00"
          ],
          "rowNumber": 1832809,
          "rowPosition": 1832810,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78284\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1832810\" violates the foreign key: for \"id_contrato\": values \"78284\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44002",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "58665",
            "1",
            "42",
            "624",
            "2986",
            "16476",
            "381314",
            "78291",
            "1544",
            "1831334",
            "2923",
            "3331",
            "2022",
            "2022-11-07",
            "800.0000",
            "24.1000",
            "19280.00",
            "9.9500",
            "7960.00",
            "7960.00"
          ],
          "rowNumber": 1832810,
          "rowPosition": 1832811,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78291\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1832811\" violates the foreign key: for \"id_contrato\": values \"78291\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44002",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "14353",
            "1",
            "85",
            "616",
            "4142",
            "143572",
            "381314",
            "78284",
            "889",
            "1831329",
            "2927",
            "3331",
            "2022",
            "2022-11-07",
            "150.0000",
            "1.5400",
            "231.00",
            "1.2300",
            "184.50",
            "184.50"
          ],
          "rowNumber": 1832811,
          "rowPosition": 1832812,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78284\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1832812\" violates the foreign key: for \"id_contrato\": values \"78284\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44002",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "24550",
            "1",
            "85",
            "616",
            "5722",
            "111180",
            "381314",
            "78279",
            "889",
            "1831329",
            "2927",
            "3331",
            "2022",
            "2022-11-07",
            "200.0000",
            "15.9500",
            "3190.00",
            "15.8500",
            "3170.00",
            "3170.00"
          ],
          "rowNumber": 1832812,
          "rowPosition": 1832813,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78279\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1832813\" violates the foreign key: for \"id_contrato\": values \"78279\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44440",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "59703",
            "1",
            "36",
            "631",
            "13988",
            "245388",
            "383276",
            "78290",
            "98",
            "1831132",
            "2539",
            "3043",
            "2022",
            "2022-12-01",
            "128000.0000",
            "6.3600",
            "814080.00",
            "6.3600",
            "814080.00",
            "814080.00"
          ],
          "rowNumber": 1850391,
          "rowPosition": 1850392,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78290\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1850392\" violates the foreign key: for \"id_contrato\": values \"78290\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44440",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "67038",
            "1",
            "36",
            "631",
            "15902",
            "244582",
            "383276",
            "78281",
            "98",
            "1831132",
            "2539",
            "3043",
            "2022",
            "2022-12-01",
            "506000.0000",
            "2.5500",
            "1290300.00",
            "2.5500",
            "1290300.00",
            "1290300.00"
          ],
          "rowNumber": 1850392,
          "rowPosition": 1850393,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78281\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1850393\" violates the foreign key: for \"id_contrato\": values \"78281\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44432",
            "1",
            "1831047",
            "37",
            "1",
            "1",
            "66",
            "19729",
            "1",
            "77",
            "533",
            "4338",
            "90067",
            "383399",
            "78287",
            "889",
            "1831751",
            "2807",
            "3044",
            "2022",
            "2022-12-01",
            "0.0000",
            "233322.0000",
            "233322.00",
            "233322.0000",
            "233322.00",
            "233322.00"
          ],
          "rowNumber": 1855800,
          "rowPosition": 1855801,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78287\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1855801\" violates the foreign key: for \"id_contrato\": values \"78287\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43963",
            "14",
            "1831044",
            "36",
            "1",
            "1",
            "66",
            "66171",
            "1",
            "44",
            "724",
            "7562",
            "170274",
            "377929",
            "78288",
            "889",
            "1831991",
            "3018",
            "2633",
            "2022",
            "2022-11-30",
            "15.0000",
            "65.0000",
            "975.00",
            "46.5800",
            "698.70",
            "698.70"
          ],
          "rowNumber": 1861985,
          "rowPosition": 1861986,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78288\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1861986\" violates the foreign key: for \"id_contrato\": values \"78288\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43544",
            "4",
            "1831101",
            "97",
            "1",
            "1",
            "66",
            "24293",
            "1",
            "77",
            "808",
            "4383",
            "145722",
            "382859",
            "78282",
            "889",
            "1899033",
            "2869",
            "2259",
            "2022",
            "2022-11-25",
            "0.0000",
            "109172.8500",
            "109172.85",
            "91891.2500",
            "91891.25",
            "91891.25"
          ],
          "rowNumber": 1862782,
          "rowPosition": 1862783,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78282\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1862783\" violates the foreign key: for \"id_contrato\": values \"78282\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43963",
            "14",
            "1831044",
            "36",
            "1",
            "1",
            "66",
            "70159",
            "1",
            "83",
            "617",
            "10316",
            "369034",
            "377929",
            "78292",
            "889",
            "1831825",
            "3018",
            "2633",
            "2022",
            "2022-09-16",
            "1.0000",
            "250.0000",
            "250.00",
            "248.5000",
            "248.50",
            "248.50"
          ],
          "rowNumber": 1887192,
          "rowPosition": 1887193,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78292\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1887193\" violates the foreign key: for \"id_contrato\": values \"78292\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43963",
            "14",
            "1831044",
            "36",
            "1",
            "1",
            "66",
            "33624",
            "1",
            "83",
            "120",
            "11058",
            "154011",
            "377929",
            "78276",
            "889",
            "1831825",
            "3018",
            "2633",
            "2022",
            "2022-09-16",
            "1.0000",
            "3340.0000",
            "3340.00",
            "3250.0000",
            "3250.00",
            "3250.00"
          ],
          "rowNumber": 1887193,
          "rowPosition": 1887194,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78276\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1887194\" violates the foreign key: for \"id_contrato\": values \"78276\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43963",
            "14",
            "1831044",
            "36",
            "1",
            "1",
            "66",
            "33624",
            "1",
            "67",
            "738",
            "21551",
            "169493",
            "377929",
            "78276",
            "889",
            "1831979",
            "3078",
            "2633",
            "2022",
            "2022-09-16",
            "1.0000",
            "2345.0000",
            "2345.00",
            "2250.0000",
            "2250.00",
            "2250.00"
          ],
          "rowNumber": 1887194,
          "rowPosition": 1887195,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78276\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1887195\" violates the foreign key: for \"id_contrato\": values \"78276\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43963",
            "14",
            "1831044",
            "36",
            "1",
            "1",
            "66",
            "27921",
            "1",
            "44",
            "724",
            "15676",
            "202814",
            "377929",
            "78293",
            "889",
            "1831304",
            "3018",
            "2633",
            "2022",
            "2022-09-16",
            "2.0000",
            "3490.0000",
            "6980.00",
            "938.0000",
            "1876.00",
            "1876.00"
          ],
          "rowNumber": 1887195,
          "rowPosition": 1887196,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78293\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1887196\" violates the foreign key: for \"id_contrato\": values \"78293\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44037",
            "2",
            "1831058",
            "54",
            "1",
            "1",
            "66",
            "329",
            "1",
            "39",
            "130",
            "21730",
            "265333",
            "378906",
            "78280",
            "889",
            "1831805",
            "3067",
            "2012",
            "2022",
            "2022-09-29",
            "0.0000",
            "16817.2800",
            "16817.28",
            "16817.2800",
            "16817.28",
            "16817.28"
          ],
          "rowNumber": 1896932,
          "rowPosition": 1896933,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78280\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1896933\" violates the foreign key: for \"id_contrato\": values \"78280\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44037",
            "2",
            "1831058",
            "54",
            "1",
            "1",
            "66",
            "329",
            "1",
            "39",
            "130",
            "22219",
            "265325",
            "378906",
            "78280",
            "889",
            "1831805",
            "3067",
            "2012",
            "2022",
            "2022-09-29",
            "0.0000",
            "10483.2100",
            "10483.21",
            "10483.2100",
            "10483.21",
            "10483.21"
          ],
          "rowNumber": 1896933,
          "rowPosition": 1896934,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78280\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1896934\" violates the foreign key: for \"id_contrato\": values \"78280\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43585",
            "1",
            "1831008",
            "5",
            "1",
            "1",
            "66",
            "20687",
            "1",
            "51",
            "383",
            "17638",
            "92859",
            "382620",
            "78277",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-11-23",
            "0.0000",
            "20134.7400",
            "20134.74",
            "20134.7400",
            "20134.74",
            "20134.74"
          ],
          "rowNumber": 1898329,
          "rowPosition": 1898330,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78277\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1898330\" violates the foreign key: for \"id_contrato\": values \"78277\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43585",
            "1",
            "1831008",
            "5",
            "1",
            "1",
            "66",
            "20687",
            "1",
            "51",
            "383",
            "17638",
            "92859",
            "382620",
            "78277",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-11-23",
            "0.0000",
            "126179.9300",
            "126179.93",
            "126179.9300",
            "126179.93",
            "126179.93"
          ],
          "rowNumber": 1899278,
          "rowPosition": 1899279,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78277\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1899279\" violates the foreign key: for \"id_contrato\": values \"78277\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43585",
            "1",
            "1831008",
            "5",
            "1",
            "1",
            "66",
            "20687",
            "1",
            "51",
            "383",
            "17638",
            "92859",
            "382620",
            "78277",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-11-23",
            "0.0000",
            "354467.9400",
            "354467.94",
            "354467.9400",
            "354467.94",
            "354467.94"
          ],
          "rowNumber": 1901939,
          "rowPosition": 1901940,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78277\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1901940\" violates the foreign key: for \"id_contrato\": values \"78277\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43585",
            "1",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "20687",
            "1",
            "51",
            "383",
            "17638",
            "92859",
            "382620",
            "78277",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-11-23",
            "0.0000",
            "38594.3600",
            "38594.36",
            "38594.3600",
            "38594.36",
            "38594.36"
          ],
          "rowNumber": 1901954,
          "rowPosition": 1901955,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78277\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1901955\" violates the foreign key: for \"id_contrato\": values \"78277\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 49
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 49,
    "tasks": 1
  },
  "valid": false
}