{
  "version": "4.38.0",
  "time": 413.316,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_compras",
        "title": "Compras",
        "path": "data/ft_compras.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_tempo",
              "title": "Tempo - Chave",
              "type": "integer",
              "format": "default",
              "description": "- > \n  Chave estrangeira (Foreign Key) que aponta para a Chave Primária (Primary keys) da tabela dm_tempo_diario. \n  Ou seja, por meio dessa chave é possível identificar a data completa a qual o dado se refere.\n\n  Nota: \n  No site dados.mg.gov.br a tabela dm_tempo_diario pode ser encontrada no recurso Calendários - Dias \n  de cada conjunto.\n",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_procedimento",
              "title": "Procedimento de Contratação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_demanda",
              "title": "Órgão Demandante - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_contrato",
              "title": "Órgão do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_proc",
              "title": "Situação do Processo de Compra - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_cont",
              "title": "Situação do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_municipio",
              "title": "Município - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contratado",
              "title": "Contratado - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_tipo_licitacao",
              "title": "Tipo de Licitação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_grupo_matserv",
              "title": "Grupo Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_classe_matserv",
              "title": "Classe Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_material_servico",
              "title": "Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item_matserv",
              "title": "Item Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_processo",
              "title": "Processo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contrato",
              "title": "Número do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_medida",
              "title": "Unidade de Medida - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_linha_fornec",
              "title": "Linha de Fornecimento - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_orc",
              "title": "Unidade Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "unique": false
              }
            },
            {
              "name": "ano_particao",
              "title": "Ano Partição",
              "type": "year",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true
              }
            },
            {
              "name": "dt_item_homologa",
              "title": "Data da Homologação do Item",
              "type": "date",
              "format": "default",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "qt_item_pedido",
              "title": "Item do Pedido - Quantidade",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_referencia",
              "title": "Valor Unitário de Referência",
              "description": "Valor unitário estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_referencia",
              "title": "Valor de Referência",
              "description": "Valor estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_homologado",
              "title": "Valor Unitário Homologado",
              "description": "Valor unitário final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_homologado",
              "title": "Valor Homologado",
              "description": "Valor final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_atualizado",
              "title": "Valor Atualizado",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_processo"
              ],
              "reference": {
                "fields": [
                  "id_processo"
                ],
                "resource": "dm_processo"
              }
            },
            {
              "fields": [
                "id_situacao_cont"
              ],
              "reference": {
                "fields": [
                  "id_situacao_cont"
                ],
                "resource": "dm_situacao_cont"
              }
            },
            {
              "fields": [
                "id_situacao_proc"
              ],
              "reference": {
                "fields": [
                  "id_situacao_proc"
                ],
                "resource": "dm_situacao_proc"
              }
            },
            {
              "fields": [
                "id_linha_fornec"
              ],
              "reference": {
                "fields": [
                  "id_linha_fornec"
                ],
                "resource": "dm_linha_fornec"
              }
            },
            {
              "fields": [
                "id_classe_matserv"
              ],
              "reference": {
                "fields": [
                  "id_classe_matserv"
                ],
                "resource": "dm_classe_matserv"
              }
            },
            {
              "fields": [
                "id_tempo"
              ],
              "reference": {
                "fields": [
                  "id_tempo"
                ],
                "resource": "dm_tempo_diario"
              }
            },
            {
              "fields": [
                "id_municipio"
              ],
              "reference": {
                "fields": [
                  "id_municipio"
                ],
                "resource": "dm_municipio"
              }
            },
            {
              "fields": [
                "id_item_matserv"
              ],
              "reference": {
                "fields": [
                  "id_item_matserv"
                ],
                "resource": "dm_item_matserv"
              }
            },
            {
              "fields": [
                "id_tipo_licitacao"
              ],
              "reference": {
                "fields": [
                  "id_tipo_licitacao"
                ],
                "resource": "dm_tipo_licitacao"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_material_servico"
              ],
              "reference": {
                "fields": [
                  "id_material_servico"
                ],
                "resource": "dm_material_servico"
              }
            },
            {
              "fields": [
                "id_orgao_contrato"
              ],
              "reference": {
                "fields": [
                  "id_orgao_contrato"
                ],
                "resource": "dm_orgao_contrato"
              }
            },
            {
              "fields": [
                "id_contrato"
              ],
              "reference": {
                "fields": [
                  "id_contrato"
                ],
                "resource": "dm_contrato"
              }
            },
            {
              "fields": [
                "id_orgao_demanda"
              ],
              "reference": {
                "fields": [
                  "id_orgao_demanda"
                ],
                "resource": "dm_orgao_demanda"
              }
            },
            {
              "fields": [
                "id_unidade_medida"
              ],
              "reference": {
                "fields": [
                  "id_unidade_medida"
                ],
                "resource": "dm_unidade_medida"
              }
            },
            {
              "fields": [
                "id_grupo_matserv"
              ],
              "reference": {
                "fields": [
                  "id_grupo_matserv"
                ],
                "resource": "dm_grupo_matserv"
              }
            },
            {
              "fields": [
                "id_contratado"
              ],
              "reference": {
                "fields": [
                  "id_contratado"
                ],
                "resource": "dm_contratado"
              }
            },
            {
              "fields": [
                "id_procedimento"
              ],
              "reference": {
                "fields": [
                  "id_procedimento"
                ],
                "resource": "dm_procedimento"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_compras"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "213963b1cfbce9086e4d18da314710c4",
          "bytes": 58452966,
          "fields": 27,
          "rows": 1918770
        }
      },
      "time": 413.316,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "44040",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "23602",
            "1",
            "51",
            "383",
            "17638",
            "358000",
            "385029",
            "79208",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-12-23",
            "0.0000",
            "2958437.8000",
            "2958437.79",
            "1295536.7500",
            "1295536.75",
            "1295536.75"
          ],
          "rowNumber": 1812895,
          "rowPosition": 1812896,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79208\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812896\" violates the foreign key: for \"id_contrato\": values \"79208\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44040",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "23602",
            "1",
            "51",
            "383",
            "17638",
            "358001",
            "385029",
            "79208",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-12-23",
            "0.0000",
            "560807.6600",
            "560807.66",
            "522646.0500",
            "522646.05",
            "522646.05"
          ],
          "rowNumber": 1812896,
          "rowPosition": 1812897,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79208\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812897\" violates the foreign key: for \"id_contrato\": values \"79208\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44040",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "23602",
            "1",
            "51",
            "383",
            "17638",
            "358001",
            "385029",
            "79208",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-12-23",
            "0.0000",
            "27181.0400",
            "27181.04",
            "25331.3000",
            "25331.30",
            "25331.30"
          ],
          "rowNumber": 1812899,
          "rowPosition": 1812900,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79208\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812900\" violates the foreign key: for \"id_contrato\": values \"79208\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44040",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "23602",
            "1",
            "51",
            "383",
            "17638",
            "358000",
            "385029",
            "79208",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-12-23",
            "0.0000",
            "621261.7500",
            "621261.74",
            "378942.4700",
            "378942.47",
            "378942.47"
          ],
          "rowNumber": 1812900,
          "rowPosition": 1812901,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79208\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812901\" violates the foreign key: for \"id_contrato\": values \"79208\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44040",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "23602",
            "1",
            "51",
            "383",
            "17638",
            "358000",
            "385029",
            "79208",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-12-23",
            "0.0000",
            "581133.8600",
            "581133.86",
            "328416.8100",
            "328416.81",
            "328416.81"
          ],
          "rowNumber": 1812904,
          "rowPosition": 1812905,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79208\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812905\" violates the foreign key: for \"id_contrato\": values \"79208\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44040",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "23602",
            "1",
            "51",
            "383",
            "17638",
            "358001",
            "385029",
            "79208",
            "981",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-12-23",
            "0.0000",
            "21446.4900",
            "21446.49",
            "19987.0400",
            "19987.04",
            "19987.04"
          ],
          "rowNumber": 1812905,
          "rowPosition": 1812906,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79208\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812906\" violates the foreign key: for \"id_contrato\": values \"79208\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44040",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "23602",
            "1",
            "51",
            "383",
            "17638",
            "358000",
            "385029",
            "79208",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-12-23",
            "0.0000",
            "2027711.7600",
            "2027711.76",
            "884199.1000",
            "884199.10",
            "884199.10"
          ],
          "rowNumber": 1812906,
          "rowPosition": 1812907,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79208\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812907\" violates the foreign key: for \"id_contrato\": values \"79208\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44040",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "23602",
            "1",
            "51",
            "383",
            "17638",
            "358001",
            "385029",
            "79208",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-12-23",
            "0.0000",
            "441590.7600",
            "441590.76",
            "411541.7800",
            "411541.78",
            "411541.78"
          ],
          "rowNumber": 1812907,
          "rowPosition": 1812908,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79208\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812908\" violates the foreign key: for \"id_contrato\": values \"79208\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44040",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "23602",
            "1",
            "51",
            "383",
            "17638",
            "358000",
            "385029",
            "79208",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-12-23",
            "0.0000",
            "1078944.9100",
            "1078944.90",
            "588880.3400",
            "588880.34",
            "588880.34"
          ],
          "rowNumber": 1812913,
          "rowPosition": 1812914,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79208\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812914\" violates the foreign key: for \"id_contrato\": values \"79208\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44040",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "23602",
            "1",
            "51",
            "383",
            "17638",
            "358001",
            "385029",
            "79208",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-12-23",
            "0.0000",
            "235510.0900",
            "235510.09",
            "219484.3800",
            "219484.38",
            "219484.38"
          ],
          "rowNumber": 1812914,
          "rowPosition": 1812915,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79208\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812915\" violates the foreign key: for \"id_contrato\": values \"79208\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44040",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "23602",
            "1",
            "51",
            "383",
            "17638",
            "358000",
            "385029",
            "79208",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-12-23",
            "0.0000",
            "591863.6700",
            "591863.67",
            "341048.2200",
            "341048.22",
            "341048.22"
          ],
          "rowNumber": 1812924,
          "rowPosition": 1812925,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79208\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812925\" violates the foreign key: for \"id_contrato\": values \"79208\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44040",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "23602",
            "1",
            "51",
            "383",
            "17638",
            "358001",
            "385029",
            "79208",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-12-23",
            "0.0000",
            "28344.7000",
            "28344.70",
            "26415.9000",
            "26415.90",
            "26415.90"
          ],
          "rowNumber": 1812925,
          "rowPosition": 1812926,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79208\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812926\" violates the foreign key: for \"id_contrato\": values \"79208\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44040",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "23602",
            "1",
            "51",
            "383",
            "17638",
            "358000",
            "385029",
            "79208",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-12-23",
            "0.0000",
            "869678.0400",
            "869678.04",
            "341048.2200",
            "341048.22",
            "341048.22"
          ],
          "rowNumber": 1812946,
          "rowPosition": 1812947,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79208\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812947\" violates the foreign key: for \"id_contrato\": values \"79208\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44040",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "23602",
            "1",
            "51",
            "383",
            "17638",
            "358001",
            "385029",
            "79208",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-12-23",
            "0.0000",
            "250086.8900",
            "250086.88",
            "233069.1600",
            "233069.16",
            "233069.16"
          ],
          "rowNumber": 1812947,
          "rowPosition": 1812948,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79208\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812948\" violates the foreign key: for \"id_contrato\": values \"79208\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43479",
            "4",
            "1831030",
            "27",
            "1",
            "1",
            "876",
            "899",
            "1",
            "58",
            "115",
            "13675",
            "90034",
            "383764",
            "79202",
            "889",
            "1831387",
            "2995",
            "2270",
            "2022",
            "2022-12-07",
            "13.0000",
            "772.0000",
            "10036.00",
            "566.8000",
            "7368.40",
            "7368.40"
          ],
          "rowNumber": 1814682,
          "rowPosition": 1814683,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79202\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1814683\" violates the foreign key: for \"id_contrato\": values \"79202\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43479",
            "4",
            "1831030",
            "27",
            "1",
            "1",
            "876",
            "899",
            "1",
            "58",
            "115",
            "13675",
            "85463",
            "383764",
            "79202",
            "889",
            "1831387",
            "2995",
            "2270",
            "2022",
            "2022-12-07",
            "15.0000",
            "669.0000",
            "10035.00",
            "515.2000",
            "7728.00",
            "7728.00"
          ],
          "rowNumber": 1814683,
          "rowPosition": 1814684,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79202\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1814684\" violates the foreign key: for \"id_contrato\": values \"79202\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43479",
            "4",
            "1831030",
            "27",
            "1",
            "1",
            "876",
            "899",
            "1",
            "58",
            "115",
            "13675",
            "14663",
            "383764",
            "79202",
            "889",
            "1831387",
            "2995",
            "2270",
            "2022",
            "2022-12-07",
            "13.0000",
            "669.0000",
            "8697.00",
            "515.2000",
            "6697.60",
            "6697.60"
          ],
          "rowNumber": 1814684,
          "rowPosition": 1814685,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79202\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1814685\" violates the foreign key: for \"id_contrato\": values \"79202\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43479",
            "4",
            "1831030",
            "27",
            "1",
            "1",
            "876",
            "899",
            "1",
            "47",
            "242",
            "22388",
            "271224",
            "383764",
            "79202",
            "889",
            "1831974",
            "2995",
            "2270",
            "2022",
            "2022-12-07",
            "150.0000",
            "45.0000",
            "6750.00",
            "41.6100",
            "6241.50",
            "6241.50"
          ],
          "rowNumber": 1814693,
          "rowPosition": 1814694,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79202\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1814694\" violates the foreign key: for \"id_contrato\": values \"79202\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43479",
            "4",
            "1831030",
            "27",
            "1",
            "1",
            "876",
            "899",
            "1",
            "55",
            "731",
            "18617",
            "158032",
            "383764",
            "79202",
            "889",
            "1831986",
            "2541",
            "2270",
            "2022",
            "2022-12-07",
            "7.0000",
            "1400.0000",
            "9800.00",
            "1167.0000",
            "8169.00",
            "8169.00"
          ],
          "rowNumber": 1814694,
          "rowPosition": 1814695,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79202\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1814695\" violates the foreign key: for \"id_contrato\": values \"79202\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43479",
            "4",
            "1831030",
            "27",
            "1",
            "1",
            "876",
            "899",
            "1",
            "55",
            "731",
            "18617",
            "116740",
            "383764",
            "79202",
            "889",
            "1831986",
            "2541",
            "2270",
            "2022",
            "2022-12-07",
            "7.0000",
            "1535.0000",
            "10745.00",
            "1501.5000",
            "10510.50",
            "10510.50"
          ],
          "rowNumber": 1814695,
          "rowPosition": 1814696,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79202\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1814696\" violates the foreign key: for \"id_contrato\": values \"79202\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43479",
            "4",
            "1831030",
            "27",
            "1",
            "1",
            "876",
            "899",
            "1",
            "47",
            "634",
            "12848",
            "134857",
            "383764",
            "79202",
            "889",
            "1831974",
            "2744",
            "2270",
            "2022",
            "2022-12-07",
            "5.0000",
            "5024.0000",
            "25120.00",
            "4160.0000",
            "20800.00",
            "20800.00"
          ],
          "rowNumber": 1814696,
          "rowPosition": 1814697,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79202\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1814697\" violates the foreign key: for \"id_contrato\": values \"79202\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43479",
            "4",
            "1831030",
            "27",
            "1",
            "1",
            "876",
            "899",
            "1",
            "58",
            "115",
            "20597",
            "162565",
            "383764",
            "79202",
            "889",
            "1831387",
            "2813",
            "2270",
            "2022",
            "2022-12-07",
            "3.0000",
            "15660.0000",
            "46980.00",
            "15633.3300",
            "46899.99",
            "46899.99"
          ],
          "rowNumber": 1814698,
          "rowPosition": 1814699,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79202\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1814699\" violates the foreign key: for \"id_contrato\": values \"79202\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43479",
            "4",
            "1831030",
            "27",
            "1",
            "1",
            "876",
            "899",
            "1",
            "67",
            "738",
            "10259",
            "219101",
            "383764",
            "79202",
            "889",
            "1831846",
            "2554",
            "2270",
            "2022",
            "2022-12-07",
            "2.0000",
            "7580.0000",
            "15160.00",
            "3900.0000",
            "7800.00",
            "7800.00"
          ],
          "rowNumber": 1815554,
          "rowPosition": 1815555,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79202\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1815555\" violates the foreign key: for \"id_contrato\": values \"79202\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43479",
            "4",
            "1831030",
            "27",
            "1",
            "1",
            "876",
            "899",
            "1",
            "35",
            "514",
            "9913",
            "103438",
            "383764",
            "79202",
            "889",
            "1831303",
            "2922",
            "2270",
            "2022",
            "2022-12-07",
            "11.0000",
            "2760.0000",
            "30360.00",
            "1946.1000",
            "21407.10",
            "21407.10"
          ],
          "rowNumber": 1815556,
          "rowPosition": 1815557,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79202\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1815557\" violates the foreign key: for \"id_contrato\": values \"79202\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43479",
            "4",
            "1831030",
            "27",
            "1",
            "1",
            "876",
            "899",
            "1",
            "58",
            "732",
            "16135",
            "16432",
            "383764",
            "79202",
            "889",
            "1831373",
            "2796",
            "2270",
            "2022",
            "2022-12-07",
            "70.0000",
            "15.5000",
            "1085.00",
            "8.5700",
            "599.90",
            "599.90"
          ],
          "rowNumber": 1815557,
          "rowPosition": 1815558,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79202\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1815558\" violates the foreign key: for \"id_contrato\": values \"79202\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43479",
            "4",
            "1831030",
            "27",
            "1",
            "1",
            "876",
            "899",
            "1",
            "58",
            "732",
            "22433",
            "288538",
            "383764",
            "79202",
            "1729",
            "1831373",
            "2796",
            "2270",
            "2022",
            "2022-12-07",
            "60.0000",
            "60.1300",
            "3607.80",
            "65.0000",
            "3900.00",
            "3900.00"
          ],
          "rowNumber": 1815558,
          "rowPosition": 1815559,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79202\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1815559\" violates the foreign key: for \"id_contrato\": values \"79202\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43969",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "71396",
            "1",
            "39",
            "831",
            "21867",
            "188821",
            "384252",
            "79199",
            "889",
            "1831925",
            "3068",
            "3042",
            "2022",
            "2022-12-15",
            "0.0000",
            "195864.1200",
            "195864.12",
            "195799.8000",
            "195799.80",
            "195799.80"
          ],
          "rowNumber": 1821398,
          "rowPosition": 1821399,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79199\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1821399\" violates the foreign key: for \"id_contrato\": values \"79199\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43555",
            "4",
            "1831102",
            "89",
            "1",
            "1",
            "66",
            "21079",
            "1",
            "9",
            "576",
            "9773",
            "93244",
            "384099",
            "79204",
            "889",
            "1831684",
            "2736",
            "2838",
            "2022",
            "2022-12-13",
            "0.0000",
            "222000.0000",
            "222000.00",
            "221999.9600",
            "221999.96",
            "221999.96"
          ],
          "rowNumber": 1824017,
          "rowPosition": 1824018,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1824018\" violates the foreign key: for \"id_contrato\": values \"79204\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44040",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "23602",
            "1",
            "51",
            "383",
            "17638",
            "358000",
            "385029",
            "79208",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-12-23",
            "0.0000",
            "357515.9200",
            "357515.92",
            "353328.2000",
            "353328.20",
            "353328.20"
          ],
          "rowNumber": 1825506,
          "rowPosition": 1825507,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79208\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1825507\" violates the foreign key: for \"id_contrato\": values \"79208\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44040",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "23602",
            "1",
            "51",
            "383",
            "17638",
            "358001",
            "385029",
            "79208",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-12-23",
            "0.0000",
            "55916.2300",
            "55916.23",
            "52111.3600",
            "52111.36",
            "52111.36"
          ],
          "rowNumber": 1825507,
          "rowPosition": 1825508,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79208\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1825508\" violates the foreign key: for \"id_contrato\": values \"79208\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43493",
            "4",
            "1831102",
            "89",
            "1",
            "1",
            "66",
            "71854",
            "1",
            "19",
            "730",
            "15741",
            "170382",
            "382771",
            "79206",
            "588",
            "1831295",
            "2995",
            "2838",
            "2022",
            "2022-11-25",
            "8.0000",
            "494.1200",
            "3952.92",
            "487.5000",
            "3900.00",
            "3900.00"
          ],
          "rowNumber": 1858183,
          "rowPosition": 1858184,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79206\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1858184\" violates the foreign key: for \"id_contrato\": values \"79206\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43493",
            "4",
            "1831102",
            "89",
            "1",
            "1",
            "66",
            "71854",
            "1",
            "3",
            "143",
            "18489",
            "276359",
            "382771",
            "79206",
            "889",
            "1831295",
            "3018",
            "2838",
            "2022",
            "2022-11-25",
            "10.0000",
            "53300.0000",
            "533000.00",
            "16570.0000",
            "165700.00",
            "165700.00"
          ],
          "rowNumber": 1858184,
          "rowPosition": 1858185,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79206\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1858185\" violates the foreign key: for \"id_contrato\": values \"79206\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43493",
            "4",
            "1831102",
            "89",
            "1",
            "1",
            "66",
            "71854",
            "1",
            "54",
            "776",
            "22159",
            "276888",
            "382771",
            "79206",
            "987",
            "1831950",
            "2944",
            "2838",
            "2022",
            "2022-11-25",
            "9.0000",
            "1700.0000",
            "15300.00",
            "1700.0000",
            "15300.00",
            "15300.00"
          ],
          "rowNumber": 1858185,
          "rowPosition": 1858186,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79206\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1858186\" violates the foreign key: for \"id_contrato\": values \"79206\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44406",
            "14",
            "1831096",
            "92",
            "1",
            "1",
            "206",
            "36126",
            "1",
            "69",
            "439",
            "21705",
            "174016",
            "382277",
            "79207",
            "1927",
            "1831312",
            "2538",
            "2631",
            "2022",
            "2022-11-21",
            "1200.0000",
            "12.0200",
            "14418.60",
            "11.9000",
            "14280.00",
            "14280.00"
          ],
          "rowNumber": 1859949,
          "rowPosition": 1859950,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79207\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1859950\" violates the foreign key: for \"id_contrato\": values \"79207\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43585",
            "4",
            "1831095",
            "96",
            "1",
            "1",
            "305",
            "13878",
            "1",
            "77",
            "808",
            "4383",
            "199499",
            "386089",
            "79205",
            "889",
            "1831737",
            "2869",
            "3293",
            "2022",
            "2023-01-12",
            "0.0000",
            "5861141.9100",
            "5861141.91",
            "4849950.5500",
            "4849950.55",
            "4849950.55"
          ],
          "rowNumber": 1913700,
          "rowPosition": 1913701,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79205\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913701\" violates the foreign key: for \"id_contrato\": values \"79205\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43479",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "21322",
            "1",
            "63",
            "124",
            "15925",
            "81211",
            "386084",
            "79203",
            "889",
            "1831888",
            "2811",
            "3042",
            "2022",
            "2023-01-12",
            "170.0000",
            "203.3300",
            "34566.10",
            "176.4700",
            "29999.90",
            "29999.90"
          ],
          "rowNumber": 1913710,
          "rowPosition": 1913711,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79203\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913711\" violates the foreign key: for \"id_contrato\": values \"79203\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43585",
            "4",
            "1831095",
            "96",
            "1",
            "1",
            "378",
            "13878",
            "1",
            "77",
            "808",
            "4383",
            "199499",
            "386089",
            "79205",
            "889",
            "1831737",
            "2869",
            "3293",
            "2022",
            "2023-01-12",
            "0.0000",
            "3168024.6400",
            "3168024.64",
            "2627320.2400",
            "2627320.24",
            "2627320.24"
          ],
          "rowNumber": 1913778,
          "rowPosition": 1913779,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79205\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913779\" violates the foreign key: for \"id_contrato\": values \"79205\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44474",
            "2",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "73316",
            "1",
            "9",
            "581",
            "12418",
            "93129",
            "386070",
            "79200",
            "322",
            "1831697",
            "2669",
            "1760",
            "2023",
            "2023-01-11",
            "0.0000",
            "3780000.0000",
            "3780000.00",
            "3780000.0000",
            "3780000.00",
            "3780000.00"
          ],
          "rowNumber": 1914316,
          "rowPosition": 1914317,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79200\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1914317\" violates the foreign key: for \"id_contrato\": values \"79200\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44426",
            "4",
            "1831030",
            "27",
            "1",
            "1",
            "305",
            "61560",
            "1",
            "51",
            "384",
            "14882",
            "130529",
            "385461",
            "79201",
            "889",
            "1831520",
            "2670",
            "2270",
            "2022",
            "2022-12-28",
            "0.0000",
            "158940.0000",
            "158940.00",
            "87690.0000",
            "87690.00",
            "87690.00"
          ],
          "rowNumber": 1916127,
          "rowPosition": 1916128,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79201\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916128\" violates the foreign key: for \"id_contrato\": values \"79201\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43479",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "21322",
            "1",
            "48",
            "346",
            "15984",
            "339047",
            "386084",
            "79203",
            "889",
            "1831940",
            "2811",
            "3042",
            "2022",
            "2023-01-13",
            "50.0000",
            "486.6700",
            "24333.50",
            "486.6700",
            "24333.50",
            "24333.50"
          ],
          "rowNumber": 1916550,
          "rowPosition": 1916551,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79203\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916551\" violates the foreign key: for \"id_contrato\": values \"79203\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43479",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "21322",
            "1",
            "48",
            "346",
            "15984",
            "339047",
            "386084",
            "79203",
            "889",
            "1831940",
            "2811",
            "3042",
            "2022",
            "2023-01-13",
            "40.0000",
            "400.0000",
            "16000.00",
            "400.0000",
            "16000.00",
            "16000.00"
          ],
          "rowNumber": 1916551,
          "rowPosition": 1916552,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79203\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916552\" violates the foreign key: for \"id_contrato\": values \"79203\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43479",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "21322",
            "1",
            "48",
            "346",
            "15984",
            "339047",
            "386084",
            "79203",
            "889",
            "1831940",
            "2811",
            "3042",
            "2022",
            "2023-01-13",
            "40.0000",
            "500.0000",
            "20000.00",
            "500.0000",
            "20000.00",
            "20000.00"
          ],
          "rowNumber": 1916552,
          "rowPosition": 1916553,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79203\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916553\" violates the foreign key: for \"id_contrato\": values \"79203\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43479",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "21322",
            "1",
            "48",
            "346",
            "15984",
            "339047",
            "386084",
            "79203",
            "889",
            "1831940",
            "2811",
            "3042",
            "2022",
            "2023-01-13",
            "4.0000",
            "3216.6700",
            "12866.68",
            "3216.6200",
            "12866.48",
            "12866.48"
          ],
          "rowNumber": 1916553,
          "rowPosition": 1916554,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79203\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916554\" violates the foreign key: for \"id_contrato\": values \"79203\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44040",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "23602",
            "1",
            "51",
            "383",
            "17638",
            "358000",
            "385029",
            "79208",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-12-23",
            "0.0000",
            "1845364.5800",
            "1845364.57",
            "1059984.6100",
            "1059984.61",
            "1059984.61"
          ],
          "rowNumber": 1918618,
          "rowPosition": 1918619,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79208\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918619\" violates the foreign key: for \"id_contrato\": values \"79208\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44040",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "23602",
            "1",
            "51",
            "383",
            "17638",
            "358001",
            "385029",
            "79208",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-12-23",
            "0.0000",
            "244569.9400",
            "244569.93",
            "227927.5100",
            "227927.51",
            "227927.51"
          ],
          "rowNumber": 1918619,
          "rowPosition": 1918620,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79208\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918620\" violates the foreign key: for \"id_contrato\": values \"79208\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 45
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 45,
    "tasks": 1
  },
  "valid": false
}