{
  "version": "4.38.0",
  "time": 409.188,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_compras",
        "title": "Compras",
        "path": "data/ft_compras.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_tempo",
              "title": "Tempo - Chave",
              "type": "integer",
              "format": "default",
              "description": "- > \n  Chave estrangeira (Foreign Key) que aponta para a Chave Primária (Primary keys) da tabela dm_tempo_diario. \n  Ou seja, por meio dessa chave é possível identificar a data completa a qual o dado se refere.\n\n  Nota: \n  No site dados.mg.gov.br a tabela dm_tempo_diario pode ser encontrada no recurso Calendários - Dias \n  de cada conjunto.\n",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_procedimento",
              "title": "Procedimento de Contratação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_demanda",
              "title": "Órgão Demandante - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_contrato",
              "title": "Órgão do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_proc",
              "title": "Situação do Processo de Compra - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_cont",
              "title": "Situação do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_municipio",
              "title": "Município - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contratado",
              "title": "Contratado - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_tipo_licitacao",
              "title": "Tipo de Licitação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_grupo_matserv",
              "title": "Grupo Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_classe_matserv",
              "title": "Classe Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_material_servico",
              "title": "Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item_matserv",
              "title": "Item Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_processo",
              "title": "Processo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contrato",
              "title": "Número do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_medida",
              "title": "Unidade de Medida - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_linha_fornec",
              "title": "Linha de Fornecimento - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_orc",
              "title": "Unidade Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "unique": false
              }
            },
            {
              "name": "ano_particao",
              "title": "Ano Partição",
              "type": "year",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true
              }
            },
            {
              "name": "dt_item_homologa",
              "title": "Data da Homologação do Item",
              "type": "date",
              "format": "default",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "qt_item_pedido",
              "title": "Item do Pedido - Quantidade",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_referencia",
              "title": "Valor Unitário de Referência",
              "description": "Valor unitário estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_referencia",
              "title": "Valor de Referência",
              "description": "Valor estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_homologado",
              "title": "Valor Unitário Homologado",
              "description": "Valor unitário final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_homologado",
              "title": "Valor Homologado",
              "description": "Valor final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_atualizado",
              "title": "Valor Atualizado",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_processo"
              ],
              "reference": {
                "fields": [
                  "id_processo"
                ],
                "resource": "dm_processo"
              }
            },
            {
              "fields": [
                "id_situacao_cont"
              ],
              "reference": {
                "fields": [
                  "id_situacao_cont"
                ],
                "resource": "dm_situacao_cont"
              }
            },
            {
              "fields": [
                "id_situacao_proc"
              ],
              "reference": {
                "fields": [
                  "id_situacao_proc"
                ],
                "resource": "dm_situacao_proc"
              }
            },
            {
              "fields": [
                "id_linha_fornec"
              ],
              "reference": {
                "fields": [
                  "id_linha_fornec"
                ],
                "resource": "dm_linha_fornec"
              }
            },
            {
              "fields": [
                "id_classe_matserv"
              ],
              "reference": {
                "fields": [
                  "id_classe_matserv"
                ],
                "resource": "dm_classe_matserv"
              }
            },
            {
              "fields": [
                "id_tempo"
              ],
              "reference": {
                "fields": [
                  "id_tempo"
                ],
                "resource": "dm_tempo_diario"
              }
            },
            {
              "fields": [
                "id_municipio"
              ],
              "reference": {
                "fields": [
                  "id_municipio"
                ],
                "resource": "dm_municipio"
              }
            },
            {
              "fields": [
                "id_item_matserv"
              ],
              "reference": {
                "fields": [
                  "id_item_matserv"
                ],
                "resource": "dm_item_matserv"
              }
            },
            {
              "fields": [
                "id_tipo_licitacao"
              ],
              "reference": {
                "fields": [
                  "id_tipo_licitacao"
                ],
                "resource": "dm_tipo_licitacao"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_material_servico"
              ],
              "reference": {
                "fields": [
                  "id_material_servico"
                ],
                "resource": "dm_material_servico"
              }
            },
            {
              "fields": [
                "id_orgao_contrato"
              ],
              "reference": {
                "fields": [
                  "id_orgao_contrato"
                ],
                "resource": "dm_orgao_contrato"
              }
            },
            {
              "fields": [
                "id_contrato"
              ],
              "reference": {
                "fields": [
                  "id_contrato"
                ],
                "resource": "dm_contrato"
              }
            },
            {
              "fields": [
                "id_orgao_demanda"
              ],
              "reference": {
                "fields": [
                  "id_orgao_demanda"
                ],
                "resource": "dm_orgao_demanda"
              }
            },
            {
              "fields": [
                "id_unidade_medida"
              ],
              "reference": {
                "fields": [
                  "id_unidade_medida"
                ],
                "resource": "dm_unidade_medida"
              }
            },
            {
              "fields": [
                "id_grupo_matserv"
              ],
              "reference": {
                "fields": [
                  "id_grupo_matserv"
                ],
                "resource": "dm_grupo_matserv"
              }
            },
            {
              "fields": [
                "id_contratado"
              ],
              "reference": {
                "fields": [
                  "id_contratado"
                ],
                "resource": "dm_contratado"
              }
            },
            {
              "fields": [
                "id_procedimento"
              ],
              "reference": {
                "fields": [
                  "id_procedimento"
                ],
                "resource": "dm_procedimento"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_compras"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "2f79d7c663876c3cf0ee1a9021465dea",
          "bytes": 57966331,
          "fields": 27,
          "rows": 1901419
        }
      },
      "time": 409.188,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "43487",
            "2",
            "1831020",
            "9",
            "1",
            "1",
            "66",
            "31915",
            "1",
            "39",
            "190",
            "4584",
            "171501",
            "377623",
            "78066",
            "889",
            "1831812",
            "3065",
            "2839",
            "2022",
            "2022-09-14",
            "0.0000",
            "840.0000",
            "840.00",
            "840.0000",
            "840.00",
            "840.00"
          ],
          "rowNumber": 1799257,
          "rowPosition": 1799258,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78066\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1799258\" violates the foreign key: for \"id_contrato\": values \"78066\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43487",
            "2",
            "1831020",
            "9",
            "1",
            "1",
            "66",
            "31915",
            "1",
            "39",
            "190",
            "4584",
            "105067",
            "377623",
            "78066",
            "889",
            "1831812",
            "3065",
            "2839",
            "2022",
            "2022-09-14",
            "0.0000",
            "1968.0000",
            "1968.00",
            "1968.0000",
            "1968.00",
            "1968.00"
          ],
          "rowNumber": 1799258,
          "rowPosition": 1799259,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78066\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1799259\" violates the foreign key: for \"id_contrato\": values \"78066\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43487",
            "2",
            "1831020",
            "9",
            "1",
            "1",
            "66",
            "31915",
            "1",
            "39",
            "190",
            "20350",
            "98705",
            "377623",
            "78066",
            "889",
            "1831812",
            "3065",
            "2839",
            "2022",
            "2022-09-14",
            "0.0000",
            "12372.0000",
            "12372.00",
            "12372.0000",
            "12372.00",
            "12372.00"
          ],
          "rowNumber": 1799259,
          "rowPosition": 1799260,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78066\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1799260\" violates the foreign key: for \"id_contrato\": values \"78066\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43487",
            "2",
            "1831020",
            "9",
            "1",
            "1",
            "66",
            "31915",
            "1",
            "39",
            "190",
            "7099",
            "234266",
            "377623",
            "78066",
            "889",
            "1831812",
            "3065",
            "2839",
            "2022",
            "2022-09-14",
            "0.0000",
            "14700.0000",
            "14700.00",
            "14700.0000",
            "14700.00",
            "14700.00"
          ],
          "rowNumber": 1799260,
          "rowPosition": 1799261,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78066\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1799261\" violates the foreign key: for \"id_contrato\": values \"78066\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44419",
            "15",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "1777",
            "1",
            "44",
            "106",
            "14581",
            "132680",
            "381899",
            "78064",
            "889",
            "1831992",
            "2746",
            "1760",
            "2022",
            "2022-11-16",
            "5.0000",
            "7909.0000",
            "39545.00",
            "7909.0000",
            "39545.00",
            "39545.00"
          ],
          "rowNumber": 1813103,
          "rowPosition": 1813104,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78064\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813104\" violates the foreign key: for \"id_contrato\": values \"78064\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43585",
            "13",
            "1831044",
            "36",
            "1",
            "1",
            "38",
            "56836",
            "1",
            "17",
            "379",
            "7051",
            "94368",
            "381973",
            "78080",
            "889",
            "1831370",
            "2816",
            "2633",
            "2022",
            "2022-11-16",
            "0.0000",
            "265923.7900",
            "265923.79",
            "265923.7900",
            "265923.79",
            "265923.79"
          ],
          "rowNumber": 1813414,
          "rowPosition": 1813415,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78080\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813415\" violates the foreign key: for \"id_contrato\": values \"78080\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43535",
            "1",
            "1831102",
            "89",
            "1",
            "1",
            "66",
            "19919",
            "1",
            "77",
            "700",
            "14929",
            "134354",
            "380862",
            "78071",
            "981",
            "1831700",
            "2553",
            "2838",
            "2022",
            "2022-10-26",
            "0.0000",
            "10801626.0200",
            "10801626.02",
            "10801626.0200",
            "10801626.02",
            "10801626.02"
          ],
          "rowNumber": 1814095,
          "rowPosition": 1814096,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78071\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1814096\" violates the foreign key: for \"id_contrato\": values \"78071\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43561",
            "2",
            "1831008",
            "5",
            "1",
            "1",
            "66",
            "22000",
            "1",
            "77",
            "73",
            "9726",
            "92493",
            "380751",
            "78078",
            "889",
            "1831901",
            "2623",
            "2925",
            "2022",
            "2022-10-25",
            "0.0000",
            "81597.7800",
            "81597.78",
            "81597.7800",
            "81597.78",
            "81597.78"
          ],
          "rowNumber": 1821613,
          "rowPosition": 1821614,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78078\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1821614\" violates the foreign key: for \"id_contrato\": values \"78078\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43480",
            "1",
            "1831105",
            "91",
            "1",
            "1",
            "883",
            "66588",
            "1",
            "77",
            "475",
            "17643",
            "244763",
            "379179",
            "78081",
            "889",
            "1831368",
            "2741",
            "3042",
            "2022",
            "2022-10-05",
            "0.0000",
            "10000.0000",
            "10000.00",
            "10000.0000",
            "10000.00",
            "10000.00"
          ],
          "rowNumber": 1821963,
          "rowPosition": 1821964,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78081\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1821964\" violates the foreign key: for \"id_contrato\": values \"78081\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44406",
            "4",
            "1831095",
            "96",
            "1",
            "1",
            "66",
            "69957",
            "1",
            "30",
            "173",
            "1784",
            "96321",
            "381121",
            "78070",
            "889",
            "1831471",
            "2670",
            "3955",
            "2022",
            "2022-11-03",
            "0.0000",
            "86642.3200",
            "86642.32",
            "85775.9000",
            "85775.90",
            "85775.90"
          ],
          "rowNumber": 1825249,
          "rowPosition": 1825250,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78070\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1825250\" violates the foreign key: for \"id_contrato\": values \"78070\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "34146",
            "1",
            "8",
            "687",
            "14824",
            "91236",
            "381137",
            "78074",
            "889",
            "1831348",
            "2970",
            "3043",
            "2022",
            "2022-11-03",
            "0.0000",
            "34000.0000",
            "34000.00",
            "21000.0000",
            "21000.00",
            "21000.00"
          ],
          "rowNumber": 1827066,
          "rowPosition": 1827067,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78074\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1827067\" violates the foreign key: for \"id_contrato\": values \"78074\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44057",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "31387",
            "1",
            "80",
            "621",
            "16004",
            "116125",
            "381057",
            "78065",
            "1307",
            "1831306",
            "2994",
            "2081",
            "2022",
            "2022-10-28",
            "50.0000",
            "8.0600",
            "403.00",
            "8.0600",
            "403.00",
            "403.00"
          ],
          "rowNumber": 1831946,
          "rowPosition": 1831947,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78065\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1831947\" violates the foreign key: for \"id_contrato\": values \"78065\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44057",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "31387",
            "1",
            "80",
            "621",
            "18718",
            "6297",
            "381057",
            "78065",
            "189",
            "1831306",
            "2994",
            "2081",
            "2022",
            "2022-10-28",
            "1500.0000",
            "2.6000",
            "3892.50",
            "2.7000",
            "4050.00",
            "4050.00"
          ],
          "rowNumber": 1832802,
          "rowPosition": 1832803,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78065\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1832803\" violates the foreign key: for \"id_contrato\": values \"78065\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44057",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "19758",
            "1",
            "18",
            "650",
            "21697",
            "173778",
            "381057",
            "78077",
            "1917",
            "1831311",
            "2994",
            "2081",
            "2022",
            "2022-10-28",
            "3000.0000",
            "18.1400",
            "54420.00",
            "15.0000",
            "45000.00",
            "45000.00"
          ],
          "rowNumber": 1832804,
          "rowPosition": 1832805,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78077\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1832805\" violates the foreign key: for \"id_contrato\": values \"78077\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44057",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "31387",
            "1",
            "80",
            "621",
            "18648",
            "155694",
            "381057",
            "78065",
            "229",
            "1831306",
            "2994",
            "2081",
            "2022",
            "2022-10-28",
            "400.0000",
            "13.0000",
            "5200.00",
            "8.6200",
            "3448.00",
            "3448.00"
          ],
          "rowNumber": 1832806,
          "rowPosition": 1832807,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78065\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1832807\" violates the foreign key: for \"id_contrato\": values \"78065\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44057",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "31387",
            "1",
            "32",
            "623",
            "21799",
            "180333",
            "381057",
            "78065",
            "1917",
            "1831306",
            "2994",
            "2081",
            "2022",
            "2022-10-28",
            "1200.0000",
            "12.0000",
            "14400.00",
            "8.3300",
            "9996.00",
            "9996.00"
          ],
          "rowNumber": 1832814,
          "rowPosition": 1832815,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78065\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1832815\" violates the foreign key: for \"id_contrato\": values \"78065\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44057",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "19758",
            "1",
            "10",
            "501",
            "21761",
            "178025",
            "381057",
            "78077",
            "1917",
            "1831306",
            "2994",
            "2081",
            "2022",
            "2022-10-28",
            "500.0000",
            "3.6000",
            "1800.00",
            "17.2700",
            "8635.00",
            "8635.00"
          ],
          "rowNumber": 1832819,
          "rowPosition": 1832820,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78077\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1832820\" violates the foreign key: for \"id_contrato\": values \"78077\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44057",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "19758",
            "1",
            "10",
            "501",
            "21761",
            "178032",
            "381057",
            "78077",
            "1917",
            "1831306",
            "2994",
            "2081",
            "2022",
            "2022-10-28",
            "500.0000",
            "19.0500",
            "9525.00",
            "11.8300",
            "5915.00",
            "5915.00"
          ],
          "rowNumber": 1832820,
          "rowPosition": 1832821,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78077\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1832821\" violates the foreign key: for \"id_contrato\": values \"78077\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44057",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "19758",
            "1",
            "10",
            "501",
            "21761",
            "178027",
            "381057",
            "78077",
            "1917",
            "1831306",
            "2994",
            "2081",
            "2022",
            "2022-10-28",
            "1000.0000",
            "44.9000",
            "44900.00",
            "33.3800",
            "33380.00",
            "33380.00"
          ],
          "rowNumber": 1832821,
          "rowPosition": 1832822,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78077\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1832822\" violates the foreign key: for \"id_contrato\": values \"78077\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43506",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "19474",
            "1",
            "14",
            "429",
            "18516",
            "339437",
            "382259",
            "78067",
            "889",
            "1831983",
            "2685",
            "2081",
            "2022",
            "2022-11-21",
            "4.0000",
            "4332.0000",
            "17328.00",
            "4332.0000",
            "17328.00",
            "17328.00"
          ],
          "rowNumber": 1850901,
          "rowPosition": 1850902,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78067\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1850902\" violates the foreign key: for \"id_contrato\": values \"78067\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43506",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "19474",
            "1",
            "14",
            "429",
            "19099",
            "134462",
            "382259",
            "78067",
            "889",
            "1831983",
            "2685",
            "2081",
            "2022",
            "2022-11-21",
            "3.0000",
            "6873.3200",
            "20619.96",
            "6873.0000",
            "20619.00",
            "20619.00"
          ],
          "rowNumber": 1850902,
          "rowPosition": 1850903,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78067\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1850903\" violates the foreign key: for \"id_contrato\": values \"78067\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43506",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "19474",
            "1",
            "14",
            "429",
            "19099",
            "146240",
            "382259",
            "78067",
            "889",
            "1831983",
            "2685",
            "2081",
            "2022",
            "2022-11-21",
            "2.0000",
            "11590.6400",
            "23181.28",
            "11590.0000",
            "23180.00",
            "23180.00"
          ],
          "rowNumber": 1850903,
          "rowPosition": 1850904,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78067\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1850904\" violates the foreign key: for \"id_contrato\": values \"78067\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43506",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "19474",
            "1",
            "14",
            "429",
            "18516",
            "339437",
            "382259",
            "78067",
            "889",
            "1831983",
            "2685",
            "2081",
            "2022",
            "2022-11-21",
            "7.0000",
            "6211.4400",
            "43480.08",
            "6211.0000",
            "43477.00",
            "43477.00"
          ],
          "rowNumber": 1850904,
          "rowPosition": 1850905,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78067\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1850905\" violates the foreign key: for \"id_contrato\": values \"78067\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43506",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "19474",
            "1",
            "87",
            "221",
            "5297",
            "157681",
            "382259",
            "78067",
            "889",
            "1831963",
            "2685",
            "2081",
            "2022",
            "2022-11-21",
            "1.0000",
            "11888.8900",
            "11888.89",
            "11888.0000",
            "11888.00",
            "11888.00"
          ],
          "rowNumber": 1850905,
          "rowPosition": 1850906,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78067\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1850906\" violates the foreign key: for \"id_contrato\": values \"78067\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43585",
            "2",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "242",
            "1",
            "35",
            "225",
            "2650",
            "169193",
            "381547",
            "78083",
            "889",
            "1831307",
            "2586",
            "3331",
            "2022",
            "2022-11-09",
            "21300.0000",
            "0.3500",
            "7455.00",
            "0.3500",
            "7455.00",
            "7455.00"
          ],
          "rowNumber": 1851738,
          "rowPosition": 1851739,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78083\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1851739\" violates the foreign key: for \"id_contrato\": values \"78083\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44420",
            "14",
            "1831094",
            "95",
            "1",
            "1",
            "883",
            "67674",
            "1",
            "77",
            "700",
            "14929",
            "124354",
            "382020",
            "78063",
            "889",
            "1831700",
            "2553",
            "3043",
            "2022",
            "2022-11-17",
            "0.0000",
            "11000.0000",
            "11000.00",
            "9555.7700",
            "9555.77",
            "9555.77"
          ],
          "rowNumber": 1852526,
          "rowPosition": 1852527,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78063\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1852527\" violates the foreign key: for \"id_contrato\": values \"78063\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43583",
            "2",
            "1831081",
            "77",
            "1",
            "1",
            "66",
            "29170",
            "1",
            "26",
            "478",
            "7631",
            "150240",
            "382048",
            "78076",
            "889",
            "1831233",
            "2863",
            "2014",
            "2022",
            "2022-11-17",
            "72000.0000",
            "1.9800",
            "142560.00",
            "1.9800",
            "142560.00",
            "142560.00"
          ],
          "rowNumber": 1856841,
          "rowPosition": 1856842,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78076\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1856842\" violates the foreign key: for \"id_contrato\": values \"78076\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44426",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "22394",
            "1",
            "37",
            "142",
            "20473",
            "131156",
            "382100",
            "78069",
            "889",
            "1831952",
            "2927",
            "3043",
            "2022",
            "2022-11-17",
            "700.0000",
            "162.3700",
            "113659.00",
            "162.3700",
            "113659.00",
            "113659.00"
          ],
          "rowNumber": 1856843,
          "rowPosition": 1856844,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78069\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1856844\" violates the foreign key: for \"id_contrato\": values \"78069\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44426",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "22394",
            "1",
            "37",
            "142",
            "20473",
            "131534",
            "382100",
            "78069",
            "889",
            "1831952",
            "2927",
            "3043",
            "2022",
            "2022-11-17",
            "606.0000",
            "142.3600",
            "86270.16",
            "142.3600",
            "86270.16",
            "86270.16"
          ],
          "rowNumber": 1856844,
          "rowPosition": 1856845,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78069\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1856845\" violates the foreign key: for \"id_contrato\": values \"78069\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44419",
            "15",
            "1831079",
            "76",
            "1",
            "1",
            "844",
            "4625",
            "1",
            "54",
            "502",
            "6435",
            "144721",
            "381599",
            "78075",
            "889",
            "1831296",
            "2944",
            "2046",
            "2022",
            "2022-11-10",
            "19.0000",
            "768.0000",
            "14592.00",
            "768.0000",
            "14592.00",
            "14592.00"
          ],
          "rowNumber": 1890228,
          "rowPosition": 1890229,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78075\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1890229\" violates the foreign key: for \"id_contrato\": values \"78075\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44420",
            "1",
            "1831034",
            "50",
            "1",
            "8",
            "66",
            "72772",
            "1",
            "77",
            "479",
            "1836",
            "91508",
            "382392",
            "46296",
            "889",
            "1831808",
            "3144",
            "1760",
            "2022",
            "2022-11-22",
            "0.0000",
            "16000.0000",
            "16000.00",
            "16000.0000",
            "16000.00",
            "16000.00"
          ],
          "rowNumber": 1890712,
          "rowPosition": 1890713,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contratado\": values \"72772\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "message": "Row at position \"1890713\" violates the foreign key: for \"id_contratado\": values \"72772\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44420",
            "1",
            "1831065",
            "65",
            "1",
            "1",
            "66",
            "28244",
            "1",
            "39",
            "130",
            "20370",
            "151133",
            "382197",
            "78072",
            "889",
            "1831805",
            "3067",
            "2884",
            "2022",
            "2022-11-18",
            "0.0000",
            "79286.1600",
            "79286.16",
            "79286.1600",
            "79286.16",
            "79286.16"
          ],
          "rowNumber": 1897755,
          "rowPosition": 1897756,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78072\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1897756\" violates the foreign key: for \"id_contrato\": values \"78072\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44402",
            "17",
            "1831020",
            "9",
            "1",
            "1",
            "66",
            "64989",
            "1",
            "3",
            "143",
            "18489",
            "374253",
            "382184",
            "78068",
            "889",
            "1831295",
            "2611",
            "2839",
            "2022",
            "2022-11-18",
            "100.0000",
            "1460.0000",
            "146000.00",
            "1256.0000",
            "125600.00",
            "125600.00"
          ],
          "rowNumber": 1897760,
          "rowPosition": 1897761,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78068\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1897761\" violates the foreign key: for \"id_contrato\": values \"78068\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43481",
            "5",
            "1831084",
            "81",
            "1",
            "1",
            "856",
            "18728",
            "1",
            "17",
            "175",
            "6976",
            "92592",
            "382462",
            "78073",
            "889",
            "1831350",
            "2613",
            "1859",
            "2022",
            "2022-11-22",
            "0.0000",
            "27292407.2700",
            "27292407.27",
            "22375355.1900",
            "22375355.19",
            "22375355.19"
          ],
          "rowNumber": 1899133,
          "rowPosition": 1899134,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78073\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1899134\" violates the foreign key: for \"id_contrato\": values \"78073\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44029",
            "5",
            "1831084",
            "81",
            "1",
            "1",
            "856",
            "67629",
            "1",
            "77",
            "533",
            "1834",
            "91484",
            "382451",
            "78082",
            "889",
            "1831370",
            "2675",
            "1859",
            "2022",
            "2022-11-22",
            "0.0000",
            "10140041.7000",
            "10140041.70",
            "7569814.6800",
            "7569814.68",
            "7569814.68"
          ],
          "rowNumber": 1899134,
          "rowPosition": 1899135,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78082\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1899135\" violates the foreign key: for \"id_contrato\": values \"78082\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 35
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 35,
    "tasks": 1
  },
  "valid": false
}