{
  "version": "4.38.0",
  "time": 407.469,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_compras",
        "title": "Compras",
        "path": "data/ft_compras.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_tempo",
              "title": "Tempo - Chave",
              "type": "integer",
              "format": "default",
              "description": "- > \n  Chave estrangeira (Foreign Key) que aponta para a Chave Primária (Primary keys) da tabela dm_tempo_diario. \n  Ou seja, por meio dessa chave é possível identificar a data completa a qual o dado se refere.\n\n  Nota: \n  No site dados.mg.gov.br a tabela dm_tempo_diario pode ser encontrada no recurso Calendários - Dias \n  de cada conjunto.\n",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_procedimento",
              "title": "Procedimento de Contratação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_demanda",
              "title": "Órgão Demandante - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_contrato",
              "title": "Órgão do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_proc",
              "title": "Situação do Processo de Compra - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_cont",
              "title": "Situação do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_municipio",
              "title": "Município - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contratado",
              "title": "Contratado - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_tipo_licitacao",
              "title": "Tipo de Licitação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_grupo_matserv",
              "title": "Grupo Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_classe_matserv",
              "title": "Classe Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_material_servico",
              "title": "Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item_matserv",
              "title": "Item Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_processo",
              "title": "Processo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contrato",
              "title": "Número do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_medida",
              "title": "Unidade de Medida - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_linha_fornec",
              "title": "Linha de Fornecimento - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_orc",
              "title": "Unidade Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "unique": false
              }
            },
            {
              "name": "ano_particao",
              "title": "Ano Partição",
              "type": "year",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true
              }
            },
            {
              "name": "dt_item_homologa",
              "title": "Data da Homologação do Item",
              "type": "date",
              "format": "default",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "qt_item_pedido",
              "title": "Item do Pedido - Quantidade",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_referencia",
              "title": "Valor Unitário de Referência",
              "description": "Valor unitário estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_referencia",
              "title": "Valor de Referência",
              "description": "Valor estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_homologado",
              "title": "Valor Unitário Homologado",
              "description": "Valor unitário final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_homologado",
              "title": "Valor Homologado",
              "description": "Valor final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_atualizado",
              "title": "Valor Atualizado",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_processo"
              ],
              "reference": {
                "fields": [
                  "id_processo"
                ],
                "resource": "dm_processo"
              }
            },
            {
              "fields": [
                "id_situacao_cont"
              ],
              "reference": {
                "fields": [
                  "id_situacao_cont"
                ],
                "resource": "dm_situacao_cont"
              }
            },
            {
              "fields": [
                "id_situacao_proc"
              ],
              "reference": {
                "fields": [
                  "id_situacao_proc"
                ],
                "resource": "dm_situacao_proc"
              }
            },
            {
              "fields": [
                "id_linha_fornec"
              ],
              "reference": {
                "fields": [
                  "id_linha_fornec"
                ],
                "resource": "dm_linha_fornec"
              }
            },
            {
              "fields": [
                "id_classe_matserv"
              ],
              "reference": {
                "fields": [
                  "id_classe_matserv"
                ],
                "resource": "dm_classe_matserv"
              }
            },
            {
              "fields": [
                "id_tempo"
              ],
              "reference": {
                "fields": [
                  "id_tempo"
                ],
                "resource": "dm_tempo_diario"
              }
            },
            {
              "fields": [
                "id_municipio"
              ],
              "reference": {
                "fields": [
                  "id_municipio"
                ],
                "resource": "dm_municipio"
              }
            },
            {
              "fields": [
                "id_item_matserv"
              ],
              "reference": {
                "fields": [
                  "id_item_matserv"
                ],
                "resource": "dm_item_matserv"
              }
            },
            {
              "fields": [
                "id_tipo_licitacao"
              ],
              "reference": {
                "fields": [
                  "id_tipo_licitacao"
                ],
                "resource": "dm_tipo_licitacao"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_material_servico"
              ],
              "reference": {
                "fields": [
                  "id_material_servico"
                ],
                "resource": "dm_material_servico"
              }
            },
            {
              "fields": [
                "id_orgao_contrato"
              ],
              "reference": {
                "fields": [
                  "id_orgao_contrato"
                ],
                "resource": "dm_orgao_contrato"
              }
            },
            {
              "fields": [
                "id_contrato"
              ],
              "reference": {
                "fields": [
                  "id_contrato"
                ],
                "resource": "dm_contrato"
              }
            },
            {
              "fields": [
                "id_orgao_demanda"
              ],
              "reference": {
                "fields": [
                  "id_orgao_demanda"
                ],
                "resource": "dm_orgao_demanda"
              }
            },
            {
              "fields": [
                "id_unidade_medida"
              ],
              "reference": {
                "fields": [
                  "id_unidade_medida"
                ],
                "resource": "dm_unidade_medida"
              }
            },
            {
              "fields": [
                "id_grupo_matserv"
              ],
              "reference": {
                "fields": [
                  "id_grupo_matserv"
                ],
                "resource": "dm_grupo_matserv"
              }
            },
            {
              "fields": [
                "id_contratado"
              ],
              "reference": {
                "fields": [
                  "id_contratado"
                ],
                "resource": "dm_contratado"
              }
            },
            {
              "fields": [
                "id_procedimento"
              ],
              "reference": {
                "fields": [
                  "id_procedimento"
                ],
                "resource": "dm_procedimento"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_compras"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "f86ebbaebf509b400c2deb4ef6598bbc",
          "bytes": 58443324,
          "fields": 27,
          "rows": 1918450
        }
      },
      "time": 407.469,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "44439",
            "4",
            "1831030",
            "27",
            "1",
            "1",
            "387",
            "72456",
            "5",
            "77",
            "480",
            "22057",
            "217883",
            "384247",
            "79172",
            "1729",
            "1831531",
            "2738",
            "2270",
            "2022",
            "2022-12-15",
            "0.0000",
            "13498.2000",
            "13498.20",
            "13560.0000",
            "13560.00",
            "13560.00"
          ],
          "rowNumber": 1815146,
          "rowPosition": 1815147,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79172\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1815147\" violates the foreign key: for \"id_contrato\": values \"79172\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43554",
            "4",
            "1831017",
            "12",
            "1",
            "1",
            "66",
            "59863",
            "1",
            "57",
            "779",
            "10791",
            "5796",
            "383835",
            "79168",
            "190",
            "1831313",
            "2797",
            "2842",
            "2022",
            "2022-12-09",
            "600000.0000",
            "7.0600",
            "4234800.00",
            "5.9400",
            "3566580.00",
            "3566580.00"
          ],
          "rowNumber": 1823137,
          "rowPosition": 1823138,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79168\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1823138\" violates the foreign key: for \"id_contrato\": values \"79168\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43554",
            "4",
            "1831009",
            "12",
            "1",
            "1",
            "66",
            "59863",
            "1",
            "57",
            "779",
            "10791",
            "5796",
            "383856",
            "79168",
            "190",
            "1831313",
            "2797",
            "2413",
            "2022",
            "2022-12-09",
            "200000.0000",
            "7.0600",
            "1411600.00",
            "5.9400",
            "1188860.00",
            "1188860.00"
          ],
          "rowNumber": 1857382,
          "rowPosition": 1857383,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79168\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1857383\" violates the foreign key: for \"id_contrato\": values \"79168\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43576",
            "4",
            "1831102",
            "89",
            "1",
            "1",
            "66",
            "66582",
            "1",
            "77",
            "533",
            "20154",
            "91366",
            "383280",
            "79170",
            "889",
            "1831440",
            "2890",
            "2838",
            "2022",
            "2022-12-01",
            "0.0000",
            "4528.8000",
            "4528.80",
            "4528.0000",
            "4528.00",
            "4528.00"
          ],
          "rowNumber": 1866174,
          "rowPosition": 1866175,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79170\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1866175\" violates the foreign key: for \"id_contrato\": values \"79170\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43557",
            "2",
            "1831102",
            "89",
            "1",
            "1",
            "66",
            "20343",
            "1",
            "69",
            "740",
            "13114",
            "147581",
            "379561",
            "79167",
            "98",
            "1831312",
            "2538",
            "2838",
            "2022",
            "2022-10-10",
            "3100.0000",
            "42.9600",
            "133176.00",
            "37.2000",
            "115320.00",
            "115320.00"
          ],
          "rowNumber": 1895097,
          "rowPosition": 1895098,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79167\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1895098\" violates the foreign key: for \"id_contrato\": values \"79167\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43557",
            "2",
            "1831102",
            "89",
            "1",
            "1",
            "66",
            "20343",
            "1",
            "69",
            "740",
            "13114",
            "133463",
            "379561",
            "79167",
            "98",
            "1831312",
            "2538",
            "2838",
            "2022",
            "2022-10-10",
            "30.0000",
            "58.8200",
            "1764.68",
            "55.8000",
            "1674.00",
            "1674.00"
          ],
          "rowNumber": 1895098,
          "rowPosition": 1895099,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79167\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1895099\" violates the foreign key: for \"id_contrato\": values \"79167\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44474",
            "2",
            "1831034",
            "50",
            "1",
            "8",
            "66",
            "73316",
            "1",
            "9",
            "581",
            "12418",
            "93129",
            "386070",
            "46296",
            "322",
            "1831697",
            "2669",
            "1760",
            "2023",
            "2023-01-11",
            "0.0000",
            "3780000.0000",
            "3780000.00",
            "3780000.0000",
            "3780000.00",
            "3780000.00"
          ],
          "rowNumber": 1914200,
          "rowPosition": 1914201,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contratado\": values \"73316\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "message": "Row at position \"1914201\" violates the foreign key: for \"id_contratado\": values \"73316\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44420",
            "4",
            "1831095",
            "96",
            "1",
            "1",
            "315",
            "12061",
            "1",
            "66",
            "702",
            "4422",
            "93091",
            "385254",
            "79173",
            "889",
            "1831575",
            "2837",
            "3293",
            "2022",
            "2022-12-27",
            "0.0000",
            "1958400.0000",
            "1958400.00",
            "889989.1200",
            "889989.12",
            "889989.12"
          ],
          "rowNumber": 1915311,
          "rowPosition": 1915312,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79173\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1915312\" violates the foreign key: for \"id_contrato\": values \"79173\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44474",
            "4",
            "1831102",
            "89",
            "1",
            "1",
            "66",
            "35340",
            "1",
            "48",
            "14",
            "7819",
            "127612",
            "386000",
            "79171",
            "889",
            "1831309",
            "3075",
            "2838",
            "2023",
            "2023-01-04",
            "304.0000",
            "175.0000",
            "53200.00",
            "145.0000",
            "44080.00",
            "44080.00"
          ],
          "rowNumber": 1916331,
          "rowPosition": 1916332,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79171\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916332\" violates the foreign key: for \"id_contrato\": values \"79171\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44474",
            "4",
            "1831102",
            "89",
            "1",
            "1",
            "66",
            "35340",
            "1",
            "48",
            "734",
            "150",
            "6973",
            "386000",
            "79171",
            "595",
            "1831309",
            "3075",
            "2838",
            "2023",
            "2023-01-04",
            "136.0000",
            "290.0000",
            "39440.00",
            "255.3000",
            "34720.80",
            "34720.80"
          ],
          "rowNumber": 1916332,
          "rowPosition": 1916333,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79171\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916333\" violates the foreign key: for \"id_contrato\": values \"79171\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44474",
            "4",
            "1831102",
            "89",
            "1",
            "1",
            "66",
            "35340",
            "1",
            "48",
            "313",
            "13424",
            "120877",
            "386000",
            "79171",
            "889",
            "1831309",
            "3075",
            "2838",
            "2023",
            "2023-01-04",
            "28.0000",
            "296.5000",
            "8302.00",
            "296.5000",
            "8302.00",
            "8302.00"
          ],
          "rowNumber": 1916333,
          "rowPosition": 1916334,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79171\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916334\" violates the foreign key: for \"id_contrato\": values \"79171\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44474",
            "4",
            "1831102",
            "89",
            "1",
            "1",
            "66",
            "35340",
            "1",
            "48",
            "537",
            "13240",
            "120544",
            "386000",
            "79171",
            "889",
            "1831309",
            "3075",
            "2838",
            "2023",
            "2023-01-04",
            "72.0000",
            "85.0000",
            "6120.00",
            "73.0000",
            "5256.00",
            "5256.00"
          ],
          "rowNumber": 1916334,
          "rowPosition": 1916335,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79171\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916335\" violates the foreign key: for \"id_contrato\": values \"79171\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44474",
            "4",
            "1831102",
            "89",
            "1",
            "1",
            "66",
            "35340",
            "1",
            "48",
            "14",
            "13141",
            "717",
            "386000",
            "79171",
            "889",
            "1831309",
            "3075",
            "2838",
            "2023",
            "2023-01-04",
            "136.0000",
            "870.0000",
            "118320.00",
            "750.0000",
            "102000.00",
            "102000.00"
          ],
          "rowNumber": 1916335,
          "rowPosition": 1916336,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79171\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916336\" violates the foreign key: for \"id_contrato\": values \"79171\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44474",
            "4",
            "1831102",
            "89",
            "1",
            "1",
            "66",
            "35340",
            "1",
            "48",
            "313",
            "15694",
            "149009",
            "386000",
            "79171",
            "889",
            "1831309",
            "3075",
            "2838",
            "2023",
            "2023-01-04",
            "70.0000",
            "202.0000",
            "14140.00",
            "202.0000",
            "14140.00",
            "14140.00"
          ],
          "rowNumber": 1916336,
          "rowPosition": 1916337,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79171\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916337\" violates the foreign key: for \"id_contrato\": values \"79171\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44474",
            "4",
            "1831102",
            "89",
            "1",
            "1",
            "66",
            "35340",
            "1",
            "48",
            "537",
            "18772",
            "77810",
            "386000",
            "79171",
            "889",
            "1831309",
            "3075",
            "2838",
            "2023",
            "2023-01-04",
            "136.0000",
            "54.0000",
            "7344.00",
            "45.0000",
            "6120.00",
            "6120.00"
          ],
          "rowNumber": 1916337,
          "rowPosition": 1916338,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79171\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916338\" violates the foreign key: for \"id_contrato\": values \"79171\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44474",
            "4",
            "1831102",
            "89",
            "1",
            "1",
            "66",
            "35340",
            "1",
            "48",
            "128",
            "16075",
            "156324",
            "386000",
            "79171",
            "595",
            "1831309",
            "3075",
            "2838",
            "2023",
            "2023-01-04",
            "70.0000",
            "55.0000",
            "3850.00",
            "55.0000",
            "3850.00",
            "3850.00"
          ],
          "rowNumber": 1916338,
          "rowPosition": 1916339,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79171\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916339\" violates the foreign key: for \"id_contrato\": values \"79171\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44474",
            "4",
            "1831102",
            "89",
            "1",
            "1",
            "66",
            "35340",
            "1",
            "48",
            "313",
            "16051",
            "24342",
            "386000",
            "79171",
            "889",
            "1831309",
            "3075",
            "2838",
            "2023",
            "2023-01-04",
            "28.0000",
            "550.0000",
            "15400.00",
            "550.0000",
            "15400.00",
            "15400.00"
          ],
          "rowNumber": 1916339,
          "rowPosition": 1916340,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79171\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916340\" violates the foreign key: for \"id_contrato\": values \"79171\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44474",
            "4",
            "1831102",
            "89",
            "1",
            "1",
            "66",
            "35340",
            "1",
            "48",
            "537",
            "2968",
            "139652",
            "386000",
            "79171",
            "595",
            "1831309",
            "3075",
            "2838",
            "2023",
            "2023-01-04",
            "296.0000",
            "31.5000",
            "9324.00",
            "25.0000",
            "7400.00",
            "7400.00"
          ],
          "rowNumber": 1916340,
          "rowPosition": 1916341,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79171\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916341\" violates the foreign key: for \"id_contrato\": values \"79171\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44474",
            "4",
            "1831102",
            "89",
            "1",
            "1",
            "66",
            "35340",
            "1",
            "48",
            "14",
            "15750",
            "32301",
            "386000",
            "79171",
            "889",
            "1831309",
            "3075",
            "2838",
            "2023",
            "2023-01-04",
            "8.0000",
            "358.5000",
            "2868.00",
            "350.0000",
            "2800.00",
            "2800.00"
          ],
          "rowNumber": 1916341,
          "rowPosition": 1916342,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79171\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916342\" violates the foreign key: for \"id_contrato\": values \"79171\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43556",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "22100",
            "1",
            "51",
            "75",
            "14915",
            "92939",
            "385987",
            "79169",
            "889",
            "1831500",
            "2670",
            "3042",
            "2022",
            "2023-01-03",
            "0.0000",
            "29250.0000",
            "29250.00",
            "13500.0000",
            "13500.00",
            "13500.00"
          ],
          "rowNumber": 1916536,
          "rowPosition": 1916537,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79169\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916537\" violates the foreign key: for \"id_contrato\": values \"79169\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43556",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "22100",
            "1",
            "51",
            "75",
            "14915",
            "112523",
            "385987",
            "79169",
            "889",
            "1831500",
            "2670",
            "3042",
            "2022",
            "2023-01-03",
            "0.0000",
            "9600.0000",
            "9600.00",
            "6000.0000",
            "6000.00",
            "6000.00"
          ],
          "rowNumber": 1916537,
          "rowPosition": 1916538,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79169\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916538\" violates the foreign key: for \"id_contrato\": values \"79169\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43556",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "22100",
            "1",
            "51",
            "75",
            "14915",
            "112523",
            "385987",
            "79169",
            "889",
            "1831500",
            "2670",
            "3042",
            "2022",
            "2023-01-03",
            "0.0000",
            "16800.0000",
            "16800.00",
            "6000.0000",
            "6000.00",
            "6000.00"
          ],
          "rowNumber": 1916538,
          "rowPosition": 1916539,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79169\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916539\" violates the foreign key: for \"id_contrato\": values \"79169\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43556",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "22100",
            "1",
            "51",
            "75",
            "14915",
            "112523",
            "385987",
            "79169",
            "889",
            "1831500",
            "2670",
            "3042",
            "2022",
            "2023-01-03",
            "0.0000",
            "16800.0000",
            "16800.00",
            "6000.0000",
            "6000.00",
            "6000.00"
          ],
          "rowNumber": 1916539,
          "rowPosition": 1916540,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79169\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916540\" violates the foreign key: for \"id_contrato\": values \"79169\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43556",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "22100",
            "1",
            "51",
            "75",
            "14915",
            "112523",
            "385987",
            "79169",
            "889",
            "1831500",
            "2670",
            "3042",
            "2022",
            "2023-01-03",
            "0.0000",
            "17820.0000",
            "17820.00",
            "6000.0000",
            "6000.00",
            "6000.00"
          ],
          "rowNumber": 1916540,
          "rowPosition": 1916541,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79169\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916541\" violates the foreign key: for \"id_contrato\": values \"79169\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43556",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "22100",
            "1",
            "51",
            "75",
            "14915",
            "112523",
            "385987",
            "79169",
            "889",
            "1831500",
            "2670",
            "3042",
            "2022",
            "2023-01-03",
            "0.0000",
            "19200.0000",
            "19200.00",
            "9248.8800",
            "9248.88",
            "9248.88"
          ],
          "rowNumber": 1916541,
          "rowPosition": 1916542,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79169\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916542\" violates the foreign key: for \"id_contrato\": values \"79169\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43556",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "520",
            "22100",
            "1",
            "51",
            "75",
            "14915",
            "112523",
            "385987",
            "79169",
            "889",
            "1831500",
            "2670",
            "3042",
            "2022",
            "2023-01-03",
            "0.0000",
            "18600.0000",
            "18600.00",
            "9248.8800",
            "9248.88",
            "9248.88"
          ],
          "rowNumber": 1916542,
          "rowPosition": 1916543,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79169\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916543\" violates the foreign key: for \"id_contrato\": values \"79169\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43556",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "790",
            "22100",
            "1",
            "51",
            "75",
            "14915",
            "112523",
            "385987",
            "79169",
            "889",
            "1831500",
            "2670",
            "3042",
            "2022",
            "2023-01-03",
            "0.0000",
            "16800.0000",
            "16800.00",
            "6000.0000",
            "6000.00",
            "6000.00"
          ],
          "rowNumber": 1916543,
          "rowPosition": 1916544,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79169\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916544\" violates the foreign key: for \"id_contrato\": values \"79169\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43556",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "22100",
            "1",
            "51",
            "75",
            "14915",
            "112523",
            "385987",
            "79169",
            "889",
            "1831500",
            "2670",
            "3042",
            "2022",
            "2023-01-03",
            "0.0000",
            "84654.0000",
            "84654.00",
            "27746.6400",
            "27746.64",
            "27746.64"
          ],
          "rowNumber": 1916544,
          "rowPosition": 1916545,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79169\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916545\" violates the foreign key: for \"id_contrato\": values \"79169\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43556",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "22100",
            "1",
            "51",
            "75",
            "14915",
            "112523",
            "385987",
            "79169",
            "889",
            "1831500",
            "2670",
            "3042",
            "2022",
            "2023-01-03",
            "0.0000",
            "38400.0000",
            "38400.00",
            "18497.7600",
            "18497.76",
            "18497.76"
          ],
          "rowNumber": 1916545,
          "rowPosition": 1916546,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79169\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916546\" violates the foreign key: for \"id_contrato\": values \"79169\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43556",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "22100",
            "1",
            "51",
            "75",
            "14915",
            "112523",
            "385987",
            "79169",
            "889",
            "1831500",
            "2670",
            "3042",
            "2022",
            "2023-01-03",
            "0.0000",
            "41340.0000",
            "41340.00",
            "18497.7600",
            "18497.76",
            "18497.76"
          ],
          "rowNumber": 1916546,
          "rowPosition": 1916547,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79169\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916547\" violates the foreign key: for \"id_contrato\": values \"79169\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43556",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "22100",
            "1",
            "51",
            "75",
            "14915",
            "112523",
            "385987",
            "79169",
            "889",
            "1831500",
            "2670",
            "3042",
            "2022",
            "2023-01-03",
            "0.0000",
            "16800.0000",
            "16800.00",
            "6000.0000",
            "6000.00",
            "6000.00"
          ],
          "rowNumber": 1916547,
          "rowPosition": 1916548,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79169\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916548\" violates the foreign key: for \"id_contrato\": values \"79169\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43556",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "22100",
            "1",
            "51",
            "75",
            "14915",
            "112523",
            "385987",
            "79169",
            "889",
            "1831500",
            "2670",
            "3042",
            "2022",
            "2023-01-03",
            "0.0000",
            "89820.0000",
            "89820.00",
            "27746.6400",
            "27746.64",
            "27746.64"
          ],
          "rowNumber": 1916548,
          "rowPosition": 1916549,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79169\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916549\" violates the foreign key: for \"id_contrato\": values \"79169\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43556",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "22100",
            "1",
            "51",
            "75",
            "14915",
            "112523",
            "385987",
            "79169",
            "889",
            "1831500",
            "2670",
            "3042",
            "2022",
            "2023-01-03",
            "0.0000",
            "86760.0000",
            "86760.00",
            "27746.6400",
            "27746.64",
            "27746.64"
          ],
          "rowNumber": 1916549,
          "rowPosition": 1916550,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79169\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916550\" violates the foreign key: for \"id_contrato\": values \"79169\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43556",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "22100",
            "1",
            "51",
            "75",
            "14915",
            "112523",
            "385987",
            "79169",
            "889",
            "1831500",
            "2670",
            "3042",
            "2022",
            "2023-01-03",
            "0.0000",
            "89820.0000",
            "89820.00",
            "27746.6400",
            "27746.64",
            "27746.64"
          ],
          "rowNumber": 1916550,
          "rowPosition": 1916551,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79169\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916551\" violates the foreign key: for \"id_contrato\": values \"79169\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43963",
            "1",
            "1831081",
            "77",
            "1",
            "1",
            "66",
            "73078",
            "1",
            "39",
            "130",
            "21730",
            "237881",
            "385476",
            "79174",
            "889",
            "1831805",
            "3067",
            "2014",
            "2022",
            "2022-12-28",
            "0.0000",
            "100800.0000",
            "100800.00",
            "100800.0000",
            "100800.00",
            "100800.00"
          ],
          "rowNumber": 1917392,
          "rowPosition": 1917393,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79174\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1917393\" violates the foreign key: for \"id_contrato\": values \"79174\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 35
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 35,
    "tasks": 1
  },
  "valid": false
}