{
  "version": "4.38.0",
  "time": 410.132,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_compras",
        "title": "Compras",
        "path": "data/ft_compras.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_tempo",
              "title": "Tempo - Chave",
              "type": "integer",
              "format": "default",
              "description": "- > \n  Chave estrangeira (Foreign Key) que aponta para a Chave Primária (Primary keys) da tabela dm_tempo_diario. \n  Ou seja, por meio dessa chave é possível identificar a data completa a qual o dado se refere.\n\n  Nota: \n  No site dados.mg.gov.br a tabela dm_tempo_diario pode ser encontrada no recurso Calendários - Dias \n  de cada conjunto.\n",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_procedimento",
              "title": "Procedimento de Contratação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_demanda",
              "title": "Órgão Demandante - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_contrato",
              "title": "Órgão do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_proc",
              "title": "Situação do Processo de Compra - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_cont",
              "title": "Situação do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_municipio",
              "title": "Município - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contratado",
              "title": "Contratado - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_tipo_licitacao",
              "title": "Tipo de Licitação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_grupo_matserv",
              "title": "Grupo Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_classe_matserv",
              "title": "Classe Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_material_servico",
              "title": "Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item_matserv",
              "title": "Item Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_processo",
              "title": "Processo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contrato",
              "title": "Número do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_medida",
              "title": "Unidade de Medida - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_linha_fornec",
              "title": "Linha de Fornecimento - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_orc",
              "title": "Unidade Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "unique": false
              }
            },
            {
              "name": "ano_particao",
              "title": "Ano Partição",
              "type": "year",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true
              }
            },
            {
              "name": "dt_item_homologa",
              "title": "Data da Homologação do Item",
              "type": "date",
              "format": "default",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "qt_item_pedido",
              "title": "Item do Pedido - Quantidade",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_referencia",
              "title": "Valor Unitário de Referência",
              "description": "Valor unitário estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_referencia",
              "title": "Valor de Referência",
              "description": "Valor estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_homologado",
              "title": "Valor Unitário Homologado",
              "description": "Valor unitário final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_homologado",
              "title": "Valor Homologado",
              "description": "Valor final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_atualizado",
              "title": "Valor Atualizado",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_processo"
              ],
              "reference": {
                "fields": [
                  "id_processo"
                ],
                "resource": "dm_processo"
              }
            },
            {
              "fields": [
                "id_situacao_cont"
              ],
              "reference": {
                "fields": [
                  "id_situacao_cont"
                ],
                "resource": "dm_situacao_cont"
              }
            },
            {
              "fields": [
                "id_situacao_proc"
              ],
              "reference": {
                "fields": [
                  "id_situacao_proc"
                ],
                "resource": "dm_situacao_proc"
              }
            },
            {
              "fields": [
                "id_linha_fornec"
              ],
              "reference": {
                "fields": [
                  "id_linha_fornec"
                ],
                "resource": "dm_linha_fornec"
              }
            },
            {
              "fields": [
                "id_classe_matserv"
              ],
              "reference": {
                "fields": [
                  "id_classe_matserv"
                ],
                "resource": "dm_classe_matserv"
              }
            },
            {
              "fields": [
                "id_tempo"
              ],
              "reference": {
                "fields": [
                  "id_tempo"
                ],
                "resource": "dm_tempo_diario"
              }
            },
            {
              "fields": [
                "id_municipio"
              ],
              "reference": {
                "fields": [
                  "id_municipio"
                ],
                "resource": "dm_municipio"
              }
            },
            {
              "fields": [
                "id_item_matserv"
              ],
              "reference": {
                "fields": [
                  "id_item_matserv"
                ],
                "resource": "dm_item_matserv"
              }
            },
            {
              "fields": [
                "id_tipo_licitacao"
              ],
              "reference": {
                "fields": [
                  "id_tipo_licitacao"
                ],
                "resource": "dm_tipo_licitacao"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_material_servico"
              ],
              "reference": {
                "fields": [
                  "id_material_servico"
                ],
                "resource": "dm_material_servico"
              }
            },
            {
              "fields": [
                "id_orgao_contrato"
              ],
              "reference": {
                "fields": [
                  "id_orgao_contrato"
                ],
                "resource": "dm_orgao_contrato"
              }
            },
            {
              "fields": [
                "id_contrato"
              ],
              "reference": {
                "fields": [
                  "id_contrato"
                ],
                "resource": "dm_contrato"
              }
            },
            {
              "fields": [
                "id_orgao_demanda"
              ],
              "reference": {
                "fields": [
                  "id_orgao_demanda"
                ],
                "resource": "dm_orgao_demanda"
              }
            },
            {
              "fields": [
                "id_unidade_medida"
              ],
              "reference": {
                "fields": [
                  "id_unidade_medida"
                ],
                "resource": "dm_unidade_medida"
              }
            },
            {
              "fields": [
                "id_grupo_matserv"
              ],
              "reference": {
                "fields": [
                  "id_grupo_matserv"
                ],
                "resource": "dm_grupo_matserv"
              }
            },
            {
              "fields": [
                "id_contratado"
              ],
              "reference": {
                "fields": [
                  "id_contratado"
                ],
                "resource": "dm_contratado"
              }
            },
            {
              "fields": [
                "id_procedimento"
              ],
              "reference": {
                "fields": [
                  "id_procedimento"
                ],
                "resource": "dm_procedimento"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_compras"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "d41f1f558a6bbc991b81e58a15c384aa",
          "bytes": 58076256,
          "fields": 27,
          "rows": 1905341
        }
      },
      "time": 410.132,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "43541",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "72459",
            "1",
            "30",
            "173",
            "6926",
            "122351",
            "383096",
            "78255",
            "889",
            "1831435",
            "3067",
            "3042",
            "2022",
            "2022-11-29",
            "0.0000",
            "46683.0000",
            "46683.00",
            "36000.0000",
            "36000.00",
            "36000.00"
          ],
          "rowNumber": 1813403,
          "rowPosition": 1813404,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78255\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813404\" violates the foreign key: for \"id_contrato\": values \"78255\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44416",
            "17",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "31394",
            "1",
            "30",
            "173",
            "4089",
            "236747",
            "382975",
            "78253",
            "889",
            "1831467",
            "3067",
            "2045",
            "2022",
            "2022-11-28",
            "0.0000",
            "2000.0000",
            "2000.00",
            "2000.0000",
            "2000.00",
            "2000.00"
          ],
          "rowNumber": 1815992,
          "rowPosition": 1815993,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78253\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1815993\" violates the foreign key: for \"id_contrato\": values \"78253\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44416",
            "17",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "31394",
            "1",
            "3",
            "284",
            "4635",
            "312606",
            "382975",
            "78253",
            "889",
            "1831295",
            "2611",
            "2045",
            "2022",
            "2022-11-28",
            "2.0000",
            "324000.0000",
            "648000.00",
            "324000.0000",
            "648000.00",
            "648000.00"
          ],
          "rowNumber": 1815993,
          "rowPosition": 1815994,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78253\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1815994\" violates the foreign key: for \"id_contrato\": values \"78253\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44057",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "70040",
            "1",
            "18",
            "506",
            "21741",
            "175918",
            "381057",
            "78252",
            "1917",
            "1831311",
            "2994",
            "2081",
            "2022",
            "2022-10-28",
            "400.0000",
            "16.5400",
            "6616.00",
            "13.1000",
            "5240.00",
            "5240.00"
          ],
          "rowNumber": 1833142,
          "rowPosition": 1833143,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78252\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1833143\" violates the foreign key: for \"id_contrato\": values \"78252\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44057",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "70040",
            "1",
            "42",
            "399",
            "21794",
            "180139",
            "381057",
            "78252",
            "1917",
            "1831306",
            "2994",
            "2081",
            "2022",
            "2022-10-28",
            "150.0000",
            "64.2900",
            "9642.75",
            "57.3300",
            "8599.50",
            "8599.50"
          ],
          "rowNumber": 1833143,
          "rowPosition": 1833144,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78252\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1833144\" violates the foreign key: for \"id_contrato\": values \"78252\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44057",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "70040",
            "1",
            "42",
            "399",
            "21794",
            "180149",
            "381057",
            "78252",
            "1917",
            "1831306",
            "2994",
            "2081",
            "2022",
            "2022-10-28",
            "150.0000",
            "19.3000",
            "2895.00",
            "16.0000",
            "2400.00",
            "2400.00"
          ],
          "rowNumber": 1833144,
          "rowPosition": 1833145,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78252\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1833145\" violates the foreign key: for \"id_contrato\": values \"78252\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44057",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "70040",
            "1",
            "18",
            "506",
            "21741",
            "175917",
            "381057",
            "78252",
            "1916",
            "1831311",
            "2994",
            "2081",
            "2022",
            "2022-10-28",
            "2000.0000",
            "6.7500",
            "13500.00",
            "6.6300",
            "13260.00",
            "13260.00"
          ],
          "rowNumber": 1833998,
          "rowPosition": 1833999,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78252\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1833999\" violates the foreign key: for \"id_contrato\": values \"78252\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44440",
            "20",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "11676",
            "1",
            "77",
            "82",
            "7067",
            "95658",
            "383327",
            "78239",
            "889",
            "1831925",
            "3069",
            "2840",
            "2022",
            "2022-12-01",
            "0.0000",
            "38182.0000",
            "38182.00",
            "38182.0000",
            "38182.00",
            "38182.00"
          ],
          "rowNumber": 1849874,
          "rowPosition": 1849875,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78239\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1849875\" violates the foreign key: for \"id_contrato\": values \"78239\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44440",
            "21",
            "1831027",
            "22",
            "1",
            "1",
            "790",
            "72873",
            "1",
            "9",
            "581",
            "12418",
            "93129",
            "383351",
            "78244",
            "322",
            "1831697",
            "2932",
            "2045",
            "2022",
            "2022-12-01",
            "0.0000",
            "273721.9300",
            "273721.93",
            "273721.9300",
            "273721.93",
            "273721.93"
          ],
          "rowNumber": 1849879,
          "rowPosition": 1849880,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78244\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1849880\" violates the foreign key: for \"id_contrato\": values \"78244\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44440",
            "21",
            "1831027",
            "22",
            "1",
            "1",
            "790",
            "72873",
            "1",
            "9",
            "581",
            "12418",
            "93129",
            "383351",
            "78244",
            "322",
            "1831697",
            "2932",
            "2045",
            "2022",
            "2022-12-01",
            "0.0000",
            "273721.9300",
            "273721.93",
            "273721.9300",
            "273721.93",
            "273721.93"
          ],
          "rowNumber": 1849879,
          "rowPosition": 1849880,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contratado\": values \"72873\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "message": "Row at position \"1849880\" violates the foreign key: for \"id_contratado\": values \"72873\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44434",
            "17",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "71469",
            "1",
            "39",
            "834",
            "21872",
            "341933",
            "382853",
            "78243",
            "889",
            "1831739",
            "3067",
            "2840",
            "2022",
            "2022-11-25",
            "0.0000",
            "10000.0000",
            "10000.00",
            "1000.0000",
            "1000.00",
            "1000.00"
          ],
          "rowNumber": 1851790,
          "rowPosition": 1851791,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78243\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1851791\" violates the foreign key: for \"id_contrato\": values \"78243\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44434",
            "17",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "71469",
            "1",
            "39",
            "834",
            "21872",
            "341933",
            "382853",
            "78243",
            "889",
            "1831739",
            "3067",
            "2840",
            "2022",
            "2022-11-25",
            "0.0000",
            "186300.0000",
            "186300.00",
            "143550.0000",
            "143550.00",
            "143550.00"
          ],
          "rowNumber": 1851791,
          "rowPosition": 1851792,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78243\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1851792\" violates the foreign key: for \"id_contrato\": values \"78243\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44434",
            "17",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "71469",
            "1",
            "39",
            "834",
            "21872",
            "341933",
            "382853",
            "78243",
            "889",
            "1831739",
            "3067",
            "2840",
            "2022",
            "2022-11-25",
            "0.0000",
            "10200.0000",
            "10200.00",
            "200.0000",
            "200.00",
            "200.00"
          ],
          "rowNumber": 1851792,
          "rowPosition": 1851793,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78243\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1851793\" violates the foreign key: for \"id_contrato\": values \"78243\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44434",
            "17",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "71469",
            "1",
            "39",
            "834",
            "21872",
            "341933",
            "382853",
            "78243",
            "889",
            "1831739",
            "3067",
            "2840",
            "2022",
            "2022-11-25",
            "0.0000",
            "6240.0000",
            "6240.00",
            "4450.0000",
            "4450.00",
            "4450.00"
          ],
          "rowNumber": 1851793,
          "rowPosition": 1851794,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78243\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1851794\" violates the foreign key: for \"id_contrato\": values \"78243\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44434",
            "14",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "15243",
            "1",
            "77",
            "183",
            "4381",
            "386519",
            "382818",
            "78237",
            "889",
            "1831800",
            "3136",
            "2840",
            "2022",
            "2022-11-25",
            "0.0000",
            "3450.0000",
            "3450.00",
            "3400.0000",
            "3400.00",
            "3400.00"
          ],
          "rowNumber": 1851794,
          "rowPosition": 1851795,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78237\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1851795\" violates the foreign key: for \"id_contrato\": values \"78237\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44434",
            "15",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "72084",
            "1",
            "3",
            "509",
            "20590",
            "124079",
            "382921",
            "78247",
            "889",
            "1831295",
            "2584",
            "1760",
            "2022",
            "2022-11-25",
            "5950.0000",
            "39.7000",
            "236215.00",
            "39.7000",
            "236215.00",
            "236215.00"
          ],
          "rowNumber": 1851868,
          "rowPosition": 1851869,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78247\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1851869\" violates the foreign key: for \"id_contrato\": values \"78247\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44439",
            "4",
            "1831044",
            "36",
            "1",
            "1",
            "835",
            "33734",
            "1",
            "77",
            "183",
            "17661",
            "93278",
            "383228",
            "78256",
            "889",
            "1831520",
            "2670",
            "2633",
            "2022",
            "2022-11-30",
            "0.0000",
            "20000.0000",
            "20000.00",
            "10449.6000",
            "10449.60",
            "10449.60"
          ],
          "rowNumber": 1851894,
          "rowPosition": 1851895,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78256\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1851895\" violates the foreign key: for \"id_contrato\": values \"78256\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44404",
            "17",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "39076",
            "1",
            "30",
            "173",
            "4089",
            "120106",
            "383176",
            "78254",
            "889",
            "1831467",
            "3067",
            "2925",
            "2022",
            "2022-11-30",
            "250.0000",
            "11000.0000",
            "2750000.00",
            "11000.0000",
            "2750000.00",
            "2750000.00"
          ],
          "rowNumber": 1851901,
          "rowPosition": 1851902,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78254\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1851902\" violates the foreign key: for \"id_contrato\": values \"78254\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44404",
            "17",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "39076",
            "1",
            "30",
            "173",
            "4089",
            "140895",
            "383176",
            "78254",
            "889",
            "1831467",
            "3067",
            "2925",
            "2022",
            "2022-11-30",
            "0.0000",
            "414000.0000",
            "414000.00",
            "414000.0000",
            "414000.00",
            "414000.00"
          ],
          "rowNumber": 1851902,
          "rowPosition": 1851903,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78254\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1851903\" violates the foreign key: for \"id_contrato\": values \"78254\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44404",
            "17",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "39076",
            "1",
            "30",
            "173",
            "4089",
            "140896",
            "383176",
            "78254",
            "889",
            "1831467",
            "3067",
            "2925",
            "2022",
            "2022-11-30",
            "655.0000",
            "4500.0000",
            "2947500.00",
            "4500.0000",
            "2947500.00",
            "2947500.00"
          ],
          "rowNumber": 1851903,
          "rowPosition": 1851904,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78254\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1851904\" violates the foreign key: for \"id_contrato\": values \"78254\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43493",
            "2",
            "1831032",
            "26",
            "1",
            "1",
            "66",
            "58853",
            "1",
            "9",
            "581",
            "12418",
            "93129",
            "382898",
            "78246",
            "322",
            "1831697",
            "2669",
            "3109",
            "2022",
            "2022-11-25",
            "0.0000",
            "6480000.0000",
            "6480000.00",
            "6480000.0000",
            "6480000.00",
            "6480000.00"
          ],
          "rowNumber": 1858715,
          "rowPosition": 1858716,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78246\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1858716\" violates the foreign key: for \"id_contrato\": values \"78246\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44426",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "20319",
            "1",
            "37",
            "17",
            "18749",
            "125207",
            "382082",
            "78249",
            "371",
            "1831952",
            "2927",
            "3043",
            "2022",
            "2022-11-17",
            "10.0000",
            "3540.0000",
            "35400.00",
            "3540.0000",
            "35400.00",
            "35400.00"
          ],
          "rowNumber": 1859484,
          "rowPosition": 1859485,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78249\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1859485\" violates the foreign key: for \"id_contrato\": values \"78249\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44426",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "20319",
            "1",
            "37",
            "17",
            "18749",
            "113021",
            "382082",
            "78249",
            "371",
            "1831952",
            "2927",
            "3043",
            "2022",
            "2022-11-17",
            "65.0000",
            "4830.0000",
            "313950.00",
            "4830.0000",
            "313950.00",
            "313950.00"
          ],
          "rowNumber": 1859485,
          "rowPosition": 1859486,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78249\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1859486\" violates the foreign key: for \"id_contrato\": values \"78249\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43554",
            "1",
            "1831095",
            "96",
            "1",
            "1",
            "821",
            "12868",
            "1",
            "77",
            "73",
            "9726",
            "92493",
            "379527",
            "78245",
            "889",
            "1831901",
            "2623",
            "3293",
            "2022",
            "2022-10-07",
            "0.0000",
            "79011.7600",
            "79011.76",
            "79011.7600",
            "79011.76",
            "79011.76"
          ],
          "rowNumber": 1881149,
          "rowPosition": 1881150,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78245\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1881150\" violates the foreign key: for \"id_contrato\": values \"78245\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44417",
            "1",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "7787",
            "1",
            "77",
            "272",
            "6933",
            "143804",
            "381856",
            "78242",
            "322",
            "1831726",
            "2666",
            "2840",
            "2022",
            "2022-11-11",
            "0.0000",
            "1580.9600",
            "1580.96",
            "1580.9600",
            "1580.96",
            "1580.96"
          ],
          "rowNumber": 1893729,
          "rowPosition": 1893730,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78242\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1893730\" violates the foreign key: for \"id_contrato\": values \"78242\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43575",
            "2",
            "1831099",
            "90",
            "1",
            "1",
            "66",
            "31915",
            "1",
            "39",
            "130",
            "20348",
            "98672",
            "380608",
            "78257",
            "889",
            "1831812",
            "3135",
            "2001",
            "2022",
            "2022-10-24",
            "0.0000",
            "3975936.0000",
            "3975936.00",
            "3975936.0000",
            "3975936.00",
            "3975936.00"
          ],
          "rowNumber": 1894214,
          "rowPosition": 1894215,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78257\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1894215\" violates the foreign key: for \"id_contrato\": values \"78257\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44402",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "20073",
            "1",
            "77",
            "700",
            "14929",
            "93680",
            "382567",
            "78240",
            "981",
            "1831731",
            "2553",
            "2840",
            "2022",
            "2022-11-23",
            "0.0000",
            "1045804.0800",
            "1045804.08",
            "903057.3600",
            "903057.36",
            "903057.36"
          ],
          "rowNumber": 1894868,
          "rowPosition": 1894869,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78240\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1894869\" violates the foreign key: for \"id_contrato\": values \"78240\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44402",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "18",
            "56033",
            "1",
            "77",
            "700",
            "17682",
            "93674",
            "382170",
            "78238",
            "889",
            "1831731",
            "2879",
            "3043",
            "2022",
            "2022-11-18",
            "0.0000",
            "101652.2400",
            "101652.24",
            "92194.8300",
            "92194.83",
            "92194.83"
          ],
          "rowNumber": 1901456,
          "rowPosition": 1901457,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78238\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1901457\" violates the foreign key: for \"id_contrato\": values \"78238\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43583",
            "4",
            "1910409",
            "59",
            "1",
            "1",
            "66",
            "69474",
            "1",
            "8",
            "687",
            "12333",
            "92275",
            "382599",
            "78251",
            "889",
            "1831347",
            "2741",
            "2840",
            "2022",
            "2022-11-23",
            "0.0000",
            "39493.0700",
            "39493.07",
            "27500.0000",
            "27500.00",
            "27500.00"
          ],
          "rowNumber": 1902100,
          "rowPosition": 1902101,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78251\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1902101\" violates the foreign key: for \"id_contrato\": values \"78251\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44002",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "806",
            "72384",
            "1",
            "66",
            "579",
            "14976",
            "93931",
            "382391",
            "78241",
            "889",
            "1831566",
            "3014",
            "3043",
            "2022",
            "2022-11-22",
            "0.0000",
            "297500.0000",
            "297500.00",
            "297500.0000",
            "297500.00",
            "297500.00"
          ],
          "rowNumber": 1902902,
          "rowPosition": 1902903,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78241\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1902903\" violates the foreign key: for \"id_contrato\": values \"78241\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44406",
            "4",
            "1831083",
            "82",
            "1",
            "1",
            "66",
            "62715",
            "1",
            "77",
            "533",
            "1804",
            "157757",
            "382648",
            "78250",
            "889",
            "1831586",
            "2738",
            "2083",
            "2022",
            "2022-11-24",
            "0.0000",
            "148500.0000",
            "148500.00",
            "35640.0000",
            "35640.00",
            "35640.00"
          ],
          "rowNumber": 1902993,
          "rowPosition": 1902994,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78250\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1902994\" violates the foreign key: for \"id_contrato\": values \"78250\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43535",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "60360",
            "1",
            "77",
            "700",
            "7024",
            "93673",
            "381832",
            "78258",
            "889",
            "1831730",
            "2954",
            "3042",
            "2022",
            "2022-11-11",
            "0.0000",
            "6896.0000",
            "6896.00",
            "6896.0000",
            "6896.00",
            "6896.00"
          ],
          "rowNumber": 1903700,
          "rowPosition": 1903701,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78258\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1903701\" violates the foreign key: for \"id_contrato\": values \"78258\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43535",
            "4",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "60360",
            "1",
            "77",
            "700",
            "7024",
            "93673",
            "381832",
            "78258",
            "889",
            "1831730",
            "2954",
            "3042",
            "2022",
            "2022-11-11",
            "0.0000",
            "61901.5100",
            "61901.51",
            "32984.8200",
            "32984.82",
            "32984.82"
          ],
          "rowNumber": 1903701,
          "rowPosition": 1903702,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78258\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1903702\" violates the foreign key: for \"id_contrato\": values \"78258\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44410",
            "15",
            "1831101",
            "97",
            "1",
            "1",
            "883",
            "379",
            "1",
            "57",
            "779",
            "16006",
            "118342",
            "381119",
            "78248",
            "190",
            "1831313",
            "2928",
            "2259",
            "2022",
            "2022-11-02",
            "1000.0000",
            "5.6300",
            "5628.60",
            "5.6300",
            "5628.60",
            "5628.60"
          ],
          "rowNumber": 1905212,
          "rowPosition": 1905213,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78248\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1905213\" violates the foreign key: for \"id_contrato\": values \"78248\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44410",
            "15",
            "1831101",
            "97",
            "1",
            "1",
            "883",
            "379",
            "1",
            "57",
            "779",
            "2941",
            "5465",
            "381119",
            "78248",
            "190",
            "1831313",
            "2928",
            "2259",
            "2022",
            "2022-11-02",
            "5000.0000",
            "3.9300",
            "19630.50",
            "3.9300",
            "19630.50",
            "19630.50"
          ],
          "rowNumber": 1905213,
          "rowPosition": 1905214,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78248\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1905214\" violates the foreign key: for \"id_contrato\": values \"78248\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 35
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 35,
    "tasks": 1
  },
  "valid": false
}