{
  "version": "4.38.0",
  "time": 409.725,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_compras",
        "title": "Compras",
        "path": "data/ft_compras.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_tempo",
              "title": "Tempo - Chave",
              "type": "integer",
              "format": "default",
              "description": "- > \n  Chave estrangeira (Foreign Key) que aponta para a Chave Primária (Primary keys) da tabela dm_tempo_diario. \n  Ou seja, por meio dessa chave é possível identificar a data completa a qual o dado se refere.\n\n  Nota: \n  No site dados.mg.gov.br a tabela dm_tempo_diario pode ser encontrada no recurso Calendários - Dias \n  de cada conjunto.\n",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_procedimento",
              "title": "Procedimento de Contratação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_demanda",
              "title": "Órgão Demandante - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_contrato",
              "title": "Órgão do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_proc",
              "title": "Situação do Processo de Compra - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_cont",
              "title": "Situação do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_municipio",
              "title": "Município - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contratado",
              "title": "Contratado - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_tipo_licitacao",
              "title": "Tipo de Licitação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_grupo_matserv",
              "title": "Grupo Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_classe_matserv",
              "title": "Classe Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_material_servico",
              "title": "Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item_matserv",
              "title": "Item Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_processo",
              "title": "Processo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contrato",
              "title": "Número do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_medida",
              "title": "Unidade de Medida - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_linha_fornec",
              "title": "Linha de Fornecimento - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_orc",
              "title": "Unidade Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "unique": false
              }
            },
            {
              "name": "ano_particao",
              "title": "Ano Partição",
              "type": "year",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true
              }
            },
            {
              "name": "dt_item_homologa",
              "title": "Data da Homologação do Item",
              "type": "date",
              "format": "default",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "qt_item_pedido",
              "title": "Item do Pedido - Quantidade",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_referencia",
              "title": "Valor Unitário de Referência",
              "description": "Valor unitário estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_referencia",
              "title": "Valor de Referência",
              "description": "Valor estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_homologado",
              "title": "Valor Unitário Homologado",
              "description": "Valor unitário final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_homologado",
              "title": "Valor Homologado",
              "description": "Valor final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_atualizado",
              "title": "Valor Atualizado",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_processo"
              ],
              "reference": {
                "fields": [
                  "id_processo"
                ],
                "resource": "dm_processo"
              }
            },
            {
              "fields": [
                "id_situacao_cont"
              ],
              "reference": {
                "fields": [
                  "id_situacao_cont"
                ],
                "resource": "dm_situacao_cont"
              }
            },
            {
              "fields": [
                "id_situacao_proc"
              ],
              "reference": {
                "fields": [
                  "id_situacao_proc"
                ],
                "resource": "dm_situacao_proc"
              }
            },
            {
              "fields": [
                "id_linha_fornec"
              ],
              "reference": {
                "fields": [
                  "id_linha_fornec"
                ],
                "resource": "dm_linha_fornec"
              }
            },
            {
              "fields": [
                "id_classe_matserv"
              ],
              "reference": {
                "fields": [
                  "id_classe_matserv"
                ],
                "resource": "dm_classe_matserv"
              }
            },
            {
              "fields": [
                "id_tempo"
              ],
              "reference": {
                "fields": [
                  "id_tempo"
                ],
                "resource": "dm_tempo_diario"
              }
            },
            {
              "fields": [
                "id_municipio"
              ],
              "reference": {
                "fields": [
                  "id_municipio"
                ],
                "resource": "dm_municipio"
              }
            },
            {
              "fields": [
                "id_item_matserv"
              ],
              "reference": {
                "fields": [
                  "id_item_matserv"
                ],
                "resource": "dm_item_matserv"
              }
            },
            {
              "fields": [
                "id_tipo_licitacao"
              ],
              "reference": {
                "fields": [
                  "id_tipo_licitacao"
                ],
                "resource": "dm_tipo_licitacao"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_material_servico"
              ],
              "reference": {
                "fields": [
                  "id_material_servico"
                ],
                "resource": "dm_material_servico"
              }
            },
            {
              "fields": [
                "id_orgao_contrato"
              ],
              "reference": {
                "fields": [
                  "id_orgao_contrato"
                ],
                "resource": "dm_orgao_contrato"
              }
            },
            {
              "fields": [
                "id_contrato"
              ],
              "reference": {
                "fields": [
                  "id_contrato"
                ],
                "resource": "dm_contrato"
              }
            },
            {
              "fields": [
                "id_orgao_demanda"
              ],
              "reference": {
                "fields": [
                  "id_orgao_demanda"
                ],
                "resource": "dm_orgao_demanda"
              }
            },
            {
              "fields": [
                "id_unidade_medida"
              ],
              "reference": {
                "fields": [
                  "id_unidade_medida"
                ],
                "resource": "dm_unidade_medida"
              }
            },
            {
              "fields": [
                "id_grupo_matserv"
              ],
              "reference": {
                "fields": [
                  "id_grupo_matserv"
                ],
                "resource": "dm_grupo_matserv"
              }
            },
            {
              "fields": [
                "id_contratado"
              ],
              "reference": {
                "fields": [
                  "id_contratado"
                ],
                "resource": "dm_contratado"
              }
            },
            {
              "fields": [
                "id_procedimento"
              ],
              "reference": {
                "fields": [
                  "id_procedimento"
                ],
                "resource": "dm_procedimento"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_compras"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "a8ec66397235c6965fe5fc39f448401d",
          "bytes": 58024303,
          "fields": 27,
          "rows": 1903525
        }
      },
      "time": 409.725,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "43556",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "883",
            "67724",
            "1",
            "39",
            "712",
            "7131",
            "242303",
            "381886",
            "78155",
            "889",
            "1831925",
            "3067",
            "1760",
            "2022",
            "2022-11-16",
            "150.0000",
            "240.0000",
            "36000.00",
            "7.0000",
            "1050.00",
            "1050.00"
          ],
          "rowNumber": 1813104,
          "rowPosition": 1813105,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78155\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813105\" violates the foreign key: for \"id_contrato\": values \"78155\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43556",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "883",
            "67724",
            "1",
            "39",
            "712",
            "7131",
            "171415",
            "381886",
            "78155",
            "889",
            "1831925",
            "3067",
            "1760",
            "2022",
            "2022-11-16",
            "11700.0000",
            "51.8400",
            "606528.00",
            "35.0000",
            "409500.00",
            "409500.00"
          ],
          "rowNumber": 1813105,
          "rowPosition": 1813106,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78155\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813106\" violates the foreign key: for \"id_contrato\": values \"78155\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43556",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "883",
            "67724",
            "1",
            "39",
            "712",
            "20379",
            "100999",
            "381886",
            "78155",
            "889",
            "1831925",
            "3067",
            "1760",
            "2022",
            "2022-11-16",
            "25.0000",
            "186.7300",
            "4668.25",
            "35.0000",
            "875.00",
            "875.00"
          ],
          "rowNumber": 1813106,
          "rowPosition": 1813107,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78155\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813107\" violates the foreign key: for \"id_contrato\": values \"78155\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43556",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "883",
            "67724",
            "1",
            "39",
            "712",
            "20379",
            "161458",
            "381886",
            "78155",
            "889",
            "1831925",
            "3067",
            "1760",
            "2022",
            "2022-11-16",
            "5.0000",
            "217.3800",
            "1086.90",
            "30.0000",
            "150.00",
            "150.00"
          ],
          "rowNumber": 1813107,
          "rowPosition": 1813108,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78155\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813108\" violates the foreign key: for \"id_contrato\": values \"78155\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43556",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "883",
            "67724",
            "1",
            "39",
            "712",
            "20379",
            "161459",
            "381886",
            "78155",
            "889",
            "1831925",
            "3067",
            "1760",
            "2022",
            "2022-11-16",
            "12.0000",
            "266.2300",
            "3194.76",
            "35.0000",
            "420.00",
            "420.00"
          ],
          "rowNumber": 1813108,
          "rowPosition": 1813109,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78155\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813109\" violates the foreign key: for \"id_contrato\": values \"78155\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43556",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "883",
            "67724",
            "1",
            "39",
            "712",
            "7131",
            "265542",
            "381886",
            "78155",
            "889",
            "1831925",
            "3067",
            "1760",
            "2022",
            "2022-11-16",
            "750.0000",
            "104.3000",
            "78225.00",
            "81.5000",
            "61125.00",
            "61125.00"
          ],
          "rowNumber": 1813109,
          "rowPosition": 1813110,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78155\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813110\" violates the foreign key: for \"id_contrato\": values \"78155\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43556",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "883",
            "67724",
            "1",
            "39",
            "712",
            "7131",
            "242303",
            "381886",
            "78155",
            "889",
            "1831925",
            "3067",
            "1760",
            "2022",
            "2022-11-16",
            "360.0000",
            "170.0500",
            "61218.00",
            "5.0000",
            "1800.00",
            "1800.00"
          ],
          "rowNumber": 1813110,
          "rowPosition": 1813111,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78155\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813111\" violates the foreign key: for \"id_contrato\": values \"78155\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43557",
            "4",
            "1831079",
            "76",
            "1",
            "1",
            "66",
            "61546",
            "1",
            "51",
            "75",
            "14915",
            "112523",
            "381933",
            "78160",
            "889",
            "1831500",
            "2670",
            "2046",
            "2022",
            "2022-11-16",
            "0.0000",
            "5250.0000",
            "5250.00",
            "1800.0000",
            "1800.00",
            "1800.00"
          ],
          "rowNumber": 1813415,
          "rowPosition": 1813416,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813416\" violates the foreign key: for \"id_contrato\": values \"78160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44425",
            "15",
            "1831044",
            "96",
            "1",
            "1",
            "844",
            "4625",
            "1",
            "54",
            "502",
            "6435",
            "156231",
            "381983",
            "78169",
            "889",
            "1831296",
            "2944",
            "2633",
            "2022",
            "2022-11-16",
            "425.0000",
            "519.0000",
            "220575.00",
            "519.0000",
            "220575.00",
            "220575.00"
          ],
          "rowNumber": 1813564,
          "rowPosition": 1813565,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78169\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813565\" violates the foreign key: for \"id_contrato\": values \"78169\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44425",
            "15",
            "1831044",
            "96",
            "1",
            "1",
            "844",
            "31148",
            "1",
            "54",
            "502",
            "14376",
            "128397",
            "381983",
            "78164",
            "889",
            "1831296",
            "2944",
            "2633",
            "2022",
            "2022-11-16",
            "79.0000",
            "1676.0900",
            "132411.11",
            "1676.0900",
            "132411.11",
            "132411.11"
          ],
          "rowNumber": 1813565,
          "rowPosition": 1813566,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78164\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813566\" violates the foreign key: for \"id_contrato\": values \"78164\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44425",
            "15",
            "1831044",
            "96",
            "1",
            "1",
            "844",
            "31148",
            "1",
            "54",
            "502",
            "15252",
            "138494",
            "381983",
            "78164",
            "889",
            "1831296",
            "2944",
            "2633",
            "2022",
            "2022-11-16",
            "90.0000",
            "631.3800",
            "56824.20",
            "631.3800",
            "56824.20",
            "56824.20"
          ],
          "rowNumber": 1813567,
          "rowPosition": 1813568,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78164\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813568\" violates the foreign key: for \"id_contrato\": values \"78164\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44403",
            "17",
            "1831102",
            "89",
            "1",
            "1",
            "66",
            "33407",
            "1",
            "3",
            "284",
            "4635",
            "384567",
            "380736",
            "78171",
            "889",
            "1831295",
            "2611",
            "2838",
            "2022",
            "2022-10-25",
            "2.0000",
            "145450.0000",
            "290900.00",
            "130000.0000",
            "260000.00",
            "260000.00"
          ],
          "rowNumber": 1822083,
          "rowPosition": 1822084,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78171\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1822084\" violates the foreign key: for \"id_contrato\": values \"78171\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43562",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "876",
            "57005",
            "1",
            "39",
            "834",
            "22816",
            "359234",
            "381424",
            "78165",
            "1729",
            "1831739",
            "3067",
            "3043",
            "2022",
            "2022-11-08",
            "0.0000",
            "9150.0000",
            "9150.00",
            "6072.0000",
            "6072.00",
            "6072.00"
          ],
          "rowNumber": 1822148,
          "rowPosition": 1822149,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78165\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1822149\" violates the foreign key: for \"id_contrato\": values \"78165\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44403",
            "15",
            "1831016",
            "16",
            "1",
            "1",
            "883",
            "33019",
            "1",
            "3",
            "627",
            "3013",
            "226208",
            "380801",
            "78172",
            "889",
            "1831295",
            "2611",
            "2082",
            "2022",
            "2022-10-25",
            "50.0000",
            "4921.1000",
            "246055.00",
            "4921.1000",
            "246055.00",
            "246055.00"
          ],
          "rowNumber": 1823908,
          "rowPosition": 1823909,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78172\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1823909\" violates the foreign key: for \"id_contrato\": values \"78172\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44057",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "69417",
            "1",
            "80",
            "621",
            "21585",
            "170097",
            "381057",
            "78163",
            "1071",
            "1831226",
            "2994",
            "2081",
            "2022",
            "2022-10-28",
            "2500.0000",
            "7.9900",
            "19975.00",
            "6.1200",
            "15300.00",
            "15300.00"
          ],
          "rowNumber": 1832419,
          "rowPosition": 1832420,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78163\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1832420\" violates the foreign key: for \"id_contrato\": values \"78163\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44057",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "69417",
            "1",
            "46",
            "123",
            "3039",
            "195180",
            "381057",
            "78163",
            "940",
            "1831340",
            "3084",
            "2081",
            "2022",
            "2022-10-28",
            "4650.0000",
            "6.2700",
            "29155.50",
            "4.3000",
            "19995.00",
            "19995.00"
          ],
          "rowNumber": 1832420,
          "rowPosition": 1832421,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78163\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1832421\" violates the foreign key: for \"id_contrato\": values \"78163\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44057",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "69417",
            "1",
            "80",
            "621",
            "18638",
            "4699",
            "381057",
            "78163",
            "222",
            "1831958",
            "2994",
            "2081",
            "2022",
            "2022-10-28",
            "25.0000",
            "16.7500",
            "418.75",
            "16.7300",
            "418.25",
            "418.25"
          ],
          "rowNumber": 1833275,
          "rowPosition": 1833276,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78163\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1833276\" violates the foreign key: for \"id_contrato\": values \"78163\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44057",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "69417",
            "1",
            "80",
            "621",
            "2604",
            "4995",
            "381057",
            "78163",
            "1204",
            "1831306",
            "2994",
            "2081",
            "2022",
            "2022-10-28",
            "300.0000",
            "4.5200",
            "1354.50",
            "3.8400",
            "1152.00",
            "1152.00"
          ],
          "rowNumber": 1833279,
          "rowPosition": 1833280,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78163\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1833280\" violates the foreign key: for \"id_contrato\": values \"78163\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44057",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "69417",
            "1",
            "80",
            "621",
            "20071",
            "85201",
            "381057",
            "78163",
            "439",
            "1831306",
            "2994",
            "2081",
            "2022",
            "2022-10-28",
            "50.0000",
            "3.2000",
            "160.00",
            "2.3900",
            "119.50",
            "119.50"
          ],
          "rowNumber": 1833280,
          "rowPosition": 1833281,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78163\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1833281\" violates the foreign key: for \"id_contrato\": values \"78163\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44057",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "69417",
            "1",
            "80",
            "621",
            "10598",
            "129110",
            "381057",
            "78163",
            "439",
            "1831306",
            "2994",
            "2081",
            "2022",
            "2022-10-28",
            "700.0000",
            "2.9000",
            "2030.00",
            "2.3400",
            "1638.00",
            "1638.00"
          ],
          "rowNumber": 1833281,
          "rowPosition": 1833282,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78163\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1833282\" violates the foreign key: for \"id_contrato\": values \"78163\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44057",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "69417",
            "1",
            "80",
            "621",
            "364",
            "109633",
            "381057",
            "78163",
            "439",
            "1831306",
            "2994",
            "2081",
            "2022",
            "2022-10-28",
            "1000.0000",
            "2.0500",
            "2050.00",
            "1.3700",
            "1370.00",
            "1370.00"
          ],
          "rowNumber": 1833282,
          "rowPosition": 1833283,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78163\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1833283\" violates the foreign key: for \"id_contrato\": values \"78163\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44057",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "69417",
            "1",
            "80",
            "308",
            "15699",
            "6193",
            "381057",
            "78163",
            "937",
            "1831306",
            "2994",
            "2081",
            "2022",
            "2022-10-28",
            "100.0000",
            "1.8200",
            "182.00",
            "1.7800",
            "178.00",
            "178.00"
          ],
          "rowNumber": 1833283,
          "rowPosition": 1833284,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78163\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1833284\" violates the foreign key: for \"id_contrato\": values \"78163\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44057",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "69417",
            "1",
            "80",
            "308",
            "5152",
            "55",
            "381057",
            "78163",
            "889",
            "1831306",
            "2994",
            "2081",
            "2022",
            "2022-10-28",
            "3000.0000",
            "0.8300",
            "2490.00",
            "0.7500",
            "2250.00",
            "2250.00"
          ],
          "rowNumber": 1833284,
          "rowPosition": 1833285,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78163\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1833285\" violates the foreign key: for \"id_contrato\": values \"78163\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44057",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "69417",
            "1",
            "80",
            "308",
            "2568",
            "56",
            "381057",
            "78163",
            "889",
            "1831306",
            "2994",
            "2081",
            "2022",
            "2022-10-28",
            "1200.0000",
            "2.0000",
            "2400.00",
            "1.9600",
            "2352.00",
            "2352.00"
          ],
          "rowNumber": 1833285,
          "rowPosition": 1833286,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78163\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1833286\" violates the foreign key: for \"id_contrato\": values \"78163\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44057",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "69417",
            "1",
            "32",
            "623",
            "13292",
            "2991",
            "381057",
            "78163",
            "476",
            "1831306",
            "2994",
            "2081",
            "2022",
            "2022-10-28",
            "300.0000",
            "10.7600",
            "3228.00",
            "8.5000",
            "2550.00",
            "2550.00"
          ],
          "rowNumber": 1833287,
          "rowPosition": 1833288,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78163\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1833288\" violates the foreign key: for \"id_contrato\": values \"78163\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44057",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "69417",
            "1",
            "32",
            "623",
            "13292",
            "48373",
            "381057",
            "78163",
            "476",
            "1831306",
            "2994",
            "2081",
            "2022",
            "2022-10-28",
            "300.0000",
            "11.6000",
            "3480.00",
            "8.5000",
            "2550.00",
            "2550.00"
          ],
          "rowNumber": 1833288,
          "rowPosition": 1833289,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78163\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1833289\" violates the foreign key: for \"id_contrato\": values \"78163\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44057",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "69417",
            "1",
            "80",
            "621",
            "21715",
            "174481",
            "381057",
            "78163",
            "1928",
            "1831306",
            "2994",
            "2081",
            "2022",
            "2022-10-28",
            "800.0000",
            "2.1600",
            "1728.00",
            "1.8700",
            "1496.00",
            "1496.00"
          ],
          "rowNumber": 1833290,
          "rowPosition": 1833291,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78163\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1833291\" violates the foreign key: for \"id_contrato\": values \"78163\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44427",
            "14",
            "1831102",
            "50",
            "1",
            "8",
            "66",
            "72800",
            "1",
            "77",
            "533",
            "9675",
            "91476",
            "382811",
            "46296",
            "889",
            "1831533",
            "2866",
            "2838",
            "2022",
            "2022-11-25",
            "0.0000",
            "4240.0000",
            "4240.00",
            "4240.0000",
            "4240.00",
            "0.00"
          ],
          "rowNumber": 1848751,
          "rowPosition": 1848752,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contratado\": values \"72800\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "message": "Row at position \"1848752\" violates the foreign key: for \"id_contratado\": values \"72800\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44427",
            "14",
            "1831102",
            "50",
            "1",
            "8",
            "66",
            "72800",
            "1",
            "77",
            "533",
            "9675",
            "91476",
            "382811",
            "46296",
            "889",
            "1831415",
            "2670",
            "2838",
            "2022",
            "2022-11-25",
            "0.0000",
            "4240.0000",
            "0.00",
            "0.0000",
            "0.00",
            "4240.00"
          ],
          "rowNumber": 1848752,
          "rowPosition": 1848753,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contratado\": values \"72800\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "message": "Row at position \"1848753\" violates the foreign key: for \"id_contratado\": values \"72800\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44432",
            "1",
            "1831096",
            "92",
            "1",
            "1",
            "876",
            "16674",
            "1",
            "39",
            "834",
            "21815",
            "383456",
            "382900",
            "78167",
            "889",
            "1831739",
            "3067",
            "2631",
            "2022",
            "2022-11-25",
            "0.0000",
            "1126020.3400",
            "1126020.34",
            "1126020.3400",
            "1126020.34",
            "1126020.34"
          ],
          "rowNumber": 1850915,
          "rowPosition": 1850916,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78167\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1850916\" violates the foreign key: for \"id_contrato\": values \"78167\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44432",
            "1",
            "1831096",
            "92",
            "1",
            "1",
            "876",
            "16674",
            "1",
            "39",
            "834",
            "21815",
            "383458",
            "382900",
            "78167",
            "889",
            "1831739",
            "3067",
            "2631",
            "2022",
            "2022-11-25",
            "0.0000",
            "119667.5400",
            "119667.54",
            "119667.5400",
            "119667.54",
            "119667.54"
          ],
          "rowNumber": 1850916,
          "rowPosition": 1850917,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78167\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1850917\" violates the foreign key: for \"id_contrato\": values \"78167\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43502",
            "4",
            "1831084",
            "81",
            "1",
            "1",
            "66",
            "57711",
            "1",
            "41",
            "806",
            "4360",
            "91237",
            "382947",
            "78156",
            "889",
            "1831347",
            "2594",
            "1859",
            "2022",
            "2022-11-25",
            "0.0000",
            "9743199.8400",
            "9743199.84",
            "6733485.1200",
            "6733485.12",
            "6733485.12"
          ],
          "rowNumber": 1850918,
          "rowPosition": 1850919,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78156\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1850919\" violates the foreign key: for \"id_contrato\": values \"78156\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43480",
            "13",
            "1831084",
            "81",
            "1",
            "1",
            "66",
            "66406",
            "1",
            "41",
            "806",
            "20217",
            "92543",
            "382787",
            "78179",
            "889",
            "1831347",
            "2741",
            "1859",
            "2022",
            "2022-11-25",
            "0.0000",
            "661721.4100",
            "661721.41",
            "522761.0300",
            "522761.03",
            "522761.03"
          ],
          "rowNumber": 1850919,
          "rowPosition": 1850920,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78179\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1850920\" violates the foreign key: for \"id_contrato\": values \"78179\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44038",
            "5",
            "1831018",
            "11",
            "1",
            "1",
            "66",
            "56240",
            "1",
            "77",
            "533",
            "1912",
            "92803",
            "382815",
            "78181",
            "889",
            "1831368",
            "2738",
            "2008",
            "2022",
            "2022-11-25",
            "0.0000",
            "7382490.8200",
            "7382490.82",
            "6259348.0000",
            "6259348.00",
            "6259348.00"
          ],
          "rowNumber": 1850920,
          "rowPosition": 1850921,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78181\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1850921\" violates the foreign key: for \"id_contrato\": values \"78181\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44434",
            "14",
            "1831020",
            "50",
            "1",
            "8",
            "66",
            "72808",
            "1",
            "77",
            "479",
            "7690",
            "391204",
            "382823",
            "46296",
            "889",
            "1831808",
            "2806",
            "2839",
            "2022",
            "2022-11-25",
            "0.0000",
            "1200.0000",
            "1200.00",
            "1200.0000",
            "1200.00",
            "1200.00"
          ],
          "rowNumber": 1851060,
          "rowPosition": 1851061,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contratado\": values \"72808\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "message": "Row at position \"1851061\" violates the foreign key: for \"id_contratado\": values \"72808\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43575",
            "4",
            "1831094",
            "95",
            "2",
            "1",
            "66",
            "67504",
            "1",
            "77",
            "700",
            "20243",
            "92759",
            "382255",
            "78176",
            "889",
            "1831747",
            "2954",
            "3043",
            "2022",
            "2022-11-21",
            "0.0000",
            "15970.0000",
            "15970.00",
            "15970.0000",
            "15970.00",
            "15970.00"
          ],
          "rowNumber": 1851857,
          "rowPosition": 1851858,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78176\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1851858\" violates the foreign key: for \"id_contrato\": values \"78176\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43575",
            "4",
            "1831094",
            "95",
            "2",
            "1",
            "66",
            "4826",
            "1",
            "51",
            "384",
            "14882",
            "130529",
            "382255",
            "78158",
            "889",
            "1831520",
            "2670",
            "3043",
            "2022",
            "2022-11-21",
            "0.0000",
            "10360.0000",
            "10360.00",
            "9900.0000",
            "9900.00",
            "9900.00"
          ],
          "rowNumber": 1851858,
          "rowPosition": 1851859,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78158\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1851859\" violates the foreign key: for \"id_contrato\": values \"78158\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43585",
            "2",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "242",
            "1",
            "77",
            "271",
            "1817",
            "93794",
            "381525",
            "78168",
            "889",
            "1831744",
            "2597",
            "3331",
            "2022",
            "2022-11-09",
            "0.0000",
            "9072.0000",
            "9072.00",
            "9072.0000",
            "9072.00",
            "9072.00"
          ],
          "rowNumber": 1852701,
          "rowPosition": 1852702,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78168\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1852702\" violates the foreign key: for \"id_contrato\": values \"78168\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43573",
            "4",
            "1831009",
            "1",
            "1",
            "1",
            "368",
            "71096",
            "1",
            "17",
            "379",
            "17564",
            "94354",
            "382053",
            "78159",
            "889",
            "1831370",
            "2594",
            "2413",
            "2022",
            "2022-11-17",
            "0.0000",
            "99964.0000",
            "99964.00",
            "99400.0000",
            "99400.00",
            "99400.00"
          ],
          "rowNumber": 1853494,
          "rowPosition": 1853495,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78159\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1853495\" violates the foreign key: for \"id_contrato\": values \"78159\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44432",
            "17",
            "1831094",
            "50",
            "1",
            "8",
            "66",
            "72807",
            "1",
            "73",
            "456",
            "3223",
            "154301",
            "382897",
            "46296",
            "889",
            "1831976",
            "2944",
            "3043",
            "2022",
            "2022-11-25",
            "100.0000",
            "134.0000",
            "13400.00",
            "134.0000",
            "13400.00",
            "13400.00"
          ],
          "rowNumber": 1857898,
          "rowPosition": 1857899,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contratado\": values \"72807\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "message": "Row at position \"1857899\" violates the foreign key: for \"id_contratado\": values \"72807\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44421",
            "15",
            "1831044",
            "96",
            "1",
            "1",
            "844",
            "31148",
            "1",
            "54",
            "502",
            "15252",
            "138494",
            "381879",
            "78154",
            "889",
            "1831296",
            "2944",
            "2633",
            "2022",
            "2022-11-14",
            "12.0000",
            "631.3800",
            "7576.56",
            "631.3800",
            "7576.56",
            "7576.56"
          ],
          "rowNumber": 1890189,
          "rowPosition": 1890190,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78154\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1890190\" violates the foreign key: for \"id_contrato\": values \"78154\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44419",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "22394",
            "1",
            "37",
            "544",
            "13338",
            "164277",
            "381628",
            "78162",
            "1292",
            "1831952",
            "2927",
            "3043",
            "2022",
            "2022-11-10",
            "13500.0000",
            "0.4000",
            "5400.00",
            "0.4000",
            "5400.00",
            "5400.00"
          ],
          "rowNumber": 1891677,
          "rowPosition": 1891678,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78162\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1891678\" violates the foreign key: for \"id_contrato\": values \"78162\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44419",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "23230",
            "1",
            "37",
            "142",
            "12146",
            "137476",
            "381689",
            "78170",
            "889",
            "1831952",
            "2927",
            "3043",
            "2022",
            "2022-11-10",
            "25.0000",
            "299.8300",
            "7495.75",
            "299.8300",
            "7495.75",
            "7495.75"
          ],
          "rowNumber": 1891680,
          "rowPosition": 1891681,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78170\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1891681\" violates the foreign key: for \"id_contrato\": values \"78170\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44419",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "22394",
            "1",
            "37",
            "142",
            "20473",
            "131534",
            "381689",
            "78161",
            "889",
            "1831952",
            "2927",
            "3043",
            "2022",
            "2022-11-10",
            "23.0000",
            "142.3600",
            "3274.28",
            "142.3600",
            "3274.28",
            "3274.28"
          ],
          "rowNumber": 1891681,
          "rowPosition": 1891682,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78161\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1891682\" violates the foreign key: for \"id_contrato\": values \"78161\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44419",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "23230",
            "1",
            "37",
            "142",
            "20473",
            "112582",
            "381689",
            "78170",
            "889",
            "1831952",
            "2927",
            "3043",
            "2022",
            "2022-11-10",
            "24.0000",
            "377.4700",
            "9059.28",
            "377.4700",
            "9059.28",
            "9059.28"
          ],
          "rowNumber": 1891682,
          "rowPosition": 1891683,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78170\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1891683\" violates the foreign key: for \"id_contrato\": values \"78170\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43562",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "19566",
            "1",
            "51",
            "810",
            "4980",
            "148762",
            "382527",
            "78153",
            "889",
            "1831356",
            "2599",
            "3043",
            "2022",
            "2022-11-23",
            "0.0000",
            "1650000.0000",
            "1650000.00",
            "1000000.0000",
            "1000000.00",
            "1000000.00"
          ],
          "rowNumber": 1893030,
          "rowPosition": 1893031,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78153\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1893031\" violates the foreign key: for \"id_contrato\": values \"78153\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43562",
            "4",
            "1831017",
            "95",
            "1",
            "1",
            "66",
            "19566",
            "1",
            "51",
            "810",
            "4980",
            "148762",
            "382532",
            "78153",
            "889",
            "1831356",
            "2599",
            "2842",
            "2022",
            "2022-11-23",
            "0.0000",
            "710000.0000",
            "710000.00",
            "450000.0000",
            "450000.00",
            "450000.00"
          ],
          "rowNumber": 1893050,
          "rowPosition": 1893051,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78153\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1893051\" violates the foreign key: for \"id_contrato\": values \"78153\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43562",
            "4",
            "1831019",
            "95",
            "1",
            "1",
            "66",
            "19566",
            "1",
            "51",
            "810",
            "4980",
            "148762",
            "382618",
            "78153",
            "889",
            "1831356",
            "2599",
            "2000",
            "2022",
            "2022-11-23",
            "0.0000",
            "2360000.0000",
            "2360000.00",
            "1450000.0000",
            "1450000.00",
            "1450000.00"
          ],
          "rowNumber": 1893051,
          "rowPosition": 1893052,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78153\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1893052\" violates the foreign key: for \"id_contrato\": values \"78153\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43544",
            "4",
            "1831044",
            "36",
            "1",
            "1",
            "551",
            "71812",
            "1",
            "69",
            "740",
            "13114",
            "147581",
            "382588",
            "78152",
            "1174",
            "1831312",
            "2538",
            "2633",
            "2022",
            "2022-11-23",
            "660.0000",
            "21.5000",
            "14187.36",
            "21.4000",
            "14124.00",
            "14124.00"
          ],
          "rowNumber": 1895768,
          "rowPosition": 1895769,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78152\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1895769\" violates the foreign key: for \"id_contrato\": values \"78152\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44402",
            "4",
            "1831030",
            "27",
            "1",
            "1",
            "66",
            "72096",
            "5",
            "77",
            "480",
            "22057",
            "217883",
            "381863",
            "78166",
            "1729",
            "1831531",
            "2738",
            "2270",
            "2022",
            "2022-11-11",
            "0.0000",
            "9298.8000",
            "9298.80",
            "9298.8000",
            "9298.80",
            "9298.80"
          ],
          "rowNumber": 1896413,
          "rowPosition": 1896414,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78166\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1896414\" violates the foreign key: for \"id_contrato\": values \"78166\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43561",
            "4",
            "1831009",
            "1",
            "1",
            "1",
            "357",
            "72528",
            "1",
            "17",
            "379",
            "17564",
            "94354",
            "382149",
            "78157",
            "889",
            "1831449",
            "2594",
            "2413",
            "2022",
            "2022-11-18",
            "0.0000",
            "64508.9600",
            "64508.96",
            "64299.5600",
            "64299.56",
            "64299.56"
          ],
          "rowNumber": 1899638,
          "rowPosition": 1899639,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78157\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1899639\" violates the foreign key: for \"id_contrato\": values \"78157\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44433",
            "2",
            "1831083",
            "82",
            "1",
            "1",
            "824",
            "70144",
            "1",
            "9",
            "581",
            "12418",
            "93129",
            "382752",
            "78177",
            "322",
            "1831697",
            "2932",
            "2083",
            "2022",
            "2022-11-24",
            "0.0000",
            "72000.0000",
            "72000.00",
            "64128.0000",
            "64128.00",
            "64128.00"
          ],
          "rowNumber": 1900286,
          "rowPosition": 1900287,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78177\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1900287\" violates the foreign key: for \"id_contrato\": values \"78177\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44433",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "883",
            "33019",
            "1",
            "3",
            "627",
            "3013",
            "226208",
            "382751",
            "78180",
            "889",
            "1831295",
            "2611",
            "3043",
            "2022",
            "2022-11-24",
            "2.0000",
            "4921.1000",
            "9842.20",
            "4921.1000",
            "9842.20",
            "9842.20"
          ],
          "rowNumber": 1900289,
          "rowPosition": 1900290,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1900290\" violates the foreign key: for \"id_contrato\": values \"78180\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44433",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "883",
            "33019",
            "1",
            "3",
            "627",
            "3013",
            "226216",
            "382730",
            "78175",
            "889",
            "1831295",
            "2611",
            "3043",
            "2022",
            "2022-11-24",
            "9.0000",
            "4217.5700",
            "37958.13",
            "4217.5700",
            "37958.13",
            "37958.13"
          ],
          "rowNumber": 1900290,
          "rowPosition": 1900291,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78175\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1900291\" violates the foreign key: for \"id_contrato\": values \"78175\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44433",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "883",
            "33019",
            "1",
            "3",
            "627",
            "3013",
            "226208",
            "382729",
            "78173",
            "889",
            "1831295",
            "2611",
            "3043",
            "2022",
            "2022-11-24",
            "20.0000",
            "4921.1000",
            "98422.00",
            "4921.1000",
            "98422.00",
            "98422.00"
          ],
          "rowNumber": 1900291,
          "rowPosition": 1900292,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78173\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1900292\" violates the foreign key: for \"id_contrato\": values \"78173\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44433",
            "17",
            "1831044",
            "36",
            "1",
            "1",
            "883",
            "33019",
            "1",
            "3",
            "627",
            "3013",
            "226208",
            "382712",
            "78178",
            "889",
            "1831295",
            "2611",
            "2633",
            "2022",
            "2022-11-24",
            "52.0000",
            "4921.1000",
            "255897.20",
            "4921.1000",
            "255897.20",
            "255897.20"
          ],
          "rowNumber": 1900295,
          "rowPosition": 1900296,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78178\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1900296\" violates the foreign key: for \"id_contrato\": values \"78178\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44403",
            "14",
            "1831095",
            "96",
            "1",
            "1",
            "821",
            "57105",
            "1",
            "8",
            "687",
            "22461",
            "289950",
            "382388",
            "78174",
            "1729",
            "1831044",
            "2883",
            "2210",
            "2022",
            "2022-11-22",
            "0.0000",
            "13200.0000",
            "13200.00",
            "13200.0000",
            "13200.00",
            "13200.00"
          ],
          "rowNumber": 1901966,
          "rowPosition": 1901967,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78174\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1901967\" violates the foreign key: for \"id_contrato\": values \"78174\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44403",
            "14",
            "1831095",
            "96",
            "1",
            "1",
            "389",
            "57105",
            "1",
            "8",
            "687",
            "22461",
            "289950",
            "382388",
            "78174",
            "1729",
            "1831044",
            "2883",
            "2210",
            "2022",
            "2022-11-22",
            "0.0000",
            "19800.0000",
            "19800.00",
            "19800.0000",
            "19800.00",
            "19800.00"
          ],
          "rowNumber": 1901967,
          "rowPosition": 1901968,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78174\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1901968\" violates the foreign key: for \"id_contrato\": values \"78174\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 58
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 58,
    "tasks": 1
  },
  "valid": false
}