{
  "version": "4.38.0",
  "time": 412.33,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_compras",
        "title": "Compras",
        "path": "data/ft_compras.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_tempo",
              "title": "Tempo - Chave",
              "type": "integer",
              "format": "default",
              "description": "- > \n  Chave estrangeira (Foreign Key) que aponta para a Chave Primária (Primary keys) da tabela dm_tempo_diario. \n  Ou seja, por meio dessa chave é possível identificar a data completa a qual o dado se refere.\n\n  Nota: \n  No site dados.mg.gov.br a tabela dm_tempo_diario pode ser encontrada no recurso Calendários - Dias \n  de cada conjunto.\n",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_procedimento",
              "title": "Procedimento de Contratação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_demanda",
              "title": "Órgão Demandante - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_contrato",
              "title": "Órgão do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_proc",
              "title": "Situação do Processo de Compra - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_cont",
              "title": "Situação do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_municipio",
              "title": "Município - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contratado",
              "title": "Contratado - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_tipo_licitacao",
              "title": "Tipo de Licitação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_grupo_matserv",
              "title": "Grupo Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_classe_matserv",
              "title": "Classe Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_material_servico",
              "title": "Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item_matserv",
              "title": "Item Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_processo",
              "title": "Processo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contrato",
              "title": "Número do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_medida",
              "title": "Unidade de Medida - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_linha_fornec",
              "title": "Linha de Fornecimento - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_orc",
              "title": "Unidade Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "unique": false
              }
            },
            {
              "name": "ano_particao",
              "title": "Ano Partição",
              "type": "year",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true
              }
            },
            {
              "name": "dt_item_homologa",
              "title": "Data da Homologação do Item",
              "type": "date",
              "format": "default",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "qt_item_pedido",
              "title": "Item do Pedido - Quantidade",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_referencia",
              "title": "Valor Unitário de Referência",
              "description": "Valor unitário estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_referencia",
              "title": "Valor de Referência",
              "description": "Valor estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_homologado",
              "title": "Valor Unitário Homologado",
              "description": "Valor unitário final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_homologado",
              "title": "Valor Homologado",
              "description": "Valor final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_atualizado",
              "title": "Valor Atualizado",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_processo"
              ],
              "reference": {
                "fields": [
                  "id_processo"
                ],
                "resource": "dm_processo"
              }
            },
            {
              "fields": [
                "id_situacao_cont"
              ],
              "reference": {
                "fields": [
                  "id_situacao_cont"
                ],
                "resource": "dm_situacao_cont"
              }
            },
            {
              "fields": [
                "id_situacao_proc"
              ],
              "reference": {
                "fields": [
                  "id_situacao_proc"
                ],
                "resource": "dm_situacao_proc"
              }
            },
            {
              "fields": [
                "id_linha_fornec"
              ],
              "reference": {
                "fields": [
                  "id_linha_fornec"
                ],
                "resource": "dm_linha_fornec"
              }
            },
            {
              "fields": [
                "id_classe_matserv"
              ],
              "reference": {
                "fields": [
                  "id_classe_matserv"
                ],
                "resource": "dm_classe_matserv"
              }
            },
            {
              "fields": [
                "id_tempo"
              ],
              "reference": {
                "fields": [
                  "id_tempo"
                ],
                "resource": "dm_tempo_diario"
              }
            },
            {
              "fields": [
                "id_municipio"
              ],
              "reference": {
                "fields": [
                  "id_municipio"
                ],
                "resource": "dm_municipio"
              }
            },
            {
              "fields": [
                "id_item_matserv"
              ],
              "reference": {
                "fields": [
                  "id_item_matserv"
                ],
                "resource": "dm_item_matserv"
              }
            },
            {
              "fields": [
                "id_tipo_licitacao"
              ],
              "reference": {
                "fields": [
                  "id_tipo_licitacao"
                ],
                "resource": "dm_tipo_licitacao"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_material_servico"
              ],
              "reference": {
                "fields": [
                  "id_material_servico"
                ],
                "resource": "dm_material_servico"
              }
            },
            {
              "fields": [
                "id_orgao_contrato"
              ],
              "reference": {
                "fields": [
                  "id_orgao_contrato"
                ],
                "resource": "dm_orgao_contrato"
              }
            },
            {
              "fields": [
                "id_contrato"
              ],
              "reference": {
                "fields": [
                  "id_contrato"
                ],
                "resource": "dm_contrato"
              }
            },
            {
              "fields": [
                "id_orgao_demanda"
              ],
              "reference": {
                "fields": [
                  "id_orgao_demanda"
                ],
                "resource": "dm_orgao_demanda"
              }
            },
            {
              "fields": [
                "id_unidade_medida"
              ],
              "reference": {
                "fields": [
                  "id_unidade_medida"
                ],
                "resource": "dm_unidade_medida"
              }
            },
            {
              "fields": [
                "id_grupo_matserv"
              ],
              "reference": {
                "fields": [
                  "id_grupo_matserv"
                ],
                "resource": "dm_grupo_matserv"
              }
            },
            {
              "fields": [
                "id_contratado"
              ],
              "reference": {
                "fields": [
                  "id_contratado"
                ],
                "resource": "dm_contratado"
              }
            },
            {
              "fields": [
                "id_procedimento"
              ],
              "reference": {
                "fields": [
                  "id_procedimento"
                ],
                "resource": "dm_procedimento"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_compras"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "8c10db2ec2e6a7bdb0f32937485c1056",
          "bytes": 58185767,
          "fields": 27,
          "rows": 1909233
        }
      },
      "time": 412.33,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "43558",
            "4",
            "1831044",
            "36",
            "1",
            "1",
            "501",
            "68152",
            "1",
            "51",
            "384",
            "1875",
            "120955",
            "383735",
            "78464",
            "889",
            "1831520",
            "2670",
            "2633",
            "2022",
            "2022-12-07",
            "0.0000",
            "17582.5400",
            "17582.54",
            "9460.0000",
            "9460.00",
            "9460.00"
          ],
          "rowNumber": 1813712,
          "rowPosition": 1813713,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78464\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813713\" violates the foreign key: for \"id_contrato\": values \"78464\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43558",
            "4",
            "1831044",
            "36",
            "1",
            "1",
            "501",
            "68152",
            "1",
            "30",
            "173",
            "1784",
            "147670",
            "383735",
            "78464",
            "889",
            "1831471",
            "2670",
            "2633",
            "2022",
            "2022-12-07",
            "0.0000",
            "286.4600",
            "286.46",
            "180.0000",
            "180.00",
            "180.00"
          ],
          "rowNumber": 1813713,
          "rowPosition": 1813714,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78464\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813714\" violates the foreign key: for \"id_contrato\": values \"78464\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43558",
            "4",
            "1831044",
            "36",
            "1",
            "1",
            "501",
            "68152",
            "1",
            "30",
            "173",
            "1784",
            "93268",
            "383735",
            "78464",
            "889",
            "1831471",
            "2670",
            "2633",
            "2022",
            "2022-12-07",
            "2.0000",
            "1300.0000",
            "2600.00",
            "290.0000",
            "580.00",
            "580.00"
          ],
          "rowNumber": 1813714,
          "rowPosition": 1813715,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78464\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813715\" violates the foreign key: for \"id_contrato\": values \"78464\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43558",
            "4",
            "1831044",
            "36",
            "1",
            "1",
            "501",
            "68152",
            "1",
            "51",
            "384",
            "14882",
            "130529",
            "383735",
            "78464",
            "889",
            "1831520",
            "2670",
            "2633",
            "2022",
            "2022-12-07",
            "0.0000",
            "55722.0000",
            "55722.00",
            "30780.0000",
            "30780.00",
            "30780.00"
          ],
          "rowNumber": 1813715,
          "rowPosition": 1813716,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78464\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813716\" violates the foreign key: for \"id_contrato\": values \"78464\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44446",
            "1",
            "1831055",
            "51",
            "1",
            "1",
            "66",
            "38145",
            "1",
            "77",
            "479",
            "7690",
            "210306",
            "383755",
            "78451",
            "889",
            "1831808",
            "2602",
            "2523",
            "2022",
            "2022-12-07",
            "0.0000",
            "56000.0000",
            "56000.00",
            "56000.0000",
            "56000.00",
            "56000.00"
          ],
          "rowNumber": 1813716,
          "rowPosition": 1813717,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78451\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813717\" violates the foreign key: for \"id_contrato\": values \"78451\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43575",
            "4",
            "1831019",
            "10",
            "1",
            "1",
            "66",
            "4826",
            "1",
            "51",
            "384",
            "14882",
            "92447",
            "383724",
            "78465",
            "889",
            "1831520",
            "2670",
            "2000",
            "2022",
            "2022-12-07",
            "0.0000",
            "6500.0000",
            "6500.00",
            "6500.0000",
            "6500.00",
            "6500.00"
          ],
          "rowNumber": 1813720,
          "rowPosition": 1813721,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78465\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813721\" violates the foreign key: for \"id_contrato\": values \"78465\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43575",
            "4",
            "1831019",
            "10",
            "1",
            "1",
            "66",
            "62995",
            "1",
            "51",
            "384",
            "14882",
            "92447",
            "383724",
            "78437",
            "889",
            "1831520",
            "2670",
            "2000",
            "2022",
            "2022-12-07",
            "0.0000",
            "230380.0000",
            "230380.00",
            "68200.0000",
            "68200.00",
            "68200.00"
          ],
          "rowNumber": 1813721,
          "rowPosition": 1813722,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78437\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813722\" violates the foreign key: for \"id_contrato\": values \"78437\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44432",
            "2",
            "1831097",
            "98",
            "1",
            "1",
            "66",
            "23393",
            "1",
            "39",
            "834",
            "21966",
            "387007",
            "383566",
            "78462",
            "889",
            "1831739",
            "3067",
            "2078",
            "2022",
            "2022-12-05",
            "0.0000",
            "145327.6400",
            "145327.64",
            "145327.6400",
            "145327.64",
            "145327.64"
          ],
          "rowNumber": 1818349,
          "rowPosition": 1818350,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78462\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1818350\" violates the foreign key: for \"id_contrato\": values \"78462\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43568",
            "4",
            "1831019",
            "10",
            "1",
            "1",
            "66",
            "71812",
            "1",
            "69",
            "740",
            "13114",
            "147581",
            "383696",
            "78447",
            "1174",
            "1831312",
            "2538",
            "2000",
            "2022",
            "2022-12-07",
            "2000.0000",
            "25.5300",
            "51054.20",
            "19.9000",
            "39800.00",
            "39800.00"
          ],
          "rowNumber": 1818940,
          "rowPosition": 1818941,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78447\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1818941\" violates the foreign key: for \"id_contrato\": values \"78447\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44403",
            "1",
            "1831096",
            "92",
            "1",
            "1",
            "876",
            "16276",
            "1",
            "51",
            "80",
            "20153",
            "158725",
            "384216",
            "78450",
            "889",
            "1831507",
            "2670",
            "2631",
            "2022",
            "2022-12-14",
            "0.0000",
            "3324631.5100",
            "3324631.51",
            "3324631.5100",
            "3324631.51",
            "3324631.51"
          ],
          "rowNumber": 1819557,
          "rowPosition": 1819558,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78450\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1819558\" violates the foreign key: for \"id_contrato\": values \"78450\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44403",
            "1",
            "1831096",
            "92",
            "1",
            "1",
            "876",
            "16276",
            "1",
            "39",
            "130",
            "21730",
            "386059",
            "384216",
            "78450",
            "889",
            "1831805",
            "3067",
            "2631",
            "2022",
            "2022-12-14",
            "0.0000",
            "1022528.7100",
            "1022528.71",
            "1022528.7100",
            "1022528.71",
            "1022528.71"
          ],
          "rowNumber": 1819558,
          "rowPosition": 1819559,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78450\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1819559\" violates the foreign key: for \"id_contrato\": values \"78450\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44403",
            "1",
            "1831096",
            "92",
            "1",
            "1",
            "876",
            "16276",
            "1",
            "39",
            "130",
            "21730",
            "386054",
            "384216",
            "78450",
            "889",
            "1831805",
            "3067",
            "2631",
            "2022",
            "2022-12-14",
            "0.0000",
            "1079879.9600",
            "1079879.96",
            "1079879.9600",
            "1079879.96",
            "1079879.96"
          ],
          "rowNumber": 1819559,
          "rowPosition": 1819560,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78450\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1819560\" violates the foreign key: for \"id_contrato\": values \"78450\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43572",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "72161",
            "1",
            "77",
            "808",
            "4383",
            "145722",
            "383786",
            "78440",
            "889",
            "1831737",
            "2869",
            "1760",
            "2022",
            "2022-12-07",
            "0.0000",
            "376921.0800",
            "376921.08",
            "348998.4000",
            "348998.40",
            "348998.40"
          ],
          "rowNumber": 1819612,
          "rowPosition": 1819613,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78440\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1819613\" violates the foreign key: for \"id_contrato\": values \"78440\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43565",
            "4",
            "1831095",
            "96",
            "1",
            "1",
            "824",
            "34107",
            "1",
            "77",
            "808",
            "4383",
            "199499",
            "383554",
            "78456",
            "889",
            "1831737",
            "2869",
            "3293",
            "2022",
            "2022-12-05",
            "0.0000",
            "13289169.1000",
            "13289169.10",
            "9067497.0600",
            "9067497.06",
            "9067497.06"
          ],
          "rowNumber": 1820305,
          "rowPosition": 1820306,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78456\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1820306\" violates the foreign key: for \"id_contrato\": values \"78456\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44427",
            "2",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "18805",
            "1",
            "80",
            "308",
            "8586",
            "142850",
            "383557",
            "78449",
            "889",
            "1831306",
            "2994",
            "3331",
            "2022",
            "2022-12-05",
            "3000.0000",
            "0.9500",
            "2850.00",
            "0.9500",
            "2850.00",
            "2850.00"
          ],
          "rowNumber": 1820308,
          "rowPosition": 1820309,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78449\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1820309\" violates the foreign key: for \"id_contrato\": values \"78449\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44451",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "23230",
            "1",
            "37",
            "544",
            "10256",
            "164207",
            "383962",
            "78443",
            "1292",
            "1831952",
            "2927",
            "3043",
            "2022",
            "2022-12-12",
            "2700.0000",
            "1.3600",
            "3667.68",
            "1.3600",
            "3667.68",
            "3667.68"
          ],
          "rowNumber": 1820444,
          "rowPosition": 1820445,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78443\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1820445\" violates the foreign key: for \"id_contrato\": values \"78443\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44451",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "23230",
            "1",
            "37",
            "544",
            "13338",
            "164188",
            "383962",
            "78443",
            "1292",
            "1831952",
            "2927",
            "3043",
            "2022",
            "2022-12-12",
            "1300.0000",
            "0.9000",
            "1170.00",
            "0.9000",
            "1170.00",
            "1170.00"
          ],
          "rowNumber": 1820446,
          "rowPosition": 1820447,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78443\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1820447\" violates the foreign key: for \"id_contrato\": values \"78443\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44451",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "23230",
            "1",
            "37",
            "17",
            "13232",
            "148162",
            "383913",
            "78435",
            "889",
            "1831952",
            "2927",
            "3043",
            "2022",
            "2022-12-12",
            "346.0000",
            "32.2600",
            "11161.96",
            "32.2600",
            "11161.96",
            "11161.96"
          ],
          "rowNumber": 1820447,
          "rowPosition": 1820448,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78435\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1820448\" violates the foreign key: for \"id_contrato\": values \"78435\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44451",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "23230",
            "1",
            "37",
            "142",
            "12146",
            "137476",
            "383913",
            "78435",
            "889",
            "1831952",
            "2927",
            "3043",
            "2022",
            "2022-12-12",
            "15.0000",
            "299.8300",
            "4497.45",
            "299.8300",
            "4497.45",
            "4497.45"
          ],
          "rowNumber": 1820448,
          "rowPosition": 1820449,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78435\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1820449\" violates the foreign key: for \"id_contrato\": values \"78435\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44451",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "23230",
            "1",
            "37",
            "142",
            "20473",
            "112582",
            "383913",
            "78435",
            "889",
            "1831952",
            "2927",
            "3043",
            "2022",
            "2022-12-12",
            "6.0000",
            "377.4700",
            "2264.82",
            "377.4700",
            "2264.82",
            "2264.82"
          ],
          "rowNumber": 1820449,
          "rowPosition": 1820450,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78435\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1820450\" violates the foreign key: for \"id_contrato\": values \"78435\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44451",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "23230",
            "1",
            "37",
            "17",
            "13232",
            "139833",
            "383913",
            "78435",
            "889",
            "1831952",
            "2927",
            "3043",
            "2022",
            "2022-12-12",
            "50.0000",
            "32.2600",
            "1613.00",
            "32.2600",
            "1613.00",
            "1613.00"
          ],
          "rowNumber": 1820450,
          "rowPosition": 1820451,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78435\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1820451\" violates the foreign key: for \"id_contrato\": values \"78435\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44427",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "615",
            "26931",
            "1",
            "17",
            "379",
            "17564",
            "94354",
            "383854",
            "78442",
            "1968",
            "1831449",
            "2594",
            "3043",
            "2022",
            "2022-12-09",
            "0.0000",
            "75831.7000",
            "75831.70",
            "39310.8500",
            "39310.85",
            "39310.85"
          ],
          "rowNumber": 1820531,
          "rowPosition": 1820532,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78442\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1820532\" violates the foreign key: for \"id_contrato\": values \"78442\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44427",
            "2",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "18805",
            "1",
            "80",
            "308",
            "5792",
            "376204",
            "383557",
            "78449",
            "889",
            "1831306",
            "2994",
            "3331",
            "2022",
            "2022-12-05",
            "3000.0000",
            "1.2500",
            "3750.00",
            "1.2500",
            "3750.00",
            "3750.00"
          ],
          "rowNumber": 1820815,
          "rowPosition": 1820816,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78449\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1820816\" violates the foreign key: for \"id_contrato\": values \"78449\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44427",
            "2",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "18805",
            "1",
            "80",
            "308",
            "8586",
            "142851",
            "383557",
            "78449",
            "889",
            "1831306",
            "2994",
            "3331",
            "2022",
            "2022-12-05",
            "3000.0000",
            "3.0600",
            "9180.00",
            "3.0600",
            "9180.00",
            "9180.00"
          ],
          "rowNumber": 1820816,
          "rowPosition": 1820817,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78449\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1820817\" violates the foreign key: for \"id_contrato\": values \"78449\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44427",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "615",
            "26931",
            "1",
            "17",
            "379",
            "17564",
            "94354",
            "383854",
            "78442",
            "1968",
            "1831449",
            "2594",
            "3043",
            "2022",
            "2022-12-09",
            "0.0000",
            "248520.1700",
            "248520.17",
            "161563.4700",
            "161563.47",
            "161563.47"
          ],
          "rowNumber": 1821040,
          "rowPosition": 1821041,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78442\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1821041\" violates the foreign key: for \"id_contrato\": values \"78442\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43529",
            "1",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "35083",
            "1",
            "77",
            "808",
            "12309",
            "91623",
            "384068",
            "78448",
            "889",
            "1831741",
            "2902",
            "2925",
            "2022",
            "2022-12-13",
            "0.0000",
            "820741.0700",
            "820741.07",
            "820741.0700",
            "820741.07",
            "820741.07"
          ],
          "rowNumber": 1821050,
          "rowPosition": 1821051,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78448\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1821051\" violates the foreign key: for \"id_contrato\": values \"78448\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43485",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "59703",
            "1",
            "58",
            "732",
            "10561",
            "48111",
            "383054",
            "78463",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-11-29",
            "3100.0000",
            "2.8000",
            "8680.00",
            "1.4200",
            "4402.00",
            "4402.00"
          ],
          "rowNumber": 1821266,
          "rowPosition": 1821267,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78463\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1821267\" violates the foreign key: for \"id_contrato\": values \"78463\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43485",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "59703",
            "1",
            "58",
            "732",
            "10561",
            "165642",
            "383054",
            "78463",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-11-29",
            "2500.0000",
            "4.6000",
            "11500.00",
            "1.9300",
            "4825.00",
            "4825.00"
          ],
          "rowNumber": 1821267,
          "rowPosition": 1821268,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78463\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1821268\" violates the foreign key: for \"id_contrato\": values \"78463\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43485",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "59703",
            "1",
            "58",
            "732",
            "10561",
            "41315",
            "383054",
            "78463",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-11-29",
            "8500.0000",
            "3.9000",
            "33150.00",
            "2.4200",
            "20570.00",
            "20570.00"
          ],
          "rowNumber": 1821268,
          "rowPosition": 1821269,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78463\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1821269\" violates the foreign key: for \"id_contrato\": values \"78463\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43485",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "59703",
            "1",
            "58",
            "735",
            "5584",
            "7247",
            "383054",
            "78463",
            "916",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-11-29",
            "5.0000",
            "201.6400",
            "1008.20",
            "201.6400",
            "1008.20",
            "1008.20"
          ],
          "rowNumber": 1821269,
          "rowPosition": 1821270,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78463\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1821270\" violates the foreign key: for \"id_contrato\": values \"78463\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43485",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "59703",
            "1",
            "58",
            "732",
            "10561",
            "126326",
            "383054",
            "78463",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-11-29",
            "30000.0000",
            "0.9300",
            "27900.00",
            "0.3500",
            "10500.00",
            "10500.00"
          ],
          "rowNumber": 1821271,
          "rowPosition": 1821272,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78463\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1821272\" violates the foreign key: for \"id_contrato\": values \"78463\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43485",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "19086",
            "1",
            "58",
            "732",
            "10561",
            "109070",
            "383054",
            "78459",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-11-29",
            "200.0000",
            "5.5000",
            "1100.00",
            "3.0000",
            "600.00",
            "600.00"
          ],
          "rowNumber": 1821272,
          "rowPosition": 1821273,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78459\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1821273\" violates the foreign key: for \"id_contrato\": values \"78459\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43485",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "21260",
            "1",
            "58",
            "732",
            "10561",
            "96026",
            "383054",
            "78444",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-11-29",
            "500.0000",
            "0.8200",
            "410.00",
            "0.8200",
            "410.00",
            "410.00"
          ],
          "rowNumber": 1821273,
          "rowPosition": 1821274,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78444\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1821274\" violates the foreign key: for \"id_contrato\": values \"78444\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43485",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "21260",
            "1",
            "58",
            "732",
            "6103",
            "106765",
            "383054",
            "78444",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-11-29",
            "4.0000",
            "442.0000",
            "1768.00",
            "442.0000",
            "1768.00",
            "1768.00"
          ],
          "rowNumber": 1821274,
          "rowPosition": 1821275,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78444\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1821275\" violates the foreign key: for \"id_contrato\": values \"78444\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43485",
            "4",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "59703",
            "1",
            "58",
            "732",
            "7439",
            "130322",
            "383054",
            "78463",
            "889",
            "1831373",
            "2796",
            "3331",
            "2022",
            "2022-11-29",
            "10.0000",
            "50.0000",
            "500.00",
            "50.0000",
            "500.00",
            "500.00"
          ],
          "rowNumber": 1821275,
          "rowPosition": 1821276,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78463\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1821276\" violates the foreign key: for \"id_contrato\": values \"78463\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43485",
            "4",
            "1831017",
            "99",
            "1",
            "1",
            "66",
            "59703",
            "1",
            "58",
            "732",
            "10561",
            "48111",
            "383157",
            "78463",
            "889",
            "1831373",
            "2796",
            "2842",
            "2022",
            "2022-11-29",
            "20000.0000",
            "2.8000",
            "56000.00",
            "1.4200",
            "28400.00",
            "28400.00"
          ],
          "rowNumber": 1821851,
          "rowPosition": 1821852,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78463\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1821852\" violates the foreign key: for \"id_contrato\": values \"78463\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43485",
            "4",
            "1831017",
            "99",
            "1",
            "1",
            "66",
            "59703",
            "1",
            "58",
            "732",
            "10561",
            "41315",
            "383157",
            "78463",
            "889",
            "1831373",
            "2796",
            "2842",
            "2022",
            "2022-11-29",
            "14000.0000",
            "3.9000",
            "54600.00",
            "2.4200",
            "33880.00",
            "33880.00"
          ],
          "rowNumber": 1821852,
          "rowPosition": 1821853,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78463\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1821853\" violates the foreign key: for \"id_contrato\": values \"78463\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43485",
            "4",
            "1831017",
            "99",
            "1",
            "1",
            "66",
            "59703",
            "1",
            "58",
            "732",
            "10561",
            "126326",
            "383157",
            "78463",
            "889",
            "1831373",
            "2796",
            "2842",
            "2022",
            "2022-11-29",
            "18000.0000",
            "0.9300",
            "16740.00",
            "0.3500",
            "6300.00",
            "6300.00"
          ],
          "rowNumber": 1821853,
          "rowPosition": 1821854,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78463\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1821854\" violates the foreign key: for \"id_contrato\": values \"78463\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43485",
            "4",
            "1831017",
            "99",
            "1",
            "1",
            "66",
            "19086",
            "1",
            "58",
            "732",
            "10561",
            "165643",
            "383157",
            "78459",
            "889",
            "1831373",
            "2796",
            "2842",
            "2022",
            "2022-11-29",
            "2000.0000",
            "5.3000",
            "10600.00",
            "2.2900",
            "4580.00",
            "4580.00"
          ],
          "rowNumber": 1821854,
          "rowPosition": 1821855,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78459\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1821855\" violates the foreign key: for \"id_contrato\": values \"78459\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43485",
            "4",
            "1831017",
            "99",
            "1",
            "1",
            "66",
            "59703",
            "1",
            "58",
            "732",
            "13966",
            "239760",
            "383157",
            "78463",
            "889",
            "1831373",
            "2796",
            "2842",
            "2022",
            "2022-11-29",
            "50000.0000",
            "0.1000",
            "5000.00",
            "0.1000",
            "5000.00",
            "5000.00"
          ],
          "rowNumber": 1821855,
          "rowPosition": 1821856,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78463\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1821856\" violates the foreign key: for \"id_contrato\": values \"78463\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43529",
            "1",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "35083",
            "1",
            "77",
            "808",
            "12309",
            "91623",
            "384068",
            "78448",
            "889",
            "1831741",
            "2902",
            "2925",
            "2022",
            "2022-12-13",
            "0.0000",
            "494261.5200",
            "494261.52",
            "494261.5200",
            "494261.52",
            "494261.52"
          ],
          "rowNumber": 1822203,
          "rowPosition": 1822204,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78448\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1822204\" violates the foreign key: for \"id_contrato\": values \"78448\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43575",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "33325",
            "1",
            "41",
            "806",
            "14879",
            "92391",
            "382255",
            "78438",
            "889",
            "1831346",
            "2891",
            "3043",
            "2022",
            "2022-12-06",
            "0.0000",
            "71920.0000",
            "71920.00",
            "59900.0000",
            "59900.00",
            "59900.00"
          ],
          "rowNumber": 1852453,
          "rowPosition": 1852454,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78438\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1852454\" violates the foreign key: for \"id_contrato\": values \"78438\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44445",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "876",
            "68447",
            "1",
            "3",
            "627",
            "16158",
            "147571",
            "383673",
            "78452",
            "889",
            "1831295",
            "2611",
            "3043",
            "2022",
            "2022-12-06",
            "1.0000",
            "1227.0000",
            "1227.00",
            "1227.0000",
            "1227.00",
            "1227.00"
          ],
          "rowNumber": 1852488,
          "rowPosition": 1852489,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78452\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1852489\" violates the foreign key: for \"id_contrato\": values \"78452\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43563",
            "13",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "72840",
            "1",
            "17",
            "185",
            "20222",
            "92554",
            "383300",
            "78454",
            "889",
            "1831370",
            "2816",
            "3043",
            "2022",
            "2022-12-01",
            "0.0000",
            "100013.6000",
            "100013.60",
            "100013.6000",
            "100013.60",
            "100013.60"
          ],
          "rowNumber": 1852809,
          "rowPosition": 1852810,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78454\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1852810\" violates the foreign key: for \"id_contrato\": values \"78454\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44419",
            "13",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "72840",
            "1",
            "17",
            "185",
            "20222",
            "92554",
            "383595",
            "78446",
            "889",
            "1831370",
            "2816",
            "3043",
            "2022",
            "2022-12-06",
            "0.0000",
            "691348.5200",
            "691348.52",
            "691348.5200",
            "691348.52",
            "691348.52"
          ],
          "rowNumber": 1853120,
          "rowPosition": 1853121,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78446\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1853121\" violates the foreign key: for \"id_contrato\": values \"78446\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44434",
            "15",
            "1831081",
            "77",
            "1",
            "1",
            "883",
            "67898",
            "1",
            "77",
            "73",
            "14768",
            "101321",
            "382769",
            "78436",
            "889",
            "1831763",
            "3068",
            "2014",
            "2022",
            "2022-11-25",
            "750000.0000",
            "0.0500",
            "37500.00",
            "0.0500",
            "37500.00",
            "37500.00"
          ],
          "rowNumber": 1853195,
          "rowPosition": 1853196,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78436\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1853196\" violates the foreign key: for \"id_contrato\": values \"78436\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44434",
            "15",
            "1831081",
            "77",
            "1",
            "1",
            "883",
            "67898",
            "1",
            "77",
            "73",
            "14768",
            "101321",
            "382769",
            "78436",
            "889",
            "1831763",
            "3068",
            "4077",
            "2022",
            "2022-11-25",
            "750000.0000",
            "0.0500",
            "37500.00",
            "0.0500",
            "37500.00",
            "37500.00"
          ],
          "rowNumber": 1853196,
          "rowPosition": 1853197,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78436\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1853197\" violates the foreign key: for \"id_contrato\": values \"78436\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44437",
            "1",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "17936",
            "1",
            "42",
            "104",
            "17102",
            "384584",
            "383606",
            "78445",
            "889",
            "1831334",
            "2813",
            "3043",
            "2022",
            "2022-12-06",
            "1.0000",
            "127100.0000",
            "127100.00",
            "127100.0000",
            "127100.00",
            "127100.00"
          ],
          "rowNumber": 1853385,
          "rowPosition": 1853386,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78445\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1853386\" violates the foreign key: for \"id_contrato\": values \"78445\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44437",
            "1",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "17936",
            "1",
            "42",
            "104",
            "16076",
            "385201",
            "383606",
            "78445",
            "889",
            "1831334",
            "2813",
            "3043",
            "2022",
            "2022-12-06",
            "1.0000",
            "137760.0000",
            "137760.00",
            "137760.0000",
            "137760.00",
            "137760.00"
          ],
          "rowNumber": 1853386,
          "rowPosition": 1853387,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78445\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1853387\" violates the foreign key: for \"id_contrato\": values \"78445\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44437",
            "1",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "17936",
            "1",
            "42",
            "107",
            "14305",
            "383221",
            "383606",
            "78445",
            "889",
            "1831334",
            "2995",
            "3043",
            "2022",
            "2022-12-06",
            "2.0000",
            "3936.0000",
            "7872.00",
            "3936.0000",
            "7872.00",
            "7872.00"
          ],
          "rowNumber": 1853388,
          "rowPosition": 1853389,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78445\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1853389\" violates the foreign key: for \"id_contrato\": values \"78445\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44437",
            "1",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "17936",
            "1",
            "42",
            "104",
            "1040",
            "171765",
            "383606",
            "78445",
            "889",
            "1831334",
            "2813",
            "3043",
            "2022",
            "2022-12-06",
            "1.0000",
            "117096.0000",
            "117096.00",
            "117096.0000",
            "117096.00",
            "117096.00"
          ],
          "rowNumber": 1853389,
          "rowPosition": 1853390,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78445\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1853390\" violates the foreign key: for \"id_contrato\": values \"78445\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44437",
            "1",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "17936",
            "1",
            "42",
            "104",
            "17103",
            "202913",
            "383606",
            "78445",
            "889",
            "1831334",
            "2813",
            "3043",
            "2022",
            "2022-12-06",
            "3.0000",
            "77408.0000",
            "232224.00",
            "77408.0000",
            "232224.00",
            "232224.00"
          ],
          "rowNumber": 1853390,
          "rowPosition": 1853391,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78445\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1853391\" violates the foreign key: for \"id_contrato\": values \"78445\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44437",
            "1",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "17936",
            "1",
            "42",
            "104",
            "1040",
            "384581",
            "383606",
            "78445",
            "889",
            "1831334",
            "2813",
            "3043",
            "2022",
            "2022-12-06",
            "1.0000",
            "117096.0000",
            "117096.00",
            "117096.0000",
            "117096.00",
            "117096.00"
          ],
          "rowNumber": 1853391,
          "rowPosition": 1853392,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78445\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1853392\" violates the foreign key: for \"id_contrato\": values \"78445\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43528",
            "4",
            "1831081",
            "77",
            "1",
            "1",
            "66",
            "18817",
            "1",
            "42",
            "399",
            "14488",
            "123011",
            "382891",
            "78458",
            "889",
            "1831334",
            "2923",
            "2014",
            "2022",
            "2022-11-25",
            "60.0000",
            "807.7800",
            "48466.80",
            "520.0000",
            "31200.00",
            "31200.00"
          ],
          "rowNumber": 1854104,
          "rowPosition": 1854105,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78458\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1854105\" violates the foreign key: for \"id_contrato\": values \"78458\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43528",
            "4",
            "1831081",
            "77",
            "1",
            "1",
            "66",
            "18679",
            "1",
            "42",
            "399",
            "514",
            "61656",
            "382891",
            "78453",
            "889",
            "1831334",
            "2923",
            "2014",
            "2022",
            "2022-11-25",
            "60.0000",
            "42.0000",
            "2520.00",
            "42.0000",
            "2520.00",
            "2520.00"
          ],
          "rowNumber": 1854105,
          "rowPosition": 1854106,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78453\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1854106\" violates the foreign key: for \"id_contrato\": values \"78453\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43528",
            "4",
            "1831081",
            "77",
            "1",
            "1",
            "66",
            "14350",
            "1",
            "42",
            "399",
            "3861",
            "131216",
            "382891",
            "78455",
            "889",
            "1831334",
            "2923",
            "2014",
            "2022",
            "2022-11-25",
            "340.0000",
            "108.6800",
            "36949.50",
            "85.1700",
            "28957.80",
            "28957.80"
          ],
          "rowNumber": 1854106,
          "rowPosition": 1854107,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78455\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1854107\" violates the foreign key: for \"id_contrato\": values \"78455\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43556",
            "4",
            "1831095",
            "96",
            "1",
            "1",
            "569",
            "17300",
            "1",
            "77",
            "808",
            "4383",
            "199499",
            "383170",
            "78457",
            "889",
            "1831737",
            "2869",
            "3293",
            "2022",
            "2022-11-30",
            "0.0000",
            "1229642.8800",
            "1229642.88",
            "1099809.6000",
            "1099809.60",
            "1099809.60"
          ],
          "rowNumber": 1863190,
          "rowPosition": 1863191,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78457\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1863191\" violates the foreign key: for \"id_contrato\": values \"78457\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43572",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "58476",
            "1",
            "8",
            "687",
            "12333",
            "92275",
            "383265",
            "78439",
            "889",
            "1831347",
            "2970",
            "1760",
            "2022",
            "2022-12-01",
            "0.0000",
            "818699.5000",
            "818699.50",
            "529000.0000",
            "529000.00",
            "529000.00"
          ],
          "rowNumber": 1863869,
          "rowPosition": 1863870,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78439\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1863870\" violates the foreign key: for \"id_contrato\": values \"78439\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43548",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "58460",
            "1",
            "42",
            "104",
            "16113",
            "7521",
            "383844",
            "78461",
            "889",
            "1831221",
            "2813",
            "2081",
            "2022",
            "2022-12-09",
            "8.0000",
            "278.4500",
            "2227.60",
            "225.0000",
            "1800.00",
            "1800.00"
          ],
          "rowNumber": 1865089,
          "rowPosition": 1865090,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78461\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1865090\" violates the foreign key: for \"id_contrato\": values \"78461\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44419",
            "14",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "67729",
            "1",
            "77",
            "533",
            "6925",
            "91288",
            "381646",
            "78460",
            "889",
            "1831522",
            "2807",
            "1760",
            "2022",
            "2022-11-10",
            "0.0000",
            "17000.0000",
            "17000.00",
            "17000.0000",
            "17000.00",
            "17000.00"
          ],
          "rowNumber": 1896720,
          "rowPosition": 1896721,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78460\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1896721\" violates the foreign key: for \"id_contrato\": values \"78460\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43548",
            "4",
            "1831016",
            "16",
            "1",
            "1",
            "206",
            "36522",
            "1",
            "58",
            "732",
            "10561",
            "100005",
            "382419",
            "78441",
            "371",
            "1831373",
            "2796",
            "2082",
            "2022",
            "2022-11-22",
            "12.0000",
            "280.0000",
            "3360.00",
            "104.1600",
            "1249.92",
            "1249.92"
          ],
          "rowNumber": 1907680,
          "rowPosition": 1907681,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78441\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1907681\" violates the foreign key: for \"id_contrato\": values \"78441\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 61
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 61,
    "tasks": 1
  },
  "valid": false
}