{
  "version": "4.38.0",
  "time": 413.605,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_compras",
        "title": "Compras",
        "path": "data/ft_compras.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_tempo",
              "title": "Tempo - Chave",
              "type": "integer",
              "format": "default",
              "description": "- > \n  Chave estrangeira (Foreign Key) que aponta para a Chave Primária (Primary keys) da tabela dm_tempo_diario. \n  Ou seja, por meio dessa chave é possível identificar a data completa a qual o dado se refere.\n\n  Nota: \n  No site dados.mg.gov.br a tabela dm_tempo_diario pode ser encontrada no recurso Calendários - Dias \n  de cada conjunto.\n",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_procedimento",
              "title": "Procedimento de Contratação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_demanda",
              "title": "Órgão Demandante - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_contrato",
              "title": "Órgão do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_proc",
              "title": "Situação do Processo de Compra - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_cont",
              "title": "Situação do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_municipio",
              "title": "Município - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contratado",
              "title": "Contratado - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_tipo_licitacao",
              "title": "Tipo de Licitação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_grupo_matserv",
              "title": "Grupo Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_classe_matserv",
              "title": "Classe Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_material_servico",
              "title": "Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item_matserv",
              "title": "Item Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_processo",
              "title": "Processo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contrato",
              "title": "Número do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_medida",
              "title": "Unidade de Medida - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_linha_fornec",
              "title": "Linha de Fornecimento - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_orc",
              "title": "Unidade Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "unique": false
              }
            },
            {
              "name": "ano_particao",
              "title": "Ano Partição",
              "type": "year",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true
              }
            },
            {
              "name": "dt_item_homologa",
              "title": "Data da Homologação do Item",
              "type": "date",
              "format": "default",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "qt_item_pedido",
              "title": "Item do Pedido - Quantidade",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_referencia",
              "title": "Valor Unitário de Referência",
              "description": "Valor unitário estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_referencia",
              "title": "Valor de Referência",
              "description": "Valor estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_homologado",
              "title": "Valor Unitário Homologado",
              "description": "Valor unitário final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_homologado",
              "title": "Valor Homologado",
              "description": "Valor final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_atualizado",
              "title": "Valor Atualizado",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_processo"
              ],
              "reference": {
                "fields": [
                  "id_processo"
                ],
                "resource": "dm_processo"
              }
            },
            {
              "fields": [
                "id_situacao_cont"
              ],
              "reference": {
                "fields": [
                  "id_situacao_cont"
                ],
                "resource": "dm_situacao_cont"
              }
            },
            {
              "fields": [
                "id_situacao_proc"
              ],
              "reference": {
                "fields": [
                  "id_situacao_proc"
                ],
                "resource": "dm_situacao_proc"
              }
            },
            {
              "fields": [
                "id_linha_fornec"
              ],
              "reference": {
                "fields": [
                  "id_linha_fornec"
                ],
                "resource": "dm_linha_fornec"
              }
            },
            {
              "fields": [
                "id_classe_matserv"
              ],
              "reference": {
                "fields": [
                  "id_classe_matserv"
                ],
                "resource": "dm_classe_matserv"
              }
            },
            {
              "fields": [
                "id_tempo"
              ],
              "reference": {
                "fields": [
                  "id_tempo"
                ],
                "resource": "dm_tempo_diario"
              }
            },
            {
              "fields": [
                "id_municipio"
              ],
              "reference": {
                "fields": [
                  "id_municipio"
                ],
                "resource": "dm_municipio"
              }
            },
            {
              "fields": [
                "id_item_matserv"
              ],
              "reference": {
                "fields": [
                  "id_item_matserv"
                ],
                "resource": "dm_item_matserv"
              }
            },
            {
              "fields": [
                "id_tipo_licitacao"
              ],
              "reference": {
                "fields": [
                  "id_tipo_licitacao"
                ],
                "resource": "dm_tipo_licitacao"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_material_servico"
              ],
              "reference": {
                "fields": [
                  "id_material_servico"
                ],
                "resource": "dm_material_servico"
              }
            },
            {
              "fields": [
                "id_orgao_contrato"
              ],
              "reference": {
                "fields": [
                  "id_orgao_contrato"
                ],
                "resource": "dm_orgao_contrato"
              }
            },
            {
              "fields": [
                "id_contrato"
              ],
              "reference": {
                "fields": [
                  "id_contrato"
                ],
                "resource": "dm_contrato"
              }
            },
            {
              "fields": [
                "id_orgao_demanda"
              ],
              "reference": {
                "fields": [
                  "id_orgao_demanda"
                ],
                "resource": "dm_orgao_demanda"
              }
            },
            {
              "fields": [
                "id_unidade_medida"
              ],
              "reference": {
                "fields": [
                  "id_unidade_medida"
                ],
                "resource": "dm_unidade_medida"
              }
            },
            {
              "fields": [
                "id_grupo_matserv"
              ],
              "reference": {
                "fields": [
                  "id_grupo_matserv"
                ],
                "resource": "dm_grupo_matserv"
              }
            },
            {
              "fields": [
                "id_contratado"
              ],
              "reference": {
                "fields": [
                  "id_contratado"
                ],
                "resource": "dm_contratado"
              }
            },
            {
              "fields": [
                "id_procedimento"
              ],
              "reference": {
                "fields": [
                  "id_procedimento"
                ],
                "resource": "dm_procedimento"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_compras"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "328579fc341278e9727afc718f1e14eb",
          "bytes": 58439146,
          "fields": 27,
          "rows": 1918305
        }
      },
      "time": 413.605,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "44040",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "72299",
            "1",
            "51",
            "383",
            "17638",
            "358000",
            "385029",
            "79160",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-12-23",
            "0.0000",
            "3375599.2800",
            "3375599.28",
            "1275050.6400",
            "1275050.64",
            "1275050.64"
          ],
          "rowNumber": 1812897,
          "rowPosition": 1812898,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812898\" violates the foreign key: for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44040",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "72299",
            "1",
            "51",
            "383",
            "17638",
            "358001",
            "385029",
            "79160",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-12-23",
            "0.0000",
            "350513.6800",
            "350513.67",
            "619117.3800",
            "619117.38",
            "619117.38"
          ],
          "rowNumber": 1812898,
          "rowPosition": 1812899,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812899\" violates the foreign key: for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44040",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "72299",
            "1",
            "51",
            "383",
            "17638",
            "358000",
            "385029",
            "79160",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-12-23",
            "0.0000",
            "807041.4000",
            "807041.40",
            "318762.7200",
            "318762.72",
            "318762.72"
          ],
          "rowNumber": 1812926,
          "rowPosition": 1812927,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812927\" violates the foreign key: for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44040",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "72299",
            "1",
            "51",
            "383",
            "17638",
            "358001",
            "385029",
            "79160",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-12-23",
            "0.0000",
            "354501.8700",
            "354501.86",
            "13146.4000",
            "13146.40",
            "13146.40"
          ],
          "rowNumber": 1812927,
          "rowPosition": 1812928,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812928\" violates the foreign key: for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44040",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "72299",
            "1",
            "51",
            "383",
            "17638",
            "358000",
            "385029",
            "79160",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-12-23",
            "0.0000",
            "2183635.9200",
            "2183635.92",
            "1275050.6400",
            "1275050.64",
            "1275050.64"
          ],
          "rowNumber": 1812928,
          "rowPosition": 1812929,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812929\" violates the foreign key: for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44040",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "72299",
            "1",
            "51",
            "383",
            "17638",
            "358001",
            "385029",
            "79160",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-12-23",
            "0.0000",
            "295959.9900",
            "295959.99",
            "272152.6000",
            "272152.60",
            "272152.60"
          ],
          "rowNumber": 1812929,
          "rowPosition": 1812930,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812930\" violates the foreign key: for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44040",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "72299",
            "1",
            "51",
            "383",
            "17638",
            "358000",
            "385029",
            "79160",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-12-23",
            "0.0000",
            "81864.7200",
            "81864.72",
            "63752.4000",
            "63752.40",
            "63752.40"
          ],
          "rowNumber": 1812934,
          "rowPosition": 1812935,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812935\" violates the foreign key: for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44040",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "72299",
            "1",
            "51",
            "383",
            "17638",
            "358001",
            "385029",
            "79160",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-12-23",
            "0.0000",
            "12506.1000",
            "12506.10",
            "11500.0000",
            "11500.00",
            "11500.00"
          ],
          "rowNumber": 1812935,
          "rowPosition": 1812936,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812936\" violates the foreign key: for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44040",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "72299",
            "1",
            "51",
            "383",
            "17638",
            "358000",
            "385029",
            "79160",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-12-23",
            "0.0000",
            "1184690.6100",
            "1184690.60",
            "637525.2000",
            "637525.20",
            "637525.20"
          ],
          "rowNumber": 1812937,
          "rowPosition": 1812938,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812938\" violates the foreign key: for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44040",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "72299",
            "1",
            "51",
            "383",
            "17638",
            "358001",
            "385029",
            "79160",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-12-23",
            "0.0000",
            "13960.3700",
            "13960.37",
            "49406.8800",
            "49406.88",
            "49406.88"
          ],
          "rowNumber": 1812938,
          "rowPosition": 1812939,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812939\" violates the foreign key: for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44446",
            "17",
            "1831044",
            "36",
            "1",
            "1",
            "883",
            "24687",
            "1",
            "17",
            "379",
            "17564",
            "246594",
            "384174",
            "79156",
            "889",
            "1831449",
            "2594",
            "2633",
            "2022",
            "2022-12-14",
            "0.0000",
            "187473.6000",
            "187473.60",
            "187473.6000",
            "187473.60",
            "187473.60"
          ],
          "rowNumber": 1816363,
          "rowPosition": 1816364,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79156\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1816364\" violates the foreign key: for \"id_contrato\": values \"79156\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43547",
            "4",
            "1831081",
            "77",
            "1",
            "1",
            "66",
            "55817",
            "1",
            "42",
            "399",
            "10482",
            "115252",
            "384602",
            "79155",
            "1729",
            "1831334",
            "2923",
            "2014",
            "2022",
            "2022-12-20",
            "12.0000",
            "12500.0000",
            "150000.00",
            "9200.0000",
            "110400.00",
            "110400.00"
          ],
          "rowNumber": 1825077,
          "rowPosition": 1825078,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79155\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1825078\" violates the foreign key: for \"id_contrato\": values \"79155\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43547",
            "4",
            "1831081",
            "77",
            "1",
            "1",
            "66",
            "55817",
            "1",
            "42",
            "399",
            "10482",
            "124139",
            "384602",
            "79155",
            "1729",
            "1831334",
            "2923",
            "2014",
            "2022",
            "2022-12-20",
            "24.0000",
            "48900.0000",
            "1173600.00",
            "42900.0000",
            "1029600.00",
            "1029600.00"
          ],
          "rowNumber": 1825078,
          "rowPosition": 1825079,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79155\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1825079\" violates the foreign key: for \"id_contrato\": values \"79155\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44040",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "72299",
            "1",
            "51",
            "383",
            "17638",
            "358000",
            "385029",
            "79160",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-12-23",
            "0.0000",
            "304386.2400",
            "304386.24",
            "63752.4000",
            "63752.40",
            "63752.40"
          ],
          "rowNumber": 1826367,
          "rowPosition": 1826368,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1826368\" violates the foreign key: for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44040",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "72299",
            "1",
            "51",
            "383",
            "17638",
            "358001",
            "385029",
            "79160",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-12-23",
            "0.0000",
            "12506.1000",
            "12506.10",
            "11500.0000",
            "11500.00",
            "11500.00"
          ],
          "rowNumber": 1826368,
          "rowPosition": 1826369,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1826369\" violates the foreign key: for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44040",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "72299",
            "1",
            "51",
            "383",
            "17638",
            "358000",
            "385029",
            "79160",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-12-23",
            "0.0000",
            "64174.8000",
            "64174.80",
            "63752.4000",
            "63752.40",
            "63752.40"
          ],
          "rowNumber": 1826370,
          "rowPosition": 1826371,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1826371\" violates the foreign key: for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44040",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "72299",
            "1",
            "51",
            "383",
            "17638",
            "358001",
            "385029",
            "79160",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-12-23",
            "0.0000",
            "12506.1000",
            "12506.10",
            "11500.0000",
            "11500.00",
            "11500.00"
          ],
          "rowNumber": 1826371,
          "rowPosition": 1826372,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1826372\" violates the foreign key: for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44040",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "72299",
            "1",
            "51",
            "383",
            "17638",
            "358000",
            "385029",
            "79160",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-12-23",
            "0.0000",
            "409324.0800",
            "409324.08",
            "63753.1200",
            "63753.12",
            "63753.12"
          ],
          "rowNumber": 1826372,
          "rowPosition": 1826373,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1826373\" violates the foreign key: for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44040",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "72299",
            "1",
            "51",
            "383",
            "17638",
            "358001",
            "385029",
            "79160",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-12-23",
            "0.0000",
            "40186.5900",
            "40186.58",
            "36954.1000",
            "36954.10",
            "36954.10"
          ],
          "rowNumber": 1826373,
          "rowPosition": 1826374,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1826374\" violates the foreign key: for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43551",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "37781",
            "1",
            "30",
            "173",
            "14875",
            "94067",
            "385061",
            "79153",
            "889",
            "1831355",
            "2594",
            "2925",
            "2022",
            "2022-12-23",
            "0.0000",
            "1179916.2100",
            "1179916.21",
            "1137439.2300",
            "1137439.23",
            "1137439.23"
          ],
          "rowNumber": 1826374,
          "rowPosition": 1826375,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79153\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1826375\" violates the foreign key: for \"id_contrato\": values \"79153\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44040",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "72299",
            "1",
            "51",
            "383",
            "17638",
            "358000",
            "385029",
            "79160",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-12-23",
            "0.0000",
            "705518.6200",
            "705518.62",
            "454683.3600",
            "454683.36",
            "454683.36"
          ],
          "rowNumber": 1826375,
          "rowPosition": 1826376,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1826376\" violates the foreign key: for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44040",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "72299",
            "1",
            "51",
            "383",
            "17638",
            "358001",
            "385029",
            "79160",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-12-23",
            "0.0000",
            "33302.4800",
            "33302.48",
            "30623.5800",
            "30623.58",
            "30623.58"
          ],
          "rowNumber": 1826376,
          "rowPosition": 1826377,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1826377\" violates the foreign key: for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44040",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "72299",
            "1",
            "51",
            "383",
            "17638",
            "358000",
            "385029",
            "79160",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-12-23",
            "0.0000",
            "1911981.9300",
            "1911981.93",
            "844411.9200",
            "844411.92",
            "844411.92"
          ],
          "rowNumber": 1826381,
          "rowPosition": 1826382,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1826382\" violates the foreign key: for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44040",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "72299",
            "1",
            "51",
            "383",
            "17638",
            "358001",
            "385029",
            "79160",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-12-23",
            "0.0000",
            "314586.6300",
            "314586.63",
            "289280.9200",
            "289280.92",
            "289280.92"
          ],
          "rowNumber": 1826382,
          "rowPosition": 1826383,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1826383\" violates the foreign key: for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43514",
            "14",
            "1831081",
            "77",
            "1",
            "1",
            "66",
            "31399",
            "1",
            "26",
            "170",
            "8339",
            "106947",
            "376851",
            "79157",
            "1883",
            "1831313",
            "2923",
            "2014",
            "2022",
            "2022-09-02",
            "240.0000",
            "24.5000",
            "5880.00",
            "20.0000",
            "4800.00",
            "4800.00"
          ],
          "rowNumber": 1907512,
          "rowPosition": 1907513,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79157\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1907513\" violates the foreign key: for \"id_contrato\": values \"79157\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43578",
            "4",
            "1831016",
            "16",
            "1",
            "1",
            "66",
            "27591",
            "1",
            "9",
            "576",
            "6977",
            "92610",
            "382248",
            "79159",
            "889",
            "1831498",
            "2736",
            "2082",
            "2022",
            "2022-11-19",
            "0.0000",
            "1103760.0000",
            "1103760.00",
            "662400.0000",
            "662400.00",
            "662400.00"
          ],
          "rowNumber": 1910868,
          "rowPosition": 1910869,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79159\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1910869\" violates the foreign key: for \"id_contrato\": values \"79159\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44434",
            "1",
            "1831034",
            "50",
            "1",
            "8",
            "66",
            "73283",
            "1",
            "77",
            "187",
            "20450",
            "110021",
            "386042",
            "46296",
            "889",
            "1831904",
            "3144",
            "1760",
            "2022",
            "2023-01-09",
            "0.0000",
            "7200.0000",
            "7200.00",
            "7200.0000",
            "7200.00",
            "7200.00"
          ],
          "rowNumber": 1913550,
          "rowPosition": 1913551,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contratado\": values \"73283\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "message": "Row at position \"1913551\" violates the foreign key: for \"id_contratado\": values \"73283\" not found in the lookup table \"dm_contratado\" as \"id_contratado\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43555",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "58681",
            "1",
            "18",
            "506",
            "21741",
            "175920",
            "385188",
            "79154",
            "1071",
            "1831311",
            "2994",
            "2081",
            "2022",
            "2022-12-26",
            "500.0000",
            "2.9000",
            "1450.00",
            "2.8000",
            "1400.00",
            "1400.00"
          ],
          "rowNumber": 1915270,
          "rowPosition": 1915271,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79154\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1915271\" violates the foreign key: for \"id_contrato\": values \"79154\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44460",
            "2",
            "1831030",
            "27",
            "1",
            "1",
            "560",
            "60238",
            "1",
            "9",
            "581",
            "12418",
            "93129",
            "385855",
            "79158",
            "322",
            "1831697",
            "2932",
            "2270",
            "2022",
            "2022-12-30",
            "0.0000",
            "384000.0000",
            "384000.00",
            "384000.0000",
            "384000.00",
            "384000.00"
          ],
          "rowNumber": 1916591,
          "rowPosition": 1916592,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79158\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916592\" violates the foreign key: for \"id_contrato\": values \"79158\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44040",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "72299",
            "1",
            "51",
            "383",
            "17638",
            "358000",
            "385029",
            "79160",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-12-23",
            "0.0000",
            "38504.8800",
            "38504.88",
            "63752.4000",
            "63752.40",
            "63752.40"
          ],
          "rowNumber": 1918213,
          "rowPosition": 1918214,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918214\" violates the foreign key: for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44040",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "72299",
            "1",
            "51",
            "383",
            "17638",
            "358001",
            "385029",
            "79160",
            "889",
            "1831360",
            "2670",
            "2925",
            "2022",
            "2022-12-23",
            "0.0000",
            "12506.1000",
            "12506.10",
            "11500.0000",
            "11500.00",
            "11500.00"
          ],
          "rowNumber": 1918214,
          "rowPosition": 1918215,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1918215\" violates the foreign key: for \"id_contrato\": values \"79160\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 31
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 31,
    "tasks": 1
  },
  "valid": false
}