{
  "version": "4.38.0",
  "time": 506.013,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_despesa_2022",
        "title": "Despesa 2022",
        "path": "data/ft_despesa_2022.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_tempo",
              "title": "Tempo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "description": "- > \n  Chave estrangeira (Foreign Key) que aponta para a Chave Primária (Primary keys) da tabela dm_tempo_diario. \n  Ou seja, por meio dessa chave é possível identificar a data completa a qual o dado se refere.\n\n  Nota: \n  No site dados.mg.gov.br a tabela dm_tempo_diario pode ser encontrada no recurso Calendários - Dias \n  de cada conjunto.\n",
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_categ_econ",
              "title": "Categoria Econômica da Despesa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_grupo",
              "title": "Grupo de Despesa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_elemento",
              "title": "Elemento de Despesa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item de Despesa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_fonte",
              "title": "Fonte de Recurso - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_modalidade_aplic",
              "title": "Modalidade de Aplicação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_funcao",
              "title": "Função - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_subfuncao",
              "title": "Subfunção - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_programa",
              "title": "Programa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_acao",
              "title": "Ação Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_procedencia",
              "title": "Procedência - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_orc",
              "title": "Unidade Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_favorecido",
              "title": "Favorecido - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_empenho",
              "title": "Número do Empenho - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_tipo_documento",
              "title": "Tipo de Documento - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "tp_operacao",
              "title": "Tipo Operação - Chave Origem",
              "type": "string",
              "format": "default",
              "constraints": {
                "enum": [
                  "1",
                  "2"
                ]
              }
            },
            {
              "name": "cd_documento",
              "title": "Documento - Código",
              "type": "string",
              "format": "default",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "cd_evento",
              "title": "Evento - Código",
              "type": "string",
              "format": "default",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "dt_anomes",
              "title": "Ano e Mês",
              "type": "string",
              "format": "default",
              "bareNumber": true,
              "notes": [
                "O tipo yearmonth somente aceita representação YYYY-MM (ie. com hífen)"
              ]
            },
            {
              "name": "ano_particao",
              "title": "Ano Partição",
              "type": "year",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_empenhado",
              "title": "Valor Empenhado",
              "description": "Valor do orçamento reservado para fazer face a compromisso formalmente assumido com fornecedor ou credor.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_liquidado",
              "title": "Valor Liquidado",
              "description": "Valor que o fornecedor ou credor tem direito a receber referente a produto ou serviço devidamente entregue ou prestado.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_pago",
              "title": "Valor Pago",
              "description": "- > \nValor referente aos pagamentos efetuados através de movimentações bancárias, escriturais e apropriação contábil da\ndespesa. O efetivo pagamento pode estar pendente de transmissão ao banco e/ou sujeito a compensação bancária.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_unidade_orc"
              ],
              "reference": {
                "fields": [
                  "id_unidade_orc"
                ],
                "resource": "dm_unidade_orc"
              }
            },
            {
              "fields": [
                "id_tipo_documento"
              ],
              "reference": {
                "fields": [
                  "id_tipo_documento"
                ],
                "resource": "dm_tipo_documento"
              }
            },
            {
              "fields": [
                "id_programa"
              ],
              "reference": {
                "fields": [
                  "id_programa"
                ],
                "resource": "dm_programa"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_categ_econ"
              ],
              "reference": {
                "fields": [
                  "id_categ_econ"
                ],
                "resource": "dm_categ_econ"
              }
            },
            {
              "fields": [
                "id_grupo"
              ],
              "reference": {
                "fields": [
                  "id_grupo"
                ],
                "resource": "dm_grupo_desp"
              }
            },
            {
              "fields": [
                "id_funcao"
              ],
              "reference": {
                "fields": [
                  "id_funcao"
                ],
                "resource": "dm_funcao_desp"
              }
            },
            {
              "fields": [
                "id_empenho"
              ],
              "reference": {
                "fields": [
                  "id_empenho"
                ],
                "resource": "dm_empenho_desp_2022"
              }
            },
            {
              "fields": [
                "id_tempo"
              ],
              "reference": {
                "fields": [
                  "id_tempo"
                ],
                "resource": "dm_tempo_diario"
              }
            },
            {
              "fields": [
                "id_subfuncao"
              ],
              "reference": {
                "fields": [
                  "id_subfuncao"
                ],
                "resource": "dm_subfuncao_desp"
              }
            },
            {
              "fields": [
                "id_acao"
              ],
              "reference": {
                "fields": [
                  "id_acao"
                ],
                "resource": "dm_acao"
              }
            },
            {
              "fields": [
                "id_modalidade_aplic"
              ],
              "reference": {
                "fields": [
                  "id_modalidade_aplic"
                ],
                "resource": "dm_modalidade_aplic"
              }
            },
            {
              "fields": [
                "id_procedencia"
              ],
              "reference": {
                "fields": [
                  "id_procedencia"
                ],
                "resource": "dm_procedencia"
              }
            },
            {
              "fields": [
                "id_elemento"
              ],
              "reference": {
                "fields": [
                  "id_elemento"
                ],
                "resource": "dm_elemento_desp"
              }
            },
            {
              "fields": [
                "id_fonte"
              ],
              "reference": {
                "fields": [
                  "id_fonte"
                ],
                "resource": "dm_fonte"
              }
            },
            {
              "fields": [
                "id_favorecido"
              ],
              "reference": {
                "fields": [
                  "id_favorecido"
                ],
                "resource": "dm_favorecido"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_despesa_2022"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "9fbb707058b100a16b85254d36cede49",
          "bytes": 46374024,
          "fields": 24,
          "rows": 2930348
        }
      },
      "time": 506.013,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "44468",
            "20",
            "42",
            "466",
            "3174",
            "58",
            "130",
            "1950",
            "3940",
            "14390",
            "56496",
            "93",
            "4247",
            "1622564",
            "13650256",
            "1",
            "2",
            "17",
            "502001",
            "202212",
            "2022",
            "550618035.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 2911128,
          "rowPosition": 2911129,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3174\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2911129\" violates the foreign key: for \"id_item\": values \"3174\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13650439",
            "510",
            "2",
            "1201",
            "503002",
            "202212",
            "2022",
            "0.00",
            "122372411.56",
            "0.00"
          ],
          "rowNumber": 2911129,
          "rowPosition": 2911130,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2911130\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13650439",
            "510",
            "2",
            "1200",
            "503002",
            "202212",
            "2022",
            "0.00",
            "141717767.98",
            "0.00"
          ],
          "rowNumber": 2911130,
          "rowPosition": 2911131,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2911131\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649519",
            "510",
            "2",
            "1186",
            "503002",
            "202212",
            "2022",
            "0.00",
            "288567224.00",
            "0.00"
          ],
          "rowNumber": 2911131,
          "rowPosition": 2911132,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2911132\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649357",
            "510",
            "2",
            "1187",
            "503002",
            "202212",
            "2022",
            "0.00",
            "17929597.39",
            "0.00"
          ],
          "rowNumber": 2911132,
          "rowPosition": 2911133,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2911133\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649519",
            "510",
            "2",
            "1191",
            "503002",
            "202212",
            "2022",
            "0.00",
            "292326771.39",
            "0.00"
          ],
          "rowNumber": 2911133,
          "rowPosition": 2911134,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2911134\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649519",
            "510",
            "2",
            "1189",
            "503002",
            "202212",
            "2022",
            "0.00",
            "290204740.57",
            "0.00"
          ],
          "rowNumber": 2911134,
          "rowPosition": 2911135,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2911135\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649519",
            "510",
            "2",
            "1193",
            "503002",
            "202212",
            "2022",
            "0.00",
            "293773547.13",
            "0.00"
          ],
          "rowNumber": 2911135,
          "rowPosition": 2911136,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2911136\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13650439",
            "510",
            "2",
            "1198",
            "503002",
            "202212",
            "2022",
            "0.00",
            "121004368.26",
            "0.00"
          ],
          "rowNumber": 2911136,
          "rowPosition": 2911137,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2911137\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649519",
            "558",
            "2",
            "1011",
            "504001",
            "202212",
            "2022",
            "290204740.57",
            "0.00",
            "0.00"
          ],
          "rowNumber": 2911137,
          "rowPosition": 2911138,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2911138\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649519",
            "558",
            "2",
            "1013",
            "504001",
            "202212",
            "2022",
            "292326771.39",
            "0.00",
            "0.00"
          ],
          "rowNumber": 2911138,
          "rowPosition": 2911139,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2911139\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649519",
            "558",
            "2",
            "1015",
            "504001",
            "202212",
            "2022",
            "293773547.13",
            "0.00",
            "0.00"
          ],
          "rowNumber": 2911139,
          "rowPosition": 2911140,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2911140\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13650439",
            "558",
            "2",
            "1017",
            "504001",
            "202212",
            "2022",
            "121717767.98",
            "0.00",
            "0.00"
          ],
          "rowNumber": 2911140,
          "rowPosition": 2911141,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2911141\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13650439",
            "558",
            "2",
            "1019",
            "504001",
            "202212",
            "2022",
            "122372411.56",
            "0.00",
            "0.00"
          ],
          "rowNumber": 2911141,
          "rowPosition": 2911142,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2911142\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13650439",
            "566",
            "2",
            "347",
            "537003",
            "202212",
            "2022",
            "0.00",
            "-20000000.00",
            "0.00"
          ],
          "rowNumber": 2911142,
          "rowPosition": 2911143,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2911143\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649519",
            "1",
            "2",
            "168",
            "502001",
            "202212",
            "2022",
            "288567224.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 2911143,
          "rowPosition": 2911144,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2911144\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13650439",
            "1",
            "2",
            "170",
            "502001",
            "202212",
            "2022",
            "121004368.26",
            "0.00",
            "0.00"
          ],
          "rowNumber": 2911857,
          "rowPosition": 2911858,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2911858\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "20",
            "46",
            "478",
            "3178",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649357",
            "1",
            "2",
            "171",
            "502001",
            "202212",
            "2022",
            "17929597.39",
            "0.00",
            "0.00"
          ],
          "rowNumber": 2911858,
          "rowPosition": 2911859,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2911859\" violates the foreign key: for \"id_item\": values \"3178\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "20",
            "42",
            "520",
            "3175",
            "44",
            "140",
            "1953",
            "3976",
            "14390",
            "56685",
            "93",
            "4247",
            "1202650",
            "13650414",
            "1",
            "2",
            "18",
            "502001",
            "202212",
            "2022",
            "591291191.59",
            "0.00",
            "0.00"
          ],
          "rowNumber": 2911859,
          "rowPosition": 2911860,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3175\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2911860\" violates the foreign key: for \"id_item\": values \"3175\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "21",
            "48",
            "496",
            "3176",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13650143",
            "510",
            "2",
            "1195",
            "503006",
            "202212",
            "2022",
            "0.00",
            "53371345.52",
            "0.00"
          ],
          "rowNumber": 2911860,
          "rowPosition": 2911861,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2911861\" violates the foreign key: for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "21",
            "48",
            "496",
            "3176",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649858",
            "510",
            "2",
            "1188",
            "503006",
            "202212",
            "2022",
            "0.00",
            "163273486.32",
            "0.00"
          ],
          "rowNumber": 2911861,
          "rowPosition": 2911862,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2911862\" violates the foreign key: for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "21",
            "48",
            "496",
            "3176",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649858",
            "510",
            "2",
            "1190",
            "503006",
            "202212",
            "2022",
            "0.00",
            "165352507.00",
            "0.00"
          ],
          "rowNumber": 2911862,
          "rowPosition": 2911863,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2911863\" violates the foreign key: for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "21",
            "48",
            "496",
            "3176",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649858",
            "510",
            "2",
            "1192",
            "503006",
            "202212",
            "2022",
            "0.00",
            "167012530.77",
            "0.00"
          ],
          "rowNumber": 2911863,
          "rowPosition": 2911864,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2911864\" violates the foreign key: for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "21",
            "48",
            "496",
            "3176",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13650143",
            "510",
            "2",
            "1194",
            "503006",
            "202212",
            "2022",
            "0.00",
            "52805332.03",
            "0.00"
          ],
          "rowNumber": 2911864,
          "rowPosition": 2911865,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2911865\" violates the foreign key: for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "21",
            "48",
            "496",
            "3176",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13650143",
            "510",
            "2",
            "1196",
            "503006",
            "202212",
            "2022",
            "0.00",
            "53916062.37",
            "0.00"
          ],
          "rowNumber": 2911865,
          "rowPosition": 2911866,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2911866\" violates the foreign key: for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "21",
            "48",
            "496",
            "3176",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649858",
            "510",
            "2",
            "1185",
            "503006",
            "202212",
            "2022",
            "0.00",
            "161537074.04",
            "0.00"
          ],
          "rowNumber": 2911866,
          "rowPosition": 2911867,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2911867\" violates the foreign key: for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "21",
            "48",
            "496",
            "3176",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649858",
            "558",
            "2",
            "1010",
            "504001",
            "202212",
            "2022",
            "163273486.32",
            "0.00",
            "0.00"
          ],
          "rowNumber": 2911867,
          "rowPosition": 2911868,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2911868\" violates the foreign key: for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "21",
            "48",
            "496",
            "3176",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649858",
            "558",
            "2",
            "1012",
            "504001",
            "202212",
            "2022",
            "165352507.00",
            "0.00",
            "0.00"
          ],
          "rowNumber": 2911868,
          "rowPosition": 2911869,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2911869\" violates the foreign key: for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "21",
            "48",
            "496",
            "3176",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649858",
            "558",
            "2",
            "1014",
            "504001",
            "202212",
            "2022",
            "167012530.77",
            "0.00",
            "0.00"
          ],
          "rowNumber": 2911869,
          "rowPosition": 2911870,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2911870\" violates the foreign key: for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "21",
            "48",
            "496",
            "3176",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13650143",
            "558",
            "2",
            "1016",
            "504001",
            "202212",
            "2022",
            "53371345.52",
            "0.00",
            "0.00"
          ],
          "rowNumber": 2911870,
          "rowPosition": 2911871,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2911871\" violates the foreign key: for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "21",
            "48",
            "496",
            "3176",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13650143",
            "558",
            "2",
            "1018",
            "504001",
            "202212",
            "2022",
            "53916062.37",
            "0.00",
            "0.00"
          ],
          "rowNumber": 2911871,
          "rowPosition": 2911872,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2911872\" violates the foreign key: for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "21",
            "48",
            "496",
            "3176",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13649858",
            "1",
            "2",
            "167",
            "502001",
            "202212",
            "2022",
            "161537074.04",
            "0.00",
            "0.00"
          ],
          "rowNumber": 2911872,
          "rowPosition": 2911873,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2911873\" violates the foreign key: for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44468",
            "21",
            "48",
            "496",
            "3176",
            "58",
            "130",
            "1953",
            "3939",
            "14390",
            "56305",
            "93",
            "4249",
            "1622564",
            "13650143",
            "1",
            "2",
            "169",
            "502001",
            "202212",
            "2022",
            "52805332.03",
            "0.00",
            "0.00"
          ],
          "rowNumber": 2911873,
          "rowPosition": 2911874,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "message": "Row at position \"2911874\" violates the foreign key: for \"id_item\": values \"3176\" not found in the lookup table \"dm_item_desp\" as \"id_item\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 33
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 33,
    "tasks": 1
  },
  "valid": false
}