{
  "version": "4.16.6",
  "time": 289.822,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_despesa_2023",
        "title": "Despesa 2023",
        "path": "data/ft_despesa_2023.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_tempo",
              "title": "Tempo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "description": "- > \n  Chave estrangeira (Foreign Key) que aponta para a Chave Primária (Primary keys) da tabela dm_tempo_diario. \n  Ou seja, por meio dessa chave é possível identificar a data completa a qual o dado se refere.\n\n  Nota: \n  No site dados.mg.gov.br a tabela dm_tempo_diario pode ser encontrada no recurso Calendários - Dias \n  de cada conjunto.\n",
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_categ_econ",
              "title": "Categoria Econômica da Despesa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_grupo",
              "title": "Grupo de Despesa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_elemento",
              "title": "Elemento de Despesa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item de Despesa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_fonte",
              "title": "Fonte de Recurso - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_modalidade_aplic",
              "title": "Modalidade de Aplicação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_funcao",
              "title": "Função - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_subfuncao",
              "title": "Subfunção - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_programa",
              "title": "Programa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_acao",
              "title": "Ação Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_procedencia",
              "title": "Procedência - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_orc",
              "title": "Unidade Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_favorecido",
              "title": "Favorecido - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_empenho",
              "title": "Número do Empenho - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_tipo_documento",
              "title": "Tipo de Documento - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "tp_operacao",
              "title": "Tipo Operação - Chave Origem",
              "type": "string",
              "format": "default",
              "constraints": {
                "enum": [
                  "1",
                  "2"
                ]
              }
            },
            {
              "name": "cd_documento",
              "title": "Documento - Código",
              "type": "string",
              "format": "default",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "cd_evento",
              "title": "Evento - Código",
              "type": "string",
              "format": "default",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "dt_anomes",
              "title": "Ano e Mês",
              "type": "string",
              "format": "default",
              "bareNumber": true,
              "notes": [
                "O tipo yearmonth somente aceita representação YYYY-MM (ie. com hífen)"
              ]
            },
            {
              "name": "ano_particao",
              "title": "Ano Partição",
              "type": "year",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_empenhado",
              "title": "Valor Empenhado",
              "description": "Valor do orçamento reservado para fazer face a compromisso formalmente assumido com fornecedor ou credor.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_liquidado",
              "title": "Valor Liquidado",
              "description": "Valor que o fornecedor ou credor tem direito a receber referente a produto ou serviço devidamente entregue ou prestado.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_pago",
              "title": "Valor Pago",
              "description": "- > \nValor referente aos pagamentos efetuados através de movimentações bancárias, escriturais e apropriação contábil da\ndespesa. O efetivo pagamento pode estar pendente de transmissão ao banco e/ou sujeito a compensação bancária.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_unidade_orc"
              ],
              "reference": {
                "fields": [
                  "id_unidade_orc"
                ],
                "resource": "dm_unidade_orc"
              }
            },
            {
              "fields": [
                "id_tipo_documento"
              ],
              "reference": {
                "fields": [
                  "id_tipo_documento"
                ],
                "resource": "dm_tipo_documento"
              }
            },
            {
              "fields": [
                "id_programa"
              ],
              "reference": {
                "fields": [
                  "id_programa"
                ],
                "resource": "dm_programa"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_categ_econ"
              ],
              "reference": {
                "fields": [
                  "id_categ_econ"
                ],
                "resource": "dm_categ_econ"
              }
            },
            {
              "fields": [
                "id_grupo"
              ],
              "reference": {
                "fields": [
                  "id_grupo"
                ],
                "resource": "dm_grupo_desp"
              }
            },
            {
              "fields": [
                "id_funcao"
              ],
              "reference": {
                "fields": [
                  "id_funcao"
                ],
                "resource": "dm_funcao_desp"
              }
            },
            {
              "fields": [
                "id_empenho"
              ],
              "reference": {
                "fields": [
                  "id_empenho"
                ],
                "resource": "dm_empenho_desp_2023"
              }
            },
            {
              "fields": [
                "id_tempo"
              ],
              "reference": {
                "fields": [
                  "id_tempo"
                ],
                "resource": "dm_tempo_diario"
              }
            },
            {
              "fields": [
                "id_subfuncao"
              ],
              "reference": {
                "fields": [
                  "id_subfuncao"
                ],
                "resource": "dm_subfuncao_desp"
              }
            },
            {
              "fields": [
                "id_acao"
              ],
              "reference": {
                "fields": [
                  "id_acao"
                ],
                "resource": "dm_acao"
              }
            },
            {
              "fields": [
                "id_modalidade_aplic"
              ],
              "reference": {
                "fields": [
                  "id_modalidade_aplic"
                ],
                "resource": "dm_modalidade_aplic"
              }
            },
            {
              "fields": [
                "id_procedencia"
              ],
              "reference": {
                "fields": [
                  "id_procedencia"
                ],
                "resource": "dm_procedencia"
              }
            },
            {
              "fields": [
                "id_elemento"
              ],
              "reference": {
                "fields": [
                  "id_elemento"
                ],
                "resource": "dm_elemento_desp"
              }
            },
            {
              "fields": [
                "id_fonte"
              ],
              "reference": {
                "fields": [
                  "id_fonte"
                ],
                "resource": "dm_fonte"
              }
            },
            {
              "fields": [
                "id_favorecido"
              ],
              "reference": {
                "fields": [
                  "id_favorecido"
                ],
                "resource": "dm_favorecido"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_despesa_2023"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "66973891647361ec802d60a83ace5a4b",
          "bytes": 20037516,
          "fields": 24,
          "rows": 1437059
        }
      },
      "time": 289.822,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1416674,
          "rowPosition": 1416675,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1416675\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1416698,
          "rowPosition": 1416699,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1416699\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1417240,
          "rowPosition": 1417241,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1417241\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1417690,
          "rowPosition": 1417691,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1417691\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1417691,
          "rowPosition": 1417692,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1417692\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1417692,
          "rowPosition": 1417693,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1417693\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1417693,
          "rowPosition": 1417694,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1417694\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1417694,
          "rowPosition": 1417695,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1417695\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1417695,
          "rowPosition": 1417696,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1417696\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1417696,
          "rowPosition": 1417697,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1417697\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1417697,
          "rowPosition": 1417698,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1417698\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1417698,
          "rowPosition": 1417699,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1417699\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1417699,
          "rowPosition": 1417700,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1417700\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1417700,
          "rowPosition": 1417701,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1417701\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1417701,
          "rowPosition": 1417702,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1417702\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1417702,
          "rowPosition": 1417703,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1417703\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1417703,
          "rowPosition": 1417704,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1417704\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1417704,
          "rowPosition": 1417705,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1417705\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1417705,
          "rowPosition": 1417706,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1417706\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1417706,
          "rowPosition": 1417707,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1417707\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1417707,
          "rowPosition": 1417708,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1417708\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1417708,
          "rowPosition": 1417709,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1417709\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1417709,
          "rowPosition": 1417710,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1417710\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1417710,
          "rowPosition": 1417711,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1417711\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1417711,
          "rowPosition": 1417712,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1417712\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1417712,
          "rowPosition": 1417713,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1417713\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1417713,
          "rowPosition": 1417714,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1417714\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1418174,
          "rowPosition": 1418175,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1418175\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1418175,
          "rowPosition": 1418176,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1418176\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1418176,
          "rowPosition": 1418177,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1418177\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1418177,
          "rowPosition": 1418178,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1418178\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1418178,
          "rowPosition": 1418179,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1418179\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1418179,
          "rowPosition": 1418180,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1418180\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1418180,
          "rowPosition": 1418181,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1418181\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1418630,
          "rowPosition": 1418631,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1418631\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1418637,
          "rowPosition": 1418638,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1418638\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1418638,
          "rowPosition": 1418639,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1418639\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1418639,
          "rowPosition": 1418640,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1418640\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1418640,
          "rowPosition": 1418641,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1418641\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1418641,
          "rowPosition": 1418642,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1418642\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1418642,
          "rowPosition": 1418643,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1418643\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1418643,
          "rowPosition": 1418644,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1418644\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1418644,
          "rowPosition": 1418645,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1418645\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1418645,
          "rowPosition": 1418646,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1418646\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1418646,
          "rowPosition": 1418647,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1418647\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1418647,
          "rowPosition": 1418648,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1418648\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 46
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 46,
    "tasks": 1
  },
  "valid": false
}