{
  "version": "4.38.0",
  "time": 103.378,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_diarias_scdp_liqpag",
        "title": "Diárias SCDP - Liquidação e Pagamento",
        "path": "data/ft_diarias_scdp_liqpag.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_documento_viagem",
              "title": "Documento de Viagem - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "description": "- > \n  Chave estrangeira (Foreign Key) que aponta para a Chave Primária (Primary keys) da tabela dm_tempo_diario. \n  Ou seja, por meio dessa chave é possível identificar a data completa a qual o dado se refere.\n\n  Nota: \n  No site dados.mg.gov.br a tabela dm_tempo_diario pode ser encontrada no recurso Calendários - Dias \n  de cada conjunto.\n",
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_empenho",
              "title": "Número do Empenho - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_programa",
              "title": "Programa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_funcao",
              "title": "Função - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_fonte",
              "title": "Fonte de Recurso - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item de Despesa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_acao",
              "title": "Ação Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "fl_passagem",
              "title": "Passagem - Flag",
              "type": "string",
              "format": "default",
              "description": "- '0' - Diárias\n- '1' - Passagem\n",
              "constraints": {
                "required": true,
                "enum": [
                  "0",
                  "1"
                ]
              }
            },
            {
              "name": "nr_liquidacao",
              "title": "Número Liquidação",
              "type": "string",
              "format": "default",
              "description": "Número do documento de liquidação.\n",
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "nr_pagamento",
              "title": "Número Pagamento",
              "type": "string",
              "format": "default",
              "description": "Número do documento de ordem de pagamento.\n",
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "dt_liquidacao",
              "title": "Data da liquidação",
              "type": "date",
              "format": "default"
            },
            {
              "name": "dt_pagamento",
              "type": "date",
              "format": "default"
            },
            {
              "name": "vr_devolvido",
              "title": "Valor Devolvido",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_liqpag",
              "title": "Valor liquidado/Pago",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "description": "- > \n  Valor pago referente às despesas com diárias e passagens aéreas e terrestres de servidor público ou \n  colaborador eventual em razão de viagem a trabalho.\n",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_funcao"
              ],
              "reference": {
                "fields": [
                  "id_funcao"
                ],
                "resource": "dm_funcao_desp"
              }
            },
            {
              "fields": [
                "id_fonte"
              ],
              "reference": {
                "fields": [
                  "id_fonte"
                ],
                "resource": "dm_fonte"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_programa"
              ],
              "reference": {
                "fields": [
                  "id_programa"
                ],
                "resource": "dm_programa"
              }
            },
            {
              "fields": [
                "id_empenho"
              ],
              "reference": {
                "fields": [
                  "id_empenho"
                ],
                "resource": "dm_empenho_desp_diarias_scdp_liqpag"
              }
            },
            {
              "fields": [
                "id_documento_viagem"
              ],
              "reference": {
                "fields": [
                  "id_documento_viagem"
                ],
                "resource": "dm_documento_viagem"
              }
            },
            {
              "fields": [
                "id_acao"
              ],
              "reference": {
                "fields": [
                  "id_acao"
                ],
                "resource": "dm_acao"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_fonte"
              ],
              "reference": {
                "fields": [
                  "id_fonte"
                ],
                "resource": "dm_fonte"
              }
            },
            {
              "fields": [
                "id_programa"
              ],
              "reference": {
                "fields": [
                  "id_programa"
                ],
                "resource": "dm_programa"
              }
            },
            {
              "fields": [
                "id_documento_viagem"
              ],
              "reference": {
                "fields": [
                  "id_documento_viagem"
                ],
                "resource": "dm_documento_viagem"
              }
            },
            {
              "fields": [
                "id_acao"
              ],
              "reference": {
                "fields": [
                  "id_acao"
                ],
                "resource": "dm_acao"
              }
            },
            {
              "fields": [
                "id_empenho"
              ],
              "reference": {
                "fields": [
                  "id_empenho"
                ],
                "resource": "dm_empenho_desp_diarias_scdp_liqpag"
              }
            },
            {
              "fields": [
                "id_funcao"
              ],
              "reference": {
                "fields": [
                  "id_funcao"
                ],
                "resource": "dm_funcao_desp"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_diarias_scdp_liqpag"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "27513c29070e305660522f5bf50b9b77",
          "bytes": 10228687,
          "fields": 14,
          "rows": 660600
        }
      },
      "time": 103.378,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "676412",
            "13246793",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "293",
            "378",
            "2022-12-06",
            "2022-12-12",
            "0.00",
            "181.00"
          ],
          "rowNumber": 655272,
          "rowPosition": 655273,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676412\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655273\" violates the foreign key: for \"id_documento_viagem\": values \"676412\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676412",
            "13246793",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "293",
            "378",
            "2022-12-06",
            "2022-12-12",
            "0.00",
            "181.00"
          ],
          "rowNumber": 655272,
          "rowPosition": 655273,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676412\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655273\" violates the foreign key: for \"id_documento_viagem\": values \"676412\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676384",
            "13246793",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "285",
            "351",
            "2022-12-06",
            "2022-12-07",
            "0.00",
            "262.92"
          ],
          "rowNumber": 655273,
          "rowPosition": 655274,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676384\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655274\" violates the foreign key: for \"id_documento_viagem\": values \"676384\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676384",
            "13246793",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "285",
            "351",
            "2022-12-06",
            "2022-12-07",
            "0.00",
            "262.92"
          ],
          "rowNumber": 655273,
          "rowPosition": 655274,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676384\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655274\" violates the foreign key: for \"id_documento_viagem\": values \"676384\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676356",
            "13240499",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "1",
            "3212",
            "2022-10-14",
            "2022-10-14",
            "0.00",
            "259.19"
          ],
          "rowNumber": 655274,
          "rowPosition": 655275,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676356\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655275\" violates the foreign key: for \"id_documento_viagem\": values \"676356\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676356",
            "13240499",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "1",
            "3212",
            "2022-10-14",
            "2022-10-14",
            "0.00",
            "259.19"
          ],
          "rowNumber": 655274,
          "rowPosition": 655275,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676356\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655275\" violates the foreign key: for \"id_documento_viagem\": values \"676356\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676422",
            "13240499",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "10",
            "3285",
            "2022-10-24",
            "2022-10-24",
            "0.00",
            "129.00"
          ],
          "rowNumber": 655275,
          "rowPosition": 655276,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676422\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655276\" violates the foreign key: for \"id_documento_viagem\": values \"676422\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676422",
            "13240499",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "10",
            "3285",
            "2022-10-24",
            "2022-10-24",
            "0.00",
            "129.00"
          ],
          "rowNumber": 655275,
          "rowPosition": 655276,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676422\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655276\" violates the foreign key: for \"id_documento_viagem\": values \"676422\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676380",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "624",
            "682",
            "2022-12-20",
            "2022-12-21",
            "0.00",
            "5334.50"
          ],
          "rowNumber": 655277,
          "rowPosition": 655278,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676380\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655278\" violates the foreign key: for \"id_documento_viagem\": values \"676380\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676380",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "624",
            "682",
            "2022-12-20",
            "2022-12-21",
            "0.00",
            "5334.50"
          ],
          "rowNumber": 655277,
          "rowPosition": 655278,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676380\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655278\" violates the foreign key: for \"id_documento_viagem\": values \"676380\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676370",
            "13240499",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "8",
            "3283",
            "2022-10-24",
            "2022-10-24",
            "0.00",
            "129.00"
          ],
          "rowNumber": 655278,
          "rowPosition": 655279,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676370\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655279\" violates the foreign key: for \"id_documento_viagem\": values \"676370\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676370",
            "13240499",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "8",
            "3283",
            "2022-10-24",
            "2022-10-24",
            "0.00",
            "129.00"
          ],
          "rowNumber": 655278,
          "rowPosition": 655279,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676370\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655279\" violates the foreign key: for \"id_documento_viagem\": values \"676370\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676390",
            "13246793",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "239",
            "306",
            "2022-11-08",
            "2022-11-14",
            "0.00",
            "262.92"
          ],
          "rowNumber": 655280,
          "rowPosition": 655281,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676390\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655281\" violates the foreign key: for \"id_documento_viagem\": values \"676390\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676390",
            "13246793",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "239",
            "306",
            "2022-11-08",
            "2022-11-14",
            "0.00",
            "262.92"
          ],
          "rowNumber": 655280,
          "rowPosition": 655281,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676390\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655281\" violates the foreign key: for \"id_documento_viagem\": values \"676390\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676414",
            "13270026",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "157",
            "166",
            "2022-08-11",
            "2022-08-11",
            "0.00",
            "2115.00"
          ],
          "rowNumber": 655281,
          "rowPosition": 655282,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676414\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655282\" violates the foreign key: for \"id_documento_viagem\": values \"676414\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676414",
            "13270026",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "157",
            "166",
            "2022-08-11",
            "2022-08-11",
            "0.00",
            "2115.00"
          ],
          "rowNumber": 655281,
          "rowPosition": 655282,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676414\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655282\" violates the foreign key: for \"id_documento_viagem\": values \"676414\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676381",
            "13270026",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "158",
            "164",
            "2022-08-11",
            "2022-08-11",
            "0.00",
            "2115.00"
          ],
          "rowNumber": 655282,
          "rowPosition": 655283,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676381\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655283\" violates the foreign key: for \"id_documento_viagem\": values \"676381\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676381",
            "13270026",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "158",
            "164",
            "2022-08-11",
            "2022-08-11",
            "0.00",
            "2115.00"
          ],
          "rowNumber": 655282,
          "rowPosition": 655283,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676381\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655283\" violates the foreign key: for \"id_documento_viagem\": values \"676381\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676399",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "17228",
            "22458",
            "2022-12-05",
            "2022-12-05",
            "0.00",
            "606.30"
          ],
          "rowNumber": 655284,
          "rowPosition": 655285,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676399\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655285\" violates the foreign key: for \"id_documento_viagem\": values \"676399\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676399",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "17228",
            "22458",
            "2022-12-05",
            "2022-12-05",
            "0.00",
            "606.30"
          ],
          "rowNumber": 655284,
          "rowPosition": 655285,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676399\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655285\" violates the foreign key: for \"id_documento_viagem\": values \"676399\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676359",
            "13246793",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "312",
            "385",
            "2022-12-21",
            "2022-12-21",
            "0.00",
            "294.97"
          ],
          "rowNumber": 655285,
          "rowPosition": 655286,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676359\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655286\" violates the foreign key: for \"id_documento_viagem\": values \"676359\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676359",
            "13246793",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "312",
            "385",
            "2022-12-21",
            "2022-12-21",
            "0.00",
            "294.97"
          ],
          "rowNumber": 655285,
          "rowPosition": 655286,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676359\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655286\" violates the foreign key: for \"id_documento_viagem\": values \"676359\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676427",
            "13240499",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "5",
            "3420",
            "2022-10-24",
            "2022-11-03",
            "0.00",
            "129.00"
          ],
          "rowNumber": 655287,
          "rowPosition": 655288,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676427\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655288\" violates the foreign key: for \"id_documento_viagem\": values \"676427\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676427",
            "13240499",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "5",
            "3420",
            "2022-10-24",
            "2022-11-03",
            "0.00",
            "129.00"
          ],
          "rowNumber": 655287,
          "rowPosition": 655288,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676427\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655288\" violates the foreign key: for \"id_documento_viagem\": values \"676427\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676368",
            "13251028",
            "14390",
            "1950",
            "58",
            "3012",
            "56714",
            "0",
            "7",
            "942",
            "2022-12-16",
            "2022-12-16",
            "0.00",
            "232.75"
          ],
          "rowNumber": 655288,
          "rowPosition": 655289,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676368\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655289\" violates the foreign key: for \"id_documento_viagem\": values \"676368\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676368",
            "13251028",
            "14390",
            "1950",
            "58",
            "3012",
            "56714",
            "0",
            "7",
            "942",
            "2022-12-16",
            "2022-12-16",
            "0.00",
            "232.75"
          ],
          "rowNumber": 655288,
          "rowPosition": 655289,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676368\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655289\" violates the foreign key: for \"id_documento_viagem\": values \"676368\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676358",
            "13240499",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "6",
            "3281",
            "2022-10-24",
            "2022-10-24",
            "0.00",
            "291.59"
          ],
          "rowNumber": 655292,
          "rowPosition": 655293,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676358\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655293\" violates the foreign key: for \"id_documento_viagem\": values \"676358\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676358",
            "13240499",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "6",
            "3281",
            "2022-10-24",
            "2022-10-24",
            "0.00",
            "291.59"
          ],
          "rowNumber": 655292,
          "rowPosition": 655293,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676358\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655293\" violates the foreign key: for \"id_documento_viagem\": values \"676358\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676355",
            "13246793",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "243",
            "350",
            "2022-11-08",
            "2022-12-07",
            "0.00",
            "129.00"
          ],
          "rowNumber": 655295,
          "rowPosition": 655296,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676355\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655296\" violates the foreign key: for \"id_documento_viagem\": values \"676355\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676355",
            "13246793",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "243",
            "350",
            "2022-11-08",
            "2022-12-07",
            "0.00",
            "129.00"
          ],
          "rowNumber": 655295,
          "rowPosition": 655296,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676355\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655296\" violates the foreign key: for \"id_documento_viagem\": values \"676355\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676405",
            "13246793",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "286",
            "379",
            "2022-12-06",
            "2022-12-12",
            "0.00",
            "262.92"
          ],
          "rowNumber": 655296,
          "rowPosition": 655297,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676405\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655297\" violates the foreign key: for \"id_documento_viagem\": values \"676405\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676405",
            "13246793",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "286",
            "379",
            "2022-12-06",
            "2022-12-12",
            "0.00",
            "262.92"
          ],
          "rowNumber": 655296,
          "rowPosition": 655297,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676405\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655297\" violates the foreign key: for \"id_documento_viagem\": values \"676405\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676351",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "572",
            "593",
            "2022-11-25",
            "2022-11-25",
            "0.00",
            "634.50"
          ],
          "rowNumber": 655297,
          "rowPosition": 655298,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676351\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655298\" violates the foreign key: for \"id_documento_viagem\": values \"676351\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676351",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "572",
            "593",
            "2022-11-25",
            "2022-11-25",
            "0.00",
            "634.50"
          ],
          "rowNumber": 655297,
          "rowPosition": 655298,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676351\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655298\" violates the foreign key: for \"id_documento_viagem\": values \"676351\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676346",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "17232",
            "22461",
            "2022-12-05",
            "2022-12-05",
            "0.00",
            "606.30"
          ],
          "rowNumber": 655298,
          "rowPosition": 655299,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676346\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655299\" violates the foreign key: for \"id_documento_viagem\": values \"676346\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676346",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "17232",
            "22461",
            "2022-12-05",
            "2022-12-05",
            "0.00",
            "606.30"
          ],
          "rowNumber": 655298,
          "rowPosition": 655299,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676346\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655299\" violates the foreign key: for \"id_documento_viagem\": values \"676346\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676420",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "60",
            "88",
            "2022-11-22",
            "2022-11-22",
            "470.00",
            "1104.50"
          ],
          "rowNumber": 655299,
          "rowPosition": 655300,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676420\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655300\" violates the foreign key: for \"id_documento_viagem\": values \"676420\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676420",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "60",
            "88",
            "2022-11-22",
            "2022-11-22",
            "470.00",
            "1104.50"
          ],
          "rowNumber": 655299,
          "rowPosition": 655300,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676420\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655300\" violates the foreign key: for \"id_documento_viagem\": values \"676420\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676418",
            "13246793",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "244",
            "310",
            "2022-11-08",
            "2022-11-14",
            "0.00",
            "181.00"
          ],
          "rowNumber": 655302,
          "rowPosition": 655303,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676418\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655303\" violates the foreign key: for \"id_documento_viagem\": values \"676418\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676418",
            "13246793",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "244",
            "310",
            "2022-11-08",
            "2022-11-14",
            "0.00",
            "181.00"
          ],
          "rowNumber": 655302,
          "rowPosition": 655303,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676418\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655303\" violates the foreign key: for \"id_documento_viagem\": values \"676418\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676415",
            "13246793",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "283",
            "348",
            "2022-12-06",
            "2022-12-07",
            "0.00",
            "294.97"
          ],
          "rowNumber": 655305,
          "rowPosition": 655306,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676415\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655306\" violates the foreign key: for \"id_documento_viagem\": values \"676415\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676415",
            "13246793",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "283",
            "348",
            "2022-12-06",
            "2022-12-07",
            "0.00",
            "294.97"
          ],
          "rowNumber": 655305,
          "rowPosition": 655306,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676415\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655306\" violates the foreign key: for \"id_documento_viagem\": values \"676415\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676387",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "17554",
            "22868",
            "2022-12-12",
            "2022-12-12",
            "0.00",
            "606.30"
          ],
          "rowNumber": 655309,
          "rowPosition": 655310,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676387\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655310\" violates the foreign key: for \"id_documento_viagem\": values \"676387\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676387",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "17554",
            "22868",
            "2022-12-12",
            "2022-12-12",
            "0.00",
            "606.30"
          ],
          "rowNumber": 655309,
          "rowPosition": 655310,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676387\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655310\" violates the foreign key: for \"id_documento_viagem\": values \"676387\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676363",
            "13240499",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "7",
            "3421",
            "2022-10-24",
            "2022-11-03",
            "0.00",
            "129.00"
          ],
          "rowNumber": 655311,
          "rowPosition": 655312,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676363\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655312\" violates the foreign key: for \"id_documento_viagem\": values \"676363\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676363",
            "13240499",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "7",
            "3421",
            "2022-10-24",
            "2022-11-03",
            "0.00",
            "129.00"
          ],
          "rowNumber": 655311,
          "rowPosition": 655312,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676363\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655312\" violates the foreign key: for \"id_documento_viagem\": values \"676363\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676393",
            "13246793",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "316",
            "392",
            "2022-12-26",
            "2022-12-27",
            "0.00",
            "294.97"
          ],
          "rowNumber": 655312,
          "rowPosition": 655313,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676393\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655313\" violates the foreign key: for \"id_documento_viagem\": values \"676393\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676393",
            "13246793",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "316",
            "392",
            "2022-12-26",
            "2022-12-27",
            "0.00",
            "294.97"
          ],
          "rowNumber": 655312,
          "rowPosition": 655313,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676393\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655313\" violates the foreign key: for \"id_documento_viagem\": values \"676393\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676419",
            "13240499",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "9",
            "3284",
            "2022-10-24",
            "2022-10-24",
            "0.00",
            "291.59"
          ],
          "rowNumber": 655313,
          "rowPosition": 655314,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676419\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655314\" violates the foreign key: for \"id_documento_viagem\": values \"676419\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676419",
            "13240499",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "9",
            "3284",
            "2022-10-24",
            "2022-10-24",
            "0.00",
            "291.59"
          ],
          "rowNumber": 655313,
          "rowPosition": 655314,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676419\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655314\" violates the foreign key: for \"id_documento_viagem\": values \"676419\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676416",
            "13246793",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "282",
            "347",
            "2022-12-06",
            "2022-12-07",
            "0.00",
            "294.97"
          ],
          "rowNumber": 655314,
          "rowPosition": 655315,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676416\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655315\" violates the foreign key: for \"id_documento_viagem\": values \"676416\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676416",
            "13246793",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "282",
            "347",
            "2022-12-06",
            "2022-12-07",
            "0.00",
            "294.97"
          ],
          "rowNumber": 655314,
          "rowPosition": 655315,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676416\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655315\" violates the foreign key: for \"id_documento_viagem\": values \"676416\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676357",
            "13246793",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "236",
            "346",
            "2022-11-08",
            "2022-12-07",
            "0.00",
            "294.97"
          ],
          "rowNumber": 655316,
          "rowPosition": 655317,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676357\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655317\" violates the foreign key: for \"id_documento_viagem\": values \"676357\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676357",
            "13246793",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "236",
            "346",
            "2022-11-08",
            "2022-12-07",
            "0.00",
            "294.97"
          ],
          "rowNumber": 655316,
          "rowPosition": 655317,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676357\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655317\" violates the foreign key: for \"id_documento_viagem\": values \"676357\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676395",
            "13246793",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "274",
            "340",
            "2022-11-30",
            "2022-12-07",
            "0.00",
            "539.57"
          ],
          "rowNumber": 655317,
          "rowPosition": 655318,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676395\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655318\" violates the foreign key: for \"id_documento_viagem\": values \"676395\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676395",
            "13246793",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "274",
            "340",
            "2022-11-30",
            "2022-12-07",
            "0.00",
            "539.57"
          ],
          "rowNumber": 655317,
          "rowPosition": 655318,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676395\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655318\" violates the foreign key: for \"id_documento_viagem\": values \"676395\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676350",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "304",
            "333",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 655318,
          "rowPosition": 655319,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676350\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655319\" violates the foreign key: for \"id_documento_viagem\": values \"676350\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676350",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "304",
            "333",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 655318,
          "rowPosition": 655319,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676350\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655319\" violates the foreign key: for \"id_documento_viagem\": values \"676350\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676398",
            "13240499",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "4",
            "3412",
            "2022-10-14",
            "2022-10-27",
            "0.00",
            "129.00"
          ],
          "rowNumber": 655319,
          "rowPosition": 655320,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676398\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655320\" violates the foreign key: for \"id_documento_viagem\": values \"676398\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676398",
            "13240499",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "4",
            "3412",
            "2022-10-14",
            "2022-10-27",
            "0.00",
            "129.00"
          ],
          "rowNumber": 655319,
          "rowPosition": 655320,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676398\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655320\" violates the foreign key: for \"id_documento_viagem\": values \"676398\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676391",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "17234",
            "22463",
            "2022-12-05",
            "2022-12-05",
            "0.00",
            "606.30"
          ],
          "rowNumber": 655321,
          "rowPosition": 655322,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676391\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655322\" violates the foreign key: for \"id_documento_viagem\": values \"676391\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676391",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "17234",
            "22463",
            "2022-12-05",
            "2022-12-05",
            "0.00",
            "606.30"
          ],
          "rowNumber": 655321,
          "rowPosition": 655322,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676391\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655322\" violates the foreign key: for \"id_documento_viagem\": values \"676391\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676374",
            "13246793",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "281",
            "345",
            "2022-12-06",
            "2022-12-07",
            "0.00",
            "181.00"
          ],
          "rowNumber": 655323,
          "rowPosition": 655324,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676374\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655324\" violates the foreign key: for \"id_documento_viagem\": values \"676374\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676374",
            "13246793",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "281",
            "345",
            "2022-12-06",
            "2022-12-07",
            "0.00",
            "181.00"
          ],
          "rowNumber": 655323,
          "rowPosition": 655324,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676374\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655324\" violates the foreign key: for \"id_documento_viagem\": values \"676374\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676361",
            "13326739",
            "14417",
            "1955",
            "58",
            "3012",
            "56260",
            "0",
            "8",
            "11858",
            "2022-12-12",
            "2022-12-12",
            "89.50",
            "1119.00"
          ],
          "rowNumber": 655324,
          "rowPosition": 655325,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676361\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655325\" violates the foreign key: for \"id_documento_viagem\": values \"676361\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676361",
            "13326739",
            "14417",
            "1955",
            "58",
            "3012",
            "56260",
            "0",
            "8",
            "11858",
            "2022-12-12",
            "2022-12-12",
            "89.50",
            "1119.00"
          ],
          "rowNumber": 655324,
          "rowPosition": 655325,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676361\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655325\" violates the foreign key: for \"id_documento_viagem\": values \"676361\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676380",
            "13385713",
            "14353",
            "1948",
            "58",
            "2772",
            "56813",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "77.64"
          ],
          "rowNumber": 655325,
          "rowPosition": 655326,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676380\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655326\" violates the foreign key: for \"id_documento_viagem\": values \"676380\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676380",
            "13385713",
            "14353",
            "1948",
            "58",
            "2772",
            "56813",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "77.64"
          ],
          "rowNumber": 655325,
          "rowPosition": 655326,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676380\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655326\" violates the foreign key: for \"id_documento_viagem\": values \"676380\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676380",
            "13385713",
            "14353",
            "1948",
            "58",
            "2772",
            "56813",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "134.97"
          ],
          "rowNumber": 655326,
          "rowPosition": 655327,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676380\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655327\" violates the foreign key: for \"id_documento_viagem\": values \"676380\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676380",
            "13385713",
            "14353",
            "1948",
            "58",
            "2772",
            "56813",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "134.97"
          ],
          "rowNumber": 655326,
          "rowPosition": 655327,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676380\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655327\" violates the foreign key: for \"id_documento_viagem\": values \"676380\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676380",
            "13357338",
            "14353",
            "1948",
            "58",
            "2772",
            "56813",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "1699.56"
          ],
          "rowNumber": 655327,
          "rowPosition": 655328,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676380\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655328\" violates the foreign key: for \"id_documento_viagem\": values \"676380\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676380",
            "13357338",
            "14353",
            "1948",
            "58",
            "2772",
            "56813",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "1699.56"
          ],
          "rowNumber": 655327,
          "rowPosition": 655328,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676380\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655328\" violates the foreign key: for \"id_documento_viagem\": values \"676380\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676380",
            "13357338",
            "14353",
            "1948",
            "58",
            "2772",
            "56813",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "1964.62"
          ],
          "rowNumber": 655328,
          "rowPosition": 655329,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676380\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655329\" violates the foreign key: for \"id_documento_viagem\": values \"676380\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676380",
            "13357338",
            "14353",
            "1948",
            "58",
            "2772",
            "56813",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "1964.62"
          ],
          "rowNumber": 655328,
          "rowPosition": 655329,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676380\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655329\" violates the foreign key: for \"id_documento_viagem\": values \"676380\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676368",
            "13252760",
            "14390",
            "1950",
            "58",
            "2772",
            "56714",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "279.43"
          ],
          "rowNumber": 655329,
          "rowPosition": 655330,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676368\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655330\" violates the foreign key: for \"id_documento_viagem\": values \"676368\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676368",
            "13252760",
            "14390",
            "1950",
            "58",
            "2772",
            "56714",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "279.43"
          ],
          "rowNumber": 655329,
          "rowPosition": 655330,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676368\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655330\" violates the foreign key: for \"id_documento_viagem\": values \"676368\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676368",
            "13252760",
            "14390",
            "1950",
            "58",
            "2772",
            "56714",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "1970.66"
          ],
          "rowNumber": 655330,
          "rowPosition": 655331,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676368\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655331\" violates the foreign key: for \"id_documento_viagem\": values \"676368\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676368",
            "13252760",
            "14390",
            "1950",
            "58",
            "2772",
            "56714",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "1970.66"
          ],
          "rowNumber": 655330,
          "rowPosition": 655331,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676368\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655331\" violates the foreign key: for \"id_documento_viagem\": values \"676368\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676351",
            "13357338",
            "14353",
            "1948",
            "58",
            "2772",
            "56813",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "1903.79"
          ],
          "rowNumber": 655331,
          "rowPosition": 655332,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676351\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655332\" violates the foreign key: for \"id_documento_viagem\": values \"676351\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676351",
            "13357338",
            "14353",
            "1948",
            "58",
            "2772",
            "56813",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "1903.79"
          ],
          "rowNumber": 655331,
          "rowPosition": 655332,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676351\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655332\" violates the foreign key: for \"id_documento_viagem\": values \"676351\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676351",
            "13357338",
            "14353",
            "1948",
            "58",
            "2772",
            "56813",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "1904.29"
          ],
          "rowNumber": 655332,
          "rowPosition": 655333,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676351\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655333\" violates the foreign key: for \"id_documento_viagem\": values \"676351\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676351",
            "13357338",
            "14353",
            "1948",
            "58",
            "2772",
            "56813",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "1904.29"
          ],
          "rowNumber": 655332,
          "rowPosition": 655333,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676351\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655333\" violates the foreign key: for \"id_documento_viagem\": values \"676351\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 82
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 82,
    "tasks": 1
  },
  "valid": false
}