{
  "version": "4.38.0",
  "time": 102.78,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_diarias_scdp_liqpag",
        "title": "Diárias SCDP - Liquidação e Pagamento",
        "path": "data/ft_diarias_scdp_liqpag.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_documento_viagem",
              "title": "Documento de Viagem - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "description": "- > \n  Chave estrangeira (Foreign Key) que aponta para a Chave Primária (Primary keys) da tabela dm_tempo_diario. \n  Ou seja, por meio dessa chave é possível identificar a data completa a qual o dado se refere.\n\n  Nota: \n  No site dados.mg.gov.br a tabela dm_tempo_diario pode ser encontrada no recurso Calendários - Dias \n  de cada conjunto.\n",
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_empenho",
              "title": "Número do Empenho - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_programa",
              "title": "Programa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_funcao",
              "title": "Função - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_fonte",
              "title": "Fonte de Recurso - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item de Despesa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_acao",
              "title": "Ação Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "fl_passagem",
              "title": "Passagem - Flag",
              "type": "string",
              "format": "default",
              "description": "- '0' - Diárias\n- '1' - Passagem\n",
              "constraints": {
                "required": true,
                "enum": [
                  "0",
                  "1"
                ]
              }
            },
            {
              "name": "nr_liquidacao",
              "title": "Número Liquidação",
              "type": "string",
              "format": "default",
              "description": "Número do documento de liquidação.\n",
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "nr_pagamento",
              "title": "Número Pagamento",
              "type": "string",
              "format": "default",
              "description": "Número do documento de ordem de pagamento.\n",
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "dt_liquidacao",
              "title": "Data da liquidação",
              "type": "date",
              "format": "default"
            },
            {
              "name": "dt_pagamento",
              "type": "date",
              "format": "default"
            },
            {
              "name": "vr_devolvido",
              "title": "Valor Devolvido",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_liqpag",
              "title": "Valor liquidado/Pago",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "description": "- > \n  Valor pago referente às despesas com diárias e passagens aéreas e terrestres de servidor público ou \n  colaborador eventual em razão de viagem a trabalho.\n",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_funcao"
              ],
              "reference": {
                "fields": [
                  "id_funcao"
                ],
                "resource": "dm_funcao_desp"
              }
            },
            {
              "fields": [
                "id_fonte"
              ],
              "reference": {
                "fields": [
                  "id_fonte"
                ],
                "resource": "dm_fonte"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_programa"
              ],
              "reference": {
                "fields": [
                  "id_programa"
                ],
                "resource": "dm_programa"
              }
            },
            {
              "fields": [
                "id_empenho"
              ],
              "reference": {
                "fields": [
                  "id_empenho"
                ],
                "resource": "dm_empenho_desp_diarias_scdp_liqpag"
              }
            },
            {
              "fields": [
                "id_documento_viagem"
              ],
              "reference": {
                "fields": [
                  "id_documento_viagem"
                ],
                "resource": "dm_documento_viagem"
              }
            },
            {
              "fields": [
                "id_acao"
              ],
              "reference": {
                "fields": [
                  "id_acao"
                ],
                "resource": "dm_acao"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_fonte"
              ],
              "reference": {
                "fields": [
                  "id_fonte"
                ],
                "resource": "dm_fonte"
              }
            },
            {
              "fields": [
                "id_programa"
              ],
              "reference": {
                "fields": [
                  "id_programa"
                ],
                "resource": "dm_programa"
              }
            },
            {
              "fields": [
                "id_documento_viagem"
              ],
              "reference": {
                "fields": [
                  "id_documento_viagem"
                ],
                "resource": "dm_documento_viagem"
              }
            },
            {
              "fields": [
                "id_acao"
              ],
              "reference": {
                "fields": [
                  "id_acao"
                ],
                "resource": "dm_acao"
              }
            },
            {
              "fields": [
                "id_empenho"
              ],
              "reference": {
                "fields": [
                  "id_empenho"
                ],
                "resource": "dm_empenho_desp_diarias_scdp_liqpag"
              }
            },
            {
              "fields": [
                "id_funcao"
              ],
              "reference": {
                "fields": [
                  "id_funcao"
                ],
                "resource": "dm_funcao_desp"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_diarias_scdp_liqpag"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "4713a83be7f71d65c27c7105a4f63651",
          "bytes": 10225437,
          "fields": 14,
          "rows": 660401
        }
      },
      "time": 102.78,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "676139",
            "13236042",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "92",
            "115",
            "2022-12-23",
            "2022-12-27",
            "0.00",
            "181.00"
          ],
          "rowNumber": 525089,
          "rowPosition": 525090,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676139\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"525090\" violates the foreign key: for \"id_documento_viagem\": values \"676139\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676139",
            "13236042",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "92",
            "115",
            "2022-12-23",
            "2022-12-27",
            "0.00",
            "181.00"
          ],
          "rowNumber": 525089,
          "rowPosition": 525090,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676139\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"525090\" violates the foreign key: for \"id_documento_viagem\": values \"676139\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676144",
            "13215758",
            "14390",
            "1957",
            "58",
            "3012",
            "56714",
            "0",
            "414",
            "7322",
            "2022-12-16",
            "2022-12-16",
            "0.00",
            "747.30"
          ],
          "rowNumber": 525092,
          "rowPosition": 525093,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676144\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"525093\" violates the foreign key: for \"id_documento_viagem\": values \"676144\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676144",
            "13215758",
            "14390",
            "1957",
            "58",
            "3012",
            "56714",
            "0",
            "414",
            "7322",
            "2022-12-16",
            "2022-12-16",
            "0.00",
            "747.30"
          ],
          "rowNumber": 525092,
          "rowPosition": 525093,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676144\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"525093\" violates the foreign key: for \"id_documento_viagem\": values \"676144\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676098",
            "13249094",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "511",
            "563",
            "2022-12-28",
            "2022-12-28",
            "0.00",
            "294.97"
          ],
          "rowNumber": 525093,
          "rowPosition": 525094,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676098\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"525094\" violates the foreign key: for \"id_documento_viagem\": values \"676098\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676098",
            "13249094",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "511",
            "563",
            "2022-12-28",
            "2022-12-28",
            "0.00",
            "294.97"
          ],
          "rowNumber": 525093,
          "rowPosition": 525094,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676098\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"525094\" violates the foreign key: for \"id_documento_viagem\": values \"676098\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676133",
            "13267186",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "91",
            "152",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "243.00"
          ],
          "rowNumber": 525110,
          "rowPosition": 525111,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676133\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"525111\" violates the foreign key: for \"id_documento_viagem\": values \"676133\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676133",
            "13267186",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "91",
            "152",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "243.00"
          ],
          "rowNumber": 525110,
          "rowPosition": 525111,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676133\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"525111\" violates the foreign key: for \"id_documento_viagem\": values \"676133\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676142",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18166",
            "23751",
            "2022-12-22",
            "2022-12-22",
            "0.00",
            "488.70"
          ],
          "rowNumber": 525111,
          "rowPosition": 525112,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676142\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"525112\" violates the foreign key: for \"id_documento_viagem\": values \"676142\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676142",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18166",
            "23751",
            "2022-12-22",
            "2022-12-22",
            "0.00",
            "488.70"
          ],
          "rowNumber": 525111,
          "rowPosition": 525112,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676142\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"525112\" violates the foreign key: for \"id_documento_viagem\": values \"676142\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676091",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18442",
            "24175",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "634.50"
          ],
          "rowNumber": 525125,
          "rowPosition": 525126,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676091\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"525126\" violates the foreign key: for \"id_documento_viagem\": values \"676091\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676091",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18442",
            "24175",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "634.50"
          ],
          "rowNumber": 525125,
          "rowPosition": 525126,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676091\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"525126\" violates the foreign key: for \"id_documento_viagem\": values \"676091\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676116",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18308",
            "24003",
            "2022-12-26",
            "2022-12-26",
            "0.00",
            "348.30"
          ],
          "rowNumber": 525126,
          "rowPosition": 525127,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676116\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"525127\" violates the foreign key: for \"id_documento_viagem\": values \"676116\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676116",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18308",
            "24003",
            "2022-12-26",
            "2022-12-26",
            "0.00",
            "348.30"
          ],
          "rowNumber": 525126,
          "rowPosition": 525127,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676116\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"525127\" violates the foreign key: for \"id_documento_viagem\": values \"676116\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676087",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18439",
            "24172",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "634.50"
          ],
          "rowNumber": 525143,
          "rowPosition": 525144,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676087\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"525144\" violates the foreign key: for \"id_documento_viagem\": values \"676087\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676087",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18439",
            "24172",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "634.50"
          ],
          "rowNumber": 525143,
          "rowPosition": 525144,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676087\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"525144\" violates the foreign key: for \"id_documento_viagem\": values \"676087\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676115",
            "13215758",
            "14390",
            "1957",
            "58",
            "3012",
            "56714",
            "0",
            "405",
            "7208",
            "2022-12-14",
            "2022-12-14",
            "366.00",
            "747.30"
          ],
          "rowNumber": 525144,
          "rowPosition": 525145,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676115\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"525145\" violates the foreign key: for \"id_documento_viagem\": values \"676115\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676115",
            "13215758",
            "14390",
            "1957",
            "58",
            "3012",
            "56714",
            "0",
            "405",
            "7208",
            "2022-12-14",
            "2022-12-14",
            "366.00",
            "747.30"
          ],
          "rowNumber": 525144,
          "rowPosition": 525145,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676115\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"525145\" violates the foreign key: for \"id_documento_viagem\": values \"676115\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676140",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18391",
            "24114",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "90.30"
          ],
          "rowNumber": 525158,
          "rowPosition": 525159,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676140\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"525159\" violates the foreign key: for \"id_documento_viagem\": values \"676140\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676140",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18391",
            "24114",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "90.30"
          ],
          "rowNumber": 525158,
          "rowPosition": 525159,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676140\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"525159\" violates the foreign key: for \"id_documento_viagem\": values \"676140\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676127",
            "13236042",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "93",
            "116",
            "2022-12-23",
            "2022-12-27",
            "0.00",
            "235.00"
          ],
          "rowNumber": 525159,
          "rowPosition": 525160,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676127\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"525160\" violates the foreign key: for \"id_documento_viagem\": values \"676127\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676127",
            "13236042",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "93",
            "116",
            "2022-12-23",
            "2022-12-27",
            "0.00",
            "235.00"
          ],
          "rowNumber": 525159,
          "rowPosition": 525160,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676127\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"525160\" violates the foreign key: for \"id_documento_viagem\": values \"676127\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676099",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18388",
            "24111",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "90.30"
          ],
          "rowNumber": 525160,
          "rowPosition": 525161,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676099\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"525161\" violates the foreign key: for \"id_documento_viagem\": values \"676099\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676099",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18388",
            "24111",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "90.30"
          ],
          "rowNumber": 525160,
          "rowPosition": 525161,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676099\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"525161\" violates the foreign key: for \"id_documento_viagem\": values \"676099\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676112",
            "13236042",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "91",
            "114",
            "2022-12-23",
            "2022-12-27",
            "0.00",
            "181.00"
          ],
          "rowNumber": 525166,
          "rowPosition": 525167,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676112\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"525167\" violates the foreign key: for \"id_documento_viagem\": values \"676112\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676112",
            "13236042",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "91",
            "114",
            "2022-12-23",
            "2022-12-27",
            "0.00",
            "181.00"
          ],
          "rowNumber": 525166,
          "rowPosition": 525167,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676112\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"525167\" violates the foreign key: for \"id_documento_viagem\": values \"676112\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676077",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18393",
            "24116",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "90.30"
          ],
          "rowNumber": 525167,
          "rowPosition": 525168,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676077\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"525168\" violates the foreign key: for \"id_documento_viagem\": values \"676077\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676077",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18393",
            "24116",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "90.30"
          ],
          "rowNumber": 525167,
          "rowPosition": 525168,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676077\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"525168\" violates the foreign key: for \"id_documento_viagem\": values \"676077\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676124",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18390",
            "24113",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "90.30"
          ],
          "rowNumber": 525180,
          "rowPosition": 525181,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676124\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"525181\" violates the foreign key: for \"id_documento_viagem\": values \"676124\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676124",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18390",
            "24113",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "90.30"
          ],
          "rowNumber": 525180,
          "rowPosition": 525181,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676124\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"525181\" violates the foreign key: for \"id_documento_viagem\": values \"676124\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676083",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18542",
            "24321",
            "2022-12-28",
            "2022-12-28",
            "0.00",
            "90.30"
          ],
          "rowNumber": 525181,
          "rowPosition": 525182,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676083\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"525182\" violates the foreign key: for \"id_documento_viagem\": values \"676083\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676083",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18542",
            "24321",
            "2022-12-28",
            "2022-12-28",
            "0.00",
            "90.30"
          ],
          "rowNumber": 525181,
          "rowPosition": 525182,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676083\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"525182\" violates the foreign key: for \"id_documento_viagem\": values \"676083\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676131",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18334",
            "24030",
            "2022-12-26",
            "2022-12-26",
            "0.00",
            "90.30"
          ],
          "rowNumber": 525182,
          "rowPosition": 525183,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676131\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"525183\" violates the foreign key: for \"id_documento_viagem\": values \"676131\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676131",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18334",
            "24030",
            "2022-12-26",
            "2022-12-26",
            "0.00",
            "90.30"
          ],
          "rowNumber": 525182,
          "rowPosition": 525183,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676131\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"525183\" violates the foreign key: for \"id_documento_viagem\": values \"676131\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676113",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18387",
            "24110",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "90.30"
          ],
          "rowNumber": 525183,
          "rowPosition": 525184,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676113\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"525184\" violates the foreign key: for \"id_documento_viagem\": values \"676113\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676113",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18387",
            "24110",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "90.30"
          ],
          "rowNumber": 525183,
          "rowPosition": 525184,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676113\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"525184\" violates the foreign key: for \"id_documento_viagem\": values \"676113\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676105",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18441",
            "24174",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "634.50"
          ],
          "rowNumber": 658551,
          "rowPosition": 658552,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676105\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658552\" violates the foreign key: for \"id_documento_viagem\": values \"676105\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676105",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18441",
            "24174",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "634.50"
          ],
          "rowNumber": 658551,
          "rowPosition": 658552,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676105\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658552\" violates the foreign key: for \"id_documento_viagem\": values \"676105\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676102",
            "13267186",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "88",
            "145",
            "2022-12-26",
            "2022-12-27",
            "0.00",
            "235.00"
          ],
          "rowNumber": 658552,
          "rowPosition": 658553,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676102\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658553\" violates the foreign key: for \"id_documento_viagem\": values \"676102\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676102",
            "13267186",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "88",
            "145",
            "2022-12-26",
            "2022-12-27",
            "0.00",
            "235.00"
          ],
          "rowNumber": 658552,
          "rowPosition": 658553,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676102\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658553\" violates the foreign key: for \"id_documento_viagem\": values \"676102\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676119",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18349",
            "24046",
            "2022-12-26",
            "2022-12-26",
            "90.30",
            "90.30"
          ],
          "rowNumber": 658553,
          "rowPosition": 658554,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676119\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658554\" violates the foreign key: for \"id_documento_viagem\": values \"676119\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676119",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18349",
            "24046",
            "2022-12-26",
            "2022-12-26",
            "90.30",
            "90.30"
          ],
          "rowNumber": 658553,
          "rowPosition": 658554,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676119\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658554\" violates the foreign key: for \"id_documento_viagem\": values \"676119\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676134",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18344",
            "24041",
            "2022-12-26",
            "2022-12-26",
            "0.00",
            "348.30"
          ],
          "rowNumber": 658554,
          "rowPosition": 658555,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676134\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658555\" violates the foreign key: for \"id_documento_viagem\": values \"676134\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676134",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18344",
            "24041",
            "2022-12-26",
            "2022-12-26",
            "0.00",
            "348.30"
          ],
          "rowNumber": 658554,
          "rowPosition": 658555,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676134\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658555\" violates the foreign key: for \"id_documento_viagem\": values \"676134\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676082",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18354",
            "24051",
            "2022-12-26",
            "2022-12-26",
            "0.00",
            "90.30"
          ],
          "rowNumber": 658555,
          "rowPosition": 658556,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676082\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658556\" violates the foreign key: for \"id_documento_viagem\": values \"676082\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676082",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18354",
            "24051",
            "2022-12-26",
            "2022-12-26",
            "0.00",
            "90.30"
          ],
          "rowNumber": 658555,
          "rowPosition": 658556,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676082\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658556\" violates the foreign key: for \"id_documento_viagem\": values \"676082\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676085",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18306",
            "24001",
            "2022-12-26",
            "2022-12-26",
            "0.00",
            "90.30"
          ],
          "rowNumber": 658556,
          "rowPosition": 658557,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676085\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658557\" violates the foreign key: for \"id_documento_viagem\": values \"676085\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676085",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18306",
            "24001",
            "2022-12-26",
            "2022-12-26",
            "0.00",
            "90.30"
          ],
          "rowNumber": 658556,
          "rowPosition": 658557,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676085\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658557\" violates the foreign key: for \"id_documento_viagem\": values \"676085\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676130",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18533",
            "24308",
            "2022-12-28",
            "2022-12-28",
            "0.00",
            "348.30"
          ],
          "rowNumber": 658557,
          "rowPosition": 658558,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676130\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658558\" violates the foreign key: for \"id_documento_viagem\": values \"676130\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676130",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18533",
            "24308",
            "2022-12-28",
            "2022-12-28",
            "0.00",
            "348.30"
          ],
          "rowNumber": 658557,
          "rowPosition": 658558,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676130\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658558\" violates the foreign key: for \"id_documento_viagem\": values \"676130\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676108",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18450",
            "24191",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "348.30"
          ],
          "rowNumber": 658558,
          "rowPosition": 658559,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676108\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658559\" violates the foreign key: for \"id_documento_viagem\": values \"676108\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676108",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18450",
            "24191",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "348.30"
          ],
          "rowNumber": 658558,
          "rowPosition": 658559,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676108\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658559\" violates the foreign key: for \"id_documento_viagem\": values \"676108\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676110",
            "13212811",
            "14390",
            "1950",
            "58",
            "3012",
            "56714",
            "0",
            "185",
            "1902",
            "2022-12-07",
            "2022-12-07",
            "0.00",
            "248.30"
          ],
          "rowNumber": 658559,
          "rowPosition": 658560,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676110\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658560\" violates the foreign key: for \"id_documento_viagem\": values \"676110\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676110",
            "13212811",
            "14390",
            "1950",
            "58",
            "3012",
            "56714",
            "0",
            "185",
            "1902",
            "2022-12-07",
            "2022-12-07",
            "0.00",
            "248.30"
          ],
          "rowNumber": 658559,
          "rowPosition": 658560,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676110\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658560\" violates the foreign key: for \"id_documento_viagem\": values \"676110\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676089",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18504",
            "24277",
            "2022-12-28",
            "2022-12-28",
            "0.00",
            "348.30"
          ],
          "rowNumber": 658560,
          "rowPosition": 658561,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676089\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658561\" violates the foreign key: for \"id_documento_viagem\": values \"676089\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676089",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18504",
            "24277",
            "2022-12-28",
            "2022-12-28",
            "0.00",
            "348.30"
          ],
          "rowNumber": 658560,
          "rowPosition": 658561,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676089\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658561\" violates the foreign key: for \"id_documento_viagem\": values \"676089\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676122",
            "13236042",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "90",
            "113",
            "2022-12-23",
            "2022-12-27",
            "0.00",
            "235.00"
          ],
          "rowNumber": 658561,
          "rowPosition": 658562,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676122\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658562\" violates the foreign key: for \"id_documento_viagem\": values \"676122\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676122",
            "13236042",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "90",
            "113",
            "2022-12-23",
            "2022-12-27",
            "0.00",
            "235.00"
          ],
          "rowNumber": 658561,
          "rowPosition": 658562,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676122\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658562\" violates the foreign key: for \"id_documento_viagem\": values \"676122\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676079",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18392",
            "24115",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "90.30"
          ],
          "rowNumber": 658562,
          "rowPosition": 658563,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676079\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658563\" violates the foreign key: for \"id_documento_viagem\": values \"676079\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676079",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18392",
            "24115",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "90.30"
          ],
          "rowNumber": 658562,
          "rowPosition": 658563,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676079\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658563\" violates the foreign key: for \"id_documento_viagem\": values \"676079\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676096",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18317",
            "24012",
            "2022-12-26",
            "2022-12-26",
            "0.00",
            "348.30"
          ],
          "rowNumber": 658563,
          "rowPosition": 658564,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676096\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658564\" violates the foreign key: for \"id_documento_viagem\": values \"676096\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676096",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18317",
            "24012",
            "2022-12-26",
            "2022-12-26",
            "0.00",
            "348.30"
          ],
          "rowNumber": 658563,
          "rowPosition": 658564,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676096\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658564\" violates the foreign key: for \"id_documento_viagem\": values \"676096\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676135",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18526",
            "24301",
            "2022-12-28",
            "2022-12-28",
            "0.00",
            "348.30"
          ],
          "rowNumber": 658564,
          "rowPosition": 658565,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676135\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658565\" violates the foreign key: for \"id_documento_viagem\": values \"676135\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676135",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18526",
            "24301",
            "2022-12-28",
            "2022-12-28",
            "0.00",
            "348.30"
          ],
          "rowNumber": 658564,
          "rowPosition": 658565,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676135\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658565\" violates the foreign key: for \"id_documento_viagem\": values \"676135\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676100",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18497",
            "24270",
            "2022-12-28",
            "2022-12-28",
            "0.00",
            "348.30"
          ],
          "rowNumber": 658565,
          "rowPosition": 658566,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676100\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658566\" violates the foreign key: for \"id_documento_viagem\": values \"676100\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676100",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18497",
            "24270",
            "2022-12-28",
            "2022-12-28",
            "0.00",
            "348.30"
          ],
          "rowNumber": 658565,
          "rowPosition": 658566,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676100\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658566\" violates the foreign key: for \"id_documento_viagem\": values \"676100\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676097",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18451",
            "24192",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "348.30"
          ],
          "rowNumber": 658566,
          "rowPosition": 658567,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676097\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658567\" violates the foreign key: for \"id_documento_viagem\": values \"676097\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676097",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18451",
            "24192",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "348.30"
          ],
          "rowNumber": 658566,
          "rowPosition": 658567,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676097\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658567\" violates the foreign key: for \"id_documento_viagem\": values \"676097\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676084",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18312",
            "24007",
            "2022-12-26",
            "2022-12-26",
            "90.30",
            "90.30"
          ],
          "rowNumber": 658567,
          "rowPosition": 658568,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676084\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658568\" violates the foreign key: for \"id_documento_viagem\": values \"676084\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676084",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18312",
            "24007",
            "2022-12-26",
            "2022-12-26",
            "90.30",
            "90.30"
          ],
          "rowNumber": 658567,
          "rowPosition": 658568,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676084\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658568\" violates the foreign key: for \"id_documento_viagem\": values \"676084\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676128",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18356",
            "24053",
            "2022-12-26",
            "2022-12-26",
            "0.00",
            "348.30"
          ],
          "rowNumber": 658568,
          "rowPosition": 658569,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676128\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658569\" violates the foreign key: for \"id_documento_viagem\": values \"676128\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676128",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18356",
            "24053",
            "2022-12-26",
            "2022-12-26",
            "0.00",
            "348.30"
          ],
          "rowNumber": 658568,
          "rowPosition": 658569,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676128\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658569\" violates the foreign key: for \"id_documento_viagem\": values \"676128\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676088",
            "13267186",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "87",
            "149",
            "2022-12-26",
            "2022-12-27",
            "0.00",
            "243.00"
          ],
          "rowNumber": 658569,
          "rowPosition": 658570,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676088\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658570\" violates the foreign key: for \"id_documento_viagem\": values \"676088\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676088",
            "13267186",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "87",
            "149",
            "2022-12-26",
            "2022-12-27",
            "0.00",
            "243.00"
          ],
          "rowNumber": 658569,
          "rowPosition": 658570,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676088\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658570\" violates the foreign key: for \"id_documento_viagem\": values \"676088\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676136",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18345",
            "24042",
            "2022-12-26",
            "2022-12-26",
            "0.00",
            "348.30"
          ],
          "rowNumber": 658570,
          "rowPosition": 658571,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676136\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658571\" violates the foreign key: for \"id_documento_viagem\": values \"676136\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676136",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18345",
            "24042",
            "2022-12-26",
            "2022-12-26",
            "0.00",
            "348.30"
          ],
          "rowNumber": 658570,
          "rowPosition": 658571,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676136\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658571\" violates the foreign key: for \"id_documento_viagem\": values \"676136\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676114",
            "13249094",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "509",
            "560",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "294.97"
          ],
          "rowNumber": 658571,
          "rowPosition": 658572,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676114\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658572\" violates the foreign key: for \"id_documento_viagem\": values \"676114\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676114",
            "13249094",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "509",
            "560",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "294.97"
          ],
          "rowNumber": 658571,
          "rowPosition": 658572,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676114\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658572\" violates the foreign key: for \"id_documento_viagem\": values \"676114\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676094",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18540",
            "24319",
            "2022-12-28",
            "2022-12-28",
            "0.00",
            "90.30"
          ],
          "rowNumber": 658572,
          "rowPosition": 658573,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676094\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658573\" violates the foreign key: for \"id_documento_viagem\": values \"676094\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676094",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18540",
            "24319",
            "2022-12-28",
            "2022-12-28",
            "0.00",
            "90.30"
          ],
          "rowNumber": 658572,
          "rowPosition": 658573,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676094\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658573\" violates the foreign key: for \"id_documento_viagem\": values \"676094\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676073",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18527",
            "24302",
            "2022-12-28",
            "2022-12-28",
            "0.00",
            "348.30"
          ],
          "rowNumber": 658573,
          "rowPosition": 658574,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676073\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658574\" violates the foreign key: for \"id_documento_viagem\": values \"676073\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676073",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18527",
            "24302",
            "2022-12-28",
            "2022-12-28",
            "0.00",
            "348.30"
          ],
          "rowNumber": 658573,
          "rowPosition": 658574,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676073\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658574\" violates the foreign key: for \"id_documento_viagem\": values \"676073\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676117",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18385",
            "24108",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "90.30"
          ],
          "rowNumber": 658574,
          "rowPosition": 658575,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676117\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658575\" violates the foreign key: for \"id_documento_viagem\": values \"676117\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676117",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18385",
            "24108",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "90.30"
          ],
          "rowNumber": 658574,
          "rowPosition": 658575,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676117\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658575\" violates the foreign key: for \"id_documento_viagem\": values \"676117\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676129",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18499",
            "24272",
            "2022-12-28",
            "2022-12-28",
            "0.00",
            "348.30"
          ],
          "rowNumber": 658575,
          "rowPosition": 658576,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676129\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658576\" violates the foreign key: for \"id_documento_viagem\": values \"676129\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676129",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18499",
            "24272",
            "2022-12-28",
            "2022-12-28",
            "0.00",
            "348.30"
          ],
          "rowNumber": 658575,
          "rowPosition": 658576,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676129\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658576\" violates the foreign key: for \"id_documento_viagem\": values \"676129\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676076",
            "13219939",
            "14353",
            "1948",
            "58",
            "3012",
            "56157",
            "0",
            "51",
            "436",
            "2022-10-27",
            "2022-10-27",
            "634.50",
            "634.50"
          ],
          "rowNumber": 658576,
          "rowPosition": 658577,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676076\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658577\" violates the foreign key: for \"id_documento_viagem\": values \"676076\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676076",
            "13219939",
            "14353",
            "1948",
            "58",
            "3012",
            "56157",
            "0",
            "51",
            "436",
            "2022-10-27",
            "2022-10-27",
            "634.50",
            "634.50"
          ],
          "rowNumber": 658576,
          "rowPosition": 658577,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676076\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658577\" violates the foreign key: for \"id_documento_viagem\": values \"676076\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676120",
            "13215758",
            "14390",
            "1957",
            "58",
            "3012",
            "56714",
            "0",
            "403",
            "7206",
            "2022-12-14",
            "2022-12-14",
            "366.00",
            "747.30"
          ],
          "rowNumber": 658577,
          "rowPosition": 658578,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676120\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658578\" violates the foreign key: for \"id_documento_viagem\": values \"676120\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676120",
            "13215758",
            "14390",
            "1957",
            "58",
            "3012",
            "56714",
            "0",
            "403",
            "7206",
            "2022-12-14",
            "2022-12-14",
            "366.00",
            "747.30"
          ],
          "rowNumber": 658577,
          "rowPosition": 658578,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676120\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658578\" violates the foreign key: for \"id_documento_viagem\": values \"676120\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676092",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18322",
            "24017",
            "2022-12-26",
            "2022-12-26",
            "0.00",
            "348.30"
          ],
          "rowNumber": 658578,
          "rowPosition": 658579,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676092\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658579\" violates the foreign key: for \"id_documento_viagem\": values \"676092\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676092",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18322",
            "24017",
            "2022-12-26",
            "2022-12-26",
            "0.00",
            "348.30"
          ],
          "rowNumber": 658578,
          "rowPosition": 658579,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676092\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658579\" violates the foreign key: for \"id_documento_viagem\": values \"676092\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676126",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18500",
            "24273",
            "2022-12-28",
            "2022-12-28",
            "0.00",
            "348.30"
          ],
          "rowNumber": 658579,
          "rowPosition": 658580,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676126\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658580\" violates the foreign key: for \"id_documento_viagem\": values \"676126\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676126",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18500",
            "24273",
            "2022-12-28",
            "2022-12-28",
            "0.00",
            "348.30"
          ],
          "rowNumber": 658579,
          "rowPosition": 658580,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676126\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658580\" violates the foreign key: for \"id_documento_viagem\": values \"676126\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676104",
            "13267186",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "85",
            "144",
            "2022-12-26",
            "2022-12-27",
            "0.00",
            "235.00"
          ],
          "rowNumber": 658580,
          "rowPosition": 658581,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676104\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658581\" violates the foreign key: for \"id_documento_viagem\": values \"676104\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676104",
            "13267186",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "85",
            "144",
            "2022-12-26",
            "2022-12-27",
            "0.00",
            "235.00"
          ],
          "rowNumber": 658580,
          "rowPosition": 658581,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676104\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658581\" violates the foreign key: for \"id_documento_viagem\": values \"676104\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676101",
            "13267186",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "90",
            "147",
            "2022-12-26",
            "2022-12-27",
            "0.00",
            "235.00"
          ],
          "rowNumber": 658582,
          "rowPosition": 658583,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676101\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658583\" violates the foreign key: for \"id_documento_viagem\": values \"676101\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676101",
            "13267186",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "90",
            "147",
            "2022-12-26",
            "2022-12-27",
            "0.00",
            "235.00"
          ],
          "rowNumber": 658582,
          "rowPosition": 658583,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676101\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658583\" violates the foreign key: for \"id_documento_viagem\": values \"676101\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676090",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18386",
            "24109",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "90.30"
          ],
          "rowNumber": 658583,
          "rowPosition": 658584,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676090\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658584\" violates the foreign key: for \"id_documento_viagem\": values \"676090\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676090",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18386",
            "24109",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "90.30"
          ],
          "rowNumber": 658583,
          "rowPosition": 658584,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676090\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658584\" violates the foreign key: for \"id_documento_viagem\": values \"676090\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676106",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18350",
            "24047",
            "2022-12-26",
            "2022-12-26",
            "0.00",
            "348.30"
          ],
          "rowNumber": 658584,
          "rowPosition": 658585,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676106\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658585\" violates the foreign key: for \"id_documento_viagem\": values \"676106\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676106",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18350",
            "24047",
            "2022-12-26",
            "2022-12-26",
            "0.00",
            "348.30"
          ],
          "rowNumber": 658584,
          "rowPosition": 658585,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676106\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658585\" violates the foreign key: for \"id_documento_viagem\": values \"676106\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676075",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18173",
            "23759",
            "2022-12-22",
            "2022-12-22",
            "0.00",
            "488.70"
          ],
          "rowNumber": 658585,
          "rowPosition": 658586,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676075\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658586\" violates the foreign key: for \"id_documento_viagem\": values \"676075\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676075",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18173",
            "23759",
            "2022-12-22",
            "2022-12-22",
            "0.00",
            "488.70"
          ],
          "rowNumber": 658585,
          "rowPosition": 658586,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676075\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658586\" violates the foreign key: for \"id_documento_viagem\": values \"676075\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676107",
            "13267186",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "89",
            "146",
            "2022-12-26",
            "2022-12-27",
            "0.00",
            "235.00"
          ],
          "rowNumber": 658586,
          "rowPosition": 658587,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676107\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658587\" violates the foreign key: for \"id_documento_viagem\": values \"676107\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676107",
            "13267186",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "89",
            "146",
            "2022-12-26",
            "2022-12-27",
            "0.00",
            "235.00"
          ],
          "rowNumber": 658586,
          "rowPosition": 658587,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676107\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658587\" violates the foreign key: for \"id_documento_viagem\": values \"676107\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676137",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18192",
            "23780",
            "2022-12-22",
            "2022-12-22",
            "0.00",
            "488.70"
          ],
          "rowNumber": 658587,
          "rowPosition": 658588,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676137\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658588\" violates the foreign key: for \"id_documento_viagem\": values \"676137\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676137",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18192",
            "23780",
            "2022-12-22",
            "2022-12-22",
            "0.00",
            "488.70"
          ],
          "rowNumber": 658587,
          "rowPosition": 658588,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676137\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658588\" violates the foreign key: for \"id_documento_viagem\": values \"676137\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676074",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18330",
            "24026",
            "2022-12-26",
            "2022-12-26",
            "0.00",
            "348.30"
          ],
          "rowNumber": 658588,
          "rowPosition": 658589,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676074\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658589\" violates the foreign key: for \"id_documento_viagem\": values \"676074\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676074",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18330",
            "24026",
            "2022-12-26",
            "2022-12-26",
            "0.00",
            "348.30"
          ],
          "rowNumber": 658588,
          "rowPosition": 658589,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676074\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658589\" violates the foreign key: for \"id_documento_viagem\": values \"676074\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676078",
            "13220200",
            "14280",
            "1957",
            "58",
            "3012",
            "56794",
            "0",
            "778",
            "2497",
            "2022-12-20",
            "2022-12-20",
            "0.00",
            "48.90"
          ],
          "rowNumber": 658589,
          "rowPosition": 658590,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676078\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658590\" violates the foreign key: for \"id_documento_viagem\": values \"676078\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676078",
            "13220200",
            "14280",
            "1957",
            "58",
            "3012",
            "56794",
            "0",
            "778",
            "2497",
            "2022-12-20",
            "2022-12-20",
            "0.00",
            "48.90"
          ],
          "rowNumber": 658589,
          "rowPosition": 658590,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676078\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658590\" violates the foreign key: for \"id_documento_viagem\": values \"676078\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676138",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18449",
            "24190",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "348.30"
          ],
          "rowNumber": 658590,
          "rowPosition": 658591,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676138\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658591\" violates the foreign key: for \"id_documento_viagem\": values \"676138\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676138",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18449",
            "24190",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "348.30"
          ],
          "rowNumber": 658590,
          "rowPosition": 658591,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676138\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658591\" violates the foreign key: for \"id_documento_viagem\": values \"676138\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676093",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18440",
            "24173",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "634.50"
          ],
          "rowNumber": 658592,
          "rowPosition": 658593,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676093\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658593\" violates the foreign key: for \"id_documento_viagem\": values \"676093\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676093",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18440",
            "24173",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "634.50"
          ],
          "rowNumber": 658592,
          "rowPosition": 658593,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676093\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658593\" violates the foreign key: for \"id_documento_viagem\": values \"676093\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676143",
            "13267186",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "86",
            "148",
            "2022-12-26",
            "2022-12-27",
            "0.00",
            "243.00"
          ],
          "rowNumber": 658593,
          "rowPosition": 658594,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676143\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658594\" violates the foreign key: for \"id_documento_viagem\": values \"676143\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676143",
            "13267186",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "86",
            "148",
            "2022-12-26",
            "2022-12-27",
            "0.00",
            "243.00"
          ],
          "rowNumber": 658593,
          "rowPosition": 658594,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676143\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"658594\" violates the foreign key: for \"id_documento_viagem\": values \"676143\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 118
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 118,
    "tasks": 1
  },
  "valid": false
}