{
  "version": "4.38.0",
  "time": 102.897,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_diarias_scdp_liqpag",
        "title": "Diárias SCDP - Liquidação e Pagamento",
        "path": "data/ft_diarias_scdp_liqpag.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_documento_viagem",
              "title": "Documento de Viagem - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "description": "- > \n  Chave estrangeira (Foreign Key) que aponta para a Chave Primária (Primary keys) da tabela dm_tempo_diario. \n  Ou seja, por meio dessa chave é possível identificar a data completa a qual o dado se refere.\n\n  Nota: \n  No site dados.mg.gov.br a tabela dm_tempo_diario pode ser encontrada no recurso Calendários - Dias \n  de cada conjunto.\n",
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_empenho",
              "title": "Número do Empenho - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_programa",
              "title": "Programa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_funcao",
              "title": "Função - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_fonte",
              "title": "Fonte de Recurso - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item de Despesa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_acao",
              "title": "Ação Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "fl_passagem",
              "title": "Passagem - Flag",
              "type": "string",
              "format": "default",
              "description": "- '0' - Diárias\n- '1' - Passagem\n",
              "constraints": {
                "required": true,
                "enum": [
                  "0",
                  "1"
                ]
              }
            },
            {
              "name": "nr_liquidacao",
              "title": "Número Liquidação",
              "type": "string",
              "format": "default",
              "description": "Número do documento de liquidação.\n",
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "nr_pagamento",
              "title": "Número Pagamento",
              "type": "string",
              "format": "default",
              "description": "Número do documento de ordem de pagamento.\n",
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "dt_liquidacao",
              "title": "Data da liquidação",
              "type": "date",
              "format": "default"
            },
            {
              "name": "dt_pagamento",
              "type": "date",
              "format": "default"
            },
            {
              "name": "vr_devolvido",
              "title": "Valor Devolvido",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_liqpag",
              "title": "Valor liquidado/Pago",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "description": "- > \n  Valor pago referente às despesas com diárias e passagens aéreas e terrestres de servidor público ou \n  colaborador eventual em razão de viagem a trabalho.\n",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_funcao"
              ],
              "reference": {
                "fields": [
                  "id_funcao"
                ],
                "resource": "dm_funcao_desp"
              }
            },
            {
              "fields": [
                "id_fonte"
              ],
              "reference": {
                "fields": [
                  "id_fonte"
                ],
                "resource": "dm_fonte"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_programa"
              ],
              "reference": {
                "fields": [
                  "id_programa"
                ],
                "resource": "dm_programa"
              }
            },
            {
              "fields": [
                "id_empenho"
              ],
              "reference": {
                "fields": [
                  "id_empenho"
                ],
                "resource": "dm_empenho_desp_diarias_scdp_liqpag"
              }
            },
            {
              "fields": [
                "id_documento_viagem"
              ],
              "reference": {
                "fields": [
                  "id_documento_viagem"
                ],
                "resource": "dm_documento_viagem"
              }
            },
            {
              "fields": [
                "id_acao"
              ],
              "reference": {
                "fields": [
                  "id_acao"
                ],
                "resource": "dm_acao"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_fonte"
              ],
              "reference": {
                "fields": [
                  "id_fonte"
                ],
                "resource": "dm_fonte"
              }
            },
            {
              "fields": [
                "id_programa"
              ],
              "reference": {
                "fields": [
                  "id_programa"
                ],
                "resource": "dm_programa"
              }
            },
            {
              "fields": [
                "id_documento_viagem"
              ],
              "reference": {
                "fields": [
                  "id_documento_viagem"
                ],
                "resource": "dm_documento_viagem"
              }
            },
            {
              "fields": [
                "id_acao"
              ],
              "reference": {
                "fields": [
                  "id_acao"
                ],
                "resource": "dm_acao"
              }
            },
            {
              "fields": [
                "id_empenho"
              ],
              "reference": {
                "fields": [
                  "id_empenho"
                ],
                "resource": "dm_empenho_desp_diarias_scdp_liqpag"
              }
            },
            {
              "fields": [
                "id_funcao"
              ],
              "reference": {
                "fields": [
                  "id_funcao"
                ],
                "resource": "dm_funcao_desp"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_diarias_scdp_liqpag"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "2dc4b61994f1da1d9e482d33d43e8f23",
          "bytes": 10226814,
          "fields": 14,
          "rows": 660489
        }
      },
      "time": 102.897,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "676204",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18290",
            "23977",
            "2022-12-26",
            "2022-12-26",
            "0.00",
            "634.50"
          ],
          "rowNumber": 660024,
          "rowPosition": 660025,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676204\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660025\" violates the foreign key: for \"id_documento_viagem\": values \"676204\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676204",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18290",
            "23977",
            "2022-12-26",
            "2022-12-26",
            "0.00",
            "634.50"
          ],
          "rowNumber": 660024,
          "rowPosition": 660025,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676204\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660025\" violates the foreign key: for \"id_documento_viagem\": values \"676204\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676212",
            "13215758",
            "14390",
            "1957",
            "58",
            "3012",
            "56714",
            "0",
            "418",
            "7525",
            "2022-12-21",
            "2022-12-21",
            "0.00",
            "1199.70"
          ],
          "rowNumber": 660025,
          "rowPosition": 660026,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676212\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660026\" violates the foreign key: for \"id_documento_viagem\": values \"676212\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676212",
            "13215758",
            "14390",
            "1957",
            "58",
            "3012",
            "56714",
            "0",
            "418",
            "7525",
            "2022-12-21",
            "2022-12-21",
            "0.00",
            "1199.70"
          ],
          "rowNumber": 660025,
          "rowPosition": 660026,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676212\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660026\" violates the foreign key: for \"id_documento_viagem\": values \"676212\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676222",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18291",
            "23978",
            "2022-12-26",
            "2022-12-26",
            "0.00",
            "634.50"
          ],
          "rowNumber": 660026,
          "rowPosition": 660027,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676222\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660027\" violates the foreign key: for \"id_documento_viagem\": values \"676222\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676222",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18291",
            "23978",
            "2022-12-26",
            "2022-12-26",
            "0.00",
            "634.50"
          ],
          "rowNumber": 660026,
          "rowPosition": 660027,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676222\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660027\" violates the foreign key: for \"id_documento_viagem\": values \"676222\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676232",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "339",
            "365",
            "2022-11-25",
            "2022-11-25",
            "0.00",
            "164.50"
          ],
          "rowNumber": 660027,
          "rowPosition": 660028,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676232\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660028\" violates the foreign key: for \"id_documento_viagem\": values \"676232\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676232",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "339",
            "365",
            "2022-11-25",
            "2022-11-25",
            "0.00",
            "164.50"
          ],
          "rowNumber": 660027,
          "rowPosition": 660028,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676232\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660028\" violates the foreign key: for \"id_documento_viagem\": values \"676232\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676247",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18292",
            "23979",
            "2022-12-26",
            "2022-12-26",
            "0.00",
            "634.50"
          ],
          "rowNumber": 660028,
          "rowPosition": 660029,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676247\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660029\" violates the foreign key: for \"id_documento_viagem\": values \"676247\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676247",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18292",
            "23979",
            "2022-12-26",
            "2022-12-26",
            "0.00",
            "634.50"
          ],
          "rowNumber": 660028,
          "rowPosition": 660029,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676247\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660029\" violates the foreign key: for \"id_documento_viagem\": values \"676247\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676201",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "340",
            "366",
            "2022-11-25",
            "2022-11-25",
            "0.00",
            "164.50"
          ],
          "rowNumber": 660029,
          "rowPosition": 660030,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676201\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660030\" violates the foreign key: for \"id_documento_viagem\": values \"676201\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676201",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "340",
            "366",
            "2022-11-25",
            "2022-11-25",
            "0.00",
            "164.50"
          ],
          "rowNumber": 660029,
          "rowPosition": 660030,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676201\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660030\" violates the foreign key: for \"id_documento_viagem\": values \"676201\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676206",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18259",
            "23906",
            "2022-12-23",
            "2022-12-23",
            "0.00",
            "90.30"
          ],
          "rowNumber": 660030,
          "rowPosition": 660031,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676206\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660031\" violates the foreign key: for \"id_documento_viagem\": values \"676206\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676206",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18259",
            "23906",
            "2022-12-23",
            "2022-12-23",
            "0.00",
            "90.30"
          ],
          "rowNumber": 660030,
          "rowPosition": 660031,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676206\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660031\" violates the foreign key: for \"id_documento_viagem\": values \"676206\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676210",
            "13336259",
            "14385",
            "1963",
            "58",
            "3012",
            "56393",
            "0",
            "12",
            "124",
            "2022-12-07",
            "2022-12-08",
            "0.00",
            "2464.60"
          ],
          "rowNumber": 660031,
          "rowPosition": 660032,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676210\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660032\" violates the foreign key: for \"id_documento_viagem\": values \"676210\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676210",
            "13336259",
            "14385",
            "1963",
            "58",
            "3012",
            "56393",
            "0",
            "12",
            "124",
            "2022-12-07",
            "2022-12-08",
            "0.00",
            "2464.60"
          ],
          "rowNumber": 660031,
          "rowPosition": 660032,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676210\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660032\" violates the foreign key: for \"id_documento_viagem\": values \"676210\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676211",
            "13224994",
            "14345",
            "1963",
            "58",
            "3012",
            "56580",
            "0",
            "68",
            "83",
            "2022-06-29",
            "2022-07-08",
            "94.02",
            "803.73"
          ],
          "rowNumber": 660032,
          "rowPosition": 660033,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676211\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660033\" violates the foreign key: for \"id_documento_viagem\": values \"676211\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676211",
            "13224994",
            "14345",
            "1963",
            "58",
            "3012",
            "56580",
            "0",
            "68",
            "83",
            "2022-06-29",
            "2022-07-08",
            "94.02",
            "803.73"
          ],
          "rowNumber": 660032,
          "rowPosition": 660033,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676211\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660033\" violates the foreign key: for \"id_documento_viagem\": values \"676211\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676219",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18532",
            "24307",
            "2022-12-28",
            "2022-12-28",
            "0.00",
            "180.60"
          ],
          "rowNumber": 660033,
          "rowPosition": 660034,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676219\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660034\" violates the foreign key: for \"id_documento_viagem\": values \"676219\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676219",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18532",
            "24307",
            "2022-12-28",
            "2022-12-28",
            "0.00",
            "180.60"
          ],
          "rowNumber": 660033,
          "rowPosition": 660034,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676219\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660034\" violates the foreign key: for \"id_documento_viagem\": values \"676219\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676236",
            "13215758",
            "14390",
            "1957",
            "58",
            "3012",
            "56714",
            "0",
            "413",
            "7321",
            "2022-12-16",
            "2022-12-16",
            "0.00",
            "747.30"
          ],
          "rowNumber": 660034,
          "rowPosition": 660035,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676236\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660035\" violates the foreign key: for \"id_documento_viagem\": values \"676236\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676236",
            "13215758",
            "14390",
            "1957",
            "58",
            "3012",
            "56714",
            "0",
            "413",
            "7321",
            "2022-12-16",
            "2022-12-16",
            "0.00",
            "747.30"
          ],
          "rowNumber": 660034,
          "rowPosition": 660035,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676236\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660035\" violates the foreign key: for \"id_documento_viagem\": values \"676236\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676250",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18389",
            "24112",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "90.30"
          ],
          "rowNumber": 660035,
          "rowPosition": 660036,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676250\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660036\" violates the foreign key: for \"id_documento_viagem\": values \"676250\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676250",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18389",
            "24112",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "90.30"
          ],
          "rowNumber": 660035,
          "rowPosition": 660036,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676250\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660036\" violates the foreign key: for \"id_documento_viagem\": values \"676250\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676205",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "343",
            "369",
            "2022-11-25",
            "2022-11-25",
            "0.00",
            "164.50"
          ],
          "rowNumber": 660036,
          "rowPosition": 660037,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676205\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660037\" violates the foreign key: for \"id_documento_viagem\": values \"676205\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676205",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "343",
            "369",
            "2022-11-25",
            "2022-11-25",
            "0.00",
            "164.50"
          ],
          "rowNumber": 660036,
          "rowPosition": 660037,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676205\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660037\" violates the foreign key: for \"id_documento_viagem\": values \"676205\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676216",
            "13215178",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "1734",
            "23419",
            "2022-12-19",
            "2022-12-19",
            "0.00",
            "912.70"
          ],
          "rowNumber": 660037,
          "rowPosition": 660038,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676216\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660038\" violates the foreign key: for \"id_documento_viagem\": values \"676216\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676216",
            "13215178",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "1734",
            "23419",
            "2022-12-19",
            "2022-12-19",
            "0.00",
            "912.70"
          ],
          "rowNumber": 660037,
          "rowPosition": 660038,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676216\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660038\" violates the foreign key: for \"id_documento_viagem\": values \"676216\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676220",
            "13215178",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "1733",
            "23418",
            "2022-12-19",
            "2022-12-19",
            "0.00",
            "912.70"
          ],
          "rowNumber": 660038,
          "rowPosition": 660039,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676220\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660039\" violates the foreign key: for \"id_documento_viagem\": values \"676220\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676220",
            "13215178",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "1733",
            "23418",
            "2022-12-19",
            "2022-12-19",
            "0.00",
            "912.70"
          ],
          "rowNumber": 660038,
          "rowPosition": 660039,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676220\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660039\" violates the foreign key: for \"id_documento_viagem\": values \"676220\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676237",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18528",
            "24303",
            "2022-12-28",
            "2022-12-28",
            "0.00",
            "180.60"
          ],
          "rowNumber": 660039,
          "rowPosition": 660040,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676237\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660040\" violates the foreign key: for \"id_documento_viagem\": values \"676237\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676237",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18528",
            "24303",
            "2022-12-28",
            "2022-12-28",
            "0.00",
            "180.60"
          ],
          "rowNumber": 660039,
          "rowPosition": 660040,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676237\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660040\" violates the foreign key: for \"id_documento_viagem\": values \"676237\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676225",
            "13215758",
            "14390",
            "1957",
            "58",
            "3012",
            "56714",
            "0",
            "419",
            "7526",
            "2022-12-21",
            "2022-12-21",
            "0.00",
            "1199.70"
          ],
          "rowNumber": 660040,
          "rowPosition": 660041,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676225\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660041\" violates the foreign key: for \"id_documento_viagem\": values \"676225\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676225",
            "13215758",
            "14390",
            "1957",
            "58",
            "3012",
            "56714",
            "0",
            "419",
            "7526",
            "2022-12-21",
            "2022-12-21",
            "0.00",
            "1199.70"
          ],
          "rowNumber": 660040,
          "rowPosition": 660041,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676225\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660041\" violates the foreign key: for \"id_documento_viagem\": values \"676225\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676214",
            "13215758",
            "14390",
            "1957",
            "58",
            "3012",
            "56714",
            "0",
            "416",
            "7328",
            "2022-12-16",
            "2022-12-16",
            "0.00",
            "747.30"
          ],
          "rowNumber": 660041,
          "rowPosition": 660042,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676214\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660042\" violates the foreign key: for \"id_documento_viagem\": values \"676214\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676214",
            "13215758",
            "14390",
            "1957",
            "58",
            "3012",
            "56714",
            "0",
            "416",
            "7328",
            "2022-12-16",
            "2022-12-16",
            "0.00",
            "747.30"
          ],
          "rowNumber": 660041,
          "rowPosition": 660042,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676214\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660042\" violates the foreign key: for \"id_documento_viagem\": values \"676214\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676233",
            "13216636",
            "14389",
            "1957",
            "58",
            "3012",
            "56228",
            "0",
            "24",
            "4863",
            "2022-12-28",
            "2022-12-28",
            "0.00",
            "822.30"
          ],
          "rowNumber": 660042,
          "rowPosition": 660043,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676233\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660043\" violates the foreign key: for \"id_documento_viagem\": values \"676233\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676233",
            "13216636",
            "14389",
            "1957",
            "58",
            "3012",
            "56228",
            "0",
            "24",
            "4863",
            "2022-12-28",
            "2022-12-28",
            "0.00",
            "822.30"
          ],
          "rowNumber": 660042,
          "rowPosition": 660043,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676233\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660043\" violates the foreign key: for \"id_documento_viagem\": values \"676233\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676221",
            "13224994",
            "14345",
            "1963",
            "58",
            "3012",
            "56580",
            "0",
            "69",
            "84",
            "2022-06-29",
            "2022-07-08",
            "94.02",
            "803.73"
          ],
          "rowNumber": 660043,
          "rowPosition": 660044,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676221\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660044\" violates the foreign key: for \"id_documento_viagem\": values \"676221\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676221",
            "13224994",
            "14345",
            "1963",
            "58",
            "3012",
            "56580",
            "0",
            "69",
            "84",
            "2022-06-29",
            "2022-07-08",
            "94.02",
            "803.73"
          ],
          "rowNumber": 660043,
          "rowPosition": 660044,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676221\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660044\" violates the foreign key: for \"id_documento_viagem\": values \"676221\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676234",
            "13216636",
            "14389",
            "1957",
            "58",
            "3012",
            "56228",
            "0",
            "19",
            "4626",
            "2022-12-12",
            "2022-12-12",
            "0.00",
            "581.30"
          ],
          "rowNumber": 660044,
          "rowPosition": 660045,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676234\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660045\" violates the foreign key: for \"id_documento_viagem\": values \"676234\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676234",
            "13216636",
            "14389",
            "1957",
            "58",
            "3012",
            "56228",
            "0",
            "19",
            "4626",
            "2022-12-12",
            "2022-12-12",
            "0.00",
            "581.30"
          ],
          "rowNumber": 660044,
          "rowPosition": 660045,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676234\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660045\" violates the foreign key: for \"id_documento_viagem\": values \"676234\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676203",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18288",
            "23975",
            "2022-12-26",
            "2022-12-26",
            "0.00",
            "634.50"
          ],
          "rowNumber": 660045,
          "rowPosition": 660046,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676203\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660046\" violates the foreign key: for \"id_documento_viagem\": values \"676203\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676203",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18288",
            "23975",
            "2022-12-26",
            "2022-12-26",
            "0.00",
            "634.50"
          ],
          "rowNumber": 660045,
          "rowPosition": 660046,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676203\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660046\" violates the foreign key: for \"id_documento_viagem\": values \"676203\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676249",
            "13243366",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "97",
            "97",
            "2022-12-23",
            "2022-12-23",
            "0.00",
            "235.00"
          ],
          "rowNumber": 660046,
          "rowPosition": 660047,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676249\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660047\" violates the foreign key: for \"id_documento_viagem\": values \"676249\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676249",
            "13243366",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "97",
            "97",
            "2022-12-23",
            "2022-12-23",
            "0.00",
            "235.00"
          ],
          "rowNumber": 660046,
          "rowPosition": 660047,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676249\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660047\" violates the foreign key: for \"id_documento_viagem\": values \"676249\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676238",
            "13224994",
            "14345",
            "1963",
            "58",
            "3012",
            "56580",
            "0",
            "30",
            "45",
            "2022-04-13",
            "2022-04-18",
            "0.00",
            "136.50"
          ],
          "rowNumber": 660047,
          "rowPosition": 660048,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676238\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660048\" violates the foreign key: for \"id_documento_viagem\": values \"676238\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676238",
            "13224994",
            "14345",
            "1963",
            "58",
            "3012",
            "56580",
            "0",
            "30",
            "45",
            "2022-04-13",
            "2022-04-18",
            "0.00",
            "136.50"
          ],
          "rowNumber": 660047,
          "rowPosition": 660048,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676238\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660048\" violates the foreign key: for \"id_documento_viagem\": values \"676238\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676235",
            "13215178",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "1735",
            "23421",
            "2022-12-19",
            "2022-12-19",
            "0.00",
            "912.70"
          ],
          "rowNumber": 660048,
          "rowPosition": 660049,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676235\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660049\" violates the foreign key: for \"id_documento_viagem\": values \"676235\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676235",
            "13215178",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "1735",
            "23421",
            "2022-12-19",
            "2022-12-19",
            "0.00",
            "912.70"
          ],
          "rowNumber": 660048,
          "rowPosition": 660049,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676235\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660049\" violates the foreign key: for \"id_documento_viagem\": values \"676235\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676217",
            "13215758",
            "14390",
            "1957",
            "58",
            "3012",
            "56714",
            "0",
            "411",
            "7300",
            "2022-12-15",
            "2022-12-15",
            "0.00",
            "564.30"
          ],
          "rowNumber": 660049,
          "rowPosition": 660050,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676217\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660050\" violates the foreign key: for \"id_documento_viagem\": values \"676217\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676217",
            "13215758",
            "14390",
            "1957",
            "58",
            "3012",
            "56714",
            "0",
            "411",
            "7300",
            "2022-12-15",
            "2022-12-15",
            "0.00",
            "564.30"
          ],
          "rowNumber": 660049,
          "rowPosition": 660050,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676217\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660050\" violates the foreign key: for \"id_documento_viagem\": values \"676217\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676228",
            "13611952",
            "14385",
            "1963",
            "58",
            "3012",
            "56393",
            "0",
            "1",
            "93",
            "2022-12-19",
            "2022-12-20",
            "0.00",
            "2464.60"
          ],
          "rowNumber": 660050,
          "rowPosition": 660051,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676228\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660051\" violates the foreign key: for \"id_documento_viagem\": values \"676228\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676228",
            "13611952",
            "14385",
            "1963",
            "58",
            "3012",
            "56393",
            "0",
            "1",
            "93",
            "2022-12-19",
            "2022-12-20",
            "0.00",
            "2464.60"
          ],
          "rowNumber": 660050,
          "rowPosition": 660051,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676228\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660051\" violates the foreign key: for \"id_documento_viagem\": values \"676228\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676218",
            "13227958",
            "14390",
            "1950",
            "58",
            "3012",
            "56714",
            "0",
            "126",
            "1973",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "348.30"
          ],
          "rowNumber": 660051,
          "rowPosition": 660052,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676218\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660052\" violates the foreign key: for \"id_documento_viagem\": values \"676218\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676218",
            "13227958",
            "14390",
            "1950",
            "58",
            "3012",
            "56714",
            "0",
            "126",
            "1973",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "348.30"
          ],
          "rowNumber": 660051,
          "rowPosition": 660052,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676218\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660052\" violates the foreign key: for \"id_documento_viagem\": values \"676218\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676202",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18529",
            "24304",
            "2022-12-28",
            "2022-12-28",
            "0.00",
            "180.60"
          ],
          "rowNumber": 660052,
          "rowPosition": 660053,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676202\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660053\" violates the foreign key: for \"id_documento_viagem\": values \"676202\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676202",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18529",
            "24304",
            "2022-12-28",
            "2022-12-28",
            "0.00",
            "180.60"
          ],
          "rowNumber": 660052,
          "rowPosition": 660053,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676202\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660053\" violates the foreign key: for \"id_documento_viagem\": values \"676202\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676248",
            "13215178",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "1738",
            "23424",
            "2022-12-19",
            "2022-12-19",
            "0.00",
            "912.70"
          ],
          "rowNumber": 660053,
          "rowPosition": 660054,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676248\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660054\" violates the foreign key: for \"id_documento_viagem\": values \"676248\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676248",
            "13215178",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "1738",
            "23424",
            "2022-12-19",
            "2022-12-19",
            "0.00",
            "912.70"
          ],
          "rowNumber": 660053,
          "rowPosition": 660054,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676248\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660054\" violates the foreign key: for \"id_documento_viagem\": values \"676248\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676215",
            "13224994",
            "14345",
            "1963",
            "58",
            "3012",
            "56580",
            "0",
            "27",
            "44",
            "2022-04-11",
            "2022-04-18",
            "0.00",
            "273.00"
          ],
          "rowNumber": 660054,
          "rowPosition": 660055,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676215\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660055\" violates the foreign key: for \"id_documento_viagem\": values \"676215\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676215",
            "13224994",
            "14345",
            "1963",
            "58",
            "3012",
            "56580",
            "0",
            "27",
            "44",
            "2022-04-11",
            "2022-04-18",
            "0.00",
            "273.00"
          ],
          "rowNumber": 660054,
          "rowPosition": 660055,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676215\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660055\" violates the foreign key: for \"id_documento_viagem\": values \"676215\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676243",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18241",
            "23888",
            "2022-12-23",
            "2022-12-23",
            "90.30",
            "90.30"
          ],
          "rowNumber": 660055,
          "rowPosition": 660056,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676243\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660056\" violates the foreign key: for \"id_documento_viagem\": values \"676243\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676243",
            "13215487",
            "14304",
            "1957",
            "58",
            "3012",
            "56341",
            "0",
            "18241",
            "23888",
            "2022-12-23",
            "2022-12-23",
            "90.30",
            "90.30"
          ],
          "rowNumber": 660055,
          "rowPosition": 660056,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676243\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660056\" violates the foreign key: for \"id_documento_viagem\": values \"676243\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676211",
            "13233727",
            "14390",
            "1950",
            "58",
            "2772",
            "56714",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "566.01"
          ],
          "rowNumber": 660056,
          "rowPosition": 660057,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676211\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660057\" violates the foreign key: for \"id_documento_viagem\": values \"676211\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676211",
            "13233727",
            "14390",
            "1950",
            "58",
            "2772",
            "56714",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "566.01"
          ],
          "rowNumber": 660056,
          "rowPosition": 660057,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676211\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660057\" violates the foreign key: for \"id_documento_viagem\": values \"676211\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676211",
            "13233727",
            "14390",
            "1950",
            "58",
            "2772",
            "56714",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "617.90"
          ],
          "rowNumber": 660057,
          "rowPosition": 660058,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676211\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660058\" violates the foreign key: for \"id_documento_viagem\": values \"676211\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676211",
            "13233727",
            "14390",
            "1950",
            "58",
            "2772",
            "56714",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "617.90"
          ],
          "rowNumber": 660057,
          "rowPosition": 660058,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676211\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660058\" violates the foreign key: for \"id_documento_viagem\": values \"676211\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676221",
            "13233727",
            "14390",
            "1950",
            "58",
            "2772",
            "56714",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "916.30"
          ],
          "rowNumber": 660058,
          "rowPosition": 660059,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676221\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660059\" violates the foreign key: for \"id_documento_viagem\": values \"676221\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676221",
            "13233727",
            "14390",
            "1950",
            "58",
            "2772",
            "56714",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "916.30"
          ],
          "rowNumber": 660058,
          "rowPosition": 660059,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676221\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660059\" violates the foreign key: for \"id_documento_viagem\": values \"676221\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676221",
            "13233727",
            "14390",
            "1950",
            "58",
            "2772",
            "56714",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "617.90"
          ],
          "rowNumber": 660059,
          "rowPosition": 660060,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676221\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660060\" violates the foreign key: for \"id_documento_viagem\": values \"676221\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676221",
            "13233727",
            "14390",
            "1950",
            "58",
            "2772",
            "56714",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "617.90"
          ],
          "rowNumber": 660059,
          "rowPosition": 660060,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676221\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660060\" violates the foreign key: for \"id_documento_viagem\": values \"676221\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 72
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 72,
    "tasks": 1
  },
  "valid": false
}