{
  "version": "4.16.6",
  "time": 141.897,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_diarias_scdp_liqpag",
        "title": "Diárias SCDP - Liquidação e Pagamento",
        "path": "data/ft_diarias_scdp_liqpag.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_documento_viagem",
              "title": "Documento de Viagem - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "description": "- > \n  Chave estrangeira (Foreign Key) que aponta para a Chave Primária (Primary keys) da tabela dm_tempo_diario. \n  Ou seja, por meio dessa chave é possível identificar a data completa a qual o dado se refere.\n\n  Nota: \n  No site dados.mg.gov.br a tabela dm_tempo_diario pode ser encontrada no recurso Calendários - Dias \n  de cada conjunto.\n",
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_empenho",
              "title": "Número do Empenho - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_programa",
              "title": "Programa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_funcao",
              "title": "Função - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_fonte",
              "title": "Fonte de Recurso - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item de Despesa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_acao",
              "title": "Ação Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "fl_passagem",
              "title": "Passagem - Flag",
              "type": "string",
              "format": "default",
              "description": "- '0' - Diárias\n- '1' - Passagem\n",
              "constraints": {
                "required": true,
                "enum": [
                  "0",
                  "1"
                ]
              }
            },
            {
              "name": "nr_liquidacao",
              "title": "Número Liquidação",
              "type": "string",
              "format": "default",
              "description": "Número do documento de liquidação.\n",
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "nr_pagamento",
              "title": "Número Pagamento",
              "type": "string",
              "format": "default",
              "description": "Número do documento de ordem de pagamento.\n",
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "dt_liquidacao",
              "title": "Data da liquidação",
              "type": "date",
              "format": "default"
            },
            {
              "name": "dt_pagamento",
              "type": "date",
              "format": "default"
            },
            {
              "name": "vr_devolvido",
              "title": "Valor Devolvido",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_liqpag",
              "title": "Valor liquidado/Pago",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "description": "- > \n  Valor pago referente às despesas com diárias e passagens aéreas e terrestres de servidor público ou \n  colaborador eventual em razão de viagem a trabalho.\n",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_funcao"
              ],
              "reference": {
                "fields": [
                  "id_funcao"
                ],
                "resource": "dm_funcao_desp"
              }
            },
            {
              "fields": [
                "id_fonte"
              ],
              "reference": {
                "fields": [
                  "id_fonte"
                ],
                "resource": "dm_fonte"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_programa"
              ],
              "reference": {
                "fields": [
                  "id_programa"
                ],
                "resource": "dm_programa"
              }
            },
            {
              "fields": [
                "id_empenho"
              ],
              "reference": {
                "fields": [
                  "id_empenho"
                ],
                "resource": "dm_empenho_desp_diarias_scdp_liqpag"
              }
            },
            {
              "fields": [
                "id_documento_viagem"
              ],
              "reference": {
                "fields": [
                  "id_documento_viagem"
                ],
                "resource": "dm_documento_viagem"
              }
            },
            {
              "fields": [
                "id_acao"
              ],
              "reference": {
                "fields": [
                  "id_acao"
                ],
                "resource": "dm_acao"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_fonte"
              ],
              "reference": {
                "fields": [
                  "id_fonte"
                ],
                "resource": "dm_fonte"
              }
            },
            {
              "fields": [
                "id_programa"
              ],
              "reference": {
                "fields": [
                  "id_programa"
                ],
                "resource": "dm_programa"
              }
            },
            {
              "fields": [
                "id_documento_viagem"
              ],
              "reference": {
                "fields": [
                  "id_documento_viagem"
                ],
                "resource": "dm_documento_viagem"
              }
            },
            {
              "fields": [
                "id_acao"
              ],
              "reference": {
                "fields": [
                  "id_acao"
                ],
                "resource": "dm_acao"
              }
            },
            {
              "fields": [
                "id_empenho"
              ],
              "reference": {
                "fields": [
                  "id_empenho"
                ],
                "resource": "dm_empenho_desp_diarias_scdp_liqpag"
              }
            },
            {
              "fields": [
                "id_funcao"
              ],
              "reference": {
                "fields": [
                  "id_funcao"
                ],
                "resource": "dm_funcao_desp"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_diarias_scdp_liqpag"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "c5e35b61682bca2ae3e27a08b71bc027",
          "bytes": 12166074,
          "fields": 14,
          "rows": 781669
        }
      },
      "time": 141.897,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780893,
          "rowPosition": 780894,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780894\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780893,
          "rowPosition": 780894,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780894\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780894,
          "rowPosition": 780895,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780895\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780894,
          "rowPosition": 780895,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780895\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780895,
          "rowPosition": 780896,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780896\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780895,
          "rowPosition": 780896,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780896\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780896,
          "rowPosition": 780897,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780897\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780896,
          "rowPosition": 780897,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780897\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780897,
          "rowPosition": 780898,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780898\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780897,
          "rowPosition": 780898,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780898\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780898,
          "rowPosition": 780899,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780899\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780898,
          "rowPosition": 780899,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780899\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780899,
          "rowPosition": 780900,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780900\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780899,
          "rowPosition": 780900,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780900\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780902,
          "rowPosition": 780903,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780903\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780902,
          "rowPosition": 780903,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780903\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780903,
          "rowPosition": 780904,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780904\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780903,
          "rowPosition": 780904,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780904\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780904,
          "rowPosition": 780905,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780905\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780904,
          "rowPosition": 780905,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780905\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780905,
          "rowPosition": 780906,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780906\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780905,
          "rowPosition": 780906,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780906\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780906,
          "rowPosition": 780907,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780907\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780906,
          "rowPosition": 780907,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780907\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780907,
          "rowPosition": 780908,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780908\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780907,
          "rowPosition": 780908,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780908\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780908,
          "rowPosition": 780909,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780909\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780908,
          "rowPosition": 780909,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780909\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780911,
          "rowPosition": 780912,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780912\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780911,
          "rowPosition": 780912,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780912\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780912,
          "rowPosition": 780913,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780913\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780912,
          "rowPosition": 780913,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780913\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780913,
          "rowPosition": 780914,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780914\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780913,
          "rowPosition": 780914,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780914\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780918,
          "rowPosition": 780919,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780919\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780918,
          "rowPosition": 780919,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780919\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780919,
          "rowPosition": 780920,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780920\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780919,
          "rowPosition": 780920,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780920\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780920,
          "rowPosition": 780921,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780921\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780920,
          "rowPosition": 780921,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780921\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780921,
          "rowPosition": 780922,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780922\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780921,
          "rowPosition": 780922,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780922\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780922,
          "rowPosition": 780923,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780923\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780922,
          "rowPosition": 780923,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780923\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780923,
          "rowPosition": 780924,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780924\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780923,
          "rowPosition": 780924,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780924\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780926,
          "rowPosition": 780927,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780927\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780926,
          "rowPosition": 780927,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780927\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780927,
          "rowPosition": 780928,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780928\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780927,
          "rowPosition": 780928,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780928\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780928,
          "rowPosition": 780929,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780929\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780928,
          "rowPosition": 780929,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780929\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780929,
          "rowPosition": 780930,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780930\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780929,
          "rowPosition": 780930,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780930\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780930,
          "rowPosition": 780931,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780931\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780930,
          "rowPosition": 780931,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780931\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780931,
          "rowPosition": 780932,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780932\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780931,
          "rowPosition": 780932,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780932\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780932,
          "rowPosition": 780933,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780933\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780932,
          "rowPosition": 780933,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780933\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780933,
          "rowPosition": 780934,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780934\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780933,
          "rowPosition": 780934,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780934\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780934,
          "rowPosition": 780935,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780935\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780934,
          "rowPosition": 780935,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780935\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780935,
          "rowPosition": 780936,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780936\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780935,
          "rowPosition": 780936,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780936\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780936,
          "rowPosition": 780937,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780937\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780936,
          "rowPosition": 780937,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780937\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 68
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 68,
    "tasks": 1
  },
  "valid": false
}