{
  "version": "4.38.0",
  "time": 103.459,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_diarias_scdp_liqpag",
        "title": "Diárias SCDP - Liquidação e Pagamento",
        "path": "data/ft_diarias_scdp_liqpag.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_documento_viagem",
              "title": "Documento de Viagem - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "description": "- > \n  Chave estrangeira (Foreign Key) que aponta para a Chave Primária (Primary keys) da tabela dm_tempo_diario. \n  Ou seja, por meio dessa chave é possível identificar a data completa a qual o dado se refere.\n\n  Nota: \n  No site dados.mg.gov.br a tabela dm_tempo_diario pode ser encontrada no recurso Calendários - Dias \n  de cada conjunto.\n",
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_empenho",
              "title": "Número do Empenho - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_programa",
              "title": "Programa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_funcao",
              "title": "Função - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_fonte",
              "title": "Fonte de Recurso - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item de Despesa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_acao",
              "title": "Ação Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "fl_passagem",
              "title": "Passagem - Flag",
              "type": "string",
              "format": "default",
              "description": "- '0' - Diárias\n- '1' - Passagem\n",
              "constraints": {
                "required": true,
                "enum": [
                  "0",
                  "1"
                ]
              }
            },
            {
              "name": "nr_liquidacao",
              "title": "Número Liquidação",
              "type": "string",
              "format": "default",
              "description": "Número do documento de liquidação.\n",
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "nr_pagamento",
              "title": "Número Pagamento",
              "type": "string",
              "format": "default",
              "description": "Número do documento de ordem de pagamento.\n",
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "dt_liquidacao",
              "title": "Data da liquidação",
              "type": "date",
              "format": "default"
            },
            {
              "name": "dt_pagamento",
              "type": "date",
              "format": "default"
            },
            {
              "name": "vr_devolvido",
              "title": "Valor Devolvido",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_liqpag",
              "title": "Valor liquidado/Pago",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "description": "- > \n  Valor pago referente às despesas com diárias e passagens aéreas e terrestres de servidor público ou \n  colaborador eventual em razão de viagem a trabalho.\n",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_funcao"
              ],
              "reference": {
                "fields": [
                  "id_funcao"
                ],
                "resource": "dm_funcao_desp"
              }
            },
            {
              "fields": [
                "id_fonte"
              ],
              "reference": {
                "fields": [
                  "id_fonte"
                ],
                "resource": "dm_fonte"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_programa"
              ],
              "reference": {
                "fields": [
                  "id_programa"
                ],
                "resource": "dm_programa"
              }
            },
            {
              "fields": [
                "id_empenho"
              ],
              "reference": {
                "fields": [
                  "id_empenho"
                ],
                "resource": "dm_empenho_desp_diarias_scdp_liqpag"
              }
            },
            {
              "fields": [
                "id_documento_viagem"
              ],
              "reference": {
                "fields": [
                  "id_documento_viagem"
                ],
                "resource": "dm_documento_viagem"
              }
            },
            {
              "fields": [
                "id_acao"
              ],
              "reference": {
                "fields": [
                  "id_acao"
                ],
                "resource": "dm_acao"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_fonte"
              ],
              "reference": {
                "fields": [
                  "id_fonte"
                ],
                "resource": "dm_fonte"
              }
            },
            {
              "fields": [
                "id_programa"
              ],
              "reference": {
                "fields": [
                  "id_programa"
                ],
                "resource": "dm_programa"
              }
            },
            {
              "fields": [
                "id_documento_viagem"
              ],
              "reference": {
                "fields": [
                  "id_documento_viagem"
                ],
                "resource": "dm_documento_viagem"
              }
            },
            {
              "fields": [
                "id_acao"
              ],
              "reference": {
                "fields": [
                  "id_acao"
                ],
                "resource": "dm_acao"
              }
            },
            {
              "fields": [
                "id_empenho"
              ],
              "reference": {
                "fields": [
                  "id_empenho"
                ],
                "resource": "dm_empenho_desp_diarias_scdp_liqpag"
              }
            },
            {
              "fields": [
                "id_funcao"
              ],
              "reference": {
                "fields": [
                  "id_funcao"
                ],
                "resource": "dm_funcao_desp"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_diarias_scdp_liqpag"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "ae715059ba5924842ce4d943c0a85cb6",
          "bytes": 10226239,
          "fields": 14,
          "rows": 660454
        }
      },
      "time": 103.459,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "676179",
            "13224994",
            "14345",
            "1963",
            "58",
            "3012",
            "56580",
            "0",
            "133",
            "145",
            "2022-12-21",
            "2022-12-26",
            "0.00",
            "448.38"
          ],
          "rowNumber": 655391,
          "rowPosition": 655392,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676179\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655392\" violates the foreign key: for \"id_documento_viagem\": values \"676179\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676179",
            "13224994",
            "14345",
            "1963",
            "58",
            "3012",
            "56580",
            "0",
            "133",
            "145",
            "2022-12-21",
            "2022-12-26",
            "0.00",
            "448.38"
          ],
          "rowNumber": 655391,
          "rowPosition": 655392,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676179\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655392\" violates the foreign key: for \"id_documento_viagem\": values \"676179\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676152",
            "12874642",
            "14168",
            "1936",
            "58",
            "3012",
            "55630",
            "0",
            "85",
            "89",
            "2021-12-27",
            "2021-12-29",
            "0.00",
            "136.50"
          ],
          "rowNumber": 655392,
          "rowPosition": 655393,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676152\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655393\" violates the foreign key: for \"id_documento_viagem\": values \"676152\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676152",
            "12874642",
            "14168",
            "1936",
            "58",
            "3012",
            "55630",
            "0",
            "85",
            "89",
            "2021-12-27",
            "2021-12-29",
            "0.00",
            "136.50"
          ],
          "rowNumber": 655392,
          "rowPosition": 655393,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676152\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655393\" violates the foreign key: for \"id_documento_viagem\": values \"676152\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676186",
            "13240804",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "131",
            "3636",
            "2022-11-23",
            "2022-11-23",
            "0.00",
            "158.81"
          ],
          "rowNumber": 655393,
          "rowPosition": 655394,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676186\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655394\" violates the foreign key: for \"id_documento_viagem\": values \"676186\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676186",
            "13240804",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "131",
            "3636",
            "2022-11-23",
            "2022-11-23",
            "0.00",
            "158.81"
          ],
          "rowNumber": 655393,
          "rowPosition": 655394,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676186\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655394\" violates the foreign key: for \"id_documento_viagem\": values \"676186\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676196",
            "13240804",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "121",
            "3626",
            "2022-11-23",
            "2022-11-23",
            "0.00",
            "226.80"
          ],
          "rowNumber": 655394,
          "rowPosition": 655395,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676196\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655395\" violates the foreign key: for \"id_documento_viagem\": values \"676196\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676196",
            "13240804",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "121",
            "3626",
            "2022-11-23",
            "2022-11-23",
            "0.00",
            "226.80"
          ],
          "rowNumber": 655394,
          "rowPosition": 655395,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676196\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655395\" violates the foreign key: for \"id_documento_viagem\": values \"676196\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676180",
            "13240804",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "132",
            "3637",
            "2022-11-23",
            "2022-11-23",
            "0.00",
            "129.00"
          ],
          "rowNumber": 655395,
          "rowPosition": 655396,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676180\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655396\" violates the foreign key: for \"id_documento_viagem\": values \"676180\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676180",
            "13240804",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "132",
            "3637",
            "2022-11-23",
            "2022-11-23",
            "0.00",
            "129.00"
          ],
          "rowNumber": 655395,
          "rowPosition": 655396,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676180\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655396\" violates the foreign key: for \"id_documento_viagem\": values \"676180\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676149",
            "13234420",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "118",
            "143",
            "2022-11-29",
            "2022-11-30",
            "0.00",
            "129.00"
          ],
          "rowNumber": 655396,
          "rowPosition": 655397,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676149\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655397\" violates the foreign key: for \"id_documento_viagem\": values \"676149\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676149",
            "13234420",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "118",
            "143",
            "2022-11-29",
            "2022-11-30",
            "0.00",
            "129.00"
          ],
          "rowNumber": 655396,
          "rowPosition": 655397,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676149\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655397\" violates the foreign key: for \"id_documento_viagem\": values \"676149\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676173",
            "13241114",
            "14390",
            "1948",
            "58",
            "3012",
            "56714",
            "0",
            "429",
            "10324",
            "2022-12-23",
            "2022-12-23",
            "0.00",
            "254.13"
          ],
          "rowNumber": 655398,
          "rowPosition": 655399,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676173\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655399\" violates the foreign key: for \"id_documento_viagem\": values \"676173\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676173",
            "13241114",
            "14390",
            "1948",
            "58",
            "3012",
            "56714",
            "0",
            "429",
            "10324",
            "2022-12-23",
            "2022-12-23",
            "0.00",
            "254.13"
          ],
          "rowNumber": 655398,
          "rowPosition": 655399,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676173\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655399\" violates the foreign key: for \"id_documento_viagem\": values \"676173\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676173",
            "13241114",
            "14390",
            "1948",
            "58",
            "3012",
            "56714",
            "0",
            "388",
            "9128",
            "2022-11-18",
            "2022-11-18",
            "0.00",
            "1260.26"
          ],
          "rowNumber": 655399,
          "rowPosition": 655400,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676173\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655400\" violates the foreign key: for \"id_documento_viagem\": values \"676173\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676173",
            "13241114",
            "14390",
            "1948",
            "58",
            "3012",
            "56714",
            "0",
            "388",
            "9128",
            "2022-11-18",
            "2022-11-18",
            "0.00",
            "1260.26"
          ],
          "rowNumber": 655399,
          "rowPosition": 655400,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676173\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655400\" violates the foreign key: for \"id_documento_viagem\": values \"676173\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676194",
            "13234420",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "114",
            "145",
            "2022-11-29",
            "2022-11-30",
            "0.00",
            "129.00"
          ],
          "rowNumber": 655400,
          "rowPosition": 655401,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676194\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655401\" violates the foreign key: for \"id_documento_viagem\": values \"676194\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676194",
            "13234420",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "114",
            "145",
            "2022-11-29",
            "2022-11-30",
            "0.00",
            "129.00"
          ],
          "rowNumber": 655400,
          "rowPosition": 655401,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676194\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655401\" violates the foreign key: for \"id_documento_viagem\": values \"676194\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676183",
            "13234420",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "100",
            "133",
            "2022-11-18",
            "2022-11-22",
            "0.00",
            "1872.00"
          ],
          "rowNumber": 655402,
          "rowPosition": 655403,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676183\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655403\" violates the foreign key: for \"id_documento_viagem\": values \"676183\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676183",
            "13234420",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "100",
            "133",
            "2022-11-18",
            "2022-11-22",
            "0.00",
            "1872.00"
          ],
          "rowNumber": 655402,
          "rowPosition": 655403,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676183\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655403\" violates the foreign key: for \"id_documento_viagem\": values \"676183\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676181",
            "13224994",
            "14345",
            "1963",
            "58",
            "3012",
            "56580",
            "0",
            "130",
            "141",
            "2022-12-15",
            "2022-12-16",
            "0.00",
            "1054.80"
          ],
          "rowNumber": 655403,
          "rowPosition": 655404,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676181\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655404\" violates the foreign key: for \"id_documento_viagem\": values \"676181\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676181",
            "13224994",
            "14345",
            "1963",
            "58",
            "3012",
            "56580",
            "0",
            "130",
            "141",
            "2022-12-15",
            "2022-12-16",
            "0.00",
            "1054.80"
          ],
          "rowNumber": 655403,
          "rowPosition": 655404,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676181\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655404\" violates the foreign key: for \"id_documento_viagem\": values \"676181\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676155",
            "13234420",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "123",
            "138",
            "2022-11-29",
            "2022-11-30",
            "0.00",
            "129.00"
          ],
          "rowNumber": 655404,
          "rowPosition": 655405,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676155\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655405\" violates the foreign key: for \"id_documento_viagem\": values \"676155\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676155",
            "13234420",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "123",
            "138",
            "2022-11-29",
            "2022-11-30",
            "0.00",
            "129.00"
          ],
          "rowNumber": 655404,
          "rowPosition": 655405,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676155\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655405\" violates the foreign key: for \"id_documento_viagem\": values \"676155\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676175",
            "13240804",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "144",
            "3812",
            "2022-12-06",
            "2022-12-06",
            "0.00",
            "129.00"
          ],
          "rowNumber": 655406,
          "rowPosition": 655407,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676175\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655407\" violates the foreign key: for \"id_documento_viagem\": values \"676175\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676175",
            "13240804",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "144",
            "3812",
            "2022-12-06",
            "2022-12-06",
            "0.00",
            "129.00"
          ],
          "rowNumber": 655406,
          "rowPosition": 655407,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676175\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655407\" violates the foreign key: for \"id_documento_viagem\": values \"676175\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676170",
            "13237629",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "639",
            "694",
            "2022-12-26",
            "2022-12-26",
            "0.00",
            "385.68"
          ],
          "rowNumber": 655407,
          "rowPosition": 655408,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676170\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655408\" violates the foreign key: for \"id_documento_viagem\": values \"676170\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676170",
            "13237629",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "639",
            "694",
            "2022-12-26",
            "2022-12-26",
            "0.00",
            "385.68"
          ],
          "rowNumber": 655407,
          "rowPosition": 655408,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676170\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655408\" violates the foreign key: for \"id_documento_viagem\": values \"676170\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676153",
            "13535659",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "19",
            "61",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "1587.57"
          ],
          "rowNumber": 655408,
          "rowPosition": 655409,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676153\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655409\" violates the foreign key: for \"id_documento_viagem\": values \"676153\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676153",
            "13535659",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "19",
            "61",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "1587.57"
          ],
          "rowNumber": 655408,
          "rowPosition": 655409,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676153\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655409\" violates the foreign key: for \"id_documento_viagem\": values \"676153\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676158",
            "13224994",
            "14345",
            "1963",
            "58",
            "3012",
            "56580",
            "0",
            "129",
            "146",
            "2022-12-15",
            "2022-12-27",
            "0.00",
            "380.74"
          ],
          "rowNumber": 655409,
          "rowPosition": 655410,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676158\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655410\" violates the foreign key: for \"id_documento_viagem\": values \"676158\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676158",
            "13224994",
            "14345",
            "1963",
            "58",
            "3012",
            "56580",
            "0",
            "129",
            "146",
            "2022-12-15",
            "2022-12-27",
            "0.00",
            "380.74"
          ],
          "rowNumber": 655409,
          "rowPosition": 655410,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676158\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655410\" violates the foreign key: for \"id_documento_viagem\": values \"676158\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676171",
            "13234420",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "115",
            "142",
            "2022-11-29",
            "2022-11-30",
            "0.00",
            "235.00"
          ],
          "rowNumber": 655410,
          "rowPosition": 655411,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676171\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655411\" violates the foreign key: for \"id_documento_viagem\": values \"676171\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676171",
            "13234420",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "115",
            "142",
            "2022-11-29",
            "2022-11-30",
            "0.00",
            "235.00"
          ],
          "rowNumber": 655410,
          "rowPosition": 655411,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676171\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655411\" violates the foreign key: for \"id_documento_viagem\": values \"676171\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676191",
            "13240804",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "146",
            "3822",
            "2022-12-07",
            "2022-12-07",
            "0.00",
            "179.98"
          ],
          "rowNumber": 655411,
          "rowPosition": 655412,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676191\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655412\" violates the foreign key: for \"id_documento_viagem\": values \"676191\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676191",
            "13240804",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "146",
            "3822",
            "2022-12-07",
            "2022-12-07",
            "0.00",
            "179.98"
          ],
          "rowNumber": 655411,
          "rowPosition": 655412,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676191\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655412\" violates the foreign key: for \"id_documento_viagem\": values \"676191\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676188",
            "13240804",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "143",
            "3811",
            "2022-12-06",
            "2022-12-06",
            "0.00",
            "179.98"
          ],
          "rowNumber": 655412,
          "rowPosition": 655413,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676188\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655413\" violates the foreign key: for \"id_documento_viagem\": values \"676188\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676188",
            "13240804",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "143",
            "3811",
            "2022-12-06",
            "2022-12-06",
            "0.00",
            "179.98"
          ],
          "rowNumber": 655412,
          "rowPosition": 655413,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676188\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655413\" violates the foreign key: for \"id_documento_viagem\": values \"676188\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676185",
            "13224994",
            "14345",
            "1963",
            "58",
            "3012",
            "56580",
            "0",
            "105",
            "119",
            "2022-09-29",
            "2022-10-04",
            "0.00",
            "300.66"
          ],
          "rowNumber": 655413,
          "rowPosition": 655414,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676185\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655414\" violates the foreign key: for \"id_documento_viagem\": values \"676185\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676185",
            "13224994",
            "14345",
            "1963",
            "58",
            "3012",
            "56580",
            "0",
            "105",
            "119",
            "2022-09-29",
            "2022-10-04",
            "0.00",
            "300.66"
          ],
          "rowNumber": 655413,
          "rowPosition": 655414,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676185\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655414\" violates the foreign key: for \"id_documento_viagem\": values \"676185\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676162",
            "13234420",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "124",
            "162",
            "2022-11-29",
            "2022-12-06",
            "0.00",
            "129.00"
          ],
          "rowNumber": 655415,
          "rowPosition": 655416,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676162\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655416\" violates the foreign key: for \"id_documento_viagem\": values \"676162\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676162",
            "13234420",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "124",
            "162",
            "2022-11-29",
            "2022-12-06",
            "0.00",
            "129.00"
          ],
          "rowNumber": 655415,
          "rowPosition": 655416,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676162\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655416\" violates the foreign key: for \"id_documento_viagem\": values \"676162\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676199",
            "13224994",
            "14345",
            "1963",
            "58",
            "3012",
            "56580",
            "0",
            "131",
            "144",
            "2022-12-19",
            "2022-12-21",
            "0.00",
            "167.70"
          ],
          "rowNumber": 655416,
          "rowPosition": 655417,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676199\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655417\" violates the foreign key: for \"id_documento_viagem\": values \"676199\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676199",
            "13224994",
            "14345",
            "1963",
            "58",
            "3012",
            "56580",
            "0",
            "131",
            "144",
            "2022-12-19",
            "2022-12-21",
            "0.00",
            "167.70"
          ],
          "rowNumber": 655416,
          "rowPosition": 655417,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676199\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655417\" violates the foreign key: for \"id_documento_viagem\": values \"676199\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676190",
            "13234420",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "122",
            "139",
            "2022-11-29",
            "2022-11-30",
            "0.00",
            "262.92"
          ],
          "rowNumber": 655417,
          "rowPosition": 655418,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676190\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655418\" violates the foreign key: for \"id_documento_viagem\": values \"676190\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676190",
            "13234420",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "122",
            "139",
            "2022-11-29",
            "2022-11-30",
            "0.00",
            "262.92"
          ],
          "rowNumber": 655417,
          "rowPosition": 655418,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676190\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655418\" violates the foreign key: for \"id_documento_viagem\": values \"676190\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676193",
            "12874642",
            "14168",
            "1936",
            "58",
            "3012",
            "55630",
            "0",
            "86",
            "88",
            "2021-12-27",
            "2021-12-29",
            "0.00",
            "136.50"
          ],
          "rowNumber": 655418,
          "rowPosition": 655419,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676193\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655419\" violates the foreign key: for \"id_documento_viagem\": values \"676193\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676193",
            "12874642",
            "14168",
            "1936",
            "58",
            "3012",
            "55630",
            "0",
            "86",
            "88",
            "2021-12-27",
            "2021-12-29",
            "0.00",
            "136.50"
          ],
          "rowNumber": 655418,
          "rowPosition": 655419,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676193\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655419\" violates the foreign key: for \"id_documento_viagem\": values \"676193\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676157",
            "13535659",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "20",
            "62",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "565.26"
          ],
          "rowNumber": 655420,
          "rowPosition": 655421,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676157\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655421\" violates the foreign key: for \"id_documento_viagem\": values \"676157\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676157",
            "13535659",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "20",
            "62",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "565.26"
          ],
          "rowNumber": 655420,
          "rowPosition": 655421,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676157\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655421\" violates the foreign key: for \"id_documento_viagem\": values \"676157\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676160",
            "13241114",
            "14390",
            "1948",
            "58",
            "3012",
            "56714",
            "0",
            "432",
            "10613",
            "2022-12-28",
            "2022-12-28",
            "0.00",
            "238.30"
          ],
          "rowNumber": 655421,
          "rowPosition": 655422,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676160\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655422\" violates the foreign key: for \"id_documento_viagem\": values \"676160\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676160",
            "13241114",
            "14390",
            "1948",
            "58",
            "3012",
            "56714",
            "0",
            "432",
            "10613",
            "2022-12-28",
            "2022-12-28",
            "0.00",
            "238.30"
          ],
          "rowNumber": 655421,
          "rowPosition": 655422,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676160\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655422\" violates the foreign key: for \"id_documento_viagem\": values \"676160\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676164",
            "13234420",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "120",
            "140",
            "2022-11-29",
            "2022-11-30",
            "0.00",
            "129.00"
          ],
          "rowNumber": 655422,
          "rowPosition": 655423,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676164\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655423\" violates the foreign key: for \"id_documento_viagem\": values \"676164\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676164",
            "13234420",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "120",
            "140",
            "2022-11-29",
            "2022-11-30",
            "0.00",
            "129.00"
          ],
          "rowNumber": 655422,
          "rowPosition": 655423,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676164\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655423\" violates the foreign key: for \"id_documento_viagem\": values \"676164\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676200",
            "13234420",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "105",
            "151",
            "2022-11-29",
            "2022-11-30",
            "0.00",
            "129.00"
          ],
          "rowNumber": 655423,
          "rowPosition": 655424,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676200\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655424\" violates the foreign key: for \"id_documento_viagem\": values \"676200\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676200",
            "13234420",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "105",
            "151",
            "2022-11-29",
            "2022-11-30",
            "0.00",
            "129.00"
          ],
          "rowNumber": 655423,
          "rowPosition": 655424,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676200\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655424\" violates the foreign key: for \"id_documento_viagem\": values \"676200\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676174",
            "13241114",
            "14390",
            "1948",
            "58",
            "3012",
            "56714",
            "0",
            "431",
            "10611",
            "2022-12-28",
            "2022-12-28",
            "0.00",
            "137.80"
          ],
          "rowNumber": 655424,
          "rowPosition": 655425,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676174\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655425\" violates the foreign key: for \"id_documento_viagem\": values \"676174\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676174",
            "13241114",
            "14390",
            "1948",
            "58",
            "3012",
            "56714",
            "0",
            "431",
            "10611",
            "2022-12-28",
            "2022-12-28",
            "0.00",
            "137.80"
          ],
          "rowNumber": 655424,
          "rowPosition": 655425,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676174\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655425\" violates the foreign key: for \"id_documento_viagem\": values \"676174\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676161",
            "13237629",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "640",
            "695",
            "2022-12-26",
            "2022-12-26",
            "0.00",
            "385.68"
          ],
          "rowNumber": 655425,
          "rowPosition": 655426,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676161\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655426\" violates the foreign key: for \"id_documento_viagem\": values \"676161\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676161",
            "13237629",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "640",
            "695",
            "2022-12-26",
            "2022-12-26",
            "0.00",
            "385.68"
          ],
          "rowNumber": 655425,
          "rowPosition": 655426,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676161\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655426\" violates the foreign key: for \"id_documento_viagem\": values \"676161\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676167",
            "13241114",
            "14390",
            "1948",
            "58",
            "3012",
            "56714",
            "0",
            "408",
            "9466",
            "2022-11-29",
            "2022-11-29",
            "0.00",
            "1349.89"
          ],
          "rowNumber": 655426,
          "rowPosition": 655427,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676167\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655427\" violates the foreign key: for \"id_documento_viagem\": values \"676167\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676167",
            "13241114",
            "14390",
            "1948",
            "58",
            "3012",
            "56714",
            "0",
            "408",
            "9466",
            "2022-11-29",
            "2022-11-29",
            "0.00",
            "1349.89"
          ],
          "rowNumber": 655426,
          "rowPosition": 655427,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676167\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655427\" violates the foreign key: for \"id_documento_viagem\": values \"676167\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676150",
            "13234420",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "134",
            "141",
            "2022-11-30",
            "2022-11-30",
            "0.00",
            "235.00"
          ],
          "rowNumber": 655427,
          "rowPosition": 655428,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676150\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655428\" violates the foreign key: for \"id_documento_viagem\": values \"676150\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676150",
            "13234420",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "134",
            "141",
            "2022-11-30",
            "2022-11-30",
            "0.00",
            "235.00"
          ],
          "rowNumber": 655427,
          "rowPosition": 655428,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676150\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655428\" violates the foreign key: for \"id_documento_viagem\": values \"676150\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676177",
            "13241114",
            "14390",
            "1948",
            "58",
            "3012",
            "56714",
            "0",
            "430",
            "10334",
            "2022-12-26",
            "2022-12-26",
            "0.00",
            "765.70"
          ],
          "rowNumber": 655429,
          "rowPosition": 655430,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676177\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655430\" violates the foreign key: for \"id_documento_viagem\": values \"676177\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676177",
            "13241114",
            "14390",
            "1948",
            "58",
            "3012",
            "56714",
            "0",
            "430",
            "10334",
            "2022-12-26",
            "2022-12-26",
            "0.00",
            "765.70"
          ],
          "rowNumber": 655429,
          "rowPosition": 655430,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676177\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655430\" violates the foreign key: for \"id_documento_viagem\": values \"676177\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676146",
            "13240804",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "122",
            "3627",
            "2022-11-23",
            "2022-11-23",
            "0.00",
            "179.98"
          ],
          "rowNumber": 655430,
          "rowPosition": 655431,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676146\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655431\" violates the foreign key: for \"id_documento_viagem\": values \"676146\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676146",
            "13240804",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "122",
            "3627",
            "2022-11-23",
            "2022-11-23",
            "0.00",
            "179.98"
          ],
          "rowNumber": 655430,
          "rowPosition": 655431,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676146\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655431\" violates the foreign key: for \"id_documento_viagem\": values \"676146\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676178",
            "13240804",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "126",
            "3631",
            "2022-11-23",
            "2022-11-23",
            "0.00",
            "179.98"
          ],
          "rowNumber": 655431,
          "rowPosition": 655432,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676178\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655432\" violates the foreign key: for \"id_documento_viagem\": values \"676178\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676178",
            "13240804",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "126",
            "3631",
            "2022-11-23",
            "2022-11-23",
            "0.00",
            "179.98"
          ],
          "rowNumber": 655431,
          "rowPosition": 655432,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676178\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655432\" violates the foreign key: for \"id_documento_viagem\": values \"676178\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676195",
            "13240804",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "127",
            "3632",
            "2022-11-23",
            "2022-11-23",
            "0.00",
            "129.00"
          ],
          "rowNumber": 655432,
          "rowPosition": 655433,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676195\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655433\" violates the foreign key: for \"id_documento_viagem\": values \"676195\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676195",
            "13240804",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "127",
            "3632",
            "2022-11-23",
            "2022-11-23",
            "0.00",
            "129.00"
          ],
          "rowNumber": 655432,
          "rowPosition": 655433,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676195\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655433\" violates the foreign key: for \"id_documento_viagem\": values \"676195\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676192",
            "13240804",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "125",
            "3630",
            "2022-11-23",
            "2022-11-23",
            "0.00",
            "179.98"
          ],
          "rowNumber": 655433,
          "rowPosition": 655434,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676192\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655434\" violates the foreign key: for \"id_documento_viagem\": values \"676192\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676192",
            "13240804",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "125",
            "3630",
            "2022-11-23",
            "2022-11-23",
            "0.00",
            "179.98"
          ],
          "rowNumber": 655433,
          "rowPosition": 655434,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676192\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655434\" violates the foreign key: for \"id_documento_viagem\": values \"676192\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676187",
            "13241114",
            "14390",
            "1948",
            "58",
            "3012",
            "56714",
            "0",
            "433",
            "10614",
            "2022-12-28",
            "2022-12-28",
            "0.00",
            "238.30"
          ],
          "rowNumber": 655434,
          "rowPosition": 655435,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676187\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655435\" violates the foreign key: for \"id_documento_viagem\": values \"676187\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676187",
            "13241114",
            "14390",
            "1948",
            "58",
            "3012",
            "56714",
            "0",
            "433",
            "10614",
            "2022-12-28",
            "2022-12-28",
            "0.00",
            "238.30"
          ],
          "rowNumber": 655434,
          "rowPosition": 655435,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676187\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655435\" violates the foreign key: for \"id_documento_viagem\": values \"676187\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676166",
            "13255793",
            "14385",
            "1963",
            "58",
            "3012",
            "56393",
            "0",
            "50",
            "146",
            "2022-12-02",
            "2022-12-20",
            "0.00",
            "321.72"
          ],
          "rowNumber": 655435,
          "rowPosition": 655436,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676166\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655436\" violates the foreign key: for \"id_documento_viagem\": values \"676166\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676166",
            "13255793",
            "14385",
            "1963",
            "58",
            "3012",
            "56393",
            "0",
            "50",
            "146",
            "2022-12-02",
            "2022-12-20",
            "0.00",
            "321.72"
          ],
          "rowNumber": 655435,
          "rowPosition": 655436,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676166\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655436\" violates the foreign key: for \"id_documento_viagem\": values \"676166\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676154",
            "13234420",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "101",
            "130",
            "2022-11-18",
            "2022-11-22",
            "0.00",
            "235.00"
          ],
          "rowNumber": 655436,
          "rowPosition": 655437,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676154\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655437\" violates the foreign key: for \"id_documento_viagem\": values \"676154\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676154",
            "13234420",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "101",
            "130",
            "2022-11-18",
            "2022-11-22",
            "0.00",
            "235.00"
          ],
          "rowNumber": 655436,
          "rowPosition": 655437,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676154\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655437\" violates the foreign key: for \"id_documento_viagem\": values \"676154\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676197",
            "13224994",
            "14345",
            "1963",
            "58",
            "3012",
            "56580",
            "0",
            "127",
            "140",
            "2022-12-15",
            "2022-12-16",
            "0.00",
            "167.70"
          ],
          "rowNumber": 655437,
          "rowPosition": 655438,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676197\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655438\" violates the foreign key: for \"id_documento_viagem\": values \"676197\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676197",
            "13224994",
            "14345",
            "1963",
            "58",
            "3012",
            "56580",
            "0",
            "127",
            "140",
            "2022-12-15",
            "2022-12-16",
            "0.00",
            "167.70"
          ],
          "rowNumber": 655437,
          "rowPosition": 655438,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676197\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655438\" violates the foreign key: for \"id_documento_viagem\": values \"676197\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676151",
            "13240804",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "123",
            "3628",
            "2022-11-23",
            "2022-11-23",
            "0.00",
            "226.80"
          ],
          "rowNumber": 655438,
          "rowPosition": 655439,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676151\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655439\" violates the foreign key: for \"id_documento_viagem\": values \"676151\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676151",
            "13240804",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "123",
            "3628",
            "2022-11-23",
            "2022-11-23",
            "0.00",
            "226.80"
          ],
          "rowNumber": 655438,
          "rowPosition": 655439,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676151\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655439\" violates the foreign key: for \"id_documento_viagem\": values \"676151\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676184",
            "13240804",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "129",
            "3634",
            "2022-11-23",
            "2022-11-23",
            "0.00",
            "243.00"
          ],
          "rowNumber": 655439,
          "rowPosition": 655440,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676184\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655440\" violates the foreign key: for \"id_documento_viagem\": values \"676184\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676184",
            "13240804",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "129",
            "3634",
            "2022-11-23",
            "2022-11-23",
            "0.00",
            "243.00"
          ],
          "rowNumber": 655439,
          "rowPosition": 655440,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676184\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655440\" violates the foreign key: for \"id_documento_viagem\": values \"676184\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676147",
            "13240804",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "124",
            "3629",
            "2022-11-23",
            "2022-11-23",
            "0.00",
            "179.98"
          ],
          "rowNumber": 655441,
          "rowPosition": 655442,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676147\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655442\" violates the foreign key: for \"id_documento_viagem\": values \"676147\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676147",
            "13240804",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "124",
            "3629",
            "2022-11-23",
            "2022-11-23",
            "0.00",
            "179.98"
          ],
          "rowNumber": 655441,
          "rowPosition": 655442,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676147\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655442\" violates the foreign key: for \"id_documento_viagem\": values \"676147\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676156",
            "13240804",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "119",
            "3624",
            "2022-11-23",
            "2022-11-23",
            "0.00",
            "129.00"
          ],
          "rowNumber": 655442,
          "rowPosition": 655443,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676156\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655443\" violates the foreign key: for \"id_documento_viagem\": values \"676156\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676156",
            "13240804",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "119",
            "3624",
            "2022-11-23",
            "2022-11-23",
            "0.00",
            "129.00"
          ],
          "rowNumber": 655442,
          "rowPosition": 655443,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676156\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655443\" violates the foreign key: for \"id_documento_viagem\": values \"676156\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676173",
            "13318247",
            "14390",
            "1948",
            "58",
            "2772",
            "56714",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "772.53"
          ],
          "rowNumber": 655443,
          "rowPosition": 655444,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676173\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655444\" violates the foreign key: for \"id_documento_viagem\": values \"676173\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676173",
            "13318247",
            "14390",
            "1948",
            "58",
            "2772",
            "56714",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "772.53"
          ],
          "rowNumber": 655443,
          "rowPosition": 655444,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676173\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655444\" violates the foreign key: for \"id_documento_viagem\": values \"676173\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676173",
            "13318247",
            "14390",
            "1948",
            "58",
            "2772",
            "56714",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "1086.15"
          ],
          "rowNumber": 655444,
          "rowPosition": 655445,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676173\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655445\" violates the foreign key: for \"id_documento_viagem\": values \"676173\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676173",
            "13318247",
            "14390",
            "1948",
            "58",
            "2772",
            "56714",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "1086.15"
          ],
          "rowNumber": 655444,
          "rowPosition": 655445,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676173\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655445\" violates the foreign key: for \"id_documento_viagem\": values \"676173\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676173",
            "13318247",
            "14390",
            "1948",
            "58",
            "2772",
            "56714",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "747.33"
          ],
          "rowNumber": 655445,
          "rowPosition": 655446,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676173\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655446\" violates the foreign key: for \"id_documento_viagem\": values \"676173\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676173",
            "13318247",
            "14390",
            "1948",
            "58",
            "2772",
            "56714",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "747.33"
          ],
          "rowNumber": 655445,
          "rowPosition": 655446,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676173\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655446\" violates the foreign key: for \"id_documento_viagem\": values \"676173\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676167",
            "13318247",
            "14390",
            "1948",
            "58",
            "2772",
            "56714",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "630.08"
          ],
          "rowNumber": 655446,
          "rowPosition": 655447,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676167\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655447\" violates the foreign key: for \"id_documento_viagem\": values \"676167\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676167",
            "13318247",
            "14390",
            "1948",
            "58",
            "2772",
            "56714",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "630.08"
          ],
          "rowNumber": 655446,
          "rowPosition": 655447,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676167\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655447\" violates the foreign key: for \"id_documento_viagem\": values \"676167\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676167",
            "13318247",
            "14390",
            "1948",
            "58",
            "2772",
            "56714",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "630.07"
          ],
          "rowNumber": 655447,
          "rowPosition": 655448,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676167\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655448\" violates the foreign key: for \"id_documento_viagem\": values \"676167\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "676167",
            "13318247",
            "14390",
            "1948",
            "58",
            "2772",
            "56714",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "630.07"
          ],
          "rowNumber": 655447,
          "rowPosition": 655448,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"676167\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"655448\" violates the foreign key: for \"id_documento_viagem\": values \"676167\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 100
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 100,
    "tasks": 1
  },
  "valid": false
}