{
  "version": "4.38.0",
  "time": 101.747,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_diarias_scdp_liqpag",
        "title": "Diárias SCDP - Liquidação e Pagamento",
        "path": "data/ft_diarias_scdp_liqpag.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_documento_viagem",
              "title": "Documento de Viagem - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "description": "- > \n  Chave estrangeira (Foreign Key) que aponta para a Chave Primária (Primary keys) da tabela dm_tempo_diario. \n  Ou seja, por meio dessa chave é possível identificar a data completa a qual o dado se refere.\n\n  Nota: \n  No site dados.mg.gov.br a tabela dm_tempo_diario pode ser encontrada no recurso Calendários - Dias \n  de cada conjunto.\n",
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_empenho",
              "title": "Número do Empenho - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_programa",
              "title": "Programa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_funcao",
              "title": "Função - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_fonte",
              "title": "Fonte de Recurso - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item de Despesa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_acao",
              "title": "Ação Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "fl_passagem",
              "title": "Passagem - Flag",
              "type": "string",
              "format": "default",
              "description": "- '0' - Diárias\n- '1' - Passagem\n",
              "constraints": {
                "required": true,
                "enum": [
                  "0",
                  "1"
                ]
              }
            },
            {
              "name": "nr_liquidacao",
              "title": "Número Liquidação",
              "type": "string",
              "format": "default",
              "description": "Número do documento de liquidação.\n",
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "nr_pagamento",
              "title": "Número Pagamento",
              "type": "string",
              "format": "default",
              "description": "Número do documento de ordem de pagamento.\n",
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "dt_liquidacao",
              "title": "Data da liquidação",
              "type": "date",
              "format": "default"
            },
            {
              "name": "dt_pagamento",
              "type": "date",
              "format": "default"
            },
            {
              "name": "vr_devolvido",
              "title": "Valor Devolvido",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_liqpag",
              "title": "Valor liquidado/Pago",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "description": "- > \n  Valor pago referente às despesas com diárias e passagens aéreas e terrestres de servidor público ou \n  colaborador eventual em razão de viagem a trabalho.\n",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_funcao"
              ],
              "reference": {
                "fields": [
                  "id_funcao"
                ],
                "resource": "dm_funcao_desp"
              }
            },
            {
              "fields": [
                "id_fonte"
              ],
              "reference": {
                "fields": [
                  "id_fonte"
                ],
                "resource": "dm_fonte"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_programa"
              ],
              "reference": {
                "fields": [
                  "id_programa"
                ],
                "resource": "dm_programa"
              }
            },
            {
              "fields": [
                "id_empenho"
              ],
              "reference": {
                "fields": [
                  "id_empenho"
                ],
                "resource": "dm_empenho_desp_diarias_scdp_liqpag"
              }
            },
            {
              "fields": [
                "id_documento_viagem"
              ],
              "reference": {
                "fields": [
                  "id_documento_viagem"
                ],
                "resource": "dm_documento_viagem"
              }
            },
            {
              "fields": [
                "id_acao"
              ],
              "reference": {
                "fields": [
                  "id_acao"
                ],
                "resource": "dm_acao"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_fonte"
              ],
              "reference": {
                "fields": [
                  "id_fonte"
                ],
                "resource": "dm_fonte"
              }
            },
            {
              "fields": [
                "id_programa"
              ],
              "reference": {
                "fields": [
                  "id_programa"
                ],
                "resource": "dm_programa"
              }
            },
            {
              "fields": [
                "id_documento_viagem"
              ],
              "reference": {
                "fields": [
                  "id_documento_viagem"
                ],
                "resource": "dm_documento_viagem"
              }
            },
            {
              "fields": [
                "id_acao"
              ],
              "reference": {
                "fields": [
                  "id_acao"
                ],
                "resource": "dm_acao"
              }
            },
            {
              "fields": [
                "id_empenho"
              ],
              "reference": {
                "fields": [
                  "id_empenho"
                ],
                "resource": "dm_empenho_desp_diarias_scdp_liqpag"
              }
            },
            {
              "fields": [
                "id_funcao"
              ],
              "reference": {
                "fields": [
                  "id_funcao"
                ],
                "resource": "dm_funcao_desp"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_diarias_scdp_liqpag"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "f3091123d79027ccce49d205deabb2d0",
          "bytes": 9966572,
          "fields": 14,
          "rows": 644493
        }
      },
      "time": 101.747,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "659650",
            "13385837",
            "14420",
            "1955",
            "20",
            "3012",
            "56642",
            "0",
            "447",
            "4351",
            "2022-11-16",
            "2022-11-17",
            "0.00",
            "15.30"
          ],
          "rowNumber": 643929,
          "rowPosition": 643930,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659650\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643930\" violates the foreign key: for \"id_documento_viagem\": values \"659650\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659650",
            "13385837",
            "14420",
            "1955",
            "20",
            "3012",
            "56642",
            "0",
            "447",
            "4351",
            "2022-11-16",
            "2022-11-17",
            "0.00",
            "15.30"
          ],
          "rowNumber": 643929,
          "rowPosition": 643930,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659650\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643930\" violates the foreign key: for \"id_documento_viagem\": values \"659650\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659675",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "372",
            "20629",
            "2022-11-24",
            "2022-11-24",
            "0.00",
            "400.00"
          ],
          "rowNumber": 643930,
          "rowPosition": 643931,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659675\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643931\" violates the foreign key: for \"id_documento_viagem\": values \"659675\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659675",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "372",
            "20629",
            "2022-11-24",
            "2022-11-24",
            "0.00",
            "400.00"
          ],
          "rowNumber": 643930,
          "rowPosition": 643931,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659675\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643931\" violates the foreign key: for \"id_documento_viagem\": values \"659675\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659675",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "349",
            "17520",
            "2022-11-10",
            "2022-11-10",
            "0.00",
            "1104.50"
          ],
          "rowNumber": 643931,
          "rowPosition": 643932,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659675\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643932\" violates the foreign key: for \"id_documento_viagem\": values \"659675\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659675",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "349",
            "17520",
            "2022-11-10",
            "2022-11-10",
            "0.00",
            "1104.50"
          ],
          "rowNumber": 643931,
          "rowPosition": 643932,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659675\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643932\" violates the foreign key: for \"id_documento_viagem\": values \"659675\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659649",
            "13236979",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "386",
            "469",
            "2022-11-22",
            "2022-11-24",
            "0.00",
            "412.96"
          ],
          "rowNumber": 643932,
          "rowPosition": 643933,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659649\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643933\" violates the foreign key: for \"id_documento_viagem\": values \"659649\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659649",
            "13236979",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "386",
            "469",
            "2022-11-22",
            "2022-11-24",
            "0.00",
            "412.96"
          ],
          "rowNumber": 643932,
          "rowPosition": 643933,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659649\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643933\" violates the foreign key: for \"id_documento_viagem\": values \"659649\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659665",
            "13385837",
            "14420",
            "1955",
            "20",
            "3012",
            "56642",
            "0",
            "145",
            "2812",
            "2022-08-09",
            "2022-08-10",
            "0.00",
            "15.30"
          ],
          "rowNumber": 643933,
          "rowPosition": 643934,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659665\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643934\" violates the foreign key: for \"id_documento_viagem\": values \"659665\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659665",
            "13385837",
            "14420",
            "1955",
            "20",
            "3012",
            "56642",
            "0",
            "145",
            "2812",
            "2022-08-09",
            "2022-08-10",
            "0.00",
            "15.30"
          ],
          "rowNumber": 643933,
          "rowPosition": 643934,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659665\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643934\" violates the foreign key: for \"id_documento_viagem\": values \"659665\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659626",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "370",
            "20627",
            "2022-11-24",
            "2022-11-24",
            "0.00",
            "246.15"
          ],
          "rowNumber": 643934,
          "rowPosition": 643935,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659626\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643935\" violates the foreign key: for \"id_documento_viagem\": values \"659626\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659626",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "370",
            "20627",
            "2022-11-24",
            "2022-11-24",
            "0.00",
            "246.15"
          ],
          "rowNumber": 643934,
          "rowPosition": 643935,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659626\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643935\" violates the foreign key: for \"id_documento_viagem\": values \"659626\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659626",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "347",
            "17517",
            "2022-11-10",
            "2022-11-10",
            "0.00",
            "2044.50"
          ],
          "rowNumber": 643935,
          "rowPosition": 643936,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659626\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643936\" violates the foreign key: for \"id_documento_viagem\": values \"659626\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659626",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "347",
            "17517",
            "2022-11-10",
            "2022-11-10",
            "0.00",
            "2044.50"
          ],
          "rowNumber": 643935,
          "rowPosition": 643936,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659626\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643936\" violates the foreign key: for \"id_documento_viagem\": values \"659626\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659630",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "373",
            "20630",
            "2022-11-24",
            "2022-11-24",
            "0.00",
            "95.65"
          ],
          "rowNumber": 643937,
          "rowPosition": 643938,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659630\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643938\" violates the foreign key: for \"id_documento_viagem\": values \"659630\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659630",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "373",
            "20630",
            "2022-11-24",
            "2022-11-24",
            "0.00",
            "95.65"
          ],
          "rowNumber": 643937,
          "rowPosition": 643938,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659630\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643938\" violates the foreign key: for \"id_documento_viagem\": values \"659630\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659630",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "345",
            "17515",
            "2022-11-10",
            "2022-11-10",
            "0.00",
            "634.50"
          ],
          "rowNumber": 643938,
          "rowPosition": 643939,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659630\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643939\" violates the foreign key: for \"id_documento_viagem\": values \"659630\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659630",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "345",
            "17515",
            "2022-11-10",
            "2022-11-10",
            "0.00",
            "634.50"
          ],
          "rowNumber": 643938,
          "rowPosition": 643939,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659630\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643939\" violates the foreign key: for \"id_documento_viagem\": values \"659630\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659658",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "368",
            "20625",
            "2022-11-24",
            "2022-11-24",
            "0.00",
            "42.39"
          ],
          "rowNumber": 643939,
          "rowPosition": 643940,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659658\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643940\" violates the foreign key: for \"id_documento_viagem\": values \"659658\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659658",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "368",
            "20625",
            "2022-11-24",
            "2022-11-24",
            "0.00",
            "42.39"
          ],
          "rowNumber": 643939,
          "rowPosition": 643940,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659658\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643940\" violates the foreign key: for \"id_documento_viagem\": values \"659658\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659658",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "341",
            "17173",
            "2022-11-09",
            "2022-11-09",
            "0.00",
            "1574.50"
          ],
          "rowNumber": 643940,
          "rowPosition": 643941,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659658\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643941\" violates the foreign key: for \"id_documento_viagem\": values \"659658\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659658",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "341",
            "17173",
            "2022-11-09",
            "2022-11-09",
            "0.00",
            "1574.50"
          ],
          "rowNumber": 643940,
          "rowPosition": 643941,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659658\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643941\" violates the foreign key: for \"id_documento_viagem\": values \"659658\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659647",
            "13492249",
            "14420",
            "1955",
            "20",
            "3012",
            "56642",
            "0",
            "117",
            "9814",
            "2022-11-18",
            "2022-11-21",
            "0.00",
            "198.30"
          ],
          "rowNumber": 643941,
          "rowPosition": 643942,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659647\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643942\" violates the foreign key: for \"id_documento_viagem\": values \"659647\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659647",
            "13492249",
            "14420",
            "1955",
            "20",
            "3012",
            "56642",
            "0",
            "117",
            "9814",
            "2022-11-18",
            "2022-11-21",
            "0.00",
            "198.30"
          ],
          "rowNumber": 643941,
          "rowPosition": 643942,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659647\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643942\" violates the foreign key: for \"id_documento_viagem\": values \"659647\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659628",
            "13385837",
            "14420",
            "1955",
            "20",
            "3012",
            "56642",
            "0",
            "166",
            "2970",
            "2022-08-12",
            "2022-08-16",
            "0.00",
            "15.30"
          ],
          "rowNumber": 643942,
          "rowPosition": 643943,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659628\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643943\" violates the foreign key: for \"id_documento_viagem\": values \"659628\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659628",
            "13385837",
            "14420",
            "1955",
            "20",
            "3012",
            "56642",
            "0",
            "166",
            "2970",
            "2022-08-12",
            "2022-08-16",
            "0.00",
            "15.30"
          ],
          "rowNumber": 643942,
          "rowPosition": 643943,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659628\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643943\" violates the foreign key: for \"id_documento_viagem\": values \"659628\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659653",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "364",
            "20621",
            "2022-11-24",
            "2022-11-24",
            "0.00",
            "313.40"
          ],
          "rowNumber": 643943,
          "rowPosition": 643944,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659653\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643944\" violates the foreign key: for \"id_documento_viagem\": values \"659653\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659653",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "364",
            "20621",
            "2022-11-24",
            "2022-11-24",
            "0.00",
            "313.40"
          ],
          "rowNumber": 643943,
          "rowPosition": 643944,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659653\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643944\" violates the foreign key: for \"id_documento_viagem\": values \"659653\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659653",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "337",
            "16972",
            "2022-11-09",
            "2022-11-09",
            "0.00",
            "1574.50"
          ],
          "rowNumber": 643944,
          "rowPosition": 643945,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659653\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643945\" violates the foreign key: for \"id_documento_viagem\": values \"659653\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659653",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "337",
            "16972",
            "2022-11-09",
            "2022-11-09",
            "0.00",
            "1574.50"
          ],
          "rowNumber": 643944,
          "rowPosition": 643945,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659653\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643945\" violates the foreign key: for \"id_documento_viagem\": values \"659653\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659634",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "371",
            "20628",
            "2022-11-24",
            "2022-11-24",
            "0.00",
            "20.60"
          ],
          "rowNumber": 643945,
          "rowPosition": 643946,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659634\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643946\" violates the foreign key: for \"id_documento_viagem\": values \"659634\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659634",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "371",
            "20628",
            "2022-11-24",
            "2022-11-24",
            "0.00",
            "20.60"
          ],
          "rowNumber": 643945,
          "rowPosition": 643946,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659634\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643946\" violates the foreign key: for \"id_documento_viagem\": values \"659634\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659634",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "358",
            "18013",
            "2022-11-11",
            "2022-11-11",
            "0.00",
            "164.50"
          ],
          "rowNumber": 643946,
          "rowPosition": 643947,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659634\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643947\" violates the foreign key: for \"id_documento_viagem\": values \"659634\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659634",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "358",
            "18013",
            "2022-11-11",
            "2022-11-11",
            "0.00",
            "164.50"
          ],
          "rowNumber": 643946,
          "rowPosition": 643947,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659634\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643947\" violates the foreign key: for \"id_documento_viagem\": values \"659634\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659677",
            "13214924",
            "14342",
            "1972",
            "55",
            "3012",
            "56575",
            "0",
            "109",
            "3398",
            "2022-11-24",
            "2022-11-24",
            "0.00",
            "104.00"
          ],
          "rowNumber": 643948,
          "rowPosition": 643949,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659677\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643949\" violates the foreign key: for \"id_documento_viagem\": values \"659677\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659677",
            "13214924",
            "14342",
            "1972",
            "55",
            "3012",
            "56575",
            "0",
            "109",
            "3398",
            "2022-11-24",
            "2022-11-24",
            "0.00",
            "104.00"
          ],
          "rowNumber": 643948,
          "rowPosition": 643949,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659677\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643949\" violates the foreign key: for \"id_documento_viagem\": values \"659677\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659677",
            "13214924",
            "14342",
            "1972",
            "55",
            "3012",
            "56575",
            "0",
            "103",
            "3172",
            "2022-11-03",
            "2022-11-03",
            "0.00",
            "875.10"
          ],
          "rowNumber": 643949,
          "rowPosition": 643950,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659677\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643950\" violates the foreign key: for \"id_documento_viagem\": values \"659677\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659677",
            "13214924",
            "14342",
            "1972",
            "55",
            "3012",
            "56575",
            "0",
            "103",
            "3172",
            "2022-11-03",
            "2022-11-03",
            "0.00",
            "875.10"
          ],
          "rowNumber": 643949,
          "rowPosition": 643950,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659677\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643950\" violates the foreign key: for \"id_documento_viagem\": values \"659677\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659651",
            "13214919",
            "14327",
            "1950",
            "58",
            "3012",
            "56215",
            "0",
            "25",
            "1028",
            "2022-11-09",
            "2022-11-09",
            "0.00",
            "381.30"
          ],
          "rowNumber": 643950,
          "rowPosition": 643951,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659651\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643951\" violates the foreign key: for \"id_documento_viagem\": values \"659651\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659651",
            "13214919",
            "14327",
            "1950",
            "58",
            "3012",
            "56215",
            "0",
            "25",
            "1028",
            "2022-11-09",
            "2022-11-09",
            "0.00",
            "381.30"
          ],
          "rowNumber": 643950,
          "rowPosition": 643951,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659651\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643951\" violates the foreign key: for \"id_documento_viagem\": values \"659651\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659633",
            "13215165",
            "14342",
            "1972",
            "55",
            "3012",
            "56475",
            "0",
            "1400",
            "3171",
            "2022-11-03",
            "2022-11-03",
            "0.00",
            "734.70"
          ],
          "rowNumber": 643951,
          "rowPosition": 643952,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659633\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643952\" violates the foreign key: for \"id_documento_viagem\": values \"659633\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659633",
            "13215165",
            "14342",
            "1972",
            "55",
            "3012",
            "56475",
            "0",
            "1400",
            "3171",
            "2022-11-03",
            "2022-11-03",
            "0.00",
            "734.70"
          ],
          "rowNumber": 643951,
          "rowPosition": 643952,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659633\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643952\" violates the foreign key: for \"id_documento_viagem\": values \"659633\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659637",
            "13385837",
            "14420",
            "1955",
            "20",
            "3012",
            "56642",
            "0",
            "144",
            "2811",
            "2022-08-09",
            "2022-08-10",
            "0.00",
            "954.50"
          ],
          "rowNumber": 643952,
          "rowPosition": 643953,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659637\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643953\" violates the foreign key: for \"id_documento_viagem\": values \"659637\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659637",
            "13385837",
            "14420",
            "1955",
            "20",
            "3012",
            "56642",
            "0",
            "144",
            "2811",
            "2022-08-09",
            "2022-08-10",
            "0.00",
            "954.50"
          ],
          "rowNumber": 643952,
          "rowPosition": 643953,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659637\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643953\" violates the foreign key: for \"id_documento_viagem\": values \"659637\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659619",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "367",
            "20624",
            "2022-11-24",
            "2022-11-24",
            "0.00",
            "203.95"
          ],
          "rowNumber": 643953,
          "rowPosition": 643954,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659619\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643954\" violates the foreign key: for \"id_documento_viagem\": values \"659619\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659619",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "367",
            "20624",
            "2022-11-24",
            "2022-11-24",
            "0.00",
            "203.95"
          ],
          "rowNumber": 643953,
          "rowPosition": 643954,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659619\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643954\" violates the foreign key: for \"id_documento_viagem\": values \"659619\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659619",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "332",
            "16817",
            "2022-11-09",
            "2022-11-09",
            "0.00",
            "1574.50"
          ],
          "rowNumber": 643954,
          "rowPosition": 643955,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659619\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643955\" violates the foreign key: for \"id_documento_viagem\": values \"659619\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659619",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "332",
            "16817",
            "2022-11-09",
            "2022-11-09",
            "0.00",
            "1574.50"
          ],
          "rowNumber": 643954,
          "rowPosition": 643955,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659619\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643955\" violates the foreign key: for \"id_documento_viagem\": values \"659619\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659678",
            "13215165",
            "14342",
            "1972",
            "55",
            "3012",
            "56475",
            "0",
            "1443",
            "3244",
            "2022-11-10",
            "2022-11-10",
            "0.00",
            "373.74"
          ],
          "rowNumber": 643955,
          "rowPosition": 643956,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659678\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643956\" violates the foreign key: for \"id_documento_viagem\": values \"659678\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659678",
            "13215165",
            "14342",
            "1972",
            "55",
            "3012",
            "56475",
            "0",
            "1443",
            "3244",
            "2022-11-10",
            "2022-11-10",
            "0.00",
            "373.74"
          ],
          "rowNumber": 643955,
          "rowPosition": 643956,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659678\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643956\" violates the foreign key: for \"id_documento_viagem\": values \"659678\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659648",
            "13421969",
            "14420",
            "1955",
            "20",
            "3012",
            "56642",
            "0",
            "69",
            "2792",
            "2022-08-11",
            "2022-08-12",
            "0.00",
            "15.30"
          ],
          "rowNumber": 643956,
          "rowPosition": 643957,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659648\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643957\" violates the foreign key: for \"id_documento_viagem\": values \"659648\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659648",
            "13421969",
            "14420",
            "1955",
            "20",
            "3012",
            "56642",
            "0",
            "69",
            "2792",
            "2022-08-11",
            "2022-08-12",
            "0.00",
            "15.30"
          ],
          "rowNumber": 643956,
          "rowPosition": 643957,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659648\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643957\" violates the foreign key: for \"id_documento_viagem\": values \"659648\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659636",
            "13215165",
            "14342",
            "1972",
            "55",
            "3012",
            "56475",
            "0",
            "1396",
            "3167",
            "2022-11-03",
            "2022-11-03",
            "0.00",
            "734.70"
          ],
          "rowNumber": 643957,
          "rowPosition": 643958,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659636\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643958\" violates the foreign key: for \"id_documento_viagem\": values \"659636\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659636",
            "13215165",
            "14342",
            "1972",
            "55",
            "3012",
            "56475",
            "0",
            "1396",
            "3167",
            "2022-11-03",
            "2022-11-03",
            "0.00",
            "734.70"
          ],
          "rowNumber": 643957,
          "rowPosition": 643958,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659636\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643958\" violates the foreign key: for \"id_documento_viagem\": values \"659636\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659661",
            "13385837",
            "14420",
            "1955",
            "20",
            "3012",
            "56642",
            "0",
            "381",
            "4010",
            "2022-10-07",
            "2022-10-10",
            "0.00",
            "15.30"
          ],
          "rowNumber": 643958,
          "rowPosition": 643959,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659661\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643959\" violates the foreign key: for \"id_documento_viagem\": values \"659661\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659661",
            "13385837",
            "14420",
            "1955",
            "20",
            "3012",
            "56642",
            "0",
            "381",
            "4010",
            "2022-10-07",
            "2022-10-10",
            "0.00",
            "15.30"
          ],
          "rowNumber": 643958,
          "rowPosition": 643959,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659661\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643959\" violates the foreign key: for \"id_documento_viagem\": values \"659661\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659639",
            "13385837",
            "14420",
            "1955",
            "20",
            "3012",
            "56642",
            "0",
            "165",
            "2969",
            "2022-08-12",
            "2022-08-16",
            "0.00",
            "15.30"
          ],
          "rowNumber": 643959,
          "rowPosition": 643960,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659639\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643960\" violates the foreign key: for \"id_documento_viagem\": values \"659639\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659639",
            "13385837",
            "14420",
            "1955",
            "20",
            "3012",
            "56642",
            "0",
            "165",
            "2969",
            "2022-08-12",
            "2022-08-16",
            "0.00",
            "15.30"
          ],
          "rowNumber": 643959,
          "rowPosition": 643960,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659639\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643960\" violates the foreign key: for \"id_documento_viagem\": values \"659639\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659623",
            "13215165",
            "14342",
            "1972",
            "55",
            "3012",
            "56475",
            "0",
            "1399",
            "3170",
            "2022-11-03",
            "2022-11-03",
            "0.00",
            "734.70"
          ],
          "rowNumber": 643960,
          "rowPosition": 643961,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659623\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643961\" violates the foreign key: for \"id_documento_viagem\": values \"659623\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659623",
            "13215165",
            "14342",
            "1972",
            "55",
            "3012",
            "56475",
            "0",
            "1399",
            "3170",
            "2022-11-03",
            "2022-11-03",
            "0.00",
            "734.70"
          ],
          "rowNumber": 643960,
          "rowPosition": 643961,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659623\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643961\" violates the foreign key: for \"id_documento_viagem\": values \"659623\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659621",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "366",
            "20623",
            "2022-11-24",
            "2022-11-24",
            "0.00",
            "295.59"
          ],
          "rowNumber": 643961,
          "rowPosition": 643962,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659621\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643962\" violates the foreign key: for \"id_documento_viagem\": values \"659621\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659621",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "366",
            "20623",
            "2022-11-24",
            "2022-11-24",
            "0.00",
            "295.59"
          ],
          "rowNumber": 643961,
          "rowPosition": 643962,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659621\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643962\" violates the foreign key: for \"id_documento_viagem\": values \"659621\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659621",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "344",
            "17514",
            "2022-11-10",
            "2022-11-10",
            "0.00",
            "1574.50"
          ],
          "rowNumber": 643962,
          "rowPosition": 643963,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659621\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643963\" violates the foreign key: for \"id_documento_viagem\": values \"659621\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659621",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "344",
            "17514",
            "2022-11-10",
            "2022-11-10",
            "0.00",
            "1574.50"
          ],
          "rowNumber": 643962,
          "rowPosition": 643963,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659621\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643963\" violates the foreign key: for \"id_documento_viagem\": values \"659621\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659673",
            "13385837",
            "14420",
            "1955",
            "20",
            "3012",
            "56642",
            "0",
            "137",
            "2804",
            "2022-08-09",
            "2022-08-10",
            "0.00",
            "15.30"
          ],
          "rowNumber": 643963,
          "rowPosition": 643964,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659673\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643964\" violates the foreign key: for \"id_documento_viagem\": values \"659673\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659673",
            "13385837",
            "14420",
            "1955",
            "20",
            "3012",
            "56642",
            "0",
            "137",
            "2804",
            "2022-08-09",
            "2022-08-10",
            "0.00",
            "15.30"
          ],
          "rowNumber": 643963,
          "rowPosition": 643964,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659673\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643964\" violates the foreign key: for \"id_documento_viagem\": values \"659673\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659642",
            "13385837",
            "14420",
            "1955",
            "20",
            "3012",
            "56642",
            "0",
            "138",
            "2805",
            "2022-08-09",
            "2022-08-10",
            "0.00",
            "15.30"
          ],
          "rowNumber": 643964,
          "rowPosition": 643965,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659642\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643965\" violates the foreign key: for \"id_documento_viagem\": values \"659642\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659642",
            "13385837",
            "14420",
            "1955",
            "20",
            "3012",
            "56642",
            "0",
            "138",
            "2805",
            "2022-08-09",
            "2022-08-10",
            "0.00",
            "15.30"
          ],
          "rowNumber": 643964,
          "rowPosition": 643965,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659642\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643965\" violates the foreign key: for \"id_documento_viagem\": values \"659642\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659672",
            "13560367",
            "14353",
            "1948",
            "58",
            "3012",
            "56157",
            "0",
            "1",
            "388",
            "2022-11-16",
            "2022-11-17",
            "0.00",
            "1274.50"
          ],
          "rowNumber": 643965,
          "rowPosition": 643966,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659672\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643966\" violates the foreign key: for \"id_documento_viagem\": values \"659672\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659672",
            "13560367",
            "14353",
            "1948",
            "58",
            "3012",
            "56157",
            "0",
            "1",
            "388",
            "2022-11-16",
            "2022-11-17",
            "0.00",
            "1274.50"
          ],
          "rowNumber": 643965,
          "rowPosition": 643966,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659672\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643966\" violates the foreign key: for \"id_documento_viagem\": values \"659672\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659654",
            "13385837",
            "14420",
            "1955",
            "20",
            "3012",
            "56642",
            "0",
            "150",
            "2817",
            "2022-08-09",
            "2022-08-10",
            "0.00",
            "15.30"
          ],
          "rowNumber": 643966,
          "rowPosition": 643967,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659654\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643967\" violates the foreign key: for \"id_documento_viagem\": values \"659654\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659654",
            "13385837",
            "14420",
            "1955",
            "20",
            "3012",
            "56642",
            "0",
            "150",
            "2817",
            "2022-08-09",
            "2022-08-10",
            "0.00",
            "15.30"
          ],
          "rowNumber": 643966,
          "rowPosition": 643967,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659654\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643967\" violates the foreign key: for \"id_documento_viagem\": values \"659654\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659631",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "369",
            "20626",
            "2022-11-24",
            "2022-11-24",
            "0.00",
            "472.83"
          ],
          "rowNumber": 643967,
          "rowPosition": 643968,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659631\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643968\" violates the foreign key: for \"id_documento_viagem\": values \"659631\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659631",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "369",
            "20626",
            "2022-11-24",
            "2022-11-24",
            "0.00",
            "472.83"
          ],
          "rowNumber": 643967,
          "rowPosition": 643968,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659631\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643968\" violates the foreign key: for \"id_documento_viagem\": values \"659631\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659631",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "342",
            "17175",
            "2022-11-09",
            "2022-11-09",
            "0.00",
            "2044.50"
          ],
          "rowNumber": 643968,
          "rowPosition": 643969,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659631\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643969\" violates the foreign key: for \"id_documento_viagem\": values \"659631\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659631",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "342",
            "17175",
            "2022-11-09",
            "2022-11-09",
            "0.00",
            "2044.50"
          ],
          "rowNumber": 643968,
          "rowPosition": 643969,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659631\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643969\" violates the foreign key: for \"id_documento_viagem\": values \"659631\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659635",
            "13234813",
            "14400",
            "1970",
            "490",
            "3012",
            "56743",
            "0",
            "79",
            "1655",
            "2022-11-09",
            "2022-11-09",
            "0.00",
            "470.60"
          ],
          "rowNumber": 643969,
          "rowPosition": 643970,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659635\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643970\" violates the foreign key: for \"id_documento_viagem\": values \"659635\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659635",
            "13234813",
            "14400",
            "1970",
            "490",
            "3012",
            "56743",
            "0",
            "79",
            "1655",
            "2022-11-09",
            "2022-11-09",
            "0.00",
            "470.60"
          ],
          "rowNumber": 643969,
          "rowPosition": 643970,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659635\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643970\" violates the foreign key: for \"id_documento_viagem\": values \"659635\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659641",
            "13385837",
            "14420",
            "1955",
            "20",
            "3012",
            "56642",
            "0",
            "134",
            "2801",
            "2022-08-09",
            "2022-08-10",
            "0.00",
            "15.30"
          ],
          "rowNumber": 643970,
          "rowPosition": 643971,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659641\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643971\" violates the foreign key: for \"id_documento_viagem\": values \"659641\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659641",
            "13385837",
            "14420",
            "1955",
            "20",
            "3012",
            "56642",
            "0",
            "134",
            "2801",
            "2022-08-09",
            "2022-08-10",
            "0.00",
            "15.30"
          ],
          "rowNumber": 643970,
          "rowPosition": 643971,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659641\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643971\" violates the foreign key: for \"id_documento_viagem\": values \"659641\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659669",
            "13421918",
            "14361",
            "1970",
            "6",
            "3012",
            "56282",
            "0",
            "13",
            "2205",
            "2022-11-09",
            "2022-11-09",
            "167.70",
            "335.40"
          ],
          "rowNumber": 643971,
          "rowPosition": 643972,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659669\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643972\" violates the foreign key: for \"id_documento_viagem\": values \"659669\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659669",
            "13421918",
            "14361",
            "1970",
            "6",
            "3012",
            "56282",
            "0",
            "13",
            "2205",
            "2022-11-09",
            "2022-11-09",
            "167.70",
            "335.40"
          ],
          "rowNumber": 643971,
          "rowPosition": 643972,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659669\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643972\" violates the foreign key: for \"id_documento_viagem\": values \"659669\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659629",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "365",
            "20622",
            "2022-11-24",
            "2022-11-24",
            "0.00",
            "231.16"
          ],
          "rowNumber": 643972,
          "rowPosition": 643973,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659629\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643973\" violates the foreign key: for \"id_documento_viagem\": values \"659629\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659629",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "365",
            "20622",
            "2022-11-24",
            "2022-11-24",
            "0.00",
            "231.16"
          ],
          "rowNumber": 643972,
          "rowPosition": 643973,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659629\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643973\" violates the foreign key: for \"id_documento_viagem\": values \"659629\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659629",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "338",
            "17010",
            "2022-11-09",
            "2022-11-09",
            "0.00",
            "1574.50"
          ],
          "rowNumber": 643973,
          "rowPosition": 643974,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659629\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643974\" violates the foreign key: for \"id_documento_viagem\": values \"659629\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659629",
            "13220297",
            "14407",
            "1958",
            "34",
            "2800",
            "56146",
            "0",
            "338",
            "17010",
            "2022-11-09",
            "2022-11-09",
            "0.00",
            "1574.50"
          ],
          "rowNumber": 643973,
          "rowPosition": 643974,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659629\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643974\" violates the foreign key: for \"id_documento_viagem\": values \"659629\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659667",
            "13412065",
            "14420",
            "1955",
            "20",
            "3012",
            "56642",
            "0",
            "590",
            "13317",
            "2022-11-17",
            "2022-11-18",
            "0.00",
            "381.30"
          ],
          "rowNumber": 643974,
          "rowPosition": 643975,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659667\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643975\" violates the foreign key: for \"id_documento_viagem\": values \"659667\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659667",
            "13412065",
            "14420",
            "1955",
            "20",
            "3012",
            "56642",
            "0",
            "590",
            "13317",
            "2022-11-17",
            "2022-11-18",
            "0.00",
            "381.30"
          ],
          "rowNumber": 643974,
          "rowPosition": 643975,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659667\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643975\" violates the foreign key: for \"id_documento_viagem\": values \"659667\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659670",
            "13385837",
            "14420",
            "1955",
            "20",
            "3012",
            "56642",
            "0",
            "457",
            "4362",
            "2022-11-21",
            "2022-11-22",
            "0.00",
            "15.30"
          ],
          "rowNumber": 643975,
          "rowPosition": 643976,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659670\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643976\" violates the foreign key: for \"id_documento_viagem\": values \"659670\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659670",
            "13385837",
            "14420",
            "1955",
            "20",
            "3012",
            "56642",
            "0",
            "457",
            "4362",
            "2022-11-21",
            "2022-11-22",
            "0.00",
            "15.30"
          ],
          "rowNumber": 643975,
          "rowPosition": 643976,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659670\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643976\" violates the foreign key: for \"id_documento_viagem\": values \"659670\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659668",
            "13214919",
            "14327",
            "1950",
            "58",
            "3012",
            "56215",
            "0",
            "26",
            "1029",
            "2022-11-09",
            "2022-11-09",
            "0.00",
            "381.30"
          ],
          "rowNumber": 643976,
          "rowPosition": 643977,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659668\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643977\" violates the foreign key: for \"id_documento_viagem\": values \"659668\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659668",
            "13214919",
            "14327",
            "1950",
            "58",
            "3012",
            "56215",
            "0",
            "26",
            "1029",
            "2022-11-09",
            "2022-11-09",
            "0.00",
            "381.30"
          ],
          "rowNumber": 643976,
          "rowPosition": 643977,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659668\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643977\" violates the foreign key: for \"id_documento_viagem\": values \"659668\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659666",
            "13385837",
            "14420",
            "1955",
            "20",
            "3012",
            "56642",
            "0",
            "380",
            "4009",
            "2022-10-07",
            "2022-10-10",
            "0.00",
            "15.30"
          ],
          "rowNumber": 643977,
          "rowPosition": 643978,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659666\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643978\" violates the foreign key: for \"id_documento_viagem\": values \"659666\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659666",
            "13385837",
            "14420",
            "1955",
            "20",
            "3012",
            "56642",
            "0",
            "380",
            "4009",
            "2022-10-07",
            "2022-10-10",
            "0.00",
            "15.30"
          ],
          "rowNumber": 643977,
          "rowPosition": 643978,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659666\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643978\" violates the foreign key: for \"id_documento_viagem\": values \"659666\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659671",
            "13215165",
            "14342",
            "1972",
            "55",
            "3012",
            "56475",
            "0",
            "1397",
            "3168",
            "2022-11-03",
            "2022-11-03",
            "0.00",
            "734.70"
          ],
          "rowNumber": 643978,
          "rowPosition": 643979,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659671\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643979\" violates the foreign key: for \"id_documento_viagem\": values \"659671\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659671",
            "13215165",
            "14342",
            "1972",
            "55",
            "3012",
            "56475",
            "0",
            "1397",
            "3168",
            "2022-11-03",
            "2022-11-03",
            "0.00",
            "734.70"
          ],
          "rowNumber": 643978,
          "rowPosition": 643979,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659671\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643979\" violates the foreign key: for \"id_documento_viagem\": values \"659671\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659652",
            "13385837",
            "14420",
            "1955",
            "20",
            "3012",
            "56642",
            "0",
            "446",
            "4350",
            "2022-11-16",
            "2022-11-17",
            "0.00",
            "15.30"
          ],
          "rowNumber": 643979,
          "rowPosition": 643980,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659652\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643980\" violates the foreign key: for \"id_documento_viagem\": values \"659652\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659652",
            "13385837",
            "14420",
            "1955",
            "20",
            "3012",
            "56642",
            "0",
            "446",
            "4350",
            "2022-11-16",
            "2022-11-17",
            "0.00",
            "15.30"
          ],
          "rowNumber": 643979,
          "rowPosition": 643980,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659652\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643980\" violates the foreign key: for \"id_documento_viagem\": values \"659652\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659625",
            "13215165",
            "14342",
            "1972",
            "55",
            "3012",
            "56475",
            "0",
            "1398",
            "3169",
            "2022-11-03",
            "2022-11-03",
            "0.00",
            "734.70"
          ],
          "rowNumber": 643980,
          "rowPosition": 643981,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659625\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643981\" violates the foreign key: for \"id_documento_viagem\": values \"659625\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659625",
            "13215165",
            "14342",
            "1972",
            "55",
            "3012",
            "56475",
            "0",
            "1398",
            "3169",
            "2022-11-03",
            "2022-11-03",
            "0.00",
            "734.70"
          ],
          "rowNumber": 643980,
          "rowPosition": 643981,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659625\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643981\" violates the foreign key: for \"id_documento_viagem\": values \"659625\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659644",
            "13385837",
            "14420",
            "1955",
            "20",
            "3012",
            "56642",
            "0",
            "135",
            "2802",
            "2022-08-09",
            "2022-08-10",
            "0.00",
            "15.30"
          ],
          "rowNumber": 643981,
          "rowPosition": 643982,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659644\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643982\" violates the foreign key: for \"id_documento_viagem\": values \"659644\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659644",
            "13385837",
            "14420",
            "1955",
            "20",
            "3012",
            "56642",
            "0",
            "135",
            "2802",
            "2022-08-09",
            "2022-08-10",
            "0.00",
            "15.30"
          ],
          "rowNumber": 643981,
          "rowPosition": 643982,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659644\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643982\" violates the foreign key: for \"id_documento_viagem\": values \"659644\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659660",
            "13385837",
            "14420",
            "1955",
            "20",
            "3012",
            "56642",
            "0",
            "382",
            "4011",
            "2022-10-07",
            "2022-10-10",
            "0.00",
            "15.30"
          ],
          "rowNumber": 643982,
          "rowPosition": 643983,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659660\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643983\" violates the foreign key: for \"id_documento_viagem\": values \"659660\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "659660",
            "13385837",
            "14420",
            "1955",
            "20",
            "3012",
            "56642",
            "0",
            "382",
            "4011",
            "2022-10-07",
            "2022-10-10",
            "0.00",
            "15.30"
          ],
          "rowNumber": 643982,
          "rowPosition": 643983,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"659660\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"643983\" violates the foreign key: for \"id_documento_viagem\": values \"659660\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 104
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 104,
    "tasks": 1
  },
  "valid": false
}