{
  "version": "4.38.0",
  "time": 101.153,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_diarias_scdp_liqpag",
        "title": "Diárias SCDP - Liquidação e Pagamento",
        "path": "data/ft_diarias_scdp_liqpag.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_documento_viagem",
              "title": "Documento de Viagem - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "description": "- > \n  Chave estrangeira (Foreign Key) que aponta para a Chave Primária (Primary keys) da tabela dm_tempo_diario. \n  Ou seja, por meio dessa chave é possível identificar a data completa a qual o dado se refere.\n\n  Nota: \n  No site dados.mg.gov.br a tabela dm_tempo_diario pode ser encontrada no recurso Calendários - Dias \n  de cada conjunto.\n",
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_empenho",
              "title": "Número do Empenho - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_programa",
              "title": "Programa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_funcao",
              "title": "Função - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_fonte",
              "title": "Fonte de Recurso - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item de Despesa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_acao",
              "title": "Ação Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "fl_passagem",
              "title": "Passagem - Flag",
              "type": "string",
              "format": "default",
              "description": "- '0' - Diárias\n- '1' - Passagem\n",
              "constraints": {
                "required": true,
                "enum": [
                  "0",
                  "1"
                ]
              }
            },
            {
              "name": "nr_liquidacao",
              "title": "Número Liquidação",
              "type": "string",
              "format": "default",
              "description": "Número do documento de liquidação.\n",
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "nr_pagamento",
              "title": "Número Pagamento",
              "type": "string",
              "format": "default",
              "description": "Número do documento de ordem de pagamento.\n",
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "dt_liquidacao",
              "title": "Data da liquidação",
              "type": "date",
              "format": "default"
            },
            {
              "name": "dt_pagamento",
              "type": "date",
              "format": "default"
            },
            {
              "name": "vr_devolvido",
              "title": "Valor Devolvido",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_liqpag",
              "title": "Valor liquidado/Pago",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "description": "- > \n  Valor pago referente às despesas com diárias e passagens aéreas e terrestres de servidor público ou \n  colaborador eventual em razão de viagem a trabalho.\n",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_funcao"
              ],
              "reference": {
                "fields": [
                  "id_funcao"
                ],
                "resource": "dm_funcao_desp"
              }
            },
            {
              "fields": [
                "id_fonte"
              ],
              "reference": {
                "fields": [
                  "id_fonte"
                ],
                "resource": "dm_fonte"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_programa"
              ],
              "reference": {
                "fields": [
                  "id_programa"
                ],
                "resource": "dm_programa"
              }
            },
            {
              "fields": [
                "id_empenho"
              ],
              "reference": {
                "fields": [
                  "id_empenho"
                ],
                "resource": "dm_empenho_desp_diarias_scdp_liqpag"
              }
            },
            {
              "fields": [
                "id_documento_viagem"
              ],
              "reference": {
                "fields": [
                  "id_documento_viagem"
                ],
                "resource": "dm_documento_viagem"
              }
            },
            {
              "fields": [
                "id_acao"
              ],
              "reference": {
                "fields": [
                  "id_acao"
                ],
                "resource": "dm_acao"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_fonte"
              ],
              "reference": {
                "fields": [
                  "id_fonte"
                ],
                "resource": "dm_fonte"
              }
            },
            {
              "fields": [
                "id_programa"
              ],
              "reference": {
                "fields": [
                  "id_programa"
                ],
                "resource": "dm_programa"
              }
            },
            {
              "fields": [
                "id_documento_viagem"
              ],
              "reference": {
                "fields": [
                  "id_documento_viagem"
                ],
                "resource": "dm_documento_viagem"
              }
            },
            {
              "fields": [
                "id_acao"
              ],
              "reference": {
                "fields": [
                  "id_acao"
                ],
                "resource": "dm_acao"
              }
            },
            {
              "fields": [
                "id_empenho"
              ],
              "reference": {
                "fields": [
                  "id_empenho"
                ],
                "resource": "dm_empenho_desp_diarias_scdp_liqpag"
              }
            },
            {
              "fields": [
                "id_funcao"
              ],
              "reference": {
                "fields": [
                  "id_funcao"
                ],
                "resource": "dm_funcao_desp"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_diarias_scdp_liqpag"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "e029b2a063a3842be144e558e1abcbfd",
          "bytes": 10022116,
          "fields": 14,
          "rows": 647966
        }
      },
      "time": 101.153,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "663564",
            "13237313",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "155",
            "160",
            "2022-12-02",
            "2022-12-02",
            "0.00",
            "294.95"
          ],
          "rowNumber": 641570,
          "rowPosition": 641571,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663564\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641571\" violates the foreign key: for \"id_documento_viagem\": values \"663564\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663564",
            "13237313",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "155",
            "160",
            "2022-12-02",
            "2022-12-02",
            "0.00",
            "294.95"
          ],
          "rowNumber": 641570,
          "rowPosition": 641571,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663564\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641571\" violates the foreign key: for \"id_documento_viagem\": values \"663564\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663564",
            "13237313",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "150",
            "154",
            "2022-11-23",
            "2022-11-23",
            "0.00",
            "1474.85"
          ],
          "rowNumber": 641571,
          "rowPosition": 641572,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663564\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641572\" violates the foreign key: for \"id_documento_viagem\": values \"663564\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663564",
            "13237313",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "150",
            "154",
            "2022-11-23",
            "2022-11-23",
            "0.00",
            "1474.85"
          ],
          "rowNumber": 641571,
          "rowPosition": 641572,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663564\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641572\" violates the foreign key: for \"id_documento_viagem\": values \"663564\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663562",
            "13215165",
            "14342",
            "1972",
            "55",
            "3012",
            "56475",
            "0",
            "1568",
            "3448",
            "2022-12-02",
            "2022-12-02",
            "0.00",
            "104.00"
          ],
          "rowNumber": 641572,
          "rowPosition": 641573,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663562\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641573\" violates the foreign key: for \"id_documento_viagem\": values \"663562\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663562",
            "13215165",
            "14342",
            "1972",
            "55",
            "3012",
            "56475",
            "0",
            "1568",
            "3448",
            "2022-12-02",
            "2022-12-02",
            "0.00",
            "104.00"
          ],
          "rowNumber": 641572,
          "rowPosition": 641573,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663562\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641573\" violates the foreign key: for \"id_documento_viagem\": values \"663562\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663562",
            "13215165",
            "14342",
            "1972",
            "55",
            "3012",
            "56475",
            "0",
            "1444",
            "3245",
            "2022-11-10",
            "2022-11-10",
            "0.00",
            "373.74"
          ],
          "rowNumber": 641573,
          "rowPosition": 641574,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663562\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641574\" violates the foreign key: for \"id_documento_viagem\": values \"663562\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663562",
            "13215165",
            "14342",
            "1972",
            "55",
            "3012",
            "56475",
            "0",
            "1444",
            "3245",
            "2022-11-10",
            "2022-11-10",
            "0.00",
            "373.74"
          ],
          "rowNumber": 641573,
          "rowPosition": 641574,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663562\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641574\" violates the foreign key: for \"id_documento_viagem\": values \"663562\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663535",
            "13226694",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "482",
            "1136",
            "2022-11-10",
            "2022-11-11",
            "0.00",
            "69.49"
          ],
          "rowNumber": 641574,
          "rowPosition": 641575,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663535\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641575\" violates the foreign key: for \"id_documento_viagem\": values \"663535\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663535",
            "13226694",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "482",
            "1136",
            "2022-11-10",
            "2022-11-11",
            "0.00",
            "69.49"
          ],
          "rowNumber": 641574,
          "rowPosition": 641575,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663535\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641575\" violates the foreign key: for \"id_documento_viagem\": values \"663535\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663526",
            "13214924",
            "14342",
            "1972",
            "55",
            "3012",
            "56575",
            "0",
            "112",
            "3452",
            "2022-12-02",
            "2022-12-02",
            "0.00",
            "244.40"
          ],
          "rowNumber": 641575,
          "rowPosition": 641576,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663526\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641576\" violates the foreign key: for \"id_documento_viagem\": values \"663526\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663526",
            "13214924",
            "14342",
            "1972",
            "55",
            "3012",
            "56575",
            "0",
            "112",
            "3452",
            "2022-12-02",
            "2022-12-02",
            "0.00",
            "244.40"
          ],
          "rowNumber": 641575,
          "rowPosition": 641576,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663526\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641576\" violates the foreign key: for \"id_documento_viagem\": values \"663526\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663526",
            "13214924",
            "14342",
            "1972",
            "55",
            "3012",
            "56575",
            "0",
            "107",
            "3327",
            "2022-11-18",
            "2022-11-18",
            "0.00",
            "734.70"
          ],
          "rowNumber": 641576,
          "rowPosition": 641577,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663526\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641577\" violates the foreign key: for \"id_documento_viagem\": values \"663526\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663526",
            "13214924",
            "14342",
            "1972",
            "55",
            "3012",
            "56575",
            "0",
            "107",
            "3327",
            "2022-11-18",
            "2022-11-18",
            "0.00",
            "734.70"
          ],
          "rowNumber": 641576,
          "rowPosition": 641577,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663526\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641577\" violates the foreign key: for \"id_documento_viagem\": values \"663526\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663571",
            "13226694",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "489",
            "1164",
            "2022-11-18",
            "2022-11-21",
            "0.00",
            "1018.25"
          ],
          "rowNumber": 641577,
          "rowPosition": 641578,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663571\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641578\" violates the foreign key: for \"id_documento_viagem\": values \"663571\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663571",
            "13226694",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "489",
            "1164",
            "2022-11-18",
            "2022-11-21",
            "0.00",
            "1018.25"
          ],
          "rowNumber": 641577,
          "rowPosition": 641578,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663571\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641578\" violates the foreign key: for \"id_documento_viagem\": values \"663571\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663541",
            "13239857",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "736",
            "871",
            "2022-11-30",
            "2022-11-30",
            "0.00",
            "26.29"
          ],
          "rowNumber": 641578,
          "rowPosition": 641579,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663541\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641579\" violates the foreign key: for \"id_documento_viagem\": values \"663541\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663541",
            "13239857",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "736",
            "871",
            "2022-11-30",
            "2022-11-30",
            "0.00",
            "26.29"
          ],
          "rowNumber": 641578,
          "rowPosition": 641579,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663541\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641579\" violates the foreign key: for \"id_documento_viagem\": values \"663541\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663541",
            "13239857",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "711",
            "846",
            "2022-11-16",
            "2022-11-25",
            "0.00",
            "262.92"
          ],
          "rowNumber": 641579,
          "rowPosition": 641580,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663541\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641580\" violates the foreign key: for \"id_documento_viagem\": values \"663541\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663541",
            "13239857",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "711",
            "846",
            "2022-11-16",
            "2022-11-25",
            "0.00",
            "262.92"
          ],
          "rowNumber": 641579,
          "rowPosition": 641580,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663541\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641580\" violates the foreign key: for \"id_documento_viagem\": values \"663541\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663532",
            "13226694",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "500",
            "1177",
            "2022-11-23",
            "2022-11-24",
            "0.00",
            "1018.25"
          ],
          "rowNumber": 641580,
          "rowPosition": 641581,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663532\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641581\" violates the foreign key: for \"id_documento_viagem\": values \"663532\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663532",
            "13226694",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "500",
            "1177",
            "2022-11-23",
            "2022-11-24",
            "0.00",
            "1018.25"
          ],
          "rowNumber": 641580,
          "rowPosition": 641581,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663532\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641581\" violates the foreign key: for \"id_documento_viagem\": values \"663532\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663570",
            "13219939",
            "14353",
            "1948",
            "58",
            "3012",
            "56157",
            "0",
            "54",
            "449",
            "2022-11-03",
            "2022-11-07",
            "0.00",
            "15.30"
          ],
          "rowNumber": 641582,
          "rowPosition": 641583,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663570\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641583\" violates the foreign key: for \"id_documento_viagem\": values \"663570\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663570",
            "13219939",
            "14353",
            "1948",
            "58",
            "3012",
            "56157",
            "0",
            "54",
            "449",
            "2022-11-03",
            "2022-11-07",
            "0.00",
            "15.30"
          ],
          "rowNumber": 641582,
          "rowPosition": 641583,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663570\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641583\" violates the foreign key: for \"id_documento_viagem\": values \"663570\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663543",
            "13237629",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "578",
            "635",
            "2022-12-01",
            "2022-12-02",
            "0.00",
            "58.99"
          ],
          "rowNumber": 641583,
          "rowPosition": 641584,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663543\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641584\" violates the foreign key: for \"id_documento_viagem\": values \"663543\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663543",
            "13237629",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "578",
            "635",
            "2022-12-01",
            "2022-12-02",
            "0.00",
            "58.99"
          ],
          "rowNumber": 641583,
          "rowPosition": 641584,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663543\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641584\" violates the foreign key: for \"id_documento_viagem\": values \"663543\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663543",
            "13237629",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "567",
            "613",
            "2022-11-10",
            "2022-11-10",
            "0.00",
            "294.97"
          ],
          "rowNumber": 641584,
          "rowPosition": 641585,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663543\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641585\" violates the foreign key: for \"id_documento_viagem\": values \"663543\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663543",
            "13237629",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "567",
            "613",
            "2022-11-10",
            "2022-11-10",
            "0.00",
            "294.97"
          ],
          "rowNumber": 641584,
          "rowPosition": 641585,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663543\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641585\" violates the foreign key: for \"id_documento_viagem\": values \"663543\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663573",
            "13239857",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "739",
            "874",
            "2022-11-30",
            "2022-11-30",
            "0.00",
            "7.12"
          ],
          "rowNumber": 641585,
          "rowPosition": 641586,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663573\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641586\" violates the foreign key: for \"id_documento_viagem\": values \"663573\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663573",
            "13239857",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "739",
            "874",
            "2022-11-30",
            "2022-11-30",
            "0.00",
            "7.12"
          ],
          "rowNumber": 641585,
          "rowPosition": 641586,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663573\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641586\" violates the foreign key: for \"id_documento_viagem\": values \"663573\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663573",
            "13239857",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "731",
            "866",
            "2022-11-25",
            "2022-11-29",
            "0.00",
            "129.00"
          ],
          "rowNumber": 641586,
          "rowPosition": 641587,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663573\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641587\" violates the foreign key: for \"id_documento_viagem\": values \"663573\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663573",
            "13239857",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "731",
            "866",
            "2022-11-25",
            "2022-11-29",
            "0.00",
            "129.00"
          ],
          "rowNumber": 641586,
          "rowPosition": 641587,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663573\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641587\" violates the foreign key: for \"id_documento_viagem\": values \"663573\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663548",
            "13215165",
            "14342",
            "1972",
            "55",
            "3012",
            "56475",
            "0",
            "1569",
            "3449",
            "2022-12-02",
            "2022-12-02",
            "0.00",
            "104.00"
          ],
          "rowNumber": 641587,
          "rowPosition": 641588,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663548\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641588\" violates the foreign key: for \"id_documento_viagem\": values \"663548\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663548",
            "13215165",
            "14342",
            "1972",
            "55",
            "3012",
            "56475",
            "0",
            "1569",
            "3449",
            "2022-12-02",
            "2022-12-02",
            "0.00",
            "104.00"
          ],
          "rowNumber": 641587,
          "rowPosition": 641588,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663548\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641588\" violates the foreign key: for \"id_documento_viagem\": values \"663548\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663548",
            "13215165",
            "14342",
            "1972",
            "55",
            "3012",
            "56475",
            "0",
            "1445",
            "3246",
            "2022-11-10",
            "2022-11-10",
            "0.00",
            "373.74"
          ],
          "rowNumber": 641588,
          "rowPosition": 641589,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663548\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641589\" violates the foreign key: for \"id_documento_viagem\": values \"663548\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663548",
            "13215165",
            "14342",
            "1972",
            "55",
            "3012",
            "56475",
            "0",
            "1445",
            "3246",
            "2022-11-10",
            "2022-11-10",
            "0.00",
            "373.74"
          ],
          "rowNumber": 641588,
          "rowPosition": 641589,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663548\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641589\" violates the foreign key: for \"id_documento_viagem\": values \"663548\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663521",
            "13521864",
            "14420",
            "1955",
            "58",
            "3012",
            "56642",
            "0",
            "33",
            "6745",
            "2022-11-21",
            "2022-11-23",
            "0.00",
            "164.50"
          ],
          "rowNumber": 641589,
          "rowPosition": 641590,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663521\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641590\" violates the foreign key: for \"id_documento_viagem\": values \"663521\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663521",
            "13521864",
            "14420",
            "1955",
            "58",
            "3012",
            "56642",
            "0",
            "33",
            "6745",
            "2022-11-21",
            "2022-11-23",
            "0.00",
            "164.50"
          ],
          "rowNumber": 641589,
          "rowPosition": 641590,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663521\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641590\" violates the foreign key: for \"id_documento_viagem\": values \"663521\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663566",
            "13226694",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "426",
            "953",
            "2022-09-16",
            "2022-09-19",
            "0.00",
            "1961.26"
          ],
          "rowNumber": 641590,
          "rowPosition": 641591,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663566\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641591\" violates the foreign key: for \"id_documento_viagem\": values \"663566\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663566",
            "13226694",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "426",
            "953",
            "2022-09-16",
            "2022-09-19",
            "0.00",
            "1961.26"
          ],
          "rowNumber": 641590,
          "rowPosition": 641591,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663566\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641591\" violates the foreign key: for \"id_documento_viagem\": values \"663566\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663536",
            "13409929",
            "14420",
            "1955",
            "20",
            "3012",
            "56642",
            "0",
            "300",
            "5347",
            "2022-12-01",
            "2022-12-02",
            "0.00",
            "198.30"
          ],
          "rowNumber": 641591,
          "rowPosition": 641592,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663536\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641592\" violates the foreign key: for \"id_documento_viagem\": values \"663536\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663536",
            "13409929",
            "14420",
            "1955",
            "20",
            "3012",
            "56642",
            "0",
            "300",
            "5347",
            "2022-12-01",
            "2022-12-02",
            "0.00",
            "198.30"
          ],
          "rowNumber": 641591,
          "rowPosition": 641592,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663536\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641592\" violates the foreign key: for \"id_documento_viagem\": values \"663536\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663563",
            "13317842",
            "14411",
            "1948",
            "58",
            "3012",
            "56823",
            "0",
            "19",
            "977",
            "2022-11-16",
            "2022-11-16",
            "0.00",
            "1744.98"
          ],
          "rowNumber": 641592,
          "rowPosition": 641593,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663563\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641593\" violates the foreign key: for \"id_documento_viagem\": values \"663563\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663563",
            "13317842",
            "14411",
            "1948",
            "58",
            "3012",
            "56823",
            "0",
            "19",
            "977",
            "2022-11-16",
            "2022-11-16",
            "0.00",
            "1744.98"
          ],
          "rowNumber": 641592,
          "rowPosition": 641593,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663563\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641593\" violates the foreign key: for \"id_documento_viagem\": values \"663563\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663539",
            "13239857",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "735",
            "870",
            "2022-11-30",
            "2022-11-30",
            "0.00",
            "26.29"
          ],
          "rowNumber": 641593,
          "rowPosition": 641594,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663539\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641594\" violates the foreign key: for \"id_documento_viagem\": values \"663539\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663539",
            "13239857",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "735",
            "870",
            "2022-11-30",
            "2022-11-30",
            "0.00",
            "26.29"
          ],
          "rowNumber": 641593,
          "rowPosition": 641594,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663539\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641594\" violates the foreign key: for \"id_documento_viagem\": values \"663539\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663539",
            "13239857",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "712",
            "845",
            "2022-11-16",
            "2022-11-25",
            "0.00",
            "262.92"
          ],
          "rowNumber": 641594,
          "rowPosition": 641595,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663539\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641595\" violates the foreign key: for \"id_documento_viagem\": values \"663539\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663539",
            "13239857",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "712",
            "845",
            "2022-11-16",
            "2022-11-25",
            "0.00",
            "262.92"
          ],
          "rowNumber": 641594,
          "rowPosition": 641595,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663539\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641595\" violates the foreign key: for \"id_documento_viagem\": values \"663539\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663544",
            "13239857",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "737",
            "872",
            "2022-11-30",
            "2022-11-30",
            "0.00",
            "26.29"
          ],
          "rowNumber": 641595,
          "rowPosition": 641596,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663544\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641596\" violates the foreign key: for \"id_documento_viagem\": values \"663544\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663544",
            "13239857",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "737",
            "872",
            "2022-11-30",
            "2022-11-30",
            "0.00",
            "26.29"
          ],
          "rowNumber": 641595,
          "rowPosition": 641596,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663544\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641596\" violates the foreign key: for \"id_documento_viagem\": values \"663544\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663544",
            "13239857",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "720",
            "850",
            "2022-11-25",
            "2022-11-25",
            "0.00",
            "262.92"
          ],
          "rowNumber": 641596,
          "rowPosition": 641597,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663544\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641597\" violates the foreign key: for \"id_documento_viagem\": values \"663544\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663544",
            "13239857",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "720",
            "850",
            "2022-11-25",
            "2022-11-25",
            "0.00",
            "262.92"
          ],
          "rowNumber": 641596,
          "rowPosition": 641597,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663544\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641597\" violates the foreign key: for \"id_documento_viagem\": values \"663544\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663556",
            "13409929",
            "14420",
            "1955",
            "20",
            "3012",
            "56642",
            "0",
            "298",
            "5302",
            "2022-11-29",
            "2022-12-01",
            "0.00",
            "15.30"
          ],
          "rowNumber": 641597,
          "rowPosition": 641598,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663556\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641598\" violates the foreign key: for \"id_documento_viagem\": values \"663556\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663556",
            "13409929",
            "14420",
            "1955",
            "20",
            "3012",
            "56642",
            "0",
            "298",
            "5302",
            "2022-11-29",
            "2022-12-01",
            "0.00",
            "15.30"
          ],
          "rowNumber": 641597,
          "rowPosition": 641598,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663556\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641598\" violates the foreign key: for \"id_documento_viagem\": values \"663556\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663567",
            "13226694",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "481",
            "1135",
            "2022-11-10",
            "2022-11-11",
            "0.00",
            "306.68"
          ],
          "rowNumber": 641598,
          "rowPosition": 641599,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663567\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641599\" violates the foreign key: for \"id_documento_viagem\": values \"663567\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663567",
            "13226694",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "481",
            "1135",
            "2022-11-10",
            "2022-11-11",
            "0.00",
            "306.68"
          ],
          "rowNumber": 641598,
          "rowPosition": 641599,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663567\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641599\" violates the foreign key: for \"id_documento_viagem\": values \"663567\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663561",
            "13216322",
            "14322",
            "1970",
            "49",
            "3012",
            "56744",
            "0",
            "73",
            "982",
            "2022-11-25",
            "2022-11-25",
            "0.00",
            "335.40"
          ],
          "rowNumber": 641600,
          "rowPosition": 641601,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663561\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641601\" violates the foreign key: for \"id_documento_viagem\": values \"663561\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663561",
            "13216322",
            "14322",
            "1970",
            "49",
            "3012",
            "56744",
            "0",
            "73",
            "982",
            "2022-11-25",
            "2022-11-25",
            "0.00",
            "335.40"
          ],
          "rowNumber": 641600,
          "rowPosition": 641601,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663561\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641601\" violates the foreign key: for \"id_documento_viagem\": values \"663561\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663565",
            "13219939",
            "14353",
            "1948",
            "58",
            "3012",
            "56157",
            "0",
            "67",
            "496",
            "2022-11-29",
            "2022-11-29",
            "0.00",
            "15.30"
          ],
          "rowNumber": 641601,
          "rowPosition": 641602,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663565\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641602\" violates the foreign key: for \"id_documento_viagem\": values \"663565\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663565",
            "13219939",
            "14353",
            "1948",
            "58",
            "3012",
            "56157",
            "0",
            "67",
            "496",
            "2022-11-29",
            "2022-11-29",
            "0.00",
            "15.30"
          ],
          "rowNumber": 641601,
          "rowPosition": 641602,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663565\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641602\" violates the foreign key: for \"id_documento_viagem\": values \"663565\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663545",
            "13231308",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "180",
            "488",
            "2022-11-23",
            "2022-11-23",
            "0.00",
            "15.30"
          ],
          "rowNumber": 641602,
          "rowPosition": 641603,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663545\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641603\" violates the foreign key: for \"id_documento_viagem\": values \"663545\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663545",
            "13231308",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "180",
            "488",
            "2022-11-23",
            "2022-11-23",
            "0.00",
            "15.30"
          ],
          "rowNumber": 641602,
          "rowPosition": 641603,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663545\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641603\" violates the foreign key: for \"id_documento_viagem\": values \"663545\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663553",
            "13219939",
            "14353",
            "1948",
            "58",
            "3012",
            "56157",
            "0",
            "69",
            "498",
            "2022-11-29",
            "2022-11-29",
            "0.00",
            "15.30"
          ],
          "rowNumber": 641603,
          "rowPosition": 641604,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663553\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641604\" violates the foreign key: for \"id_documento_viagem\": values \"663553\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663553",
            "13219939",
            "14353",
            "1948",
            "58",
            "3012",
            "56157",
            "0",
            "69",
            "498",
            "2022-11-29",
            "2022-11-29",
            "0.00",
            "15.30"
          ],
          "rowNumber": 641603,
          "rowPosition": 641604,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663553\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641604\" violates the foreign key: for \"id_documento_viagem\": values \"663553\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663534",
            "13219939",
            "14353",
            "1948",
            "58",
            "3012",
            "56157",
            "0",
            "65",
            "485",
            "2022-11-23",
            "2022-11-23",
            "0.00",
            "1104.50"
          ],
          "rowNumber": 641604,
          "rowPosition": 641605,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663534\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641605\" violates the foreign key: for \"id_documento_viagem\": values \"663534\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663534",
            "13219939",
            "14353",
            "1948",
            "58",
            "3012",
            "56157",
            "0",
            "65",
            "485",
            "2022-11-23",
            "2022-11-23",
            "0.00",
            "1104.50"
          ],
          "rowNumber": 641604,
          "rowPosition": 641605,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663534\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641605\" violates the foreign key: for \"id_documento_viagem\": values \"663534\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663551",
            "13239857",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "738",
            "873",
            "2022-11-30",
            "2022-11-30",
            "0.00",
            "26.29"
          ],
          "rowNumber": 641605,
          "rowPosition": 641606,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663551\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641606\" violates the foreign key: for \"id_documento_viagem\": values \"663551\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663551",
            "13239857",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "738",
            "873",
            "2022-11-30",
            "2022-11-30",
            "0.00",
            "26.29"
          ],
          "rowNumber": 641605,
          "rowPosition": 641606,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663551\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641606\" violates the foreign key: for \"id_documento_viagem\": values \"663551\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663551",
            "13239857",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "726",
            "856",
            "2022-11-25",
            "2022-11-25",
            "0.00",
            "262.92"
          ],
          "rowNumber": 641606,
          "rowPosition": 641607,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663551\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641607\" violates the foreign key: for \"id_documento_viagem\": values \"663551\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663551",
            "13239857",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "726",
            "856",
            "2022-11-25",
            "2022-11-25",
            "0.00",
            "262.92"
          ],
          "rowNumber": 641606,
          "rowPosition": 641607,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663551\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641607\" violates the foreign key: for \"id_documento_viagem\": values \"663551\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663558",
            "13226694",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "490",
            "1165",
            "2022-11-18",
            "2022-11-21",
            "0.00",
            "1018.25"
          ],
          "rowNumber": 641607,
          "rowPosition": 641608,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663558\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641608\" violates the foreign key: for \"id_documento_viagem\": values \"663558\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663558",
            "13226694",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "490",
            "1165",
            "2022-11-18",
            "2022-11-21",
            "0.00",
            "1018.25"
          ],
          "rowNumber": 641607,
          "rowPosition": 641608,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663558\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641608\" violates the foreign key: for \"id_documento_viagem\": values \"663558\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663538",
            "13214440",
            "14322",
            "1970",
            "6",
            "3012",
            "56742",
            "0",
            "24",
            "981",
            "2022-11-24",
            "2022-11-25",
            "503.10",
            "503.10"
          ],
          "rowNumber": 641608,
          "rowPosition": 641609,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663538\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641609\" violates the foreign key: for \"id_documento_viagem\": values \"663538\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663538",
            "13214440",
            "14322",
            "1970",
            "6",
            "3012",
            "56742",
            "0",
            "24",
            "981",
            "2022-11-24",
            "2022-11-25",
            "503.10",
            "503.10"
          ],
          "rowNumber": 641608,
          "rowPosition": 641609,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663538\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641609\" violates the foreign key: for \"id_documento_viagem\": values \"663538\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663572",
            "13226694",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "472",
            "1110",
            "2022-11-09",
            "2022-11-11",
            "0.00",
            "1018.25"
          ],
          "rowNumber": 641609,
          "rowPosition": 641610,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663572\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641610\" violates the foreign key: for \"id_documento_viagem\": values \"663572\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663572",
            "13226694",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "472",
            "1110",
            "2022-11-09",
            "2022-11-11",
            "0.00",
            "1018.25"
          ],
          "rowNumber": 641609,
          "rowPosition": 641610,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663572\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641610\" violates the foreign key: for \"id_documento_viagem\": values \"663572\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663528",
            "13226694",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "494",
            "1150",
            "2022-11-18",
            "2022-11-21",
            "0.00",
            "592.88"
          ],
          "rowNumber": 641610,
          "rowPosition": 641611,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663528\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641611\" violates the foreign key: for \"id_documento_viagem\": values \"663528\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663528",
            "13226694",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "494",
            "1150",
            "2022-11-18",
            "2022-11-21",
            "0.00",
            "592.88"
          ],
          "rowNumber": 641610,
          "rowPosition": 641611,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663528\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641611\" violates the foreign key: for \"id_documento_viagem\": values \"663528\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663529",
            "13218634",
            "14353",
            "1948",
            "58",
            "3012",
            "56157",
            "0",
            "142",
            "1068",
            "2022-10-17",
            "2022-10-18",
            "0.00",
            "879.50"
          ],
          "rowNumber": 641611,
          "rowPosition": 641612,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663529\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641612\" violates the foreign key: for \"id_documento_viagem\": values \"663529\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663529",
            "13218634",
            "14353",
            "1948",
            "58",
            "3012",
            "56157",
            "0",
            "142",
            "1068",
            "2022-10-17",
            "2022-10-18",
            "0.00",
            "879.50"
          ],
          "rowNumber": 641611,
          "rowPosition": 641612,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663529\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641612\" violates the foreign key: for \"id_documento_viagem\": values \"663529\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663559",
            "13249902",
            "14363",
            "1961",
            "486",
            "3012",
            "56673",
            "0",
            "16",
            "260",
            "2022-11-21",
            "2022-11-21",
            "0.00",
            "167.70"
          ],
          "rowNumber": 641612,
          "rowPosition": 641613,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663559\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641613\" violates the foreign key: for \"id_documento_viagem\": values \"663559\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663559",
            "13249902",
            "14363",
            "1961",
            "486",
            "3012",
            "56673",
            "0",
            "16",
            "260",
            "2022-11-21",
            "2022-11-21",
            "0.00",
            "167.70"
          ],
          "rowNumber": 641612,
          "rowPosition": 641613,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663559\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641613\" violates the foreign key: for \"id_documento_viagem\": values \"663559\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663552",
            "13267936",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "80",
            "85",
            "2022-11-23",
            "2022-12-01",
            "0.00",
            "26.29"
          ],
          "rowNumber": 641613,
          "rowPosition": 641614,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663552\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641614\" violates the foreign key: for \"id_documento_viagem\": values \"663552\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663552",
            "13267936",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "80",
            "85",
            "2022-11-23",
            "2022-12-01",
            "0.00",
            "26.29"
          ],
          "rowNumber": 641613,
          "rowPosition": 641614,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663552\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641614\" violates the foreign key: for \"id_documento_viagem\": values \"663552\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663552",
            "13267936",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "69",
            "72",
            "2022-11-04",
            "2022-11-04",
            "0.00",
            "262.92"
          ],
          "rowNumber": 641614,
          "rowPosition": 641615,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663552\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641615\" violates the foreign key: for \"id_documento_viagem\": values \"663552\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663552",
            "13267936",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "69",
            "72",
            "2022-11-04",
            "2022-11-04",
            "0.00",
            "262.92"
          ],
          "rowNumber": 641614,
          "rowPosition": 641615,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663552\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641615\" violates the foreign key: for \"id_documento_viagem\": values \"663552\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663555",
            "13226694",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "476",
            "1117",
            "2022-11-10",
            "2022-11-11",
            "0.00",
            "1018.25"
          ],
          "rowNumber": 641615,
          "rowPosition": 641616,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663555\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641616\" violates the foreign key: for \"id_documento_viagem\": values \"663555\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663555",
            "13226694",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "476",
            "1117",
            "2022-11-10",
            "2022-11-11",
            "0.00",
            "1018.25"
          ],
          "rowNumber": 641615,
          "rowPosition": 641616,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663555\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641616\" violates the foreign key: for \"id_documento_viagem\": values \"663555\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663533",
            "13225321",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "176",
            "725",
            "2022-12-01",
            "2022-12-02",
            "0.00",
            "75.00"
          ],
          "rowNumber": 641616,
          "rowPosition": 641617,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663533\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641617\" violates the foreign key: for \"id_documento_viagem\": values \"663533\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663533",
            "13225321",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "176",
            "725",
            "2022-12-01",
            "2022-12-02",
            "0.00",
            "75.00"
          ],
          "rowNumber": 641616,
          "rowPosition": 641617,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663533\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641617\" violates the foreign key: for \"id_documento_viagem\": values \"663533\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663533",
            "13225321",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "172",
            "711",
            "2022-11-25",
            "2022-11-28",
            "0.00",
            "198.30"
          ],
          "rowNumber": 641617,
          "rowPosition": 641618,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663533\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641618\" violates the foreign key: for \"id_documento_viagem\": values \"663533\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663533",
            "13225321",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "172",
            "711",
            "2022-11-25",
            "2022-11-28",
            "0.00",
            "198.30"
          ],
          "rowNumber": 641617,
          "rowPosition": 641618,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663533\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641618\" violates the foreign key: for \"id_documento_viagem\": values \"663533\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663530",
            "13226694",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "477",
            "1118",
            "2022-11-10",
            "2022-11-11",
            "0.00",
            "306.68"
          ],
          "rowNumber": 641618,
          "rowPosition": 641619,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663530\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641619\" violates the foreign key: for \"id_documento_viagem\": values \"663530\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663530",
            "13226694",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "477",
            "1118",
            "2022-11-10",
            "2022-11-11",
            "0.00",
            "306.68"
          ],
          "rowNumber": 641618,
          "rowPosition": 641619,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663530\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641619\" violates the foreign key: for \"id_documento_viagem\": values \"663530\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663549",
            "13222434",
            "14390",
            "1955",
            "58",
            "3012",
            "56714",
            "0",
            "25",
            "369",
            "2022-10-21",
            "2022-10-21",
            "0.00",
            "2139.50"
          ],
          "rowNumber": 641619,
          "rowPosition": 641620,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663549\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641620\" violates the foreign key: for \"id_documento_viagem\": values \"663549\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663549",
            "13222434",
            "14390",
            "1955",
            "58",
            "3012",
            "56714",
            "0",
            "25",
            "369",
            "2022-10-21",
            "2022-10-21",
            "0.00",
            "2139.50"
          ],
          "rowNumber": 641619,
          "rowPosition": 641620,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663549\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641620\" violates the foreign key: for \"id_documento_viagem\": values \"663549\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663560",
            "13237629",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "577",
            "639",
            "2022-12-01",
            "2022-12-02",
            "0.00",
            "7.12"
          ],
          "rowNumber": 641620,
          "rowPosition": 641621,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663560\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641621\" violates the foreign key: for \"id_documento_viagem\": values \"663560\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663560",
            "13237629",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "577",
            "639",
            "2022-12-01",
            "2022-12-02",
            "0.00",
            "7.12"
          ],
          "rowNumber": 641620,
          "rowPosition": 641621,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663560\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641621\" violates the foreign key: for \"id_documento_viagem\": values \"663560\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663560",
            "13237629",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "568",
            "615",
            "2022-11-10",
            "2022-11-10",
            "0.00",
            "129.00"
          ],
          "rowNumber": 641621,
          "rowPosition": 641622,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663560\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641622\" violates the foreign key: for \"id_documento_viagem\": values \"663560\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663560",
            "13237629",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "568",
            "615",
            "2022-11-10",
            "2022-11-10",
            "0.00",
            "129.00"
          ],
          "rowNumber": 641621,
          "rowPosition": 641622,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663560\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641622\" violates the foreign key: for \"id_documento_viagem\": values \"663560\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663531",
            "13226694",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "501",
            "1178",
            "2022-11-23",
            "2022-11-24",
            "0.00",
            "1018.25"
          ],
          "rowNumber": 641622,
          "rowPosition": 641623,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663531\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641623\" violates the foreign key: for \"id_documento_viagem\": values \"663531\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663531",
            "13226694",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "501",
            "1178",
            "2022-11-23",
            "2022-11-24",
            "0.00",
            "1018.25"
          ],
          "rowNumber": 641622,
          "rowPosition": 641623,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663531\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641623\" violates the foreign key: for \"id_documento_viagem\": values \"663531\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663546",
            "13216322",
            "14322",
            "1970",
            "49",
            "3012",
            "56744",
            "0",
            "74",
            "983",
            "2022-11-25",
            "2022-11-25",
            "0.00",
            "381.30"
          ],
          "rowNumber": 641623,
          "rowPosition": 641624,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663546\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641624\" violates the foreign key: for \"id_documento_viagem\": values \"663546\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663546",
            "13216322",
            "14322",
            "1970",
            "49",
            "3012",
            "56744",
            "0",
            "74",
            "983",
            "2022-11-25",
            "2022-11-25",
            "0.00",
            "381.30"
          ],
          "rowNumber": 641623,
          "rowPosition": 641624,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663546\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641624\" violates the foreign key: for \"id_documento_viagem\": values \"663546\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663524",
            "13214924",
            "14342",
            "1972",
            "55",
            "3012",
            "56575",
            "0",
            "111",
            "3451",
            "2022-12-02",
            "2022-12-02",
            "0.00",
            "244.40"
          ],
          "rowNumber": 641624,
          "rowPosition": 641625,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663524\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641625\" violates the foreign key: for \"id_documento_viagem\": values \"663524\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663524",
            "13214924",
            "14342",
            "1972",
            "55",
            "3012",
            "56575",
            "0",
            "111",
            "3451",
            "2022-12-02",
            "2022-12-02",
            "0.00",
            "244.40"
          ],
          "rowNumber": 641624,
          "rowPosition": 641625,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663524\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641625\" violates the foreign key: for \"id_documento_viagem\": values \"663524\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663524",
            "13214924",
            "14342",
            "1972",
            "55",
            "3012",
            "56575",
            "0",
            "106",
            "3326",
            "2022-11-18",
            "2022-11-18",
            "0.00",
            "734.70"
          ],
          "rowNumber": 641625,
          "rowPosition": 641626,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663524\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641626\" violates the foreign key: for \"id_documento_viagem\": values \"663524\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663524",
            "13214924",
            "14342",
            "1972",
            "55",
            "3012",
            "56575",
            "0",
            "106",
            "3326",
            "2022-11-18",
            "2022-11-18",
            "0.00",
            "734.70"
          ],
          "rowNumber": 641625,
          "rowPosition": 641626,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663524\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641626\" violates the foreign key: for \"id_documento_viagem\": values \"663524\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663547",
            "13226694",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "493",
            "1148",
            "2022-11-18",
            "2022-11-21",
            "0.00",
            "1018.25"
          ],
          "rowNumber": 641626,
          "rowPosition": 641627,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663547\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641627\" violates the foreign key: for \"id_documento_viagem\": values \"663547\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663547",
            "13226694",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "493",
            "1148",
            "2022-11-18",
            "2022-11-21",
            "0.00",
            "1018.25"
          ],
          "rowNumber": 641626,
          "rowPosition": 641627,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663547\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641627\" violates the foreign key: for \"id_documento_viagem\": values \"663547\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663522",
            "13226694",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "492",
            "1147",
            "2022-11-18",
            "2022-11-21",
            "0.00",
            "1018.25"
          ],
          "rowNumber": 641627,
          "rowPosition": 641628,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663522\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641628\" violates the foreign key: for \"id_documento_viagem\": values \"663522\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663522",
            "13226694",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "492",
            "1147",
            "2022-11-18",
            "2022-11-21",
            "0.00",
            "1018.25"
          ],
          "rowNumber": 641627,
          "rowPosition": 641628,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663522\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641628\" violates the foreign key: for \"id_documento_viagem\": values \"663522\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663540",
            "13226694",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "499",
            "1176",
            "2022-11-23",
            "2022-11-24",
            "0.00",
            "1018.25"
          ],
          "rowNumber": 641628,
          "rowPosition": 641629,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663540\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641629\" violates the foreign key: for \"id_documento_viagem\": values \"663540\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663540",
            "13226694",
            "14286",
            "1948",
            "58",
            "3012",
            "56726",
            "0",
            "499",
            "1176",
            "2022-11-23",
            "2022-11-24",
            "0.00",
            "1018.25"
          ],
          "rowNumber": 641628,
          "rowPosition": 641629,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663540\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641629\" violates the foreign key: for \"id_documento_viagem\": values \"663540\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663563",
            "13316639",
            "14411",
            "1948",
            "58",
            "2772",
            "56823",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "960.36"
          ],
          "rowNumber": 641629,
          "rowPosition": 641630,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663563\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641630\" violates the foreign key: for \"id_documento_viagem\": values \"663563\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663563",
            "13316639",
            "14411",
            "1948",
            "58",
            "2772",
            "56823",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "960.36"
          ],
          "rowNumber": 641629,
          "rowPosition": 641630,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663563\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641630\" violates the foreign key: for \"id_documento_viagem\": values \"663563\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663563",
            "13316639",
            "14411",
            "1948",
            "58",
            "2772",
            "56823",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "959.33"
          ],
          "rowNumber": 641630,
          "rowPosition": 641631,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663563\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641631\" violates the foreign key: for \"id_documento_viagem\": values \"663563\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663563",
            "13316639",
            "14411",
            "1948",
            "58",
            "2772",
            "56823",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "959.33"
          ],
          "rowNumber": 641630,
          "rowPosition": 641631,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663563\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641631\" violates the foreign key: for \"id_documento_viagem\": values \"663563\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663549",
            "13221349",
            "14390",
            "1955",
            "58",
            "2772",
            "56714",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "219.00"
          ],
          "rowNumber": 641631,
          "rowPosition": 641632,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663549\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641632\" violates the foreign key: for \"id_documento_viagem\": values \"663549\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "663549",
            "13221349",
            "14390",
            "1955",
            "58",
            "2772",
            "56714",
            "1",
            "0",
            "0",
            "",
            "",
            "0.00",
            "219.00"
          ],
          "rowNumber": 641631,
          "rowPosition": 641632,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"663549\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"641632\" violates the foreign key: for \"id_documento_viagem\": values \"663549\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 120
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 120,
    "tasks": 1
  },
  "valid": false
}