{
  "version": "4.16.6",
  "time": 142.03,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_diarias_scdp_liqpag",
        "title": "Diárias SCDP - Liquidação e Pagamento",
        "path": "data/ft_diarias_scdp_liqpag.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_documento_viagem",
              "title": "Documento de Viagem - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "description": "- > \n  Chave estrangeira (Foreign Key) que aponta para a Chave Primária (Primary keys) da tabela dm_tempo_diario. \n  Ou seja, por meio dessa chave é possível identificar a data completa a qual o dado se refere.\n\n  Nota: \n  No site dados.mg.gov.br a tabela dm_tempo_diario pode ser encontrada no recurso Calendários - Dias \n  de cada conjunto.\n",
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_empenho",
              "title": "Número do Empenho - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_programa",
              "title": "Programa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_funcao",
              "title": "Função - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_fonte",
              "title": "Fonte de Recurso - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item de Despesa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_acao",
              "title": "Ação Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "fl_passagem",
              "title": "Passagem - Flag",
              "type": "string",
              "format": "default",
              "description": "- '0' - Diárias\n- '1' - Passagem\n",
              "constraints": {
                "required": true,
                "enum": [
                  "0",
                  "1"
                ]
              }
            },
            {
              "name": "nr_liquidacao",
              "title": "Número Liquidação",
              "type": "string",
              "format": "default",
              "description": "Número do documento de liquidação.\n",
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "nr_pagamento",
              "title": "Número Pagamento",
              "type": "string",
              "format": "default",
              "description": "Número do documento de ordem de pagamento.\n",
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "dt_liquidacao",
              "title": "Data da liquidação",
              "type": "date",
              "format": "default"
            },
            {
              "name": "dt_pagamento",
              "type": "date",
              "format": "default"
            },
            {
              "name": "vr_devolvido",
              "title": "Valor Devolvido",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_liqpag",
              "title": "Valor liquidado/Pago",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "description": "- > \n  Valor pago referente às despesas com diárias e passagens aéreas e terrestres de servidor público ou \n  colaborador eventual em razão de viagem a trabalho.\n",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_funcao"
              ],
              "reference": {
                "fields": [
                  "id_funcao"
                ],
                "resource": "dm_funcao_desp"
              }
            },
            {
              "fields": [
                "id_fonte"
              ],
              "reference": {
                "fields": [
                  "id_fonte"
                ],
                "resource": "dm_fonte"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_programa"
              ],
              "reference": {
                "fields": [
                  "id_programa"
                ],
                "resource": "dm_programa"
              }
            },
            {
              "fields": [
                "id_empenho"
              ],
              "reference": {
                "fields": [
                  "id_empenho"
                ],
                "resource": "dm_empenho_desp_diarias_scdp_liqpag"
              }
            },
            {
              "fields": [
                "id_documento_viagem"
              ],
              "reference": {
                "fields": [
                  "id_documento_viagem"
                ],
                "resource": "dm_documento_viagem"
              }
            },
            {
              "fields": [
                "id_acao"
              ],
              "reference": {
                "fields": [
                  "id_acao"
                ],
                "resource": "dm_acao"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_fonte"
              ],
              "reference": {
                "fields": [
                  "id_fonte"
                ],
                "resource": "dm_fonte"
              }
            },
            {
              "fields": [
                "id_programa"
              ],
              "reference": {
                "fields": [
                  "id_programa"
                ],
                "resource": "dm_programa"
              }
            },
            {
              "fields": [
                "id_documento_viagem"
              ],
              "reference": {
                "fields": [
                  "id_documento_viagem"
                ],
                "resource": "dm_documento_viagem"
              }
            },
            {
              "fields": [
                "id_acao"
              ],
              "reference": {
                "fields": [
                  "id_acao"
                ],
                "resource": "dm_acao"
              }
            },
            {
              "fields": [
                "id_empenho"
              ],
              "reference": {
                "fields": [
                  "id_empenho"
                ],
                "resource": "dm_empenho_desp_diarias_scdp_liqpag"
              }
            },
            {
              "fields": [
                "id_funcao"
              ],
              "reference": {
                "fields": [
                  "id_funcao"
                ],
                "resource": "dm_funcao_desp"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_diarias_scdp_liqpag"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "83745da73653b85a975d833a4d8e2ac0",
          "bytes": 12174138,
          "fields": 14,
          "rows": 782229
        }
      },
      "time": 142.03,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778621,
          "rowPosition": 778622,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778622\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778621,
          "rowPosition": 778622,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778622\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778622,
          "rowPosition": 778623,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778623\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778622,
          "rowPosition": 778623,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778623\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778623,
          "rowPosition": 778624,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778624\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778623,
          "rowPosition": 778624,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778624\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778624,
          "rowPosition": 778625,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778625\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778624,
          "rowPosition": 778625,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778625\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778625,
          "rowPosition": 778626,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778626\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778625,
          "rowPosition": 778626,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778626\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778626,
          "rowPosition": 778627,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778627\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778626,
          "rowPosition": 778627,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778627\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778627,
          "rowPosition": 778628,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778628\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778627,
          "rowPosition": 778628,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778628\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778628,
          "rowPosition": 778629,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778629\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778628,
          "rowPosition": 778629,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778629\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778629,
          "rowPosition": 778630,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778630\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778629,
          "rowPosition": 778630,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778630\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778630,
          "rowPosition": 778631,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778631\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778630,
          "rowPosition": 778631,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778631\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778631,
          "rowPosition": 778632,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778632\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778631,
          "rowPosition": 778632,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778632\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778632,
          "rowPosition": 778633,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778633\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778632,
          "rowPosition": 778633,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778633\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778633,
          "rowPosition": 778634,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778634\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778633,
          "rowPosition": 778634,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778634\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778634,
          "rowPosition": 778635,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778635\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778634,
          "rowPosition": 778635,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778635\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778635,
          "rowPosition": 778636,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778636\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778635,
          "rowPosition": 778636,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778636\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778636,
          "rowPosition": 778637,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778637\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778636,
          "rowPosition": 778637,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778637\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778637,
          "rowPosition": 778638,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778638\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778637,
          "rowPosition": 778638,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778638\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778638,
          "rowPosition": 778639,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778639\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778638,
          "rowPosition": 778639,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778639\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778639,
          "rowPosition": 778640,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778640\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778639,
          "rowPosition": 778640,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778640\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778640,
          "rowPosition": 778641,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778641\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778640,
          "rowPosition": 778641,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778641\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778641,
          "rowPosition": 778642,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778642\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778641,
          "rowPosition": 778642,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778642\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778642,
          "rowPosition": 778643,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778643\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778642,
          "rowPosition": 778643,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778643\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778643,
          "rowPosition": 778644,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778644\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778643,
          "rowPosition": 778644,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778644\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778644,
          "rowPosition": 778645,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778645\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778644,
          "rowPosition": 778645,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778645\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778645,
          "rowPosition": 778646,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778646\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778645,
          "rowPosition": 778646,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778646\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778646,
          "rowPosition": 778647,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778647\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778646,
          "rowPosition": 778647,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778647\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778647,
          "rowPosition": 778648,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778648\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778647,
          "rowPosition": 778648,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778648\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778648,
          "rowPosition": 778649,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778649\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778648,
          "rowPosition": 778649,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778649\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778649,
          "rowPosition": 778650,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778650\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778649,
          "rowPosition": 778650,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778650\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778651,
          "rowPosition": 778652,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778652\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778651,
          "rowPosition": 778652,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778652\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778652,
          "rowPosition": 778653,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778653\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778652,
          "rowPosition": 778653,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778653\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778653,
          "rowPosition": 778654,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778654\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778653,
          "rowPosition": 778654,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778654\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778654,
          "rowPosition": 778655,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778655\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778654,
          "rowPosition": 778655,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778655\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778655,
          "rowPosition": 778656,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778656\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778655,
          "rowPosition": 778656,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778656\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778656,
          "rowPosition": 778657,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778657\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778656,
          "rowPosition": 778657,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778657\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778657,
          "rowPosition": 778658,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778658\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778657,
          "rowPosition": 778658,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778658\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778658,
          "rowPosition": 778659,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778659\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778658,
          "rowPosition": 778659,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778659\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778659,
          "rowPosition": 778660,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778660\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778659,
          "rowPosition": 778660,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778660\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778660,
          "rowPosition": 778661,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778661\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778660,
          "rowPosition": 778661,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778661\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778661,
          "rowPosition": 778662,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778662\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778661,
          "rowPosition": 778662,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778662\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778662,
          "rowPosition": 778663,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778663\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778662,
          "rowPosition": 778663,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778663\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778663,
          "rowPosition": 778664,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778664\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778663,
          "rowPosition": 778664,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778664\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778664,
          "rowPosition": 778665,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778665\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778664,
          "rowPosition": 778665,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778665\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778665,
          "rowPosition": 778666,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778666\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778665,
          "rowPosition": 778666,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778666\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778666,
          "rowPosition": 778667,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778667\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778666,
          "rowPosition": 778667,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778667\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778667,
          "rowPosition": 778668,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778668\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778667,
          "rowPosition": 778668,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778668\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778668,
          "rowPosition": 778669,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778669\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778668,
          "rowPosition": 778669,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778669\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778669,
          "rowPosition": 778670,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778670\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778669,
          "rowPosition": 778670,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778670\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778670,
          "rowPosition": 778671,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778671\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778670,
          "rowPosition": 778671,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778671\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778671,
          "rowPosition": 778672,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778672\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778671,
          "rowPosition": 778672,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778672\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778672,
          "rowPosition": 778673,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778673\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778672,
          "rowPosition": 778673,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778673\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778674,
          "rowPosition": 778675,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778675\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778674,
          "rowPosition": 778675,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778675\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778675,
          "rowPosition": 778676,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778676\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778675,
          "rowPosition": 778676,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778676\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778676,
          "rowPosition": 778677,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778677\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778676,
          "rowPosition": 778677,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778677\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778677,
          "rowPosition": 778678,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778678\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778677,
          "rowPosition": 778678,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778678\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778678,
          "rowPosition": 778679,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778679\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778678,
          "rowPosition": 778679,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778679\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778679,
          "rowPosition": 778680,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778680\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778679,
          "rowPosition": 778680,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778680\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778680,
          "rowPosition": 778681,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778681\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778680,
          "rowPosition": 778681,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778681\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778681,
          "rowPosition": 778682,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778682\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778681,
          "rowPosition": 778682,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778682\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778682,
          "rowPosition": 778683,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778683\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778682,
          "rowPosition": 778683,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778683\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778684,
          "rowPosition": 778685,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778685\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778684,
          "rowPosition": 778685,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778685\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778685,
          "rowPosition": 778686,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778686\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778685,
          "rowPosition": 778686,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778686\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778686,
          "rowPosition": 778687,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778687\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 778686,
          "rowPosition": 778687,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"778687\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 126
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 126,
    "tasks": 1
  },
  "valid": false
}