{
  "version": "4.16.6",
  "time": 305.885,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_despesa_2023",
        "title": "Despesa 2023",
        "path": "data/ft_despesa_2023.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_tempo",
              "title": "Tempo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "description": "- > \n  Chave estrangeira (Foreign Key) que aponta para a Chave Primária (Primary keys) da tabela dm_tempo_diario. \n  Ou seja, por meio dessa chave é possível identificar a data completa a qual o dado se refere.\n\n  Nota: \n  No site dados.mg.gov.br a tabela dm_tempo_diario pode ser encontrada no recurso Calendários - Dias \n  de cada conjunto.\n",
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_categ_econ",
              "title": "Categoria Econômica da Despesa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_grupo",
              "title": "Grupo de Despesa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_elemento",
              "title": "Elemento de Despesa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item de Despesa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_fonte",
              "title": "Fonte de Recurso - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_modalidade_aplic",
              "title": "Modalidade de Aplicação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_funcao",
              "title": "Função - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_subfuncao",
              "title": "Subfunção - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_programa",
              "title": "Programa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_acao",
              "title": "Ação Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_procedencia",
              "title": "Procedência - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_orc",
              "title": "Unidade Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_favorecido",
              "title": "Favorecido - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_empenho",
              "title": "Número do Empenho - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_tipo_documento",
              "title": "Tipo de Documento - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "tp_operacao",
              "title": "Tipo Operação - Chave Origem",
              "type": "string",
              "format": "default",
              "constraints": {
                "enum": [
                  "1",
                  "2"
                ]
              }
            },
            {
              "name": "cd_documento",
              "title": "Documento - Código",
              "type": "string",
              "format": "default",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "cd_evento",
              "title": "Evento - Código",
              "type": "string",
              "format": "default",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "dt_anomes",
              "title": "Ano e Mês",
              "type": "string",
              "format": "default",
              "bareNumber": true,
              "notes": [
                "O tipo yearmonth somente aceita representação YYYY-MM (ie. com hífen)"
              ]
            },
            {
              "name": "ano_particao",
              "title": "Ano Partição",
              "type": "year",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_empenhado",
              "title": "Valor Empenhado",
              "description": "Valor do orçamento reservado para fazer face a compromisso formalmente assumido com fornecedor ou credor.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_liquidado",
              "title": "Valor Liquidado",
              "description": "Valor que o fornecedor ou credor tem direito a receber referente a produto ou serviço devidamente entregue ou prestado.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_pago",
              "title": "Valor Pago",
              "description": "- > \nValor referente aos pagamentos efetuados através de movimentações bancárias, escriturais e apropriação contábil da\ndespesa. O efetivo pagamento pode estar pendente de transmissão ao banco e/ou sujeito a compensação bancária.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_unidade_orc"
              ],
              "reference": {
                "fields": [
                  "id_unidade_orc"
                ],
                "resource": "dm_unidade_orc"
              }
            },
            {
              "fields": [
                "id_tipo_documento"
              ],
              "reference": {
                "fields": [
                  "id_tipo_documento"
                ],
                "resource": "dm_tipo_documento"
              }
            },
            {
              "fields": [
                "id_programa"
              ],
              "reference": {
                "fields": [
                  "id_programa"
                ],
                "resource": "dm_programa"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_categ_econ"
              ],
              "reference": {
                "fields": [
                  "id_categ_econ"
                ],
                "resource": "dm_categ_econ"
              }
            },
            {
              "fields": [
                "id_grupo"
              ],
              "reference": {
                "fields": [
                  "id_grupo"
                ],
                "resource": "dm_grupo_desp"
              }
            },
            {
              "fields": [
                "id_funcao"
              ],
              "reference": {
                "fields": [
                  "id_funcao"
                ],
                "resource": "dm_funcao_desp"
              }
            },
            {
              "fields": [
                "id_empenho"
              ],
              "reference": {
                "fields": [
                  "id_empenho"
                ],
                "resource": "dm_empenho_desp_2023"
              }
            },
            {
              "fields": [
                "id_tempo"
              ],
              "reference": {
                "fields": [
                  "id_tempo"
                ],
                "resource": "dm_tempo_diario"
              }
            },
            {
              "fields": [
                "id_subfuncao"
              ],
              "reference": {
                "fields": [
                  "id_subfuncao"
                ],
                "resource": "dm_subfuncao_desp"
              }
            },
            {
              "fields": [
                "id_acao"
              ],
              "reference": {
                "fields": [
                  "id_acao"
                ],
                "resource": "dm_acao"
              }
            },
            {
              "fields": [
                "id_modalidade_aplic"
              ],
              "reference": {
                "fields": [
                  "id_modalidade_aplic"
                ],
                "resource": "dm_modalidade_aplic"
              }
            },
            {
              "fields": [
                "id_procedencia"
              ],
              "reference": {
                "fields": [
                  "id_procedencia"
                ],
                "resource": "dm_procedencia"
              }
            },
            {
              "fields": [
                "id_elemento"
              ],
              "reference": {
                "fields": [
                  "id_elemento"
                ],
                "resource": "dm_elemento_desp"
              }
            },
            {
              "fields": [
                "id_fonte"
              ],
              "reference": {
                "fields": [
                  "id_fonte"
                ],
                "resource": "dm_fonte"
              }
            },
            {
              "fields": [
                "id_favorecido"
              ],
              "reference": {
                "fields": [
                  "id_favorecido"
                ],
                "resource": "dm_favorecido"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_despesa_2023"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "3f60c0f9d923b7cb9cf45c4043d0a208",
          "bytes": 21420396,
          "fields": 24,
          "rows": 1521876
        }
      },
      "time": 305.885,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1496392,
          "rowPosition": 1496393,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1496393\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1496910,
          "rowPosition": 1496911,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1496911\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1497171,
          "rowPosition": 1497172,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1497172\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1497172,
          "rowPosition": 1497173,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1497173\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1497173,
          "rowPosition": 1497174,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1497174\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1497799,
          "rowPosition": 1497800,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1497800\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1498034,
          "rowPosition": 1498035,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1498035\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1498818,
          "rowPosition": 1498819,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1498819\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1499522,
          "rowPosition": 1499523,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1499523\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1499796,
          "rowPosition": 1499797,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1499797\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1499981,
          "rowPosition": 1499982,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1499982\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1499982,
          "rowPosition": 1499983,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1499983\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1499985,
          "rowPosition": 1499986,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1499986\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1499986,
          "rowPosition": 1499987,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1499987\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1499987,
          "rowPosition": 1499988,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1499988\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1500115,
          "rowPosition": 1500116,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1500116\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1500116,
          "rowPosition": 1500117,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1500117\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1500118,
          "rowPosition": 1500119,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1500119\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1500854,
          "rowPosition": 1500855,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1500855\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1500855,
          "rowPosition": 1500856,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1500856\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1500856,
          "rowPosition": 1500857,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1500857\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1500857,
          "rowPosition": 1500858,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1500858\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1500859,
          "rowPosition": 1500860,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1500860\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1500861,
          "rowPosition": 1500862,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1500862\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1500862,
          "rowPosition": 1500863,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1500863\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1500863,
          "rowPosition": 1500864,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1500864\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1500864,
          "rowPosition": 1500865,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1500865\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1500868,
          "rowPosition": 1500869,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1500869\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1500869,
          "rowPosition": 1500870,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1500870\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1500870,
          "rowPosition": 1500871,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1500871\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1500871,
          "rowPosition": 1500872,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1500872\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1500872,
          "rowPosition": 1500873,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1500873\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1500873,
          "rowPosition": 1500874,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1500874\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1500874,
          "rowPosition": 1500875,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1500875\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1500875,
          "rowPosition": 1500876,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1500876\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1500878,
          "rowPosition": 1500879,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1500879\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1500882,
          "rowPosition": 1500883,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1500883\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1500883,
          "rowPosition": 1500884,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1500884\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1500886,
          "rowPosition": 1500887,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1500887\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1500888,
          "rowPosition": 1500889,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1500889\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1500890,
          "rowPosition": 1500891,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1500891\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1500896,
          "rowPosition": 1500897,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1500897\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1501320,
          "rowPosition": 1501321,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1501321\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1502233,
          "rowPosition": 1502234,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1502234\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1502234,
          "rowPosition": 1502235,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1502235\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1502735,
          "rowPosition": 1502736,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1502736\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1502985,
          "rowPosition": 1502986,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1502986\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1502990,
          "rowPosition": 1502991,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1502991\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1502991,
          "rowPosition": 1502992,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1502992\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1502993,
          "rowPosition": 1502994,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1502994\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1502996,
          "rowPosition": 1502997,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1502997\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1502997,
          "rowPosition": 1502998,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1502998\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1502998,
          "rowPosition": 1502999,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1502999\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1503002,
          "rowPosition": 1503003,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1503003\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1503188,
          "rowPosition": 1503189,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1503189\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1503513,
          "rowPosition": 1503514,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1503514\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1503600,
          "rowPosition": 1503601,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1503601\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1506818,
          "rowPosition": 1506819,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1506819\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1506819,
          "rowPosition": 1506820,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1506820\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1507129,
          "rowPosition": 1507130,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1507130\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1507289,
          "rowPosition": 1507290,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1507290\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1507290,
          "rowPosition": 1507291,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1507291\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1507291,
          "rowPosition": 1507292,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1507292\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1507329,
          "rowPosition": 1507330,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1507330\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1507330,
          "rowPosition": 1507331,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1507331\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1507371,
          "rowPosition": 1507372,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1507372\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1507613,
          "rowPosition": 1507614,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1507614\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1507614,
          "rowPosition": 1507615,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1507615\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1507752,
          "rowPosition": 1507753,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1507753\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1508239,
          "rowPosition": 1508240,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1508240\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1508474,
          "rowPosition": 1508475,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1508475\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1508475,
          "rowPosition": 1508476,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1508476\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1508477,
          "rowPosition": 1508478,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1508478\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1508487,
          "rowPosition": 1508488,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1508488\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1508488,
          "rowPosition": 1508489,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1508489\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1508491,
          "rowPosition": 1508492,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1508492\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1508493,
          "rowPosition": 1508494,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1508494\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1508494,
          "rowPosition": 1508495,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1508495\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1508501,
          "rowPosition": 1508502,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1508502\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1508505,
          "rowPosition": 1508506,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1508506\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1508507,
          "rowPosition": 1508508,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1508508\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1508713,
          "rowPosition": 1508714,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1508714\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1509141,
          "rowPosition": 1509142,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1509142\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1509182,
          "rowPosition": 1509183,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1509183\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1509635,
          "rowPosition": 1509636,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1509636\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1510059,
          "rowPosition": 1510060,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1510060\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1510060,
          "rowPosition": 1510061,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1510061\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1510063,
          "rowPosition": 1510064,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1510064\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_tempo",
            "id_categ_econ",
            "id_grupo",
            "id_elemento",
            "id_item",
            "id_fonte",
            "id_modalidade_aplic",
            "id_funcao",
            "id_subfuncao",
            "id_programa",
            "id_acao",
            "id_procedencia",
            "id_unidade_orc",
            "id_favorecido",
            "id_empenho",
            "id_tipo_documento",
            "tp_operacao",
            "cd_documento",
            "cd_evento",
            "dt_anomes",
            "ano_particao",
            "vr_empenhado",
            "vr_liquidado",
            "vr_pago"
          ],
          "rowNumber": 1510477,
          "rowPosition": 1510478,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"1510478\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 89
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 89,
    "tasks": 1
  },
  "valid": false
}