{
  "version": "4.16.6",
  "time": 143.73,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_diarias_scdp_liqpag",
        "title": "Diárias SCDP - Liquidação e Pagamento",
        "path": "data/ft_diarias_scdp_liqpag.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_documento_viagem",
              "title": "Documento de Viagem - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "description": "- > \n  Chave estrangeira (Foreign Key) que aponta para a Chave Primária (Primary keys) da tabela dm_tempo_diario. \n  Ou seja, por meio dessa chave é possível identificar a data completa a qual o dado se refere.\n\n  Nota: \n  No site dados.mg.gov.br a tabela dm_tempo_diario pode ser encontrada no recurso Calendários - Dias \n  de cada conjunto.\n",
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_empenho",
              "title": "Número do Empenho - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_programa",
              "title": "Programa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_funcao",
              "title": "Função - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_fonte",
              "title": "Fonte de Recurso - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item de Despesa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_acao",
              "title": "Ação Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "fl_passagem",
              "title": "Passagem - Flag",
              "type": "string",
              "format": "default",
              "description": "- '0' - Diárias\n- '1' - Passagem\n",
              "constraints": {
                "required": true,
                "enum": [
                  "0",
                  "1"
                ]
              }
            },
            {
              "name": "nr_liquidacao",
              "title": "Número Liquidação",
              "type": "string",
              "format": "default",
              "description": "Número do documento de liquidação.\n",
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "nr_pagamento",
              "title": "Número Pagamento",
              "type": "string",
              "format": "default",
              "description": "Número do documento de ordem de pagamento.\n",
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "dt_liquidacao",
              "title": "Data da liquidação",
              "type": "date",
              "format": "default"
            },
            {
              "name": "dt_pagamento",
              "type": "date",
              "format": "default"
            },
            {
              "name": "vr_devolvido",
              "title": "Valor Devolvido",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_liqpag",
              "title": "Valor liquidado/Pago",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "description": "- > \n  Valor pago referente às despesas com diárias e passagens aéreas e terrestres de servidor público ou \n  colaborador eventual em razão de viagem a trabalho.\n",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_funcao"
              ],
              "reference": {
                "fields": [
                  "id_funcao"
                ],
                "resource": "dm_funcao_desp"
              }
            },
            {
              "fields": [
                "id_fonte"
              ],
              "reference": {
                "fields": [
                  "id_fonte"
                ],
                "resource": "dm_fonte"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_programa"
              ],
              "reference": {
                "fields": [
                  "id_programa"
                ],
                "resource": "dm_programa"
              }
            },
            {
              "fields": [
                "id_empenho"
              ],
              "reference": {
                "fields": [
                  "id_empenho"
                ],
                "resource": "dm_empenho_desp_diarias_scdp_liqpag"
              }
            },
            {
              "fields": [
                "id_documento_viagem"
              ],
              "reference": {
                "fields": [
                  "id_documento_viagem"
                ],
                "resource": "dm_documento_viagem"
              }
            },
            {
              "fields": [
                "id_acao"
              ],
              "reference": {
                "fields": [
                  "id_acao"
                ],
                "resource": "dm_acao"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_fonte"
              ],
              "reference": {
                "fields": [
                  "id_fonte"
                ],
                "resource": "dm_fonte"
              }
            },
            {
              "fields": [
                "id_programa"
              ],
              "reference": {
                "fields": [
                  "id_programa"
                ],
                "resource": "dm_programa"
              }
            },
            {
              "fields": [
                "id_documento_viagem"
              ],
              "reference": {
                "fields": [
                  "id_documento_viagem"
                ],
                "resource": "dm_documento_viagem"
              }
            },
            {
              "fields": [
                "id_acao"
              ],
              "reference": {
                "fields": [
                  "id_acao"
                ],
                "resource": "dm_acao"
              }
            },
            {
              "fields": [
                "id_empenho"
              ],
              "reference": {
                "fields": [
                  "id_empenho"
                ],
                "resource": "dm_empenho_desp_diarias_scdp_liqpag"
              }
            },
            {
              "fields": [
                "id_funcao"
              ],
              "reference": {
                "fields": [
                  "id_funcao"
                ],
                "resource": "dm_funcao_desp"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_diarias_scdp_liqpag"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "daf49554c7821705b28daf1f1faa4c83",
          "bytes": 12168204,
          "fields": 14,
          "rows": 781826
        }
      },
      "time": 143.73,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780720,
          "rowPosition": 780721,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780721\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780720,
          "rowPosition": 780721,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780721\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780722,
          "rowPosition": 780723,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780723\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780722,
          "rowPosition": 780723,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780723\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780723,
          "rowPosition": 780724,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780724\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780723,
          "rowPosition": 780724,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780724\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780724,
          "rowPosition": 780725,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780725\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780724,
          "rowPosition": 780725,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780725\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780725,
          "rowPosition": 780726,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780726\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780725,
          "rowPosition": 780726,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780726\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780726,
          "rowPosition": 780727,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780727\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780726,
          "rowPosition": 780727,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780727\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780727,
          "rowPosition": 780728,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780728\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780727,
          "rowPosition": 780728,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780728\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780728,
          "rowPosition": 780729,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780729\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780728,
          "rowPosition": 780729,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780729\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780729,
          "rowPosition": 780730,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780730\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780729,
          "rowPosition": 780730,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780730\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780730,
          "rowPosition": 780731,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780731\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780730,
          "rowPosition": 780731,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780731\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780732,
          "rowPosition": 780733,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780733\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780732,
          "rowPosition": 780733,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780733\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780733,
          "rowPosition": 780734,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780734\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780733,
          "rowPosition": 780734,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780734\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780734,
          "rowPosition": 780735,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780735\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780734,
          "rowPosition": 780735,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780735\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780735,
          "rowPosition": 780736,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780736\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780735,
          "rowPosition": 780736,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780736\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780736,
          "rowPosition": 780737,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780737\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780736,
          "rowPosition": 780737,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780737\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780737,
          "rowPosition": 780738,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780738\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780737,
          "rowPosition": 780738,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780738\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780738,
          "rowPosition": 780739,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780739\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780738,
          "rowPosition": 780739,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780739\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780739,
          "rowPosition": 780740,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780740\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780739,
          "rowPosition": 780740,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780740\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780740,
          "rowPosition": 780741,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780741\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780740,
          "rowPosition": 780741,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780741\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780741,
          "rowPosition": 780742,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780742\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780741,
          "rowPosition": 780742,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780742\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780742,
          "rowPosition": 780743,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780743\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780742,
          "rowPosition": 780743,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780743\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780747,
          "rowPosition": 780748,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780748\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780747,
          "rowPosition": 780748,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780748\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780748,
          "rowPosition": 780749,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780749\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "id_documento_viagem",
            "id_empenho",
            "id_programa",
            "id_funcao",
            "id_fonte",
            "id_item",
            "id_acao",
            "fl_passagem",
            "nr_liquidacao",
            "nr_pagamento",
            "dt_liquidacao",
            "dt_pagamento",
            "vr_devolvido",
            "vr_liqpag"
          ],
          "rowNumber": 780748,
          "rowPosition": 780749,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "not found in the lookup table",
          "message": "Row at position \"780749\" violates the foreign key: not found in the lookup table",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 46
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 46,
    "tasks": 1
  },
  "valid": false
}