{
  "version": "4.38.0",
  "time": 104.502,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_diarias_scdp_liqpag",
        "title": "Diárias SCDP - Liquidação e Pagamento",
        "path": "data/ft_diarias_scdp_liqpag.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_documento_viagem",
              "title": "Documento de Viagem - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "description": "- > \n  Chave estrangeira (Foreign Key) que aponta para a Chave Primária (Primary keys) da tabela dm_tempo_diario. \n  Ou seja, por meio dessa chave é possível identificar a data completa a qual o dado se refere.\n\n  Nota: \n  No site dados.mg.gov.br a tabela dm_tempo_diario pode ser encontrada no recurso Calendários - Dias \n  de cada conjunto.\n",
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_empenho",
              "title": "Número do Empenho - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_programa",
              "title": "Programa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_funcao",
              "title": "Função - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_fonte",
              "title": "Fonte de Recurso - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item de Despesa - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_acao",
              "title": "Ação Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "fl_passagem",
              "title": "Passagem - Flag",
              "type": "string",
              "format": "default",
              "description": "- '0' - Diárias\n- '1' - Passagem\n",
              "constraints": {
                "required": true,
                "enum": [
                  "0",
                  "1"
                ]
              }
            },
            {
              "name": "nr_liquidacao",
              "title": "Número Liquidação",
              "type": "string",
              "format": "default",
              "description": "Número do documento de liquidação.\n",
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "nr_pagamento",
              "title": "Número Pagamento",
              "type": "string",
              "format": "default",
              "description": "Número do documento de ordem de pagamento.\n",
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "dt_liquidacao",
              "title": "Data da liquidação",
              "type": "date",
              "format": "default"
            },
            {
              "name": "dt_pagamento",
              "type": "date",
              "format": "default"
            },
            {
              "name": "vr_devolvido",
              "title": "Valor Devolvido",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_liqpag",
              "title": "Valor liquidado/Pago",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "description": "- > \n  Valor pago referente às despesas com diárias e passagens aéreas e terrestres de servidor público ou \n  colaborador eventual em razão de viagem a trabalho.\n",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_funcao"
              ],
              "reference": {
                "fields": [
                  "id_funcao"
                ],
                "resource": "dm_funcao_desp"
              }
            },
            {
              "fields": [
                "id_fonte"
              ],
              "reference": {
                "fields": [
                  "id_fonte"
                ],
                "resource": "dm_fonte"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_programa"
              ],
              "reference": {
                "fields": [
                  "id_programa"
                ],
                "resource": "dm_programa"
              }
            },
            {
              "fields": [
                "id_empenho"
              ],
              "reference": {
                "fields": [
                  "id_empenho"
                ],
                "resource": "dm_empenho_desp_diarias_scdp_liqpag"
              }
            },
            {
              "fields": [
                "id_documento_viagem"
              ],
              "reference": {
                "fields": [
                  "id_documento_viagem"
                ],
                "resource": "dm_documento_viagem"
              }
            },
            {
              "fields": [
                "id_acao"
              ],
              "reference": {
                "fields": [
                  "id_acao"
                ],
                "resource": "dm_acao"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_fonte"
              ],
              "reference": {
                "fields": [
                  "id_fonte"
                ],
                "resource": "dm_fonte"
              }
            },
            {
              "fields": [
                "id_programa"
              ],
              "reference": {
                "fields": [
                  "id_programa"
                ],
                "resource": "dm_programa"
              }
            },
            {
              "fields": [
                "id_documento_viagem"
              ],
              "reference": {
                "fields": [
                  "id_documento_viagem"
                ],
                "resource": "dm_documento_viagem"
              }
            },
            {
              "fields": [
                "id_acao"
              ],
              "reference": {
                "fields": [
                  "id_acao"
                ],
                "resource": "dm_acao"
              }
            },
            {
              "fields": [
                "id_empenho"
              ],
              "reference": {
                "fields": [
                  "id_empenho"
                ],
                "resource": "dm_empenho_desp_diarias_scdp_liqpag"
              }
            },
            {
              "fields": [
                "id_funcao"
              ],
              "reference": {
                "fields": [
                  "id_funcao"
                ],
                "resource": "dm_funcao_desp"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_diarias_scdp_liqpag"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "766b4844e39f516efeb278f081add36a",
          "bytes": 10234274,
          "fields": 14,
          "rows": 661022
        }
      },
      "time": 104.502,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "677214",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "437",
            "460",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660543,
          "rowPosition": 660544,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677214\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660544\" violates the foreign key: for \"id_documento_viagem\": values \"677214\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677214",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "437",
            "460",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660543,
          "rowPosition": 660544,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677214\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660544\" violates the foreign key: for \"id_documento_viagem\": values \"677214\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677225",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "573",
            "594",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660544,
          "rowPosition": 660545,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677225\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660545\" violates the foreign key: for \"id_documento_viagem\": values \"677225\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677225",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "573",
            "594",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660544,
          "rowPosition": 660545,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677225\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660545\" violates the foreign key: for \"id_documento_viagem\": values \"677225\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677196",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "415",
            "438",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660545,
          "rowPosition": 660546,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677196\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660546\" violates the foreign key: for \"id_documento_viagem\": values \"677196\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677196",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "415",
            "438",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660545,
          "rowPosition": 660546,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677196\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660546\" violates the foreign key: for \"id_documento_viagem\": values \"677196\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677153",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "513",
            "534",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660547,
          "rowPosition": 660548,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677153\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660548\" violates the foreign key: for \"id_documento_viagem\": values \"677153\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677153",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "513",
            "534",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660547,
          "rowPosition": 660548,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677153\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660548\" violates the foreign key: for \"id_documento_viagem\": values \"677153\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677236",
            "13328064",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "193",
            "244",
            "2022-12-21",
            "2022-12-22",
            "0.00",
            "105.00"
          ],
          "rowNumber": 660548,
          "rowPosition": 660549,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677236\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660549\" violates the foreign key: for \"id_documento_viagem\": values \"677236\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677236",
            "13328064",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "193",
            "244",
            "2022-12-21",
            "2022-12-22",
            "0.00",
            "105.00"
          ],
          "rowNumber": 660548,
          "rowPosition": 660549,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677236\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660549\" violates the foreign key: for \"id_documento_viagem\": values \"677236\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677232",
            "13328064",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "186",
            "248",
            "2022-12-21",
            "2022-12-22",
            "0.00",
            "105.00"
          ],
          "rowNumber": 660550,
          "rowPosition": 660551,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677232\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660551\" violates the foreign key: for \"id_documento_viagem\": values \"677232\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677232",
            "13328064",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "186",
            "248",
            "2022-12-21",
            "2022-12-22",
            "0.00",
            "105.00"
          ],
          "rowNumber": 660550,
          "rowPosition": 660551,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677232\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660551\" violates the foreign key: for \"id_documento_viagem\": values \"677232\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677213",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "446",
            "469",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660551,
          "rowPosition": 660552,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677213\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660552\" violates the foreign key: for \"id_documento_viagem\": values \"677213\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677213",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "446",
            "469",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660551,
          "rowPosition": 660552,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677213\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660552\" violates the foreign key: for \"id_documento_viagem\": values \"677213\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677168",
            "13626980",
            "14316",
            "1957",
            "58",
            "3012",
            "56416",
            "0",
            "18",
            "394",
            "2022-12-20",
            "2022-12-20",
            "0.00",
            "903.00"
          ],
          "rowNumber": 660553,
          "rowPosition": 660554,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677168\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660554\" violates the foreign key: for \"id_documento_viagem\": values \"677168\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677168",
            "13626980",
            "14316",
            "1957",
            "58",
            "3012",
            "56416",
            "0",
            "18",
            "394",
            "2022-12-20",
            "2022-12-20",
            "0.00",
            "903.00"
          ],
          "rowNumber": 660553,
          "rowPosition": 660554,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677168\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660554\" violates the foreign key: for \"id_documento_viagem\": values \"677168\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677220",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "442",
            "465",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660554,
          "rowPosition": 660555,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677220\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660555\" violates the foreign key: for \"id_documento_viagem\": values \"677220\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677220",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "442",
            "465",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660554,
          "rowPosition": 660555,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677220\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660555\" violates the foreign key: for \"id_documento_viagem\": values \"677220\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677227",
            "13328064",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "255",
            "276",
            "2022-12-28",
            "2022-12-28",
            "0.00",
            "235.00"
          ],
          "rowNumber": 660555,
          "rowPosition": 660556,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677227\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660556\" violates the foreign key: for \"id_documento_viagem\": values \"677227\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677227",
            "13328064",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "255",
            "276",
            "2022-12-28",
            "2022-12-28",
            "0.00",
            "235.00"
          ],
          "rowNumber": 660555,
          "rowPosition": 660556,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677227\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660556\" violates the foreign key: for \"id_documento_viagem\": values \"677227\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677203",
            "13238884",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "349",
            "3411",
            "2022-10-27",
            "2022-10-27",
            "0.00",
            "243.00"
          ],
          "rowNumber": 660556,
          "rowPosition": 660557,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677203\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660557\" violates the foreign key: for \"id_documento_viagem\": values \"677203\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677203",
            "13238884",
            "14405",
            "1957",
            "58",
            "3012",
            "56785",
            "0",
            "349",
            "3411",
            "2022-10-27",
            "2022-10-27",
            "0.00",
            "243.00"
          ],
          "rowNumber": 660556,
          "rowPosition": 660557,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677203\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660557\" violates the foreign key: for \"id_documento_viagem\": values \"677203\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677156",
            "13328064",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "254",
            "277",
            "2022-12-28",
            "2022-12-28",
            "0.00",
            "235.00"
          ],
          "rowNumber": 660557,
          "rowPosition": 660558,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677156\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660558\" violates the foreign key: for \"id_documento_viagem\": values \"677156\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677156",
            "13328064",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "254",
            "277",
            "2022-12-28",
            "2022-12-28",
            "0.00",
            "235.00"
          ],
          "rowNumber": 660557,
          "rowPosition": 660558,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677156\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660558\" violates the foreign key: for \"id_documento_viagem\": values \"677156\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677202",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "394",
            "417",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660558,
          "rowPosition": 660559,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677202\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660559\" violates the foreign key: for \"id_documento_viagem\": values \"677202\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677202",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "394",
            "417",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660558,
          "rowPosition": 660559,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677202\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660559\" violates the foreign key: for \"id_documento_viagem\": values \"677202\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677231",
            "13235658",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "449",
            "466",
            "2022-12-23",
            "2022-12-26",
            "0.00",
            "705.00"
          ],
          "rowNumber": 660559,
          "rowPosition": 660560,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677231\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660560\" violates the foreign key: for \"id_documento_viagem\": values \"677231\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677231",
            "13235658",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "449",
            "466",
            "2022-12-23",
            "2022-12-26",
            "0.00",
            "705.00"
          ],
          "rowNumber": 660559,
          "rowPosition": 660560,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677231\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660560\" violates the foreign key: for \"id_documento_viagem\": values \"677231\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677183",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "506",
            "527",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660560,
          "rowPosition": 660561,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677183\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660561\" violates the foreign key: for \"id_documento_viagem\": values \"677183\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677183",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "506",
            "527",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660560,
          "rowPosition": 660561,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677183\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660561\" violates the foreign key: for \"id_documento_viagem\": values \"677183\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677210",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "512",
            "533",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660561,
          "rowPosition": 660562,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677210\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660562\" violates the foreign key: for \"id_documento_viagem\": values \"677210\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677210",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "512",
            "533",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660561,
          "rowPosition": 660562,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677210\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660562\" violates the foreign key: for \"id_documento_viagem\": values \"677210\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677197",
            "13215758",
            "14390",
            "1957",
            "58",
            "3012",
            "56714",
            "0",
            "350",
            "5850",
            "2022-10-17",
            "2022-10-17",
            "183.00",
            "747.30"
          ],
          "rowNumber": 660562,
          "rowPosition": 660563,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677197\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660563\" violates the foreign key: for \"id_documento_viagem\": values \"677197\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677197",
            "13215758",
            "14390",
            "1957",
            "58",
            "3012",
            "56714",
            "0",
            "350",
            "5850",
            "2022-10-17",
            "2022-10-17",
            "183.00",
            "747.30"
          ],
          "rowNumber": 660562,
          "rowPosition": 660563,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677197\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660563\" violates the foreign key: for \"id_documento_viagem\": values \"677197\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677165",
            "13215758",
            "14390",
            "1957",
            "58",
            "3012",
            "56714",
            "0",
            "399",
            "7173",
            "2022-12-12",
            "2022-12-12",
            "747.30",
            "747.30"
          ],
          "rowNumber": 660563,
          "rowPosition": 660564,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677165\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660564\" violates the foreign key: for \"id_documento_viagem\": values \"677165\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677165",
            "13215758",
            "14390",
            "1957",
            "58",
            "3012",
            "56714",
            "0",
            "399",
            "7173",
            "2022-12-12",
            "2022-12-12",
            "747.30",
            "747.30"
          ],
          "rowNumber": 660563,
          "rowPosition": 660564,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677165\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660564\" violates the foreign key: for \"id_documento_viagem\": values \"677165\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677207",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "461",
            "484",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660564,
          "rowPosition": 660565,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677207\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660565\" violates the foreign key: for \"id_documento_viagem\": values \"677207\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677207",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "461",
            "484",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660564,
          "rowPosition": 660565,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677207\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660565\" violates the foreign key: for \"id_documento_viagem\": values \"677207\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677190",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "521",
            "541",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660565,
          "rowPosition": 660566,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677190\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660566\" violates the foreign key: for \"id_documento_viagem\": values \"677190\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677190",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "521",
            "541",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660565,
          "rowPosition": 660566,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677190\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660566\" violates the foreign key: for \"id_documento_viagem\": values \"677190\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677222",
            "13234607",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "309",
            "380",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "294.97"
          ],
          "rowNumber": 660566,
          "rowPosition": 660567,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677222\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660567\" violates the foreign key: for \"id_documento_viagem\": values \"677222\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677222",
            "13234607",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "309",
            "380",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "294.97"
          ],
          "rowNumber": 660566,
          "rowPosition": 660567,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677222\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660567\" violates the foreign key: for \"id_documento_viagem\": values \"677222\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677208",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "457",
            "480",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660567,
          "rowPosition": 660568,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677208\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660568\" violates the foreign key: for \"id_documento_viagem\": values \"677208\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677208",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "457",
            "480",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660567,
          "rowPosition": 660568,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677208\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660568\" violates the foreign key: for \"id_documento_viagem\": values \"677208\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677182",
            "13234607",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "305",
            "375",
            "2022-12-23",
            "2022-12-23",
            "0.00",
            "294.97"
          ],
          "rowNumber": 660568,
          "rowPosition": 660569,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677182\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660569\" violates the foreign key: for \"id_documento_viagem\": values \"677182\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677182",
            "13234607",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "305",
            "375",
            "2022-12-23",
            "2022-12-23",
            "0.00",
            "294.97"
          ],
          "rowNumber": 660568,
          "rowPosition": 660569,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677182\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660569\" violates the foreign key: for \"id_documento_viagem\": values \"677182\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677205",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "470",
            "493",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660569,
          "rowPosition": 660570,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677205\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660570\" violates the foreign key: for \"id_documento_viagem\": values \"677205\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677205",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "470",
            "493",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660569,
          "rowPosition": 660570,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677205\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660570\" violates the foreign key: for \"id_documento_viagem\": values \"677205\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677234",
            "13328064",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "200",
            "237",
            "2022-12-21",
            "2022-12-22",
            "0.00",
            "129.00"
          ],
          "rowNumber": 660570,
          "rowPosition": 660571,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677234\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660571\" violates the foreign key: for \"id_documento_viagem\": values \"677234\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677234",
            "13328064",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "200",
            "237",
            "2022-12-21",
            "2022-12-22",
            "0.00",
            "129.00"
          ],
          "rowNumber": 660570,
          "rowPosition": 660571,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677234\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660571\" violates the foreign key: for \"id_documento_viagem\": values \"677234\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677211",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "399",
            "422",
            "2022-11-25",
            "2022-11-25",
            "164.50",
            "164.50"
          ],
          "rowNumber": 660571,
          "rowPosition": 660572,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677211\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660572\" violates the foreign key: for \"id_documento_viagem\": values \"677211\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677211",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "399",
            "422",
            "2022-11-25",
            "2022-11-25",
            "164.50",
            "164.50"
          ],
          "rowNumber": 660571,
          "rowPosition": 660572,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677211\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660572\" violates the foreign key: for \"id_documento_viagem\": values \"677211\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677148",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "400",
            "423",
            "2022-11-25",
            "2022-11-25",
            "164.50",
            "164.50"
          ],
          "rowNumber": 660572,
          "rowPosition": 660573,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677148\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660573\" violates the foreign key: for \"id_documento_viagem\": values \"677148\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677148",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "400",
            "423",
            "2022-11-25",
            "2022-11-25",
            "164.50",
            "164.50"
          ],
          "rowNumber": 660572,
          "rowPosition": 660573,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677148\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660573\" violates the foreign key: for \"id_documento_viagem\": values \"677148\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677187",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "438",
            "461",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660573,
          "rowPosition": 660574,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677187\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660574\" violates the foreign key: for \"id_documento_viagem\": values \"677187\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677187",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "438",
            "461",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660573,
          "rowPosition": 660574,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677187\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660574\" violates the foreign key: for \"id_documento_viagem\": values \"677187\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677176",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "501",
            "522",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660574,
          "rowPosition": 660575,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677176\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660575\" violates the foreign key: for \"id_documento_viagem\": values \"677176\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677176",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "501",
            "522",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660574,
          "rowPosition": 660575,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677176\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660575\" violates the foreign key: for \"id_documento_viagem\": values \"677176\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677219",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "505",
            "526",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660575,
          "rowPosition": 660576,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677219\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660576\" violates the foreign key: for \"id_documento_viagem\": values \"677219\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677219",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "505",
            "526",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660575,
          "rowPosition": 660576,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677219\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660576\" violates the foreign key: for \"id_documento_viagem\": values \"677219\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677184",
            "13235658",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "450",
            "467",
            "2022-12-23",
            "2022-12-26",
            "0.00",
            "705.00"
          ],
          "rowNumber": 660576,
          "rowPosition": 660577,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677184\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660577\" violates the foreign key: for \"id_documento_viagem\": values \"677184\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677184",
            "13235658",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "450",
            "467",
            "2022-12-23",
            "2022-12-26",
            "0.00",
            "705.00"
          ],
          "rowNumber": 660576,
          "rowPosition": 660577,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677184\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660577\" violates the foreign key: for \"id_documento_viagem\": values \"677184\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677199",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "433",
            "458",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660577,
          "rowPosition": 660578,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677199\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660578\" violates the foreign key: for \"id_documento_viagem\": values \"677199\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677199",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "433",
            "458",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660577,
          "rowPosition": 660578,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677199\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660578\" violates the foreign key: for \"id_documento_viagem\": values \"677199\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677195",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "495",
            "516",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660578,
          "rowPosition": 660579,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677195\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660579\" violates the foreign key: for \"id_documento_viagem\": values \"677195\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677195",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "495",
            "516",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660578,
          "rowPosition": 660579,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677195\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660579\" violates the foreign key: for \"id_documento_viagem\": values \"677195\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677154",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "542",
            "563",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660579,
          "rowPosition": 660580,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677154\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660580\" violates the foreign key: for \"id_documento_viagem\": values \"677154\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677154",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "542",
            "563",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660579,
          "rowPosition": 660580,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677154\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660580\" violates the foreign key: for \"id_documento_viagem\": values \"677154\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677191",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "476",
            "499",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660580,
          "rowPosition": 660581,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677191\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660581\" violates the foreign key: for \"id_documento_viagem\": values \"677191\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677191",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "476",
            "499",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660580,
          "rowPosition": 660581,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677191\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660581\" violates the foreign key: for \"id_documento_viagem\": values \"677191\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677235",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "402",
            "425",
            "2022-11-25",
            "2022-11-25",
            "164.50",
            "164.50"
          ],
          "rowNumber": 660581,
          "rowPosition": 660582,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677235\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660582\" violates the foreign key: for \"id_documento_viagem\": values \"677235\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677235",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "402",
            "425",
            "2022-11-25",
            "2022-11-25",
            "164.50",
            "164.50"
          ],
          "rowNumber": 660581,
          "rowPosition": 660582,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677235\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660582\" violates the foreign key: for \"id_documento_viagem\": values \"677235\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677175",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "418",
            "442",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660582,
          "rowPosition": 660583,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677175\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660583\" violates the foreign key: for \"id_documento_viagem\": values \"677175\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677175",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "418",
            "442",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660582,
          "rowPosition": 660583,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677175\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660583\" violates the foreign key: for \"id_documento_viagem\": values \"677175\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677206",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "439",
            "462",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660583,
          "rowPosition": 660584,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677206\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660584\" violates the foreign key: for \"id_documento_viagem\": values \"677206\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677206",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "439",
            "462",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660583,
          "rowPosition": 660584,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677206\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660584\" violates the foreign key: for \"id_documento_viagem\": values \"677206\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677178",
            "13215758",
            "14390",
            "1957",
            "58",
            "3012",
            "56714",
            "0",
            "391",
            "7064",
            "2022-12-05",
            "2022-12-05",
            "42.60",
            "747.30"
          ],
          "rowNumber": 660584,
          "rowPosition": 660585,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677178\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660585\" violates the foreign key: for \"id_documento_viagem\": values \"677178\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677178",
            "13215758",
            "14390",
            "1957",
            "58",
            "3012",
            "56714",
            "0",
            "391",
            "7064",
            "2022-12-05",
            "2022-12-05",
            "42.60",
            "747.30"
          ],
          "rowNumber": 660584,
          "rowPosition": 660585,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677178\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660585\" violates the foreign key: for \"id_documento_viagem\": values \"677178\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677186",
            "13585007",
            "14353",
            "1948",
            "58",
            "3012",
            "56813",
            "0",
            "7",
            "552",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660585,
          "rowPosition": 660586,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677186\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660586\" violates the foreign key: for \"id_documento_viagem\": values \"677186\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677186",
            "13585007",
            "14353",
            "1948",
            "58",
            "3012",
            "56813",
            "0",
            "7",
            "552",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660585,
          "rowPosition": 660586,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677186\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660586\" violates the foreign key: for \"id_documento_viagem\": values \"677186\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677181",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "468",
            "491",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660586,
          "rowPosition": 660587,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677181\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660587\" violates the foreign key: for \"id_documento_viagem\": values \"677181\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677181",
            "13357492",
            "14353",
            "1948",
            "58",
            "2800",
            "56813",
            "0",
            "468",
            "491",
            "2022-11-25",
            "2022-11-25",
            "1104.50",
            "1104.50"
          ],
          "rowNumber": 660586,
          "rowPosition": 660587,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677181\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660587\" violates the foreign key: for \"id_documento_viagem\": values \"677181\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677233",
            "13234607",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "304",
            "374",
            "2022-12-23",
            "2022-12-23",
            "0.00",
            "179.98"
          ],
          "rowNumber": 660787,
          "rowPosition": 660788,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677233\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660788\" violates the foreign key: for \"id_documento_viagem\": values \"677233\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677233",
            "13234607",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "304",
            "374",
            "2022-12-23",
            "2022-12-23",
            "0.00",
            "179.98"
          ],
          "rowNumber": 660787,
          "rowPosition": 660788,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677233\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660788\" violates the foreign key: for \"id_documento_viagem\": values \"677233\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677177",
            "13328064",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "196",
            "238",
            "2022-12-21",
            "2022-12-22",
            "0.00",
            "105.00"
          ],
          "rowNumber": 660788,
          "rowPosition": 660789,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677177\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660789\" violates the foreign key: for \"id_documento_viagem\": values \"677177\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677177",
            "13328064",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "196",
            "238",
            "2022-12-21",
            "2022-12-22",
            "0.00",
            "105.00"
          ],
          "rowNumber": 660788,
          "rowPosition": 660789,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677177\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660789\" violates the foreign key: for \"id_documento_viagem\": values \"677177\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677194",
            "13234607",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "308",
            "379",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "179.98"
          ],
          "rowNumber": 660790,
          "rowPosition": 660791,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677194\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660791\" violates the foreign key: for \"id_documento_viagem\": values \"677194\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "677194",
            "13234607",
            "14406",
            "1957",
            "58",
            "3012",
            "56227",
            "0",
            "308",
            "379",
            "2022-12-27",
            "2022-12-27",
            "0.00",
            "179.98"
          ],
          "rowNumber": 660790,
          "rowPosition": 660791,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_documento_viagem\": values \"677194\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "message": "Row at position \"660791\" violates the foreign key: for \"id_documento_viagem\": values \"677194\" not found in the lookup table \"dm_documento_viagem\" as \"id_documento_viagem\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 88
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 88,
    "tasks": 1
  },
  "valid": false
}